### ISSUE TITLE
Add Search option

### ISSUE THREAD

**Issue by AnthoDingo** [glpi-project/glpi-inventory-plugin#107]
Hello,

I migrate from FusionInventory plugins to glpi-inventory.
I see that many search options were removed.

I tried to put it back in hook.php file, inspired from fusion plugins.
```php
function plugin_glpiinventory_getAddSearchOptions($itemtype)
{

$sopt[5160] = [
            'table'         => 'glpi_agents',
            'field'         => 'useragent',
            'name'          => __('Useragent', 'glpiinventory'),
            'massiveaction' => false,
            'joinparams'    => [
                'jointype' => 'child'
            ]
        ]; 

}
```

However, on the page Computers, I get this message : 
```
Unknown column 'glpi_agents.computers_id' in 'on clause'
```

Could help me please ?

**Comment by AnthoDingo** [comment]
Solved by changing the jointype.
```php
$sopt[5160] = [
    'table'         => 'glpi_agents',
    'field'         => 'useragent',
    'name'          => __('Useragent', 'glpiinventory'),
    'massiveaction' => false,
    'joinparams'    => [
        'jointype' => 'itemtype_item'
    ]
];
```

**Comment by WebGregGit** [comment]
Hi

Thank you @AnthoDingo, it works for searching. But there is no way to disable/enable this data in the columns view. You're right - a lot has been deleted and I don't know why - it doesn't make work easier. It was a step back in my opinion.

**Comment by orthagh** [comment]
Agents are now managed by core.

After a quick check, the mentionned searchoption (useragent) was moved to the core.
If you find any missing, let me know
