### ISSUE TITLE
No field locking option

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi-inventory-plugin#108]
**Version**
GLPI 10.0.0 ( => /var/www/html/glpi)
GLPI Inventory                 Version: 1.0.0      State: Enabled

**Bug description**
I am losing my data because agents overwrite fields such as locations. I can't see what fields can be blocked. 

The following were available for fusioninventory: Administration > Fusioninventory > General > General configuration > Locks tab. 
I do not see it in GLPI inventory. 

Additionally, no massive actions for setting field locking. 

**Steps To reproduce**
Mass actions:
Assets > Computers > select a few > Action button > no "Locks (field)" option (the option was for version 9.5.6 and fusioninventory).

**Anything else?**
I found this: https://github.com/glpi-project/glpi/pull/11397 I replaced the file, but that didn't fix the problem. There are still no Locks option in actions, and there is no global configuration for blocking fields in the plugin settings.

I found also: front/lockedfield.php However, this is only a list of what is currently blocked.

**Comment by trasher** [comment]
Locks are no longer handled by plugin, this is native. You can find them in Administration > Inventory, there is a "Locked fields" button.
As of global locks, this is a feature that is not yet implemented, see https://github.com/glpi-project/glpi/issues/11490

**Comment by WebGregGit** [comment]
Hi.

Thank You for your answer. Yes, I found this button, but it's useless - it only shows what has already been blocked. The global locks are extremely necessary.
