### ISSUE TITLE
Task ESX does not start

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi-inventory-plugin#109]
I can't run ESX tasks

Does ESX tasks work with the GLPI plugin?

I have several Printer and Network Tasks Its OK but ESX ko

The task does not start
![image](https://user-images.githubusercontent.com/68054991/167373480-827a2b7e-5453-4682-a679-f18cdc62e10a.png)

![image](https://user-images.githubusercontent.com/68054991/167373217-30933864-2961-422a-8e0b-9c2c3b528c59.png)

issues Glpi ? Plugin ? Agent ? i dont know

GLPI 10.0 Last FIX 20220507
GLPI plugin 1.0.0
GLPI Agent 1.3-gita35bb063

**Comment by steph461** [comment]
[Mon May  9 10:50:20 2022][info] running task ESX
[Mon May  9 10:50:20 2022][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Mon May  9 10:50:20 2022][info] ESX task not supported by server0

maybe ? probleme with agent is possible

**Comment by g-bougard** [comment]
Hi @steph461 
please always report GLPI version, GlpiInventory plugin version and also Agent version.

**Comment by steph461** [comment]
Its correctly in my descripton sorry i forget

**Comment by g-bougard** [comment]
Okay thank you.
Can you enable debug2 in the agent and see what happens in agent log while forcing again the ESX task ?

**Comment by steph461** [comment]
[glpi-agent.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/8650581/glpi-agent.zip)

**Comment by steph461** [comment]
[glpi-agent.log](https://github.com/glpi-project/glpi-inventory-plugin/files/8650599/glpi-agent.log)

**Comment by g-bougard** [comment]
You're using the wrong URL: `http://xxxxxxxxxxxxx/glpi/front/inventory.php`

You should use `http://xxxxxxxxxxxxx/glpi/plugins/glpiinventory/` or `http://xxxxxxxxxxxxx/glpi/marketplace/glpiinventory/`
As [this is explained in GLPI Agent documentation](https://glpi-agent.readthedocs.io/en/latest/configuration.html#server).
