### ISSUE TITLE
HPE switches discovery/inventory, bug or feature?

### ISSUE THREAD

**Issue by dsiens** [glpi-project/glpi-inventory-plugin#110]
Hello GLPI,
in our previous GLPI installation, with fusioninventory, one HPE stack = 1 network equipment with the total ports of the stack in port inventory. ( 5 x 48 ports if the stack is a 5 switches stack)

Now we are testing GLPI 10 and glpi-inventory.
After discovery task, HPE stacks are discovered, one equipment for one stack. No problem.
After inventory task, all switches are created, with their ports. For a 5 switches stack, I have 5 network equipment.

I have tried to play with rules to keep only one equipment, with all ports inventoried, but with no success.

Is this the normal? can it be fixed or this is the new way of glpi-inventory to inventory stacks?

Thanks

**Comment by trasher** [comment]
The way stacked switches are inventoried has not really changed; but maybe this one was not detected and is now.
Discovery cannot know an equipment is a stack, only inventory can.
