### ISSUE TITLE
SNMP Discovery / Agent configuration

### ISSUE THREAD

**Issue by Deininger-IT** [glpi-project/glpi-inventory-plugin#111]
It´s not possible to configure any agent within the GLPI Inventory plugin to get SNMP discovery running.
The "Agent Discovery" is shown as read only, so there is no way to configure a new agent. Please provide any documentation how to configure the "GLPI Inventory" plugin to be working.
Thanks a lot for providing this plugin

**Comment by g-bougard** [comment]
Hi @Deininger-IT 
here are few constraints to be able to associate an agent to any task (including network discovery):
1. an agent must be installed on a computer,
2. an inventory must have be run by the agent on the computer from which you want to run the task: here an agent must appear in the agents list 
3. when opening the agent form in GLPI, you should check the "agent modules" tab to have the required tasks activated
