### ISSUE TITLE
I can't install glpi plugin

### ISSUE THREAD

**Issue by lvauthier** [glpi-project/glpi-inventory-plugin#113]
When I try to install glpi inventory with marketplace, I have a display bug and he it does not install.
If I try to install in command line, the web page of plugins it's doesn't works.

Before :
![image](https://user-images.githubusercontent.com/64783865/168279490-c8ca8fbd-913d-424f-b6a9-a5f278441c8c.png)
After when I click on "+" :
![image](https://user-images.githubusercontent.com/64783865/168279562-ffbfb4f0-5634-4020-abf3-cd8d09e22bb5.png)

**Comment by lvauthier** [comment]
I have this error message.
![image](https://user-images.githubusercontent.com/64783865/168283168-74458d9d-03da-45fc-9114-7d02d2e465db.png)

**Comment by trasher** [comment]
What are the values of the `transfers_id_auto` column?

**Comment by lvauthier** [comment]
La valeur est à -1.
J'ai résolu mon problème en changeant la valeur dans la base mysql.
Et en relançant la commande de migration "sudo php bin/console glpi:migration:unsigned_keys"
