### ISSUE TITLE
Deploy packages fail if agent version change

### ISSUE THREAD

**Issue by Alexmothe93** [glpi-project/glpi-inventory-plugin#115]
If there is a pending package deployment task job for an agent, but the agent has changed version since last inventory :
- The old agent in GLPI database is deleted, and a new one is created (new ID)
- The task isn't executed, agent logs says "[info] No Deploy job enabled or Deploy support disabled server side."
- The job execution status become unresponsive for few seconds/minutes, and then the actor disappear from execution status
- The task is still showed in Computer > Package deploy tab but can't be developed.

Tested with agents :
- FusionInventory Agent 2.4.6 => GLPI Agent 1.2
- GLPI Agent 1.2 => FusionInventory Agent 2.4.6
- FusionInventory Agent 2.4.6 => FusionInventory Agent 2.6

**Comment by g-bougard** [comment]
Hi @Alexmothe93 
as far as on the task you associated an agent by its deviceid, this is a normal feature. We are not intended to update tasks when the agent changes. This is the admin job to select the task target.
Indeed the agent changes can't be detected by itself as far as you can have GLPI Agent and FusionInventory Agent installed on the same computer.
Did you try to setup a dynamic group as target ?

**Comment by Alexmothe93** [comment]
Yes it's works when I force the start, and it should works with a dynamic group too. In my case, it was with a "deploy on demand" task, so there a little chance that this feature doesn't work properly if there are agent upgrades in the same time. I was worried too about possible ghosts entries in database (I didn't check due to my lack of time and knowledge about how the functionality works in backend), that's why I opened this issue, but if you consider there's no issue with that, we can close it :)
