### ISSUE TITLE
Docking not shown

### ISSUE THREAD

**Issue by rubvaz** [glpi-project/glpi-inventory-plugin#120]
Hi.

I'm not sure if it is an issue, but we are not able to have listed all the docking stations than we have.

Is it normal?

**Comment by g-bougard** [comment]
Hi @rubvaz 

this is not a GlpiInventory plugin issue, eventually a Glpi Agent issue.

Anyway docking stations are often proprietary hardware with eventually dedicated software. But I didn't event see any way to make them normally included in inventory. Sometime we can see them in USB devices but without any serial number so this is completely useless.

When asking for some hardware support, also always list what manufacturer and/or model you're targeting.
