### ISSUE TITLE
[GLPI 10] Network Discovery not importing nor rejecting devices

### ISSUE THREAD

**Issue by conjarsa** [glpi-project/glpi-inventory-plugin#122]
### GLPI Version
10.0-3de7b01 (Nightly build, but tests were made on release 10.0.0 beforehand)

### GLPI Agent version
1.3-git2a4bc72e (Nightly build, but tests were made on release 1.2 beforehand) with an "all" install (network discovery and inventory included)

### GLPI inventory version
1.0.1

### Bug description
When trying to do network discovery from the glpi interface, the devices are detected, but are neither rejected yet not imported. The agent responds correctly, and the normal "inventory" task runs as intended as wel.
![image](https://user-images.githubusercontent.com/78089095/171412429-01a3034a-5abc-4453-bee1-229186d8ed5f.png)

I'm also a bit concerned by this line found in the logs ```[Wed Jun  1 15:20:31 2022][debug] server message: remoteinventory task not supported```
because snmp remote inventory also does not work: Forcing the job will do nothing, not a single job execution will be created.
![image](https://user-images.githubusercontent.com/78089095/171418910-f47145bf-1f31-4102-80cb-f8451663875f.png)

### Releavant log output
<details><summary>"Succsessful" network discovery job done</summary><pre> 
xxxxxx
2022-06-01 15:20:40
Processed: 0 Created: 0 Updated: 0
6297679e1c980
2022-06-01 15:20:40	Ok	Processed: 0 Created: 0 Updated: 0
2022-06-01 15:20:38	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:33	Running	1 devices found
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:30	Prepared	
62976797dac8d
2022-06-01 15:20:39	Ok	Processed: 0 Created: 0 Updated: 0
2022-06-01 15:20:39	Running	1 devices found
2022-06-01 15:20:38	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:33	Running	1 devices found
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:23	Prepared	
6297679e1c980
2022-06-01 15:20:38	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:33	Running	1 devices found
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:30	Prepared	
62976797dac8d
2022-06-01 15:20:38	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:33	Running	1 devices found
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:23	Prepared	
6297679e1c980
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:33	Running	1 devices found
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:30	Prepared	
62976797dac8d
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:33	Running	1 devices found
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:23	Prepared	
6297679e1c980
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:33	Running	1 devices found
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:30	Prepared	
62976797dac8d
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:33	Running	1 devices found
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:23	Prepared	
6297679e1c980
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:33	Running	1 devices found
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:30	Prepared	
62976797dac8d
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:37	Running	1 devices found
2022-06-01 15:20:33	Running	1 devices found
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:23	Prepared	
6297679e1c980
2022-06-01 15:20:33	Running	1 devices found
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:30	Prepared	
62976797dac8d
2022-06-01 15:20:33	Running	1 devices found
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:23	Prepared	
6297679e1c980
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:30	Prepared	
62976797dac8d
2022-06-01 15:20:31	Started	0 threads 0 timeout
2022-06-01 15:20:23	Prepared	
6297679e1c980
2022-06-01 15:20:30	Prepared	
62976797dac8d
2022-06-01 15:20:23	Prepared	
</details><details><summary>Glpi Agent</summary><pre> 
(Maximum body reached, content will be in reply)
</pre></details>

### Steps to reproduce
1. Create a new task with network discovery job (Don't forget to add releavant angents and IP ranges with SNMP credentials)
2. Activate the task and force start
3. Wait until job completion
4. Check discovery status. You should have no imported nor rejected devices

### Your GLPI setup information
<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.1 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux SRV1HLD21 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64
PHP 7.4.28 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.53 (Debian) (Apache/2.4.53 (Debian) Server at helpdesk-recette.groupe-glenat.com Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53
Server Software: Debian 11
	Server Version: 10.5.15-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.28) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.15) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 10.0.1
GLPI_SCHEMA_VERSION: 10.0.1
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Champs supplémentaires         Version: 1.15.1     State: Enabled
	datainjection        Name: Data Injection                 Version: 2.11.1     State: Enabled
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.1      State: Enabled
	manageentities       Name: Portail Clients                Version: 4.0.0      State: Enabled

</pre></details>

**Comment by g-bougard** [comment]
Hi @conjarsa 

firstly, you don't have to care about `[Wed Jun 1 15:20:31 2022][debug] server message: remoteinventory task not supported`, this has nothing to do with NetDiscovery task which is the task doing snmp discovery. RemoteInventory task is about running computer inventory remotely using ssh or winrm.

Then everything seems normal in your NetDiscovery task run: the agent only got ping from remote devices. This means none of your 6 SNMP credentials worked on that devices. One good reason could be SNMP requests are filtered between the agent and your devices (UDP/161). But the best reason is often the credentials are not the good ones.

You're also missing to tell something about your devices: what kind of devices they are.

Anyway, the best place to request help is to use GLPI forum. If you finally found a bug, you can then open an issue here.
