### ISSUE TITLE
Inventory not remove uninstalled / updated softwares

### ISSUE THREAD

**Issue by brunnersm** [glpi-project/glpi-inventory-plugin#124]
After inventory run on desktop, the softwares uninstalled or updated stay in software list.
![image](https://user-images.githubusercontent.com/69863640/171924102-612f2cfe-1071-4fb3-8680-fefdbd67741e.png)
![image](https://user-images.githubusercontent.com/69863640/171924206-bc07aaa3-de65-45c5-a489-bea6ed643992.png)

**Comment by WebGregGit** [comment]
Hi @brunnersm.  How many user profiles do you have on the inventoried computer?

**Comment by brunnersm** [comment]
Hi @WebGregGit , 5 profiles.

**Comment by brunnersm** [comment]
I found a UninstallView software and softwares installed are same.
