### ISSUE TITLE
Ca

### ISSUE THREAD

**Issue by 3gmgithub** [glpi-project/glpi-inventory-plugin#129]
File dialog when uploading from server for package deployment is blank white.
I am using GLPI 10.0.1 and the new glpiinventory plugin... I upgraded from 9.5 and FusionInventory
When I disable CSRF checks the file dialog works. However, when I renable it then it just shows a blank white box again.
![06-14-2022_Selection_001](https://user-images.githubusercontent.com/2551653/173712528-e24c5472-44b4-4c3d-be36-bbb334a082fd.png)

**Comment by cedric-anne** [comment]
Hi,

Can you check #130 ?

**Comment by 3gmgithub** [comment]
I added #130 to my production code, and the file dialog works just fine now.  Thank you!!!  That was a quick fix.
