### ISSUE TITLE
Erro to install

### ISSUE THREAD

**Issue by JeanBuchweitz** [glpi-project/glpi-inventory-plugin#154]
Migration Classname : Migration (0 segundo)

Update of plugin GLPI Inventory (0 segundo)

Alteração de layout do banco de dados - glpi_plugin_glpiinventory_agents (1 segundo)

Alteração de layout do banco de dados - glpi_plugin_glpiinventory_agentmodules (1 segundo)

Alteração de layout do banco de dados - glpi_plugin_glpiinventory_configs (1 segundo)
1.1.0 multiple alter in glpi_plugin_glpiinventory_configs - Erro na consulta ao banco de dados: ALTER TABLE `glpi_plugin_glpiinventory_configs` ADD `id` INT NOT NULL AUTO_INCREMENT , ADD `type` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL , ADD `value` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL - Erro é Incorrect information in file: './glpidb/glpi_plugin_glpiinventory_configs.frm'

**Comment by trasher** [comment]
Seems a database issue, not related to the plugin.

**Comment by JeanBuchweitz** [comment]
The error only occurs when you try to install the Glpi Inventory Plugin

**Comment by JeanBuchweitz** [comment]
> Seems a database issue, not related to the plugin.

The error only occurs when you try to install the Glpi Inventory Plugin

**Comment by cedric-anne** [comment]
> Incorrect information in file: './glpidb/glpi_plugin_glpiinventory_configs.frm'

This error message means that this file is probably corrupted. This is an issue with your database, not with GLPI or its plugin.
