### ISSUE TITLE
1.0.2 - Discovery task deleting network ports

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi-inventory-plugin#157]
Hi

Before starting the task:

![image](https://user-images.githubusercontent.com/68922721/175507459-c1315480-eb67-4530-b51d-e7cf6e540c50.png)

And after:

![image](https://user-images.githubusercontent.com/68922721/175507581-47c81dc8-2624-491a-8b1b-2f3be61bba1c.png)

I have to start the inventory task and the ports will be back... until the next discovery run.

From the switch history tab:

<html>
<body>

3911718 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
-- | -- | -- | -- | --
3911717 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911716 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911715 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911714 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911713 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911712 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911711 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911710 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911709 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911708 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911707 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911706 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911705 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911704 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911703 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911702 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911701 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911700 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911699 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911698 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911697 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911696 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911695 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911694 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911693 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911692 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911691 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911690 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911689 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911687 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911686 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911685 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911684 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911683 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911682 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911681 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911680 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911679 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911678 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911677 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911676 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911675 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911674 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911673 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911672 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911671 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911670 | 2022-06-24 11:29 | inventory | Network port | Delete an item: Network port ()
3911669 | 2022-06-24 11:29 | inventory | Last inventory date | Change 2022-06-24 11:22 to 2022-06-24 11:29
3910644 | 2022-06-24 11:22 | inventory | Last inventory date | Change 2022-06-24 11:14 to 2022-06-24 11:22
3910411 | 2022-06-24 11:14 | inventory | Network port | Delete an item: Network port ()
3910410 | 2022-06-24 11:14 | inventory | Network port | Delete an item: Network port ()

</body>
</html>

1. Why I have only delete info? What about add?
2. Why I don't have which port was deleted info?
3. Why were the ports even deleted at all?

**Comment by WebGregGit** [comment]
I have a similar problem with printers https://forum.glpi-project.org/viewtopic.php?pid=493289

**Comment by stonebuzz** [comment]
Can you retry with GLPI nightly build ([Nightly build](https://nightly.glpi-project.org/glpi/10.0-30b742a.tar.gz)) 
Now the inventory prevents port deletion from discovery

Best regards

**Comment by WebGregGit** [comment]
Hi @stonebuzz 

I confirm - it looks much better now. The only thing that happened to the graphics.

![image](https://user-images.githubusercontent.com/68922721/176139238-52ca8793-d4fa-489a-9ebf-a9a0135e91d0.png)

**Comment by stonebuzz** [comment]
:+1: nice
Best regards
