### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by Pierre25340** [glpi-project/glpi-inventory-plugin#16]
Hello,
I try to install the plugins into my glpi and when the database migrate, i've this issue. (Sorry for my english i'm a french guy)

This is the log file

Migration Classname : Migration (0 seconde)
Update of plugin GLPI Inventory (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_agents (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_agentmodules (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configs (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configs (0 seconde)
Ajout des index d'unicité - glpi_plugin_glpiinventory_configs (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_entities (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_locks (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_locks (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ignoredimportdevices (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_rulematchedlogs (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_unmanageds (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_inventorycomputercriterias (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_inventorycomputerblacklists (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_inventorycomputercomputers (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_computerlicenseinfos (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_computerremotemanagements (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblockinventorynames (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblockinventories (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblocksoftwares (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblocksoftwareversions (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjobs (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ipranges (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ipranges_configsecurities (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configlogfields (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkportconnectionlogs (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkporttypes (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkports (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkportlogs (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printers (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printerlogs (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printercartridges (4 secondes)
Clean printers (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkequipments (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configsecurities (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_statediscoveries (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deployfiles (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_entities (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_groups (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_profiles (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_users (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploymirrors (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploygroups (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploygroups_staticdatas (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploygroups_dynamicdatas (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_credentials (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_credentialips (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_registries (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_registries_contents (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_wmis (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_wmis_contents (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_files (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_files_contents (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_tasks (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjobs (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjoblogs (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjobstates (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_timeslots (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_timeslotentries (7 secondes)
Add Crontasks (7 secondes)
Traitement terminé. (7 secondes)
Migration Classname : Migration (0 seconde)
Use core capabilities (0 seconde)
Use core SNMP credentials (0 seconde)
Use core network ports (0 seconde)
Use core network equipments (0 seconde)
Use core printers (0 seconde)
Use core printer logs (0 seconde)
Use core networkports logs (0 seconde)
Use core network ports types (0 seconde)
Use core agent (0 seconde)
- Erreur durant l'éxecution de la requête : UPDATE `glpi_plugin_glpiinventory_printers` SET `plugin_glpiinventory_agents_id` = '0' WHERE `plugin_glpiinventory_agents_id` = '1' - L'erreur est Table 'glpidb.glpi_plugin_glpiinventory_printers' doesn't exist

Thank's for your help

**Comment by cedric-anne** [comment]
Hi,

Could you try with #17 patch applied ?

Regards

**Comment by Pierre25340** [comment]
Hi,

I download your patch and i think it's the same...

Migration Classname : Migration (0 seconde)
Update of plugin GLPI Inventory (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_agents (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_agentmodules (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configs (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configs (1 seconde)
Ajout des index d'unicité - glpi_plugin_glpiinventory_configs (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_entities (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_locks (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_locks (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ignoredimportdevices (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_rulematchedlogs (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_unmanageds (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_inventorycomputercriterias (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_inventorycomputerblacklists (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_inventorycomputercomputers (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_computerlicenseinfos (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_computerremotemanagements (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblockinventorynames (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblockinventories (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblocksoftwares (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblocksoftwareversions (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjobs (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ipranges (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ipranges_configsecurities (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ipranges_configsecurities (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configlogfields (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkportconnectionlogs (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkportconnectionlogs (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkporttypes (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkporttypes (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkports (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkports (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkportlogs (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printers (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printers (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printerlogs (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printerlogs (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printercartridges (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printercartridges (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printercartridges (6 secondes)
Clean printers (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkequipments (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkequipments (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configsecurities (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configsecurities (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_statediscoveries (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deployfiles (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_entities (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_groups (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_profiles (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_users (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploymirrors (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploygroups (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploygroups_staticdatas (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploygroups_dynamicdatas (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_credentials (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_credentialips (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_registries (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_registries_contents (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_wmis (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_wmis_contents (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_files (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_files_contents (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_tasks (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjobs (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjoblogs (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjobstates (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_timeslots (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_timeslotentries (9 secondes)
Add Crontasks (10 secondes)
Traitement terminé. (10 secondes)
Migration Classname : Migration (0 seconde)
Use core capabilities (0 seconde)
Use core SNMP credentials (0 seconde)
Use core network ports (0 seconde)
Use core printer logs (0 seconde)
Use core networkports logs (0 seconde)
Use core network ports types (0 seconde)
Use core agent (0 seconde)
- Erreur durant l'éxecution de la requête : UPDATE `glpi_plugin_glpiinventory_printers` SET `plugin_glpiinventory_agents_id` = '0' WHERE `plugin_glpiinventory_agents_id` = '1' - L'erreur est Unknown column 'plugin_glpiinventory_agents_id' in 'where clause'


I must have made a mistake... 
Do I have to download the original file as well as the patch?

Regards

**Comment by cedric-anne** [comment]
You have to replace original file by this one : https://raw.githubusercontent.com/glpi-project/glpi-inventory-plugin/aff147909b3b5ba053c41e79a42e869118ca3af6/install/update.native.php

**Comment by Pierre25340** [comment]
Hi,

I try with the new update.native.php file but it's the same...

Migration Classname : Migration (0 seconde)
Update of plugin GLPI Inventory (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_agents (0 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_agentmodules (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configs (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configs (1 seconde)
Ajout des index d'unicité - glpi_plugin_glpiinventory_configs (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_entities (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_locks (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_locks (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ignoredimportdevices (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_rulematchedlogs (1 seconde)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_unmanageds (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_inventorycomputercriterias (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_inventorycomputerblacklists (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_inventorycomputercomputers (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_computerlicenseinfos (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_computerremotemanagements (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblockinventorynames (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblockinventories (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblocksoftwares (2 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_dblocksoftwareversions (2 secondes)
Changement de la structue de la base de données - glpi_plugin_glpiinventory_taskjobs (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ipranges (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ipranges_configsecurities (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_ipranges_configsecurities (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configlogfields (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkportconnectionlogs (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkportconnectionlogs (3 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkporttypes (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkporttypes (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkports (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkports (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkportlogs (4 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printers (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printers (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printerlogs (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printerlogs (5 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printercartridges (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printercartridges (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_printercartridges (6 secondes)
Clean printers (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkequipments (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_networkequipments (6 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configsecurities (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_configsecurities (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_statediscoveries (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deployfiles (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_entities (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_groups (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_profiles (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploypackages_users (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploymirrors (7 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploygroups (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploygroups_staticdatas (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_deploygroups_dynamicdatas (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_credentials (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_credentialips (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_registries (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_registries_contents (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_wmis (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_wmis_contents (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_files (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_collects_files_contents (8 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_tasks (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjobs (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjoblogs (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_taskjobstates (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_timeslots (9 secondes)
Changement de la structure de la base de données - glpi_plugin_glpiinventory_timeslotentries (9 secondes)
Add Crontasks (9 secondes)
Traitement terminé. (9 secondes)
Migration Classname : Migration (0 seconde)
Use core capabilities (0 seconde)
Use core SNMP credentials (0 seconde)
Use core network ports (0 seconde)
Use core printer logs (0 seconde)
Use core networkports logs (0 seconde)
Use core network ports types (0 seconde)
Use core agent (0 seconde)
- Erreur durant l'éxecution de la requête : UPDATE `glpi_plugin_glpiinventory_printers` SET `plugin_glpiinventory_agents_id` = '0' WHERE `plugin_glpiinventory_agents_id` = '1' - L'erreur est Unknown column 'plugin_glpiinventory_agents_id' in 'where clause'

I try the update of GLPI Inventory (1.0.0-rc2) and it's the same...

**Comment by trasher** [comment]
Please try with latest master, I guess it is solved now
