### ISSUE TITLE
Glpi V10 with Fusion inventory : Plugin, sometimes, not give us his TAG 

### ISSUE THREAD

**Issue by Sergio31400** [glpi-project/glpi-inventory-plugin#163]
Hi,
I had an 9.6 Glpi version with more than 1000 registered computers.
 Since upgrade to glpi v10, fusion inventory plugin seems to no longer work correctly. I've 2.5.1 and 2.6 agent version and both have the same issue. Some computers do not give his TAG but as we can see on "gestion des agents" (sorry in french) but others on the same entity give his TAG to glpi. All computers have the TAG recorded in the windows registery, nothing happenned on compututers. This issue is detected on 30% of the assets. Some others trouble with assets losted his serial number, etc ..... I plan to migrate to glpi native agent but i couldn't do it so fast i needed.
Can you help us about this issues.
Thanks

![capture information agent fusion1](https://user-images.githubusercontent.com/108276810/175942094-32b907cc-7b6d-4d5b-a9d4-6cb0ee036afc.png)

**Comment by trasher** [comment]
If you're using fusioninventory plugin, you'd better report issue on their side

**Comment by Sergio31400** [comment]
I naively thought that V10 had the same level of compatibility as V9.6 as it's writing there :
https://glpi-project.org/fr/glpi-10-native-inventory/
