### ISSUE TITLE
Bad CSS from dynamic group search criteria 

### ISSUE THREAD

**Issue by stonebuzz** [glpi-project/glpi-inventory-plugin#170]
on GLPI Inventory plug-in, in the plugins/glpiinventory/front/deploygroup.form.php page > Criteria tab of a dynamic group :

![10 0 2-plugin](https://user-images.githubusercontent.com/665751/176712357-16933fec-0b2a-4679-b3e6-e635b8c35ac1.PNG)

**Comment by stonebuzz** [comment]
@Alexmothe93

Can you try this 
https://github.com/glpi-project/glpi-inventory-plugin/pull/169

**Comment by stonebuzz** [comment]
Fixed by #169

**Comment by Alexmothe93** [comment]
In my case, it's this PR : https://github.com/glpi-project/glpi/pull/12072 that fixed the issue.
This #169, added useless blank spaces and a padding issue.
Before :
![before](https://user-images.githubusercontent.com/665751/176896080-2d435514-2a62-4ff5-8503-dc41e8e1f374.PNG)
After :
![after](https://user-images.githubusercontent.com/665751/176896126-ebd7840e-13b3-401f-be52-59abb77adcf2.PNG)
