### ISSUE TITLE
Don't running tasks

### ISSUE THREAD

**Issue by Geekul** [glpi-project/glpi-inventory-plugin#174]
On GLPI v10.0.2 with GLPI Inventory v1.0.3 dont autorunning enabled task, network discovery and network inventory(snmp).
Running only if i use "Force Start" button.
If i use "Re-prepare a target-actor if previous run is successful " after using "Force Start" button, dont reprepare task, is like that
![image](https://user-images.githubusercontent.com/15617788/177159241-e8459a6a-68e5-4ffc-abff-1f2d1276e9db.png)

**Comment by ThalesArakawa** [comment]
I'm having these problem too. But my GLPI is the most recent version, 10.0.6. The tasks working fine, but don't re-prepare in automatic. I have tried the instructions of @stonebuzz, but the folders be different. Any tip?

**Comment by stonebuzz** [comment]
Hi @ThalesArakawa 

instructions was for GLPI 10.0.2

No need to use it for GLPI 10.0.6.

Let me check

**Comment by stonebuzz** [comment]
After some test, I do not reproduce

There is my task

![image](https://user-images.githubusercontent.com/7335054/220853050-e4e2a91f-6f47-4885-9ee5-4b12e7bae108.png)

After each discovery it is re-prepared if it is not in error

 Can you check that the automatic action "task Scheduler" is active with ```CLI``` mode -> also check the cron system

![image](https://user-images.githubusercontent.com/7335054/220853382-5e6f4424-f959-4677-90de-9ec48b057fec.png)

**Comment by ThalesArakawa** [comment]
Thanks for attention @stonebuzz!! But is just a bad use from old guys...
Cronjob was not configured correctly, just that.
