### ISSUE TITLE
Network equipment discovered through Network discovery task is detected as "Computer" and import is denied

### ISSUE THREAD

**Issue by redddcyclone** [glpi-project/glpi-inventory-plugin#176]
Hello all,

As i said on another issue, I was having problems with Network Discovery, so that the devices were not showing up for network inventory when targeting an IP range.
This problem was fixed by applying this PR:
https://github.com/glpi-project/glpi/pull/12132

Also, as suggested by @stonebuzz, I have applied:
https://github.com/glpi-project/glpi/pull/12050
https://github.com/glpi-project/glpi-inventory-plugin/pull/173

Discovery is importing printers as expected, but a network equipment (the only that was ever detected as such by the network discovery on my network, for internal reasons) is now being detected as "computer", and not being imported.

![image](https://user-images.githubusercontent.com/58712628/177170889-eb20058e-5bf4-4aa3-9419-89c29f97293a.png)

Any idea on why this is happening?

Thanks for the help

**Comment by stonebuzz** [comment]
Hi @redddcyclone 
thanks for this issue.

can you run agent (for discovery) in debug mode ```--debug --debug``` and past here the result ?

Best regards

**Comment by redddcyclone** [comment]
@stonebuzz 

```
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.4-1)
[debug] initializing job 1
[debug] initializing block 10.0.0.108-10.0.0.108
[debug] Current run expiration timeout: soon
[debug] creating 1 worker threads
[debug] [thread 1] creation
[debug] [thread 1] #1, scanning 10.0.0.108
[debug] [thread 1] #1, full match for sysobjectID .1.3.6.1.4.1.5624.2.1.142 in database
[debug2] [thread 1] #1, /etc/glpi-agent/toolbox.yaml configuration not found
[debug] [thread 1] #1, - scanning 10.0.0.108 with SNMP, credentials 1: success
[debug] [thread 1] #1, - scanning 10.0.0.108 with netbios: no result
[debug] [thread 1] #1, - scanning 10.0.0.108 with echo ping: success
[debug2] [thread 1] #1, executing arp -a 10.0.0.108
[debug] [thread 1] #1, - scanning 10.0.0.108 in arp table: success
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHPORT />  <AUTHPROTOCOL />  <AUTHSNMP>1</AUTHSNMP>
      <DESCRIPTION>Enterasys Networks, Inc. C5G124-24 Rev 06.41.06.0002</DESCRIPTION>
      <DNSHOSTNAME>10.0.0.108</DNSHOSTNAME>
      <FIRMWARE>06.41.06.0002</FIRMWARE>
      <IP>10.0.0.108</IP>
      <IPS>
        <IP>10.0.0.108</IP>
      </IPS>
      <LOCATION>*hidden*</LOCATION>
      <MAC>00:1f:45:b9:bf:c2</MAC>
      <MANUFACTURER>Enterasys</MANUFACTURER>
      <MODEL>C5G124-24</MODEL>
      <SERIAL>10471364905F</SERIAL>
      <SNMPHOSTNAME>*hidden*</SNMPHOSTNAME>
      <TYPE>NETWORKING</TYPE>
      <UPTIME>49 days, 22:11:48.60</UPTIME>
    </DEVICE>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
[debug2] [thread 1] processed 1 scans
[debug] [thread 1] termination
[debug] All netdiscovery threads terminated
```

**Comment by stonebuzz** [comment]
Have you the same result from GLPI Agent 1.3 (and 1.2) ?

```<DEVICEID>``` is empty, since this agent, have you proceeded to an inventory update of computer ?

Best regards

**Comment by redddcyclone** [comment]
Hi @stonebuzz 

I'm really sorry, this was actually my mistake. After all these days trying different things, I recreated the IP ranges but forgot associating the SNMP credentials. The discovery is working fine, even on 1.4, after the PRs.

I'm closing this issue. Thanks for the help!
