### ISSUE TITLE
10.0.2 - does not sum tasks

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi-inventory-plugin#177]
The logs do not sum tasks, but display the last one. As a result, I still have 1 success - even if I am doing it again. This is with the agent 1.2.

1st pass:
![image](https://user-images.githubusercontent.com/68922721/177260553-3a8f47ea-a95f-4ff3-9612-7b2cd4782752.png)

2nd:
![image](https://user-images.githubusercontent.com/68922721/177260578-07a35368-416f-4a5b-885d-5813fc05f994.png)

**Comment by WebGregGit** [comment]
Maybe wait with that - this was the case yesterday. I will check how it looks with today nightly build.

**Comment by stonebuzz** [comment]
Hi @WebGregGit 
After reviewing the code, the counters refer to actors (agent)

My job with 2 agents :
![image](https://user-images.githubusercontent.com/7335054/177279657-387ca837-8e6d-43e7-a661-59902aa52e81.png)

When i prepared the job : 
2 prepared and not done yet
![image](https://user-images.githubusercontent.com/7335054/177280196-7d7ddf52-602a-454b-9e73-07eb38ed03c6.png)


After running only one agent : 
1 sucsessful
and 1 prepared and not done yet
![image](https://user-images.githubusercontent.com/7335054/177279819-c2096dd5-7a74-4a7d-8ec9-020ef53b6741.png)
 

After running the second agent : 
2 successful
![image](https://user-images.githubusercontent.com/7335054/177280791-ca494b58-0b5f-4d02-ad37-97a80e83b603.png)
 
This option : 
![image](https://user-images.githubusercontent.com/7335054/177280997-dfb04818-f719-4150-8298-2fbfeb94488a.png)


only refers to log by agent (not counters)
![image](https://user-images.githubusercontent.com/7335054/177281266-290f2ca3-9d61-4595-af86-1f6f97d53da4.png)

**Comment by WebGregGit** [comment]
OK, I get it. Thanks :)
