### ISSUE TITLE
10.0.2 + 1.0.3 -  the server does not end the job

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi-inventory-plugin#178]
The agent finishes the job faster than the server.

[Tue Jul  5 08:47:09 2022][info] target server0: server https://glpi.domain.com/front/inventory.php
[Tue Jul  5 08:47:09 2022][info] sending contact request to server0
[Tue Jul  5 08:47:09 2022][info] [http client] SSL Client warning: Peer certificate not verified
[Tue Jul  5 08:47:09 2022][info] [http client] SSL Client info: Cert-Issuer: '........>
[Tue Jul  5 08:47:09 2022][info] [http client] SSL server certificate fingerprint: sha.....f
[Tue Jul  5 08:47:09 2022][info] [http client] You can set it in conf as 'ssl-fingerprint' and disable 'no-ssl-check' option to trust that server certificate
[Tue Jul  5 08:47:09 2022][info] sending prolog request to server0
[Tue Jul  5 08:47:09 2022][info] [http client] SSL Client warning: Peer certificate not verified
[Tue Jul  5 08:47:09 2022][info] [http client] SSL Client info: Cert-Issuer: '........>
[Tue Jul  5 08:47:09 2022][info] [http client] SSL server certificate fingerprint: sha.....f
[Tue Jul  5 08:47:09 2022][info] [http client] You can set it in conf as 'ssl-fingerprint' and disable 'no-ssl-check' option to trust that server certificate
[Tue Jul  5 08:47:09 2022][info] running task Inventory
[Tue Jul  5 08:47:09 2022][info] New inventory from agent-2022-07-05-08-44-26 for server0
[Tue Jul  5 08:47:14 2022][info] [http client] SSL Client warning: Peer certificate not verified
[Tue Jul  5 08:47:14 2022][info] [http client] SSL Client info: Cert-Issuer: '........>
[Tue Jul  5 08:47:14 2022][info] [http client] SSL server certificate fingerprint: sha.....f
[Tue Jul  5 08:47:14 2022][info] [http client] You can set it in conf as 'ssl-fingerprint' and disable 'no-ssl-check' option to trust that server certificate
[Tue Jul  5 08:47:14 2022][info] target server0: next run: Wed Jul  6 08:31:48 2022 - https://glpi.domain.com/front/inventory.php

![image](https://user-images.githubusercontent.com/68922721/177268905-95f525e8-aa8b-44d3-8e38-ad77ed76216a.png)

I tried with agent 1.2 and 1.4 - with https://github.com/glpi-project/glpi/pull/12127/files and revert version.

**Comment by stonebuzz** [comment]
Hi @WebGregGit  can you run agent with debug mode ```--debug --debug``` and past here the result ?

Best regards
