### ISSUE TITLE
[GLPIINVENTORY 1.0.3] Error in dashboard

### ISSUE THREAD

**Issue by ASLLR** [glpi-project/glpi-inventory-plugin#181]
Hi everyone, 

when i'm connect on my GLPI 10.0.2 with the glpiinventory 1.0.3, on the dashboard of GLPI Inventory, i have a notice which appears : 

Notice
: Undefined index: users_id in
/var/www/html/glpi/src/Dashboard/Dashboard.php
on line
559

![image](https://user-images.githubusercontent.com/37147055/177352449-dad4c6d3-e22c-4fc5-9e57-0afee996c1e5.png)

How can i hide this ? 

Thank in advance.
Best Regards

**Comment by stonebuzz** [comment]
Hi @ASLLR 

can you past here the result of this SQL query 

```sql
select * from glpi_dashboards_dashboards where `key` = 'plugin_glpiinventory_dashboard';
```

Best regards

**Comment by stonebuzz** [comment]
Can you check GLPI logs ? 

Can you run this command (from root folder of GLPI)

```
php bin/console glpi:plugin:install glpiinventory --force
```
then
```
php bin/console glpi:plugin:activate glpiinventory
```
And check if dashboard is OK

Best regards

**Comment by ASLLR** [comment]
Yes, this reslov the issue ! 

thank you.
