### ISSUE TITLE
Network inventory (SNMP) change agent item type

### ISSUE THREAD

**Issue by AndiFo** [glpi-project/glpi-inventory-plugin#182]
### Describe the bug

If I do a network inventory the agent item type changed from the current linked item type computer and item id to printer without link to the printer id.

I think it is not the right way to change the item type from the host scanning computer.

### To reproduce

Network inventory with snmp and fusion inventory agent, but same result with glpi agent 1.4

### Expected behavior

Non change of item type and id of scanning host computer.

### Operating system

Windows

### GLPI Agent version

Other (See additional context below)

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.3

**Comment by stonebuzz** [comment]
Hi @AndiFo 

can you apply this patch (GLPI)
https://github.com/glpi-project/glpi/pull/12050

and retry ?

Best regards

**Comment by stonebuzz** [comment]
Fixed by https://github.com/glpi-project/glpi/pull/12050
