### ISSUE TITLE
 It does not inventory despite the IP address, and duplicates entries

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi-inventory-plugin#183]
### Describe the bug

Hi @stonebuzz
I read Your comment from https://github.com/glpi-project/glpi-inventory-plugin/issues/175
_"Then, remove all assets only created by discovery and without IPs (IP are needed for SNMP Inventory by IP Range, glpiinventory can't retrieve target without )"_

But my printers have IP addresses and they are not inventoried too. I have to delete them and import them again.

All printers are online. The first two were deleted and imported again (so there is an inventory date). The printer named 6 is before deleting. Only 1 IP address is displayed for this printer. Two printers for which inventory works have so much IP addresses as MAC addresses (even if the mac address is all zeros)
![image](https://user-images.githubusercontent.com/68922721/177551108-eb872f65-9706-43a7-a684-c28738ee402c.png)

### To reproduce

1. Delete printer
2. Start discovery task to import the printer.
3. Start inventory task to inventory the printer.
4. Check the IP column.

### Expected behavior

As before, only one (used) IP and MAC addresses are displayed.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.3

### Additional context

GLPI - the nightly build of yesterday

**Comment by stonebuzz** [comment]
Hi @WebGregGit 

can you past here full log (```--debug --debug```) for :

- netDiscovery
- netInventory

Can you limit discovery / inventory task / job to noe printer (for easy debugging)

Best regards

**Comment by WebGregGit** [comment]
Sure.

ping 1.x.x.3
64 bytes from 1.x.x.3: icmp_seq=1 ttl=254 time=2.09 ms
64 bytes from 1.x.x.3: icmp_seq=2 ttl=254 time=0.449 ms
64 bytes from 1.x.x.3: icmp_seq=3 ttl=254 time=0.638 ms

***************************************************************

```
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.4-1)
[debug] initializing job 1
[debug] initializing block 1.x.x.3-1.x.x.3
[debug] Current run expiration timeout: soon
[debug] creating 1 worker threads
[debug] [thread 1] creation
[debug] [thread 1] #1, scanning 1.x.x.3
[debug] [thread 1] #1, full match for sysobjectID .1.3.6.1.4.1.11.2.3.9.1 in database
[debug2] [thread 1] #1, /etc/glpi-agent/toolbox.yaml configuration not found
[debug] [thread 1] #1, sysobjectID match: hp-peripheral mib support enabled
[debug] [thread 1] #1, - scanning 1.x.x.3 with SNMP, credentials 1: success
[debug] [thread 1] #1, - scanning 1.x.x.3 with netbios: success
[debug] [thread 1] #1, - scanning 1.x.x.3 with echo ping: no result, ping not supported
[debug2] [thread 1] #1, executing arp -a 1.x.x.3
[debug] [thread 1] #1, - scanning 1.x.x.3 in arp table: no result
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHPORT />  <AUTHPROTOCOL />  <AUTHSNMP>1</AUTHSNMP>
      <CONTACT></CONTACT>
      <DESCRIPTION>HP ETHERNET MULTI-ENVIRONMENT,SN:P...7,FN:6...S,SVCID:2...8,PID:HP LaserJet M402dne</DESCRIPTION>
      <IP>1.x.x.3</IP>
      <IPS>
        <IP>1.x.x.3</IP>
      </IPS>
      <LOCATION></LOCATION>
      <MAC>00:00:00:00:00:00</MAC>
      <MANUFACTURER>Hewlett-Packard</MANUFACTURER>
      <MODEL>HP LaserJet M402dn</MODEL>
      <NETBIOSNAME>7</NETBIOSNAME>
      <SERIAL>P...7</SERIAL>
      <SNMPHOSTNAME>7</SNMPHOSTNAME>
      <TYPE>PRINTER</TYPE>
      <UPTIME>2 days, 09:48:05.00</UPTIME>
      <WORKGROUP>WORKGROUP</WORKGROUP>
    </DEVICE>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
[debug2] [thread 1] processed 1 scans
[debug] [thread 1] termination
[debug] All netdiscovery threads terminated
```


***************************************************************

```
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.4-1)
[debug] Current run expiration timeout: 1.0 hour
[debug] creating 1 worker threads
[debug] [thread 1] creation
[debug] [thread 1] #1, scanning 0: 1.x.x.3
[debug] [thread 1] #1, full match for sysobjectID .1.3.6.1.4.1.11.2.3.9.1 in database
[debug2] [thread 1] #1, /etc/glpi-agent/toolbox.yaml configuration not found
[debug] [thread 1] #1, sysobjectID match: hp-peripheral mib support enabled
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <CARTRIDGES>
        <TONERBLACK>27</TONERBLACK>
      </CARTRIDGES>
      <INFO>
        <COMMENTS>HP ETHERNET MULTI-ENVIRONMENT,SN:P...7,FN:6...S,SVCID:2...8,PID:HP LaserJet M402dne</COMMENTS>
        <CONTACT></CONTACT>
        <ID>0</ID>
        <IPS>
          <IP>1.x.x.3</IP>
        </IPS>
        <LOCATION></LOCATION>
        <MAC>...5d:c9:50</MAC>
        <MANUFACTURER>Hewlett-Packard</MANUFACTURER>
        <MEMORY>256</MEMORY>
        <MODEL>HP LaserJet M402dn</MODEL>
        <NAME>7</NAME>
        <RAM>256</RAM>
        <SERIAL>P...7</SERIAL>
        <TYPE>PRINTER</TYPE>
        <UPTIME>2 days, 09:53:56.00</UPTIME>
      </INFO>
      <PAGECOUNTERS>
        <DUPLEX>3187</DUPLEX>
        <TOTAL>20864</TOTAL>
      </PAGECOUNTERS>
      <PORTS>
        <PORT>
          <IFDESCR>LOOPBACK</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>32143174</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>0.00 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>LOOPBACK</IFNAME>
          <IFNUMBER>1</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>32143174</IFOUTOCTETS>
          <IFSPEED>0</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>24</IFTYPE>
        </PORT>
        <PORT>
          <IFDESCR>Ethernet</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>50832204</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>0.00 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Ethernet</IFNAME>
          <IFNUMBER>2</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>648857</IFOUTOCTETS>
          <IFSPEED>10000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <IP>1.x.x.3</IP>
          <IPS>
            <IP>1.x.x.3</IP>
          </IPS>
          <MAC>...5d:c9:50</MAC>
        </PORT>
      </PORTS>
    </DEVICE>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
[debug] [thread 1] termination
[debug] All netinventory threads terminated
```

**Comment by stonebuzz** [comment]
For 
```shell
[debug] [thread 1] #1, - scanning 1.x.x.3 in arp table: no result
```

can you run this (from the server that does the SNMP discovery and inventory)

```shell
arp -a
```
Did you see printer IP ?

can you try to ping printer  (from the server that does the SNMP discovery and inventory)

Have you est result ?

**Comment by stonebuzz** [comment]
Hi @WebGregGit 

for duplicate ```IP``` from ```Printer``` list,

can you try this -> https://github.com/glpi-project/glpi/pull/12171

Best regards

**Comment by WebGregGit** [comment]
Hi @g-bougard - what and where should i change? I don't understand.

Hi @stonebuzz - better. I see one IP now, but still several MACs :)

![image](https://user-images.githubusercontent.com/68922721/177983927-fc4b4d92-c7b4-4c8d-91b9-63b69493f97b.png)

**Comment by WebGregGit** [comment]
@stonebuzz 

> you need this -> [glpi-project/glpi#12172](https://github.com/glpi-project/glpi/pull/12172)

Column 'instantiation_type' in on clause is ambiguous



> $device{MAC} = getCanonicalMacAddress($device{MAC});
> delete $device{MAC} unless defined($device{MAC});

Added > glpi-agent service restartet > NetDiscovery Task has been launched > I still have `00:00:00:00:00:00`. 

So I deleted the printer> started the discovery job> inventory > no `00:00:00:00:00:00` mac. 


BTW - I will write only for confirmation - after running the discovery task, the IP address in the table did not appear (although it was detected for the management port). It appeared in the table only after the inventory task was completed.

**Comment by stonebuzz** [comment]
@WebGregGit 
can you apply this -> https://github.com/glpi-project/glpi/pull/12176
(without revert https://github.com/glpi-project/glpi/pull/12172 and https://github.com/glpi-project/glpi/pull/12171)

Thanks for testing glpi-agent patch
@g-bougard  any idea ?

**Comment by stonebuzz** [comment]
In fact, discovery get an ampty MAC (from arp) and its added, from inventory MAC is found ( from snmp) but glpi add it as a new management port, because of different MAC.... 

We need to improve this part on glpi-agent side

**Comment by g-bougard** [comment]
Hi @WebGregGit

for an ubuntu agent, you must apply my patch on the file located at `/usr/share/glpi-agent/lib/GLPI/Agent/Task/Task/NetDiscovery.pm`.

**Comment by jpdenss** [comment]
Hi, I'm experiencing the same problem. From what I've analyzed, I believe that this occurs when a switch is included in the automatic inventory. In this way, a rule is triggered (Rules for import and link equipments - GLOBAL) that relates the MAC of the switch port to the IP and creates duplicates. The management port is created by this rule and serves to indicate which switch this device is connected to.
![Uploading image.png…]()

**Comment by stonebuzz** [comment]
Hi @jpdenss 
Managmement Port is always created if possible by inventory.

I don't have these rules, I use the native rules of the plugin.

Best regards

**Comment by stonebuzz** [comment]
Hi @WebGregGit 

Hi

Found better way to 

- handle port management 
- prevent duplicate IP / MAC (from Printer)
- prevent IP display issue from NetworkEquipement


Please revert this patch : 
https://github.com/glpi-project/glpi/pull/12171
https://github.com/glpi-project/glpi/pull/12172
https://github.com/glpi-project/glpi/pull/12176

And follow the guide here  ->   https://github.com/glpi-project/glpi-inventory-plugin/issues/189

I closed this issue.

Best regards
