### ISSUE TITLE
Duplicated links and some MACs

### ISSUE THREAD

**Issue by leruetkins** [glpi-project/glpi-inventory-plugin#187]
> @stonebuzz , Yes, same thing. I waiting fix for this. All ports are in the xml but they don't show up.

Can you open new issue, is not same problem as duplicate IP / MAC

Best regards

_Originally posted by @stonebuzz in https://github.com/glpi-project/glpi-inventory-plugin/issues/106#issuecomment-1180375212_

**Comment by leruetkins** [comment]
Hi

![изображение](https://user-images.githubusercontent.com/15270519/178428521-5caa0e12-65de-4c18-b58a-edbc9063898d.png)

After patches : 
https://github.com/glpi-project/glpi/pull/12171
https://github.com/glpi-project/glpi/pull/12172
https://github.com/glpi-project/glpi/pull/12176
I have problems with duplicated links and some duplicated MACs:
![изображение](https://user-images.githubusercontent.com/15270519/178429060-b20f6212-8ae4-4f26-b5aa-4430dde06154.png)
I attached 2 XML of these printers:
[netinventory.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/9090410/netinventory.zip)

**Comment by stonebuzz** [comment]
Hi @leruetkins 
thanks for inventory fiels.

For ```HP95FBB0``` MAC addresses are not identical

![image](https://user-images.githubusercontent.com/7335054/178447480-53fd5974-e7b8-4401-ab67-9f4c2b582e69.png)

For ```PR-009-M426dw``` MAC ```5c:ea:1d:9f:90:f7``` appears twice but they are defined on two different network port

![image](https://user-images.githubusercontent.com/7335054/178448040-8f8137c5-fd74-4695-9d10-d95e8efb055f.png)

```Name``` and ```Port number``` are different

**Comment by stonebuzz** [comment]
For links, you can post the configuration here

**Comment by leruetkins** [comment]
Yes, you're right, I didn't notice it right away :)
If I understood you correctly this my config for external links:
![изображение](https://user-images.githubusercontent.com/15270519/178449689-aaab9977-b133-4b68-a925-22e21167ea64.png)

**Comment by stonebuzz** [comment]
@leruetkins 

can you try this patch

```patch
diff --git a/src/Link.php b/src/Link.php
index 80cd5c155b..2c87a4f8b2 100644
--- a/src/Link.php
+++ b/src/Link.php
@@ -418,6 +418,20 @@ class Link extends CommonDBTM
                         'glpi_ipaddresses.name AS ip',
                     ],
                     'FROM'   => 'glpi_networknames',
+                    'JOIN' => [
+                        'glpi_networkports'   => [
+                            'ON' => [
+                                'glpi_networkports'   => 'id',
+                                'glpi_networknames'  => 'networkports_id', [
+                                    'AND' => [
+                                        'NOT' => [
+                                            'glpi_networkports.instantiation_type'  => NetworkPortAggregate::getType()
+                                        ]
+                                    ]
+                                ]
+                            ]
+                        ]
+                    ],
                     'INNER JOIN'   => [
                         'glpi_ipaddresses'   => [
                             'ON' => [
@@ -482,7 +496,10 @@ class Link extends CommonDBTM
                 ],
                 'WHERE'        => [
                     'glpi_networkports.items_id'  => $item->getID(),
-                    'glpi_networkports.itemtype'  => $item->getType()
+                    'glpi_networkports.itemtype'  => $item->getType(),
+                    'NOT' => [
+                        'glpi_networkports.instantiation_type'  => NetworkPortAggregate::getType()
+                    ]
                 ]
             ]);
             foreach ($iterator as $data2) {
@@ -500,7 +517,10 @@ class Link extends CommonDBTM
                 'FROM'   => 'glpi_networkports',
                 'WHERE'  => [
                     'glpi_networkports.items_id'  => $item->getID(),
-                    'glpi_networkports.itemtype'  => $item->getType()
+                    'glpi_networkports.itemtype'  => $item->getType(),
+                    'NOT' => [
+                        'glpi_networkports.instantiation_type'  => NetworkPortAggregate::getType()
+                    ]
                 ],
                 'GROUP' => 'glpi_networkports.mac'
             ];

```

**Comment by leruetkins** [comment]
Should I do netdiscovery again since I applied this patch because nothing change after update?

**Comment by stonebuzz** [comment]
on which printer ?

Best regards

**Comment by leruetkins** [comment]
> on which printer ?
> 
> Best regards

All priters displayed correctly. Thanks!

**Comment by leruetkins** [comment]
And now I have problem witch network devices Aruba Switch:
![изображение](https://user-images.githubusercontent.com/15270519/178463474-1475d3d0-c199-41cb-bcea-5821ad848234.png)

There is no ports with name eth0 or Ethernet:
![изображение](https://user-images.githubusercontent.com/15270519/178463849-ac479d23-5da7-4824-9966-f3c11f55be26.png)

**Comment by stonebuzz** [comment]
Please, can you closed this issue and create another one (with XML inventory file) for this problem ?

Best regards
