### ISSUE TITLE
No IP address in aruba network devices

### ISSUE THREAD

**Issue by leruetkins** [glpi-project/glpi-inventory-plugin#188]
And now I have problem with network devices Aruba Switches after networkdiscovery :
![изображение](https://user-images.githubusercontent.com/15270519/178464095-4fef7db8-14d8-427c-b191-0c4b069ed889.png)

There is no ports with name eth0 or Ethernet:
![изображение](https://user-images.githubusercontent.com/15270519/178463849-ac479d23-5da7-4824-9966-f3c11f55be26.png)

![изображение](https://user-images.githubusercontent.com/15270519/178464341-0a64bfd1-6ebe-4775-ab77-af19758cd938.png)

_Originally posted by @leruetkins in https://github.com/glpi-project/glpi-inventory-plugin/issues/187#issuecomment-1181560521_

**Comment by stonebuzz** [comment]
Hi @leruetkins can you paste here XML inventory file

Best regards

**Comment by leruetkins** [comment]
> Hi @leruetkins can you paste here XML inventory file
> 
> Best regards

Yes, Wait a minute)
[192.168.243.1.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/9092946/192.168.243.1.zip)

**Comment by stonebuzz** [comment]
oups sorry =)

thanks let me check

**Comment by stonebuzz** [comment]
So

All ports in the XML file have no IP except port 53

Whose import is refused by default, you need to allow it

![image](https://user-images.githubusercontent.com/7335054/178494229-9cfc5e88-dc53-44ca-9665-2323b976dc28.png)

Go to Setup > Dropdowns > Network port type
Search network port type named 'propVirtual' 

Re-run ```netInventory``` to see IP

![image](https://user-images.githubusercontent.com/7335054/178494828-38a1377d-b28a-41c3-bdb7-3377f6fadf08.png)

Best regards

**Comment by stonebuzz** [comment]
hi @leruetkins 


NetworkEquipment  IP issue is due to this patches

https://github.com/glpi-project/glpi/pull/12171
https://github.com/glpi-project/glpi/pull/12172
https://github.com/glpi-project/glpi/pull/12176

You need to revert it and follow guide from  ->  -> https://github.com/glpi-project/glpi-inventory-plugin/issues/189
