### ISSUE TITLE
Netinventory after discovery never launched

### ISSUE THREAD

**Issue by ASLLR** [glpi-project/glpi-inventory-plugin#191]
### Describe the bug

Hi everyone,
I am having trouble with SNMP tasks for netinventories. I migrated my SNMP inventory agent (with discoveries, inventory and vmware inventory modules) from fusioninventory-agent to glpi-agent and from glpi server i migrated fusioninventory to glpiinventory. 

Usually with fusion, I create a discovery task on the IP ranges which will be executed only once, then I create an inventory task which is supposed to match with the previous discovery in order to be able to carry out its inventories on a recurring basis on the discovered equipment.

now, the discovery is going correctly, the ip ranges are all in the successful state, but the inventory task never starts. On inventory task, the job execution tab is empty. Even if i force to launch task, on agent side i've _"[debug] NetInventory task execution not requested"_ 

it was working before the migration. Do you have any idea ? 

thank you in advance

### To reproduce

1. Migrate your plugin from fusioninventory to glpiinventory
2. Migrate your agent from fusioninventory-agent to glpi-agent
3. To be sure, delete and recreate the tasks and agent from glpi. 
4. Create netdiscovery task with ip range
5. Create netinventory task with the same ip range

you should never have the inventory task running

### Expected behavior

Have inventory task who's launch

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.3

**Comment by redddcyclone** [comment]
Have you assigned SNMP credentials for the IP ranges? I've ran into this problem last month and it happened because I forgot to assign SNMP credentials

**Comment by ASLLR** [comment]
Hi, thank you for your answer. 

yes the SNMP is linked with my IP range, i try with v2c and 3. I think otherwise the netdiscovery not work ? 

This is my screen for netdiscovery : 
![capture1](https://user-images.githubusercontent.com/37147055/180161573-6fa62caf-6418-4d64-aa80-19133734cffc.png)

and my screen for Inventory
![Capture2](https://user-images.githubusercontent.com/37147055/180161695-2f3f231f-98f6-40b1-a7ba-4ee7f47509d4.PNG)

Thank you in advance

**Comment by ASLLR** [comment]
Hi, I've the same comportment on fresh install.

Best regards

**Comment by ASLLR** [comment]
Hi @redddcyclone, i think you're not so wrong, i'm reinstalled fusioninventory plugin on GLPI 10.0.2 (by modifying setup.php (https://github.com/fusioninventory/fusioninventory-for-glpi/issues/3357)) and it's work with my glpi-agent. 

glpiinventory plugin want to centralise snmp creditials on standard inventory not on the plugin and i think this is the problem is the most change between fusioninventory and glpiinventory.

Can we have an answer from dev please ?

Best regards,

**Comment by redddcyclone** [comment]
Hi @ASLLR,

Yes, some things changed place with GLPI 10, like the agents config and SNMP credentials moving to the native inventory part. I hope that the devs make things more consistent on future releases.

**Comment by ASLLR** [comment]
Hi everyone, i work with Infotel on this issue and we realize that the issue comes from the netdiscovery module. Fusioninventory imports the mac address and the ip to be able to match with the names in the database and launch an netinventory. glpiinventory does not import IP\MAC.

Best regards

**Comment by stonebuzz** [comment]
Hi @ASLLR can you check this https://github.com/glpi-project/glpi-inventory-plugin/issues/175#issue-1293200246 
Best regards

**Comment by ASLLR** [comment]
Hi @stonebuzz  thank you for your answer, i think this is the same issue. I look forward to the release of these corrected versions.

Have a nice day,
