### ISSUE TITLE
The discovery job updates the printer but does not add it to the inventorying job

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi-inventory-plugin#192]
### Describe the bug

BTW @stonebuzz - can this patch be implemented already? https://github.com/glpi-project/glpi/pull/12197 ? 
Yesterday I installed the nightly build and this fix is ​​still missing.

The bug...
I have a printer whose IP address has changed. I have an entry in the discovery job log that the data has been updated, but the printer is still visible under the old IP address.

Discovery job log:

<html>
<body>

2022-07-20 11:30:44 | Running | [Detail] Update the item Drukarek K-0
-- | -- | --

</body>
</html>

And the result:

![obraz](https://user-images.githubusercontent.com/68922721/180206414-34236c3a-03f9-404a-8279-51907017c19f.png)

### To reproduce

1. I have a printer with e.g. an address 10.2.0.2
2. The address is changed to 10.3.2.2
3. I'm running the discovery task for the range 10.3.0.1 - 10.3.0.254
4. From job log: Running	[Detail] Update the item Drukarek [name]   < this is the name of the printer above
5. I check the printer information in assets.
6. Still old IP.
7. Running the inventory task does not change anything - it is not performed at all, because it does not see the printer with the address 10.3.2.2

### Expected behavior

IP address should be updated to the current one (and more - I generally don't see it updating printer data).

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

development release (See additional context below)

### GLPIInventory plugin

1.0.3

### Additional context

GLPI 10.0.3 (nightly from yesterday)

**Comment by WebGregGit** [comment]
Hi. No change. The Discovery task in the log reports that the printer has been updated. 

However, the printer is not added to the inventory job.

**Comment by stonebuzz** [comment]
Hi @WebGregGit 

after test (with https://github.com/glpi-project/glpi/pull/12197)
I do not reproduce

First step my printer have IP  as ```192.168.1.159```

![image](https://user-images.githubusercontent.com/7335054/183582483-8f897d7c-276e-4a70-91e5-ca4e496b3c60.png)

Second step my printer have IP  as ```192.168.1.59```

![image](https://user-images.githubusercontent.com/7335054/183582546-a51fb3a1-cad9-4b9e-81da-c38383fc5466.png)

Can you post here the printer inventory files (one per IP) to test it?

**Comment by stonebuzz** [comment]
@WebGregGit 
Do you still have the problem with only this fix https://github.com/glpi-project/glpi/pull/12197 ?

**Comment by WebGregGit** [comment]
[printer_0_543.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/9297329/printer_0_543.zip)

I changed the extension from xml to zip. The address in the file is 192.168.1.17, but the printer's address is changed to 192.168.1.21

**Comment by stonebuzz** [comment]
192.168.1.21 is the old IP ?

If I understand, GLPI keep old IP ?

**Comment by WebGregGit** [comment]
Old: 17
Now the printer have: 21

I still see the printer with the old address. If I delete it, it will appear with 21. But after changing the address, it will be 21 until the next deletion.

I implemented this change: [https://github.com/glpi-project/glpi/pull/12197/files](https://github.com/glpi-project/glpi/pull/12197/files)
Also have this: [https://github.com/glpi-project/glpi/pull/12181/files](https://github.com/glpi-project/glpi/pull/12181/files)

**Comment by stonebuzz** [comment]
Ok, so i confirm, from discovery networks infos are never update (to prevent deletion of data from the SNMP inventory)

For me if the printer changes IP, just restart an SNMP inventory 

The IP should be updated correctly

once the IP is changed, if you want to redo an SNMP inventory of this printer you will have to change the IP range of the task (if you use IP ranges)


Best regards

**Comment by WebGregGit** [comment]
> For me if the printer changes IP, just restart an SNMP inventory

What do you mean?



> once the IP is changed, if you want to redo an SNMP inventory of this printer you will have to change the IP range of the task (if you use IP ranges)

I don't understand that either. Yes, I rely on ranges. But how do I change the range if it is the same? Or another situation

ip range 1: 10.0.1.1 - 10.0.1.255
ip range 2: 10.0.2.1 - 10.0.2.255

Two tasks are set for both ranges.

The printer changes the address from 10.0.1.2 to 10.0.2.2

How do I change ranges when tasks are scanning full both ranges?



> Ok, so i confirm, from discovery networks infos are never update (to prevent deletion of data from the SNMP inventory)

I'm not sure, but I think it worked differently. This seems troublesome in large environments where addresses can be dynamic. 
Or what if someone maliciously substitutes the address (for example, hacking)? Or there are multiple administrators and one forgets to applay the change? 

The strength of GLPI is a certain automation of inventory of resources. And here you have to do something manually?

**Comment by stonebuzz** [comment]
If your task already manages IP range 1 and IP range 2.

When the printer changes IP, you only need to restart an SNMP inventory.

The discovery task is only used for new equipment.

Can you try this : 

- Delete / purge Printer
- Run discovery to create printer with old IP
- Run SNMP inventory to get full inventory data (page counter etc ...)
- Change the printer's IP (from printer)
- Run SNMP inventory to update network informations from GLPI


Best regards

**Comment by stonebuzz** [comment]
I tested it and it doesn't work and it can't work

Even if I restart the SNMP inventory (with IP range or directly on the printer)
Glpiinventory and GLPI only know the old IP  

So, agent try with old IP and printer are never update.

**Comment by WebGregGit** [comment]
> So, agent try with old IP and printer are never update.

But here [https://github.com/glpi-project/glpi-inventory-plugin/issues/192#issuecomment-1208979987](https://github.com/glpi-project/glpi-inventory-plugin/issues/192#issuecomment-1208979987) you tested and the address has been changed. 

Sorry, maybe it's because of me and the poor English skill, but I'm confused about what's going on :) 

> Can you try this :
> 
> * Delete / purge Printer
> * Run discovery to create printer with old IP
> * Run SNMP inventory to get full inventory data (page counter etc ...)
> * Change the printer's IP (from printer)
> * Run SNMP inventory to update network informations from GLPI

Yep I'm doing it all the time :) And even more.

* Delete / purge Printer
* Run discovery to create printer
* Run SNMP inventory to get full inventory data
* Change the printer's IP
* Run discovery again
* Run SNMP inventory again

And nothing changes. When you write "restart an SNMP inventory" you mean restarting a job or something else?

**Comment by stonebuzz** [comment]
> But here https://github.com/glpi-project/glpi-inventory-plugin/issues/192#issuecomment-1208979987 you tested and the address has been changed.

Because I tested importing an XML file instead of doing the full discovery/inventory task (I didn't have a printer at the time).

> When you write "restart an SNMP inventory" you mean restarting a job ("Force an Inventory" on the agent's website) or something else?

yes 

Let me check if i found a fix

**Comment by stonebuzz** [comment]
@WebGregGit can you apply this patches

- https://github.com/glpi-project/glpi/pull/12419
- https://github.com/glpi-project/glpi/pull/12197

Then do a complete discovery / inventory 

- Delete / purge Printer
- Run discovery to create printer with old IP
- Run SNMP inventory to get full inventory data (page counter etc ...)
- Change the printer's IP (from printer)
- Run discovery  (the IP management should change in GLPI)
- Run SNMP inventory to update network information from GLPI

**Comment by WebGregGit** [comment]
[https://github.com/glpi-project/glpi/pull/12197](https://github.com/glpi-project/glpi/pull/12197) - I had it before

Applied: [https://github.com/glpi-project/glpi/pull/12419](https://github.com/glpi-project/glpi/pull/12419)

Run the discovery... and it already looks much better. It added new printers that I didn't know about. The IP address has also been updated. Now only the inventory task and... I see duplicate IP addresses :) But only 1 mac ;) 

If I delete Management port, it will not be duplicated at the next inventory. But after changing the IP address, it clears this data and the first inventory task - adds with a doublet. You have to delete Management port manually.

**Comment by stonebuzz** [comment]
I don't know if this PR is the best way to handle this case.

Because at each discovery, all printer seen (even those that do not change their IP) loose network info (except management port) .....

**Comment by WebGregGit** [comment]
> I don't know if this PR is the best way to handle this case.

You mean I should write about it here: [https://github.com/glpi-project/glpi-inventory-plugin/issues/189](https://github.com/glpi-project/glpi-inventory-plugin/issues/189)  ?



> Because at each discovery, all printer seen (even those that do not change their IP) loose network info (except management port)

I do not have a problem with that (loosing network info). But I think IP should not be duplicated in the printer list.

**Comment by stonebuzz** [comment]
> I don't know if this PR is the best way to handle this case.

The best way to handle printer IP change (not IP duplication)


For duplicate IP, 
I have updated the PR https://github.com/glpi-project/glpi/pull/12197

can you try the new version ?

Best regards

**Comment by WebGregGit** [comment]
It looks great :)

After deployed this all doublet information has been deleted automatically. It looked like after deleting the printer, running the discovery job, but before inventory. 

I restarted the inventory task and it's clean now. 

I don't know yet how it will be after a few inventories. I'll let you know.

Thank You :)

**Comment by stonebuzz** [comment]
great =)

thanks for your time.

I am waiting for your feedback

**Comment by WebGregGit** [comment]
Hi @stonebuzz 

I changed the address several times, ran tasks (discovery nad inventory) in a different order and many times - everything seems to be working as expected. Thank you :)
