### ISSUE TITLE
bad data about operating systems

### ISSUE THREAD

**Issue by mjourdan** [glpi-project/glpi-inventory-plugin#193]
### Describe the bug

The following inventory information are shown in the web ui:

![Screenshot 2022-07-21 at 11-31-03 Ordinateurs - GLPI](https://user-images.githubusercontent.com/5346620/180186978-b8c86888-67d6-489c-a3aa-50120207ea49.png)

![image](https://user-images.githubusercontent.com/5346620/180188560-948a2d7b-742c-47b0-b975-9c86c25cb6a1.png)

## OS release

Here are the information directly available from the hosts:
```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

# cat /etc/debian_version
11.4
```

```
# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core)
```

## glpi-agent xml output

The `glpi-inventory` command returns correct output for both Debian 11 and Cent OS 7:

```
# glpi-inventory | sed -n '/<OPERATINGSYSTEM>/,/<\/OPERATINGSYSTEM>/p' | grep -E "<FULL_NAME>|<NAME>|<VERSION>"
[info] New inventory from test-debian-2022-07-21-11-26-36 for local0
      <FULL_NAME>Debian GNU/Linux 11 (bullseye)</FULL_NAME>
      <NAME>Debian GNU/Linux</NAME>
        <NAME>Europe/Paris</NAME>
      <VERSION>11.4</VERSION>
```
```
# glpi-inventory | sed -n '/<OPERATINGSYSTEM>/,/<\/OPERATINGSYSTEM>/p' | grep -E "<FULL_NAME>|<NAME>|<VERSION>"
[info] New inventory from test-centos.mutu.local-2022-07-21-11-27-22 for local0
      <FULL_NAME>CentOS Linux 7 (Core)</FULL_NAME>
      <NAME>CentOS Linux</NAME>
        <NAME>Europe/Paris</NAME>
      <VERSION>7.5.1804 (Core) </VERSION>
```

### Expected behavior

We would have expected the following:
- [ ] for Debian, the OS version to be correct (ie, to show 11.4 instead of "8.11")
- [ ] for both Debian and Cent OS, the operating system (short) name to be used instead of the full_name
- [ ] for both Debian and Cent OS, to distinguish between major_version (aka version_id in /etc/os-release) and (full) version
- [ ] for Windows Server, the OS version to appear in the appropriate column, rather than within the OS name column

### Operating system

Windows, Linux

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.3

**Comment by stonebuzz** [comment]
Hi @mjourdan 

can you post here XML inventory file to test ?

Best regards

**Comment by mjourdan** [comment]
Hi @stonebuzz,
How could I cleanup sensitive information from the inventory? I tried adding options such as `glpi-inventory --json --no-category=local_users,local_groups,envs` with no luck.

**Comment by stonebuzz** [comment]
Hi @mjourdan 
can you retry with

```
glpi-agent --json --no-category=local_users,local_groups,envs
```

**Comment by mjourdan** [comment]
Same, the output file still has those categories.

**Comment by stonebuzz** [comment]
I see, you use the plural form of categories.
```
glpi-agent --json --no-category=local_user,local_group,environment
```
use this to get categories list
```
glpi-agent  --list-categories
```

**Comment by mjourdan** [comment]
Indeed, I was using names I found in the xml or json markup. Works better now, thanks!

Please find attached the output of the command below:
```
glpi-inventory --no-category=user,environment,process,local_group,local_user,accesslog
```
[test-debian.txt](https://github.com/glpi-project/glpi-inventory-plugin/files/9300991/test-debian.txt)

**Comment by g-bougard** [comment]
Just share the result of:
```
glpi-inventory --partial os
```

**Comment by g-bougard** [comment]
Anyway, there was a bug with OS versions which is fixed by: glpi-project/glpi#12390
This bug should explain why for example you have OS version 8.11 for Debian 11.
So try to apply the patch but you should probably also apply glpi-project/glpi#12146 just before otherwise you'll have a hunk failed.

**Comment by mjourdan** [comment]
Hi, thank you for the fix!

**Comment by ASLLR** [comment]
Hi everyone, i've try the new version of glpi-invetory-plugin. For this issue, the linux part seem to be corrected but for Windows we lack of homogeneity : 

![image](https://user-images.githubusercontent.com/37147055/190963261-a0562c27-cd39-4e26-b41b-5dbb6246a06b.png)

Thank you in advance,

**Comment by g-bougard** [comment]
Hi @ASLLR 

what agents are you using on each computers ? If you don't use glpi-agent on some, you still need to switch to this agent.

Can you clarify where it lacks of homogeneity in you screenshot ? I mean where this is okay and where this is not (and again check what is the used agent where this is not correct).
