### ISSUE TITLE
Error installing plugin 1.0.3

### ISSUE THREAD

**Issue by glpibr** [glpi-project/glpi-inventory-plugin#195]
### Describe the bug

When installing the plugin it complains about third-party tables that it shouldn't even analyze, aborting the installation.

- Erro na consulta ao banco de dados: UPDATE `glpi_plugin_vservices_itemtypefinancial` SET `itemtype_id` = 'Agent' WHERE `itemtype_id` = 'PluginGlpiinventoryAgent' - Erro é Truncated incorrect DOUBLE value: 'PluginGlpiinventoryAgent' 

![image](https://user-images.githubusercontent.com/22614882/181306474-efacf520-130c-4051-be3c-ea32f0fee5ef.png)

### To reproduce

I just downloaded the plugin and had it installed on a production copy base.

### Expected behavior

Plugin should have been installed.

### Operating system

Linux

### GLPI Agent version

1.3

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.3

### Additional context

I tried to repeat the process and the result is always the same.
Removing the third party plugin tables the process works but is not ideal due to loss of sensitive data to the service desk.

**Comment by cedric-anne** [comment]
Hi,

Could you test #195 ?

**Comment by stonebuzz** [comment]
Hi @glpibr 
have you try the fix?

Best regards
