### ISSUE TITLE
Dynamics groups update throught taskscheduler doesn't work

### ISSUE THREAD

**Issue by Tony710** [glpi-project/glpi-inventory-plugin#198]
### Describe the bug

Dynamics groups used to package deployement don't seems to update as needed.
After taskscheduler execution, computers_id_cache of glpi_plugin_glpiinventory_deploygroups_dynamicdatas table is empty.
![image](https://user-images.githubusercontent.com/78087722/182533920-67b588b7-cf13-403d-ba5d-b2ea6517a3e9.png)
If computers_id_cache is empty, when glpi-agent to Deployement tasks, prepared task can't be processed  because : 
"This agent no longer belongs to the list of actors for this job"
![image](https://user-images.githubusercontent.com/78087722/182534670-825e4a59-bb8d-4dd0-b9b7-df2000ecfbc3.png)

If, I manually lunch taskscheduler task in automatic actions, computers_id_cache  is correctlly populate and deployment tasks are OK.
 
In pluginGlpiinventory-jobs.log, I can find that when I lunch manually taskscheduler, my glpi user id :1500 appears but when executed with scheduler no user id is used. -> Could this be the source of the problem?
![image](https://user-images.githubusercontent.com/78087722/182535519-3aa60686-fa3b-426b-adf0-27c6c43e8792.png)

### To reproduce

Dynamic group creation
Package creation
Deployment task creation
In Computer / Tasks & Groups tab, you can show dynamic group membership of the computer.
Let automatic actions to lunch taskscheduler task.
In Computer / Tasks & Groups tab, dynamic group membership of the computer disappear.

### Expected behavior

Dynamics groups update need to work

### Operating system

Windows

### GLPI Agent version

1.3

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.3

**Comment by stonebuzz** [comment]
Hi @Tony710 
can you try this command from glpi root folder

```php
php front/cron.php --force taskscheduler
```
and check if  ```computer_id_cache``` is empty ?

can you paste here task and automatic action configuration ?

Best regards

**Comment by Tony710** [comment]
Hi @Stonebuzz,
I confirme that when I execute the command below from glpi root folder, computer_id_cache become empty.
"C:\Program Files\PHP\php.exe" front/cron.php --force taskscheduler
If I manually run taskscheduler in automatic action or if execution mode is set to GLPI and after task is run, computer_id_cache column is re-populate.
![image](https://user-images.githubusercontent.com/78087722/185193176-1318266d-97df-4824-a257-da05137849ad.png)
Best regards

**Comment by stonebuzz** [comment]
Hi @Tony710 
Can you post here crontab configuration ?

Best regards

**Comment by Tony710** [comment]
Hi @stonebuzz,

Please find below the xml file content of the schedulded task export.
In Windows tasks scheduler this task "GLPI CLI Scheduled Tasks" is lunch with system account.
In Glpi automatic actions, excepted "taskscheduler",  all other tasks are processed in CLI exécution mode without any problem.

![image](https://user-images.githubusercontent.com/78087722/185339963-2799813b-9bf4-41ce-aa50-578f3a0a2de9.png)


```
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2015-04-14T09:31:15.446727</Date>
    <Author>XXXXXXXXXXXXXX</Author>
    <Description>Taches pour l'éxecution des taches planifiées CLI de GLPI</Description>
    <URI>\GLPI\GLPI-PROD\GLPI CLI Scheduled Tasks</URI>
  </RegistrationInfo>
  <Triggers>
    <CalendarTrigger>
      <Repetition>
        <Interval>PT1M</Interval>
        <StopAtDurationEnd>false</StopAtDurationEnd>
      </Repetition>
      <StartBoundary>2022-06-07T05:00:00</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByDay>
        <DaysInterval>1</DaysInterval>
      </ScheduleByDay>
    </CalendarTrigger>
    <BootTrigger>
      <Repetition>
        <Interval>PT1M</Interval>
        <StopAtDurationEnd>false</StopAtDurationEnd>
      </Repetition>
      <Enabled>true</Enabled>
    </BootTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-18</UserId>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>"C:\Program Files\PHP\php.exe"</Command>
      <Arguments>-f "C:\GLPI-PROD\glpi\front\cron.php"</Arguments>
    </Exec>
  </Actions>
</Task>

```

**Comment by stonebuzz** [comment]
Do you have errors in the logs of GLPI (php-error, sql-error)

**Comment by Tony710** [comment]
Each time I force taskscheduler executiton  : 
`php.exe  "C:\GLPI-PROD\glpi\front\cron.php" --force taskscheduler`
I can find 4 same errors on php-error as below and nothing in sql-error.
```
[2022-08-18 10:46:40] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "REQUEST_URI" in C:\GLPI-PROD\glpi\plugins\phpsaml\setup.php at line 128
  Backtrace :
  src\Plugin.php:288                                 plugin_init_phpsaml()
  src\Plugin.php:238                                 Plugin::load()
  inc\includes.php:86                                Plugin->init()
  front\cron.php:41                                  include()
```
I hunderstand that this issue is due to phpsaml plugin activation.
I have try to disable  phpsaml plugin : errors no longer appear but the result is the same -> computer_id_cache become empty.

**Comment by Tony710** [comment]
I confirm that it works

**Comment by stonebuzz** [comment]
Can you retry by deactivating all your plugins ?

**Comment by Tony710** [comment]
Well done!
When I disable behaviors plugin 2.7.2, this work like a charm.

**Comment by stonebuzz** [comment]
Can you disable this options from behavior configuration and retry
![image](https://user-images.githubusercontent.com/7335054/185396860-368dab87-8f57-48de-b79d-f511b513038a.png)

Best regards

**Comment by stonebuzz** [comment]
@Tony710 can you check this -> https://github.com/yllen/behaviors/pull/43

is it a pull request for ```behaviors```

**Comment by Tony710** [comment]
@stonebuzz
By disabling : Show my assests options, this work.
Thanks a lot
