### ISSUE TITLE
No collect job enabled

### ISSUE THREAD

**Issue by 33hig** [glpi-project/glpi-inventory-plugin#199]
### Describe the bug

When running an inventory to my glpi server only the inventory task works, the collect and the deploy are apparently not enable or supported by my server even though they are activated on the plugins, if anyone encountered that and know how to fix it that would be a lot of help as I tried everything I could think of right now.

### To reproduce

[Fri Aug  5 11:25:46 2022][info] target server0: server http://server-glpi/glpi/marketplace/glpiinventory/
[Fri Aug  5 11:25:46 2022][info] sending contact request to server0
[Fri Aug  5 11:25:47 2022][info] sending prolog request to server0
[Fri Aug  5 11:25:48 2022][info] running task Deploy
[Fri Aug  5 11:25:48 2022][info] No Deploy job enabled or Deploy support disabled server side.
[Fri Aug  5 11:25:50 2022][info] running task Inventory
[Fri Aug  5 11:25:50 2022][info] New inventory from PC.local-2022-08-05-10-43-59 for server0
[Fri Aug  5 11:27:01 2022][info] running task Collect
[Fri Aug  5 11:27:02 2022][info] No Collect job enabled or Collect support disabled server side.
[Fri Aug  5 11:27:02 2022][info] target server0: next run: Sat Aug  6 11:20:35 2022 - http://server-glpi/glpi/marketplace/glpiinventory/
[Fri Aug  5 11:27:02 2022][info] GLPI Agent memory usage: WSS=3354624 PFU=132329472
[Fri Aug  5 11:27:02 2022][info] running task Deploy: storage maintenance event

### Expected behavior

Collecting information from my computer and deploying them directly into my glpi via the agent

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.3

**Comment by g-bougard** [comment]
Hi @33hig 
do you have any defined Deploy or Collect task in the plugin ? And if yes, is the agent associated with the defined tasks ?

**Comment by 33hig** [comment]
Hi @g-bougard I do have defined Deploy and collect task, howerver I dont know how to check if the agent is assigned with them
