### ISSUE TITLE
Discovery task : computers denied

### ISSUE THREAD

**Issue by fpelat** [glpi-project/glpi-inventory-plugin#200]
### Describe the bug

my discovery task works fine.
But each computer import  are denied

![image](https://user-images.githubusercontent.com/78596662/183714918-0066fb7c-1bab-475e-acea-ef89f706d04a.png)

in the asset refused by import rules all fiels are empty

![image](https://user-images.githubusercontent.com/78596662/183715359-f0f7bf17-ba15-43ff-bc40-f86e88be36b1.png)

when i dowload the inventory file, information are correct
![image](https://user-images.githubusercontent.com/78596662/183715851-7425739f-a28e-4362-9a1f-6d1419c61932.png)

why there is no link between inventory field and computer data checked by the rules?
when i disabled all denied rules , computers are imported with no name neither data only a date.

### To reproduce

running discovery task
check asset refused by rules
all computer are refused

### Expected behavior

computer import success

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.4

### Additional context

tested with fusin agent with the same result

**Comment by stonebuzz** [comment]
Hi @fpelat 

Discovery module / SNMP inventory is only for ```NetworkEquipement``` or ```Printer```.

This asset seems to be a ```Computer```  is that right? 

You need to install glpi-agent on it and make a classic inventory

Best regards

**Comment by fpelat** [comment]
Hi @stonebuzz 


Yes assets are computer but in my opinion glpi-inventory can handle it, there are rules for import and link computers
![image](https://user-images.githubusercontent.com/78596662/183856032-71d135b8-a004-4f16-9d12-1f3fe876b3f4.png)

my objective is to discover partner's computers on specific network but not rules by my organisation ( i cant install anything on it).
I juste want to monitor the number of these machine, so data in the inventory file are sufficient. 
I dont understand why imports of these inventory file are denied .

Thank for your help

**Comment by stonebuzz** [comment]
inventory file are denied because of this rule
![image](https://user-images.githubusercontent.com/7335054/183857708-847cbf7c-5c8d-4e74-9141-dbbb9d67e622.png)

You can try to disable it, I don't know what will happen

But glpiinventory is only useful for NetworkEquipement and Printer inventory

The rules you show are for the native inventory of GLPI, dedicated to computers

**Comment by fpelat** [comment]
thanks for your answer.
when i disabled it , it created computer asset with no information.
![image](https://user-images.githubusercontent.com/78596662/183859619-3ab8f739-cf9e-4aa9-b0c1-719b0965f0d9.png)

**Comment by stonebuzz** [comment]
Yes, discovery task is not designed for this (i mean for Computer discovery)

globally, glpiinventory is not designed for computer discovery or inventory

Best regards
