### ISSUE TITLE
SNMP Inventory does not create the tasks

### ISSUE THREAD

**Issue by Venkarian** [glpi-project/glpi-inventory-plugin#208]
Hello,
I have installed a GLPI 10.0.2 instance with the GLPI Plugin 1.0.3. I have the agent 1.0.4 install on a Windows 2019 Server installed as a service.
When I create a task using SNMP Discovery everything works fine, all the devices are collected through SNMP.
But with the SNMP inventoring task properly setup it does not creates the Job. Nothing appears in the execution Job.

Can you help me on this ?

**Comment by g-bougard** [comment]
Hi @Venkarian 

please, request basic help from the community on the forum: https://forum.glpi-project.org/

This issue tracker is really for bugs.
