### ISSUE TITLE
Net-Discovery & SNMPCredentials

### ISSUE THREAD

**Issue by Tony710** [glpi-project/glpi-inventory-plugin#209]
### Describe the bug

Net-discoverytask doesn't seems to work as expected
After execution, Network equipement are found and updated
![image](https://user-images.githubusercontent.com/78087722/185852704-19c85d0b-3f6a-4a51-96e1-8f26780474fc.png)
and "NetworkEquipment update (by serial)" import rule are verified. 
![image](https://user-images.githubusercontent.com/78087722/185853015-07dfa2a1-9855-4ab9-a032-dff43425fc48.png)
![image](https://user-images.githubusercontent.com/78087722/185853409-458596f1-e99a-4ae5-8b32-f3dd8980dcdb.png)
But, properties of the updated network equipement doesn't seems to be updated.
For example : the "snmpcredentials_id" columns of "glpi_networkequipments" table is not updated.
When performing  glpi-netdiscovery on glpi agent, I don't identify any problem
```
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.4-1)
[debug] initializing job 1
[debug] initializing block XXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXX
[debug] Current run expiration timeout: soon
[debug] creating 1 worker threads
[debug] [thread 1] creation
[debug] [thread 1] #1, scanning XXX.XXX.XXX.XXX
[debug] [thread 1] #1, full match for sysobjectID .1.3.6.1.4.1.4526.100.10.5 in database
[debug] [thread 1] #1, - scanning XXX.XXX.XXX.XXX with SNMP, credentials 1: success
[debug] [thread 1] #1, - scanning XXX.XXX.XXX.XXX with netbios: no result
[debug] [thread 1] #1, - scanning XXX.XXX.XXX.XXX with echo ping: success
[debug] [thread 1] #1, - scanning XXX.XXX.XXX.XXX in arp table: no result
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHPORT />  <AUTHPROTOCOL />  <AUTHSNMP>1</AUTHSNMP>
      <CONTACT>XXXXXXXXXXXXXXXX</CONTACT>
      <DESCRIPTION>GS748TS</DESCRIPTION>
      <DNSHOSTNAME>XXX.XXX.XXX.XXX</DNSHOSTNAME>
      <FIRMWARE>V5.2.0.11</FIRMWARE>
      <IP>XXX.XXX.XXX.XXX</IP>
      <IPS>
        <IP>0.255.255.1</IP>
        <IP>XXX.XXX.XXX.XXX</IP>
      </IPS>
      <LOCATION>XXXXXXXXX</LOCATION>
      <MAC>74:44:01:d4:4a:7d</MAC>
      <MANUFACTURER>Netgear</MANUFACTURER>
      <MODEL>GS748TS</MODEL>
      <SERIAL>XXXXXXXXXXXXXX</SERIAL>
      <SNMPHOSTNAME>XXXXXXXXX</SNMPHOSTNAME>
      <TYPE>NETWORKING</TYPE>
      <UPTIME>27 days, 19:22:18.00</UPTIME>
    </DEVICE>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
[debug] [thread 1] termination
[debug] All netdiscovery threads terminated
```
No errors on php-errors and sql-errors.

### To reproduce

Create IP RANGE for dicorvery
Create SNMPCredentals and link It to IP Range
Create and run Discovery task targeted on Networking equipment.

### Expected behavior

the "snmpcredentials_id" columns of "glpi_networkequipments" table must be updated to performe Net-Inventory

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.3

**Comment by stonebuzz** [comment]
Hi @Tony710 

Already fixed by -> https://github.com/glpi-project/glpi/pull/12181/files

The fix will be available in the next release of GLPI.

Best regards

**Comment by Tony710** [comment]
Hi @stonebuzz,
I have test the fix by updating these files : 
src/CommonDBTM.php
src/Inventory/Asset/Printer.php
templates/components/form/inventory_info.html.twig

![image](https://user-images.githubusercontent.com/78087722/185876133-4ddad438-726e-4f41-85e6-0e82d50074a6.png)

But, after new discovery task, SnmpCredentials are not updated for my networking equipement.
![image](https://user-images.githubusercontent.com/78087722/185876502-8d1fe164-b162-4f68-9623-218dc5bc1e12.png)

**Comment by stonebuzz** [comment]
@Tony710 

can you try this -> https://github.com/glpi-project/glpi/pull/12460

NB :  only update auto update system, SNMP credential and last inventory update

to prevents discoveries to remove all ports, IPs and so on found with network inventory

**Comment by stonebuzz** [comment]
@Tony710 
how did you apply patch ?

I did not reproduce ATM.

Can you post here MainAsset.php ?

Best regards

**Comment by Tony710** [comment]
@stonebuzz,
Please find MainAsset.php in the Zip file
[MainAsset.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/9394214/MainAsset.zip)

**Comment by stonebuzz** [comment]
I do not reproduce your problem
how did you apply this patch?

You will need PR too -> https://github.com/glpi-project/glpi/pull/12466

To prevent lock of ```last_inventory_update``` (you need to check if lock is already added here ```my_glpi/front/lockedfield.php```

Best regards

**Comment by Tony710** [comment]
@stonebuzz,
It's ok, I have make somme changes on MainAsset.php :
removing : `use Lockedfield;`
removing : ```
        //locked fields
        $lockedfield = new Lockedfield();
        $locks = $lockedfield->getLocks($this->item->getType(), $items_id);
        foreach ($this->data as &$data) {
            foreach ($locks as $lock) {
                if (property_exists($data, $lock)) {
                    unset($data->$lock);
                }
            }
        }
```
remplacing :` $input = $this->handleInput($val); ` by `$input = (array)$val;`
[MainAsset.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/9402999/MainAsset.zip)
