### ISSUE TITLE
Disappearing agent and linked item

### ISSUE THREAD

**Issue by conjarsa** [glpi-project/glpi-inventory-plugin#211]
### Describe the bug

When doing a network discovery or a network inventory, forcing the start of said task will remove the item linked to the agent from the agent list, making the agent unable to carry out the task, and making the agent unlisted in the task's actors list (img2). However, neither the agent nor its item (here, a computer) are not deleted. Only their link is.

Before running the task:
![image](https://user-images.githubusercontent.com/78089095/185929208-5770dc1b-e9de-48e4-8d3f-4c30279d6923.png)

After running the task. Note that the agent does not disappear from the working actors, even if its unable to be added in back.
![image](https://user-images.githubusercontent.com/78089095/185929227-a6bf88ef-9943-4b7e-b161-b434347385fd.png)

The only way I found to add back the link is to execute the `sudo glpi-agent` command. I want to point out that the `glpi-agent` process is already running as a daemon.

I tried locking the agent, to no avail.

I did not try any other task (VMware, WakeOnLan, ...).

Saddly, there is no relevant log file.

Thanks in advance.

### To reproduce

1. Add an agent to a network discovery or network inventory.
2. Force the start of the task.
3. The linked item of the agent should disappear from the agent list in one or two minutes, and the task isn't carried out.

### Expected behavior

The link between the agent and its linked item should remain unaffected.
The task should be carried out.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.3

**Comment by stonebuzz** [comment]
Hi @conjarsa 

Can you check from database if agent loose ```itemtype``` value from ```glpi_agent``` table ?

Best regards

**Comment by conjarsa** [comment]
The itemtype value is replaced to a `NetworkEquipment` value. It was a `Computer` before.

Before (on agent list):
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/78089095/185938084-fbf903ef-93ca-4cfc-89ac-746aac7c41e6.png)

After (on SQL database):
![MicrosoftTeams-image](https://user-images.githubusercontent.com/78089095/185938132-0a678d41-3f83-4c7e-bd26-988a504c0138.png)

During network discovery and network inventory, there are multiple NetworkEquipments somehow being inventoried as Computers.

I'd like to point out that this issue does not show up on every network discovery and inventory, only for a few of them. We think that it happens whenever the agent does not know what type of equipment it is inventorying.

**Comment by stonebuzz** [comment]
We have a fix for this
can you try this -> https://github.com/glpi-project/glpi/pull/12050

Best regards

**Comment by conjarsa** [comment]
I don't understand, isn't this fix already in the version 1.0.3 which I'm using?

**Comment by stonebuzz** [comment]
No, this is a GLPI fix and the fix will be released in the next version

**Comment by conjarsa** [comment]
Okay, I'm trying it.

**Comment by conjarsa** [comment]
It works! The link stays and the task is carried out! However, some imported assets are still of the wrong type (Computer instead of Phone), and I fail to see why:
![image](https://user-images.githubusercontent.com/78089095/185947200-5c7ddea5-0a49-4f69-9ca1-6cda0eb8a539.png)

**Comment by stonebuzz** [comment]
Either they are really computers and in this case the plugin is not made for this use case (you have to install the agent on the computer in question)

Or the SNMP community provided to the IP range does not allow the agent to deduce the type of equipment (printer, network equipment) during discovery -> you need to check SNMP community

**Comment by stonebuzz** [comment]
I close this issue concerning the  ```itemtype``` of the agent
Please open a new issue (if needed) concerning the equipment types (for import refused)

**Comment by conjarsa** [comment]
Thanks!
