### ISSUE TITLE
Video conference devices can't be imported

### ISSUE THREAD

**Issue by conjarsa** [glpi-project/glpi-inventory-plugin#213]
### Describe the bug

Some of our assets are Cisco video conference devices. When using a network discovery on their IP ranges, they show up as `type=Video`, but their import is denied by the "NetworkEquipment import denied" rule:

(The Xs are for anonymization purposes)
![image](https://user-images.githubusercontent.com/78089095/186354489-7f24eff7-beec-4b6d-8af7-53af93131c50.png)

![image](https://user-images.githubusercontent.com/78089095/186196671-aaca54fc-ffde-4462-8aad-3f55e9183d71.png)

I tried adding a new `Video` object type with matching import rules using the GenericObject plugin. As I saw that the object was created as `genericobjectvideo`, I changed its ID into `Video` to match what the network discovery was showing me. However, my devices are still denied by a NetworkEquipment rule.

### To reproduce

1. Make a network discovey on IP ranges that have Cisco video conference devices.
2. (Optional) Create a `Video` object using the GenericObject plugin.
3. (Optional) Create rules for importing this object.
4. (Optional) Try again step 1.

### Expected behavior

The device import should still be denied, but by the "Global import denied" rule instead.
or (if using the GenericObject plugin)
The device should be added as a Video object.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.3

**Comment by stonebuzz** [comment]
Hi @conjarsa 

glpiinventory is only dedicated (for the moment) to the NetworkEquipement (ie: switch) and Printers inventory.

your asset is refused because glpi-agent can't retrieve it's ```type``` (printer or networkequipement)

The development of this feature should be funded.

Please contact us here if you need further information -> https://portal.glpi-network.com/contact-us

Best regards
