### ISSUE TITLE
Assets present in both "Network devices" and "Unmanaged devices" lists and having their network ports undetected

### ISSUE THREAD

**Issue by conjarsa** [glpi-project/glpi-inventory-plugin#214]
### Describe the bug

A few of our network devices have a strange behavior when doing network discoveries and network inventories. Firstly, they are both listed in the "Network devices" tab of our assets, and in the list of unmanaged devices. Secondly, even if their management port can be retrieved thanks to https://github.com/glpi-project/glpi/pull/12050, network inventories will not add their network ports, instead giving the php error I put in `Additional context`.

What is really strange is that the same type of device, fitted with the exact same configuration will be discovered and inventoried properly on different IP ranges. And those IP ranges are working properly, as the other network devices in them are filled with all information.

### To reproduce

0. (Optional?) Fix the network discoveries using https://github.com/glpi-project/glpi/pull/12050
1. Launch a network discovery.
2. Launch a network inventory.
I know this is unhelpful, we just do not understand why such thing happens so randomly.

### Expected behavior

Every network port of our network devices should be filled up by network inventories, and those devices should not be present both in the "Network devices" and "Unmanaged devices" list.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.3

### Additional context

Relevant log file:
```
[2022-08-25 09:31:05] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to array_is_list() must be of the type array, string given, called in /var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php/Converter.php on line 1419 in /var/www/>  Backtrace :
  ...ect/inventory_format/lib/php/Converter.php:1419 array_is_list()
  ...ject/inventory_format/lib/php/Converter.php:380 Glpi\Inventory\Converter->convertNetworkInventory()
  ...ject/inventory_format/lib/php/Converter.php:323 Glpi\Inventory\Converter->convertTo01()
  src/Inventory/Inventory.php:141                    Glpi\Inventory\Converter->convert()
  src/Inventory/Request.php:265                      Glpi\Inventory\Inventory->setData()
  src/Inventory/Request.php:250                      Glpi\Inventory\Request->network()
  src/Inventory/Request.php:98                       Glpi\Inventory\Request->networkInventory()
  src/Agent/Communication/AbstractRequest.php:298    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:235    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:86                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()
```

**Comment by stonebuzz** [comment]
Hi @conjarsa 
can you provide XML fields from Discovery and NetInventory (at each step)

I do not reproduce ATM.

Best regards
