### ISSUE TITLE
the task of preparing an snmp scan job is not being performed

### ISSUE THREAD

**Issue by Smiley-k** [glpi-project/glpi-inventory-plugin#217]
### Describe the bug

when creating a network discovery rule, task preparation is performed, and the task itself is executed when the agent is launched, but when creating an snmp scan, preparation for scanning is not started

I attach video

https://monosnap.com/file/lMRxDAqSISkCtJdzqKqxpFV90DoUXZ

### To reproduce

create an snmp scan task and force the task

### Expected behavior

creating a task preparation for execution

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.4

**Comment by stonebuzz** [comment]
Hi @Smiley-k 
have you read this -> https://github.com/glpi-project/glpi-inventory-plugin/issues/175 ?

Best regards

**Comment by Smiley-k** [comment]
Dear @stonebuzz 

Yes, but I didn't understand what actions should I do?
