### ISSUE TITLE
Errors with Printer discovery and inventory

### ISSUE THREAD

**Issue by 575544685** [glpi-project/glpi-inventory-plugin#218]
### Describe the bug

I create a net discovery and a net inventory task on GLPI server to import a network printer via glpi inventory plugin. The discovery job is done and I can see the printer on GLPI server. The inventtory job fails with error message "device have no IP ". I check the printer net discovery job created. It is really without IP address.

Then I do a local net inventory from the agent and upload to GLPI server by injector command . The printer is with correct IP address now.  Next step I hope do a daily net inventory task to update the page numbers of the printer.  I run the inventory task above again. The task runs but the status of the printer does not update.  I try several time. The results are same. The net inventory task does not change anything.
![image](https://user-images.githubusercontent.com/111935528/188112473-9ce00cfd-4e4c-4e68-b16b-a4843795810d.png)

### To reproduce

1. Create a snmp inventory task on printer.
2. Run the task and then check the status of the printer (page numbers etc.)

### Expected behavior

The printer status should be updated after snmp inventory.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.3

**Comment by stonebuzz** [comment]
Several fix have been added to glpi and plugin
can you retry with GLPI ntghly build -> https://nightly.glpi-project.org/glpi/
and glpi-inventory-plugin develop branch

Best regards
