### ISSUE TITLE
Rules for assigning an item to an entity create a new location

### ISSUE THREAD

**Issue by jpdenss** [glpi-project/glpi-inventory-plugin#221]
### Describe the bug

Rules for assigning an item to an entity are misbehaving. After creating the rule and running agent 1.4, the discovery finds my device, but the rule that associates it with a location creates a new location, as attached.

### To reproduce

Create a location
![Captura de tela 2022-09-16 152306](https://user-images.githubusercontent.com/40672533/190706469-8fec9278-2fab-478e-9ec3-2e106b4c9e23.jpg)

I create a rule to associate a device name with a location
![Captura de tela 2022-09-16 145720](https://user-images.githubusercontent.com/40672533/190705509-8031eaac-ea90-47ac-9ce0-260af9d25e19.jpg)

I run the agent to perform network discovery and create my device
![Captura de tela 2022-09-16 145921](https://user-images.githubusercontent.com/40672533/190705537-471a84d2-4da6-4567-a0b1-3603ec9a6d3a.jpg)

The device is found but is associated with a new location, with the index name of the location that should be associated.
![Captura de tela 2022-09-16 150021](https://user-images.githubusercontent.com/40672533/190705977-ca3002e9-38a0-480c-a034-94f7a5427f9b.jpg)

Data presented in the database
![Captura de tela 2022-09-16 150152](https://user-images.githubusercontent.com/40672533/190706073-595b21b2-3071-4324-9ffc-c019db550019.jpg)

### Expected behavior

Discover devices and associate them by rules with locations

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

1.0.4

### Additional context

GLPI 10.0.3

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/issues/12758
