### ISSUE TITLE
error when installing glpi-inventory-plugin

### ISSUE THREAD

**Issue by jp-weiss** [glpi-project/glpi-inventory-plugin#222]
Hello,
When I try to install the glpi-inventory-plugin 1.0.4 with command _php bin/console glpi:plugin:install --username=glpi glpiinventory_, I got the message :

> Uncaught Exception Error: Class 'PluginGlpiinventoryMapping' not found in /var/www/glpi/plugins/glpiinventory/install/update.php at line 3893

OS : Debian 11.5
GLPI : 10.0.3

Do I miss something ?
Sincereley,

Jean-Pierre

**Comment by stonebuzz** [comment]
Hi @jp-weiss 

from your DB have you a "glpi_plugin_fusioninventory_mappings" or "plugin_glpiinventory_mappings_id" table ?

Best regards

**Comment by jp-weiss** [comment]
Hi Stanislas, 

No, neither of those tables. 

The only glpiinventory
tables that I have are : 

| glpi_plugin_glpiinventory_agentmodules |
|
glpi_plugin_glpiinventory_agents |
|
glpi_plugin_glpiinventory_computerlicenseinfos |
|
glpi_plugin_glpiinventory_computerremotemanagements |
|
glpi_plugin_glpiinventory_configlogfields |
|
glpi_plugin_glpiinventory_configs |
|
glpi_plugin_glpiinventory_dblockinventories |
|
glpi_plugin_glpiinventory_dblockinventorynames |
|
glpi_plugin_glpiinventory_dblocksoftwares |
|
glpi_plugin_glpiinventory_dblocksoftwareversions |
|
glpi_plugin_glpiinventory_entities |
|
glpi_plugin_glpiinventory_ignoredimportdevices |
|
glpi_plugin_glpiinventory_inventorycomputerblacklists |
|
glpi_plugin_glpiinventory_inventorycomputercomputers |
|
glpi_plugin_glpiinventory_inventorycomputercriterias |
|
glpi_plugin_glpiinventory_inventorycomputerstats |
|
glpi_plugin_glpiinventory_ipranges |
|
glpi_plugin_glpiinventory_ipranges_configsecurities |
|
glpi_plugin_glpiinventory_locks |
|
glpi_plugin_glpiinventory_networkportconnectionlogs |
|
glpi_plugin_glpiinventory_networkportlogs |
|
glpi_plugin_glpiinventory_networkports |
|
glpi_plugin_glpiinventory_networkporttypes |
|
glpi_plugin_glpiinventory_rulematchedlogs |
|
glpi_plugin_glpiinventory_taskjobs |
|
glpi_plugin_glpiinventory_unmanageds 

Best regards,Message ID:
***@***.***>

>

**Comment by stonebuzz** [comment]
Are you doing a first installation of the "Glpiinventory" plugin with "FusionInventory" installed?

**Comment by jp-weiss** [comment]
No, Fusioninventory was not installed. Only OCSInventory

**Comment by trasher** [comment]
Then make sur to remove all fusioninventory and glpiinventory tables, and run install again

**Comment by jp-weiss** [comment]
It works, thanks.
