### ISSUE TITLE
Deployment tasks issue with agent based URL 

### ISSUE THREAD

**Issue by Tony710** [glpi-project/glpi-inventory-plugin#223]
### Describe the bug

![image](https://user-images.githubusercontent.com/78087722/191962107-957cb22f-f2b5-487b-ac45-00b5b7717f2c.png)
For security needs, I use different URL for connecting to Glpi (glpi.XXXXX) and for  agent inventory (Inventory.XXXXX)
If I don't set the agent based URL in Entity configuration, deployment tasks use glpi.XXXXX URL
```
[Fri Sep 23 14:45:23 2022][info] running task Deploy
[Fri Sep 23 14:45:23 2022][debug2] https://inventory.XXXXXXXXXXX.XXXX/plugins/glpiinventory/?action=getConfig&machineid=XXXXXXXXXXXXXXXXXXX-2022-06-27-16-10-10&task[Deploy]=2.10
[Fri Sep 23 14:45:23 2022][debug2] Looking for Win32_LogicalDisk class WMI objects
[Fri Sep 23 14:45:23 2022][debug] Free space on C:\Program Files\GLPI-Agent\var\https..__XXXXXXXXXXXX_plugins_glpiinventory_\deploy: 108817
[Fri Sep 23 14:45:23 2022][debug2] https://glpi.XXXXXXXXXXX.XXXX/plugins/glpiinventory/b/deploy/?action=getJobs&version=2.10&machineid=XXXXXXXXXXXXXXXXXXX-2022-06-27-16-10-10
[Fri Sep 23 14:45:23 2022][debug2] Deploy job 632da7bb7d2f0 in the list
```

If I set the agent based URL in Entity configuration to https://Inventory.XXXXX, deployment task is executed but files aren't downloaded.
```
[Fri Sep 23 14:33:57 2022][debug2] https://inventory.XXXXXXXX.XXXX/plugins/glpiinventory/b/deploy/?action=setStatus&part=job&uuid=632da79e0a0e9&msg=all%20checks%20are%20ok&status=ok&machineid=XXXXXXXX.XXXX-2022-06-27-16-10-10&currentStep=checking
[Fri Sep 23 14:33:57 2022][debug2] usercheck before: no user interaction requested
[Fri Sep 23 14:33:57 2022][debug2] Downloading for job 632da79e0a0e9...
[Fri Sep 23 14:33:57 2022][debug2] https://inventory.XXXXXXXX.XXXX/plugins/glpiinventory/b/deploy/?action=setStatus&part=job&machineid=LTP000337-1.XXXXXXXX.XXXX-2022-06-27-16-10-10&uuid=632da79e0a0e9&currentStep=downloading&msg=downloading%20files
[Fri Sep 23 14:33:57 2022][debug2] https://inventory.XXXXXXXX.XXXX/plugins/glpiinventory/b/deploy/?action=setStatus&sha512=a0a46c688fe48af464f2215b1e8b5f3ebfb7fc9ad4fbf956d1164fd067bef607c8598542cef2afe8532fd521ffd248825f8a380929fbda23b18bc0eb61a7600b&part=file&machineid=XXXXXXXX.XXXX-2022-06-27-16-10-10&uuid=632da79e0a0e9&currentStep=downloading&msg=fetching%20inventory.XXXXXXXX.XXXX.pem
[Fri Sep 23 14:33:57 2022][error] Source or mirror is not a valid URL:  https://inventory.XXXXXXXX.XXXX/plugins/glpiinventory/b/deploy/?action=getFilePart&file=
```

### To reproduce

Configure two different URL for the same glpi web site.
glpi-agent must use only one of this url.

### Expected behavior

Solve [error] Source or mirror is not a valid URL when inventory based URL is set.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.4

### Additional context

GLPI version 10.0.3

**Comment by g-bougard** [comment]
Hi @Tony710 
it seems you have one space at the beginning of your source url. Can you check you didn't set the agent based URL with one space at the beginning in the entity configuration ?

**Comment by Tony710** [comment]
Hi @g-bougard 
I have check : no space at the beginning in entity configuration for inventory source URL

**Comment by Tony710** [comment]
@g-bougard 
Sorry, I have check one more time and it's OK.
