### ISSUE TITLE
GLPI Agent send to server with incorrect name

### ISSUE THREAD

**Issue by chtourou-youssef** [glpi-project/glpi-inventory-plugin#224]
### Describe the bug

I install the agent in my vm (OS : Centos)
The problem is : the name of my vm in the Glpi server is incorrect ( half of my hostname )

How i can force the agent to use the full hostname of my vm ?

Thanks

### To reproduce

n/a

### Expected behavior

n/a

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.4

**Comment by cedric-anne** [comment]
The problem is: information given by issuer in Github issue is incorrect ( half of requested information )

How can I force issuer to give all requested information ?

Regards

**Comment by g-bougard** [comment]
Hi @chtourou-youssef 

you should have provided an accurate example so we can really understand your concern.

Anyway, you may want to try the `additional-content` option:
1. Create a simple json file to update your computer name with the following format:
```
{
   "content": {
      "hardware": {
         "name": "mycomputerfirsthalfpartname.mycomputersecondhalfpartname"
      }
   }
}
```
2. Set `additional-content` option with the path to this file in conf
3. Make an inventory

For testing, you can output a partial inventory with the command: `glpi-inventory --partial hardware --additional-content computer-name.json`

Here is the result in my case:
```
{
   "action": "inventory",
   "content": {
      "bios": {
         "assettag": "LU004",
         "bdate": "2019-12-15",
         "bmanufacturer": "Dell Inc.",
         "bversion": "1.12.2",
         "mmanufacturer": "Dell Inc.",
         "mmodel": "07TYC2",
         "smanufacturer": "Dell Inc.",
         "smodel": "XPS 13 9350"
      },
      "hardware": {
         "chassis_type": "Laptop",
         "dns": "127.0.0.53",
         "name": "mycomputerfirsthalfpartname.mycomputersecondhalfpartname",
         "vmsystem": "Physical"
      },
      "versionclient": "GLPI-Inventory_v1.5-dev"
   },
   "deviceid": "LU004-2022-09-23-18-02-37",
   "itemtype": "Computer",
   "partial": true
}
```

**Comment by chtourou-youssef** [comment]
Thanks , where i create this json file ? in the vm when i run the agent ?

**Comment by g-bougard** [comment]
Yes, you can create the json and use it forever.

**Comment by chtourou-youssef** [comment]
Its work 
but i've some other issues 
i will close this issue

**Comment by chtourou-youssef** [comment]
I'am sorry but i check that the name of ùachine is changed automatically 


![image](https://user-images.githubusercontent.com/71817433/192540452-5075cb8e-a376-42f9-a227-840d46649f66.png)

**Comment by trasher** [comment]
You still do not provide requested inventory file.

**Comment by chtourou-youssef** [comment]
sorry , i don't understand 
can you please explain ?

**Comment by g-bougard** [comment]
@chtourou-youssef 
What do you mean exactly ? Is the computer renamed automatically in GLPI ? If no, did you rename it manually in the past ? If yes, you may have a lock on it, just remove the lock then.

**Comment by chtourou-youssef** [comment]
Yes is renamed automatically , but my vm is already unlocked

**Comment by g-bougard** [comment]
We still don't understand what's the remaining problem with this issue.
Can you clarify ?

**Comment by chtourou-youssef** [comment]
in fact , i create a `computer-name.json` file to set the name of my computer like that :



```
{
   "content": {
      "hardware": {
         "name": "XXX.domain.group"
      }
   }
}

```

, and i create a `file.cfg` under `conf.d/ `folder : 

```
delaytime=60
logfile=/var/log/agent-glpi.log
additional-content=/etc/glpi-agent/computer-name.json
server=http://glpi01.infra.dc01.oodrive.group/glpi/plugins/glpiinventory/
debug=1

```

in the first communication with the server , the name of computer is correct ( the same in the json file ), but the name is changed automatically

**Comment by g-bougard** [comment]
Can I guess you have tested manually ? In that case, you may have forgotten to restart the service so it reads the new configuration. Then if a service is still running without knowing it has to use `additional-content` option, it will upload the simple name to your server.

**Comment by trasher** [comment]
Finally, this does not seems a plugin issue, but rather an agent support question...
I close, feel free to reopen if there is a real bug on plugin.

**Comment by chtourou-youssef** [comment]
> Can I guess you have tested manually ? In that case, you may have forgotten to restart the service so it reads the new configuration. Then if a service is still running without knowing it has to use `additional-content` option, it will upload the simple name to your server.

i've restart the agent

**Comment by chtourou-youssef** [comment]
@trasher , please , can you check with me if i have some error in my configuration ? because i followed what  @g-bougard say , but i can't found the correct name
