### ISSUE TITLE
Task Collect: Filename not sensitive does not work

### ISSUE THREAD

**Issue by eriqueSDB** [glpi-project/glpi-inventory-plugin#226]
### Describe the bug

When we create the collect task and add it to the Plugin at: Tasks > Computer Information, the name of the file, the button right next to it that should be case sensitive or not, doesn't work.

I did some tests with the option exactly in "Not case sensitive" and did not find the file, if I use the option indicating the same folder and but putting the exact name of the file including the extension, it finds normally.

### To reproduce

Plugin at: Tasks > Computer Information
Register a file with a capital or lower case name
Check the "case insensitive" button
Make sure the file in the indicated location is using uppercase and lowercase letters and with the correct extension
Create the task and validate

### Expected behavior

Find the file regardless of whether it is uppercase or lowercase

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.3

### Additional context

It was also tested in fusioninventory on GLPI 10 and the behavior is the same

**Comment by g-bougard** [comment]
Hi @eriqueSDB 
thank you for your submission, I can confirm the file name is put into `filter_name` column in place of `filter_iname` when the "Non case sensitive" option is selected.

**Comment by trasher** [comment]
> I can confirm the file name is put into `filter_name` column in place of `filter_iname` when the "Non case sensitive" option is selected.


According to dropdown entries, it seems that is what is expected, see https://github.com/glpi-project/glpi-inventory-plugin/blob/develop/inc/collect_file.class.php#L180

**Comment by g-bougard** [comment]
Gasp, there is probably the bug: `__('Non sentitive case', 'glpiinventory')` should be set to `iname` and `__('Sentitive case', 'glpiinventory')` to `name`

@eriqueSDB can you confirm the test becomes "non sensitive" when you select the "sensitive case" ?

**Comment by eriqueSDB** [comment]
> can you confirm the test becomes "non sensitive" when you select the "sensitive case" ?

I can confirm exactly what I said, marking that it is sensitive, it becomes non-sensitive, according to the tests I performed now:

"Not case sensitive" checked, filling in the initial "name" field and filled in exactly with the exact file name: It finds the file successfully.

"Not case sensitive" checked, filling the initial "name" field and filled only with lower case with the exact name of the file: It finds the file successfully.

"Case sensitive" checked, filling in the initial "name" field and filled in exactly with the exact file name: It finds the file successfully.

"Case sensitive" checked, filling the initial "name" field and filled only with lowercase with the exact file name: It finds the file successfully. (This one was not to be found due to precisely being "case sensitive")


Plugin version 1.0.4
Using GLPI inventory 1.4

**Comment by eriqueSDB** [comment]
What led me to create this topic was precisely the use of "It is not case sensitive", using this "file name" field marked instead of the conventionally marked "name" field

<img src="https://i.ibb.co/0hGsPrz/filename.png">

It didn't seem to me that it was being used correctly, aligned to this sensitive field or not, as I hadn't found a faq or knowledge base on I opened the topic.

I still believe that the best practice would always be to use this field called "file name" instead of the "name" field, which in my conception and what it looks like is that it would just be the name of that collection task.
