### ISSUE TITLE
Missing useful informations compared to FusionInventory-Plugin

### ISSUE THREAD

**Issue by fralla2** [glpi-project/glpi-inventory-plugin#233]
### Describe the bug

Hi all,

We upgraded from GLPI 9.5.7 with FusionInventory to GLPI 10.0.3 with native inventory and glpi-inventory plugin and we saw that a few useful informations are not collected/displayed anymore for computers.

The main one missing would be the following : 
- On the computer' main tab, under "Inventory information", there used to be a field listing the last contact ip address of the agent (really useful to know if an asset is at home VS in our offices)
- On that same page, there used to be a line indicating the date of the last reboot of the computer (useful for our agents to troubleshoot issues)
- On the operating system' tab, there used to be the date of the OS install listed there.

If possible, these features would be really welcome back :)
Thanks

### To reproduce

Use GLPI 10.0.3 with native inventory and glpi-inventory plugin

### Expected behavior

Show the informations that used to be displayed there

### Operating system

Windows

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

1.0.4

### Additional context

GLPI 10.0.3
FusionInventory Agent 2.6
GLPI-Inventory-Plugin 1.0.4

**Comment by g-bougard** [comment]
On my point of view, this is an asset info, not an agent one.

**Comment by fralla2** [comment]
Wow thanks. That was quick :) It will be really appreciated by my teammates Thanks

**Comment by stonebuzz** [comment]
Hi @fralla2

- Last boot on ```Computer``` -> https://github.com/glpi-project/glpi/pull/12896

Best regards

**Comment by orthagh** [comment]
> On my point of view, this is an asset info, not an agent one.

Agree

**Comment by stonebuzz** [comment]
Hi @fralla2 
all PR are merged.
I close this issue.

Best regards
