### ISSUE TITLE
Network Discovery Problem

### ISSUE THREAD

**Issue by HugzWaaa** [glpi-project/glpi-inventory-plugin#235]
### Describe the bug

Hello everyone, I have a little problem with the networkDiscovery option of the GLPI-Inventory plugins, I have configured a network discovery task and when I force the inventory from the web page, it tells me that the inventory task is in progress ... that the deploy task is in progress but it never tells me that the network discovery task is running. However when I go to Administration ---> GLPI Inventory --->Tasks, and I select
my networkDiscovery task, it tells me that it is well in progress

### To reproduce

1. Normal Install of GLPI + setup
2. Install and setup of GLPI Inventory Agent
3. created a task for networkDiscvery
4. force the inventory to force the task to run

### Expected behavior

1. that the task stops and tells me that there is an error due to the configuration
2. Or that the task runs, but it shows me the equipment in the network

### Operating system

Windows

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

1.0.4

### Additional context

![Help](https://user-images.githubusercontent.com/113598277/195139394-a819c3d4-5f9d-45de-820f-fab07e97c75f.PNG)

![Help3](https://user-images.githubusercontent.com/113598277/195139468-3372917d-cc82-47b8-98d7-59ee82c4af8e.PNG)
![Help2](https://user-images.githubusercontent.com/113598277/195139469-c2a376bb-4e55-4fe2-8f16-082b3aeb229f.PNG)

**Comment by stonebuzz** [comment]
Hi @HugzWaaa can you enable debug and past here output of Glpi agent when you run taks ? 

Best regards

**Comment by HugzWaaa** [comment]
(I'm not sure I made the right order)

**Comment by HugzWaaa** [comment]
If you talk about debug in regedit:
![image](https://user-images.githubusercontent.com/113598277/195279933-c7a8002b-14d5-4f54-b07b-6e0b02aefaab.png)

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195283092-c870817d-3f57-41c3-bca1-bb89762de7e2.png)
![image](https://user-images.githubusercontent.com/113598277/195283556-9c2165fc-7d2c-4db5-8b03-8c37ce53f758.png)
![image](https://user-images.githubusercontent.com/113598277/195285376-ee8d6218-c045-476a-bb99-65a28532c5ce.png)

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195286051-605485ab-229c-4161-b1d1-1d963bcbd794.png)

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195286170-c59c6d65-9c02-408a-a575-cd77b9799911.png)

**Comment by g-bougard** [comment]
> ![image](https://user-images.githubusercontent.com/113598277/195281645-9980ce59-07d2-4725-8749-6e827f16e6d7.png) In the log, he only place where I have feedback on the networkDiscovery task

This means your task is correct. But there, I don't see any credential. Did you setup credentials to your ip range ? Check your ip range and add credentials if none is associated.

**Comment by HugzWaaa** [comment]
credentials is only for SNMP no ?

**Comment by HugzWaaa** [comment]
But networkDiscovery work with SNMP, Ping and NetBIOS no ? so why didn't work with ping ?

**Comment by HugzWaaa** [comment]
Igonna add a credential

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195287899-fbe8dc4a-deaa-4d58-bd5d-d739e0cc4dfa.png)
I added a snmp credential but now I want to restart the task but if it is not active I am told it is still running

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195289825-fff39a60-2fbd-4d55-8fd7-db096e058bbc.png)
(Same IP range but credential added)

**Comment by HugzWaaa** [comment]
another idea?

**Comment by stonebuzz** [comment]
provide debug output from glpi-agent side (enable debug mode 2, and redirect output to file)

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195304168-ddfe8f50-38ff-429c-9be5-bdf85c6391f5.png)
If the debug output it's do with this command, I just don't know how redirect the output

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195305310-ce1f69c4-4fb7-4ede-8397-6b651851661c.png)

**Comment by stonebuzz** [comment]
can yoo read this 
https://glpi-agent.readthedocs.io/en/latest/man/glpi-remote.html#general-options

else 

```glpi-agent.bat --json -f --local e:\```

**Comment by g-bougard** [comment]
Use `glpi-inventory` command when redirecting output.

**Comment by g-bougard** [comment]
Argh, you want to see what's happening during the network tasks...
Use better this when you run manually the agent:
```
glpi-agent.bat --logger=stderr --debug --debug
```

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195332882-008ab159-1fff-4abf-a4fa-db87e7d2cb19.png)
![image](https://user-images.githubusercontent.com/113598277/195333308-2916d931-b8dd-44a9-b5f3-7a18eb770c21.png)
![image](https://user-images.githubusercontent.com/113598277/195333714-169970fd-6e1c-4dce-98f3-191e167934e7.png)
![image](https://user-images.githubusercontent.com/113598277/195334074-0a97a598-217e-4dcb-ad80-57b6cdb67ed1.png)
![image](https://user-images.githubusercontent.com/113598277/195334606-c2000c20-6709-49f7-b4c5-c1a5441c8d73.png)
![image](https://user-images.githubusercontent.com/113598277/195334773-1a723b66-86cd-4214-9e1f-287482a3a806.png)

**Comment by HugzWaaa** [comment]
There is no mention of network discovery in the log

**Comment by g-bougard** [comment]
Your agent don't have network tasks installed as the following lines show:
```
Available tasks : 
- Collect (v2.8)
- Deploy (v2.10)
- Inventory (v1.12)
- RemoteInventory (v1.0)
```
Re-install the agent enabling the missing tasks.

**Comment by HugzWaaa** [comment]
Okay thanks a lot, I gonna try

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195347277-df6efc33-1f10-4b49-b34a-22cf24621b03.png)
you don't have a Uninstall.exe like FI ?

**Comment by g-bougard** [comment]
GLPI Agent is a MSI package.
Use the system Applications management to uninstall.

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195351274-648f452f-6270-4ee5-81d8-723bf535e88c.png)
![image](https://user-images.githubusercontent.com/113598277/195351417-a1e9e878-8915-49d2-92fc-ad94b379de9a.png)
Great !!!!! Thanks so much
If you don't have the answer it's ok, but do you know why I had to reinstall the software for it to work ?

**Comment by HugzWaaa** [comment]
(just to understand)

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195360478-d03e710c-28aa-4ed0-a6b8-f56ce1d01c9e.png)
![image](https://user-images.githubusercontent.com/113598277/195360518-efe21a09-6aa6-424c-a711-f8774a7ae0d0.png)
Another question, Why now that the task has been executed without error, I can't restart the same task

**Comment by HugzWaaa** [comment]
J'appuie sur le bouton "Forcer le démarage" et pourtant aucune task n'est préparer ou en cours

**Comment by HugzWaaa** [comment]
I press the "Force start" button and yet no task is prepared or in progress

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195361515-987dddcd-cdf8-4adb-ba25-2b87e0f3d220.png)

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195361979-dd98ab5e-2116-4884-8781-9058ed5db298.png)
And when I duplicate this same task it works WOW

**Comment by HugzWaaa** [comment]
I tried to uncheck "active" then to update the task, then to check "active" then again "Force start", but nothing happens

**Comment by HugzWaaa** [comment]
Normal to have to apply the task each time to be able to restart it manually

**Comment by HugzWaaa** [comment]
yep but if i want force start the task manually

**Comment by HugzWaaa** [comment]
and not re prepare automatically the job every time he succeeds

**Comment by HugzWaaa** [comment]
the Computers go up but without information

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195367690-810565ae-4f43-4ce4-a2e9-390ab71de2ff.png)
while the network equipment comes back with all the information

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195369387-3ae98ca9-6ce1-4e18-a29d-497efaebad3c.png)
I don't want the task to start when the previous one is successful, I want to be able to restart it manually at any time

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195370977-617d91d5-3cb9-43d7-ae62-88cdeabd33ab.png)
As for the network equipment for which the networkDiscovery works perfectly

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195372167-dca440e2-0c65-4938-84d3-d26a74d561ee.png)
![image](https://user-images.githubusercontent.com/113598277/195372639-f09bbc62-fced-4574-94f4-5b2a99e681e3.png)
this pc is back on the GLPI with the GLPI-Agent, but it is back without the screens connected to it

**Comment by stonebuzz** [comment]
![image](https://user-images.githubusercontent.com/7335054/195515871-b0755fcc-fe3a-4a8c-87a8-ea76dfda9862.png)

GlpiInventory in only dediceted to Netqork Inventory (Printer / NetworkEquipement)

If an asset is seen as "Computer" he has several reasons : 

- it's really a computer, so you have to install the agent on it
- Bad SNMP community, so the agent could not determine its type (via the SysObjectID)

> I don't want the task to start when the previous one is successful, I want to be able to restart it manually at any time

If you want restart task manually you need to enable "RE-prepare task on success"

> I would also like to have information on the PCs that come up through network discovery (at least the hostname, IP and MAC)

Add desired column with this 
![image](https://user-images.githubusercontent.com/7335054/195516574-2d4efc0f-948b-4c37-8a4f-58ee31e62e31.png)

> this pc is back on the GLPI with the GLPI-Agent, but it is back without the screens connected to it

Please open new issue, this problem is not related to this one

**Comment by HugzWaaa** [comment]
I'll tell you again, I don't want the task to restart as soon as the previous one is successful I want to be able to launch it manually at any time NOT AFTER THE OLD ONE HAS WORKED

Okay for the monitor it's not very important anyway

and for the so-called computer (on which there is no information) I will try to bring up the PLC from a client network to see if they come up with more information (unfortunately if it is not the case I could download the agent on the PLC ...)

**Comment by stonebuzz** [comment]
@HugzWaaa 
It's a bad translation
This option permit to re prepare job if previous run succeed (manually or with automatic action)

see -> https://github.com/glpi-project/glpi-inventory-plugin/pull/237

Last point :
Please remain calm and courteous during our discussions
I remind you that the community support is free, that we have spent time on your problem to understand that : 

- NetworkDiscovery module was not installed
- You have attempted to inventory a computer from a network equipment plugin
 

Best regards

**Comment by HugzWaaa** [comment]
You are right I have to stay calm I'm sorry for that it's just that I had the impression that you didn't know what I was writing (for the manual restart), then I just allow myself to write you again to tell you that no it's not necessarily because I try to inventory a computer from a network equipment plugin, I've just tested from a client network where there are PLCs, but all the PLCs are recognized as PCs and I still don't have the information I was talking about (MAC, IP HOSTNAME . ...) and unfortunately I do not believe that I must install the agent on the PLC. 

sorry again for yesterday
