### ISSUE TITLE
Net discover not working, name of all devices is N/A

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi-inventory-plugin#239]
### Describe the bug

Apparently there is an issue, all discovered devices are refused during import. In the log of the agent I can see the real name but in GLPI not.
If I go to "refused devices" all names are empty.

There is a linked issue here (with more details and screenshots):
https://github.com/glpi-project/glpi/issues/12985

### To reproduce

1. Perform a net discovery

### Expected behavior

Device should get imported.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

1.0.4

### Additional context

GLPI 10.0.3

**Comment by stonebuzz** [comment]
Hi @SteadEXE 
it appears that you are trying to inventory computers from the glpiinventory plugin right ?

**Comment by SteadEXE** [comment]
Yes, it's right, I opened an issue there aswell

**Comment by stonebuzz** [comment]
glpiinventory plugin is only dedicated to network asset inventory like ```Printer``` or ```NetworkEquipement```

If you want to inventory computers you have to install the agent on them

Best regards

**Comment by SteadEXE** [comment]
Everything is detected as computer. Even switches and Network Equipement.

**Comment by stonebuzz** [comment]
If an asset is seen as Computer there are several reasons for this :

- It's a 'real' Computer so you need to install glpi-agent on it.
- it's a real Network Equipment but glpi-agent did not find the type (Printer or NetworkEquipment) according to sysobject.ids (from SNMP ) due to bad SNMP crendential defined in IP range.

**Comment by SteadEXE** [comment]
Thanks for the reply, I will check it out next week

**Comment by victortt5** [comment]
Same problem. NetDiscovery not import a devices. Only big log empty devices in "Equipment refused by rules log"
I try add phone device by my rule "YA Phone import (by mac)":
![image](https://user-images.githubusercontent.com/116735675/198062908-25ab1a70-48c7-4731-a097-0f8d84afae05.png)
rule test:
![image](https://user-images.githubusercontent.com/116735675/198063315-444e1273-b3ec-4cef-9d81-17e216514365.png)

Start task "network discovery":
![image](https://user-images.githubusercontent.com/116735675/198064460-9065cddb-2997-4a1b-a4c0-6e1983cceadd.png)

Devices not added in "Unmanaged device"

In GLPI 9.5.6 with FI 9.5 this rule work and devices add in "Unmanaged device"!
![image](https://user-images.githubusercontent.com/116735675/198069004-a83f1a0f-3760-4238-89ac-c8e23153adcd.png)

**Comment by stonebuzz** [comment]
Hi @victortt5 glpiinventory is only dedicated ald design for network equipment like Printer or network device (switch etc..) 

IPPhone are not handle for the moment.

For computer use glpi-agent instead of this plugin

Best regards

**Comment by victortt5** [comment]
Hello, @stonebuzz. I was asking about something else. What do phones have to do with it? I asked why the rules do not work in the new version?
1) Here.
Why doesn't the import by mac rule work? Any devices. Test of rule done.
2) [https://github.com/glpi-project/glpi-inventory-plugin/issues/245](url)
Clean glpi, clean rules(without phone rule). Why is a log created if it is prohibited in the rule?
3) Why do these rules work in GLPI 9.5.6 with FI?(standard and manual rules).
Why do need rules in this version then?
