### ISSUE TITLE
Date of last inventory

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi-inventory-plugin#244]
### Describe the bug

hello
I have a lot of plug-in with 
`$requete = "SELECT `last_fusioninventory_update` FROM `glpi_plugin_fusioninventory_inventorycomputercomputers` WHERE `computers_id` = '" . $pComputerId . "'";`
but in glpiinventory version impossible to find this in base. Most of the plug-ins are in error.
So I thought:  
`../files/_inventories/computer/9/9893.xml:      <LOGDATE>2022-10-19 10:04:45</LOGDATE>`
but how? Thank you

### To reproduce

SQL query

### Expected behavior

The sql query should work

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin

1.0.4

**Comment by AdrienClairembault** [comment]
I think what you are looking for is the `last_inventory_update` field, which is found directly in the computers table: 

![image](https://user-images.githubusercontent.com/42734840/196639450-f0deba50-7c5f-46b5-a34e-19c0ba302df6.png)

**Comment by trasher** [comment]
Please use forums for this kind of topic, this is certainly not a bug. Thank you.
