### ISSUE TITLE
Equipments refused by rules - big log

### ISSUE THREAD

**Issue by victortt5** [glpi-project/glpi-inventory-plugin#245]
### Describe the bug

a log with a forbidding rule is growing

### To reproduce

I'm running a network discovery task. 
Standard rule "Computer constraint (name)":
![image](https://user-images.githubusercontent.com/116735675/198054013-24e09ef8-e3ee-4663-8fe9-8504eb53f513.png)

Equipments refused by rules log:
![image](https://user-images.githubusercontent.com/116735675/198053677-8b16f832-d25b-4bd7-b617-74fc04e639e5.png)

### Expected behavior

empty log how in GLPI 9.5.6 with FusionInventory 9.5

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin

1.0.4

**Comment by stonebuzz** [comment]
Hi @victortt5 glpiinventory is only dedicated and designed for network equipment like Printer or network device (switch etc..) 

IPPhone are not handle for the moment.

For computer use glpi-agent instead of this plugin

Best regards
