### ISSUE TITLE
after migrating from FI to GLPI-Inventory SNMP inventrory got a mess

### ISSUE THREAD

**Issue by walterdasilva** [glpi-project/glpi-inventory-plugin#246]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

1. Some devices do not update component and port information. for example, some switches only show the management port
2. 2. On the task execution tab for the SNMP inventory, devices that do not belong to that entity or network are displayed. the same devices are shown repeatedly in various other snmp tasks from other entities.

I believe the problem occurred while migrating the database.

I have already deleted all tasks from all entities and recreated each one taking care to select the correct entity before registering the tasks. and the problem came back.

any suggestions?

Thanks,

### To reproduce

1. migrar uma base  com várias entidades que usa o FI para o GLPI-Inventory

### Expected behavior

the behavior describe on bug

### Operating system

Windows, Linux

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.4, 10.0.1+1.0

**Comment by walterdasilva** [comment]
thank you very much for your attention. I wait for news.

complementing, via phpMyAdmin I could see that several inventory records of network devices (and child tables) are with entity 0.

I wait for news.

thank you so much

**Comment by stonebuzz** [comment]
Hi @walterdasilva can you try this PR -> https://github.com/glpi-project/glpi-inventory-plugin/pull/247

After applying patch, you need to force install the plugin

Run this command (from root folder of GLPI)

```shell
php bin/console glpi:plugin:install --force glpiinventory
php bin/console glpi:plugin:activate glpiinventory
```
You will see a new option (only for networkinventory method) from "Job configuration" tab (default true)

![image](https://user-images.githubusercontent.com/7335054/198522377-0e8c8f20-b894-422d-a66d-e61f8cdf5732.png)


Just prepare task, and you will see only assets related to task entity

Best regards

**Comment by walterdasilva** [comment]
Hi @stonebuzz ,

how do i to download the path from #247 ?

Thanks a lot

**Comment by cedric-anne** [comment]
> Hi @stonebuzz ,
> 
> how do i to download the path from #247 ?
> 
> Thanks a lot

https://patch-diff.githubusercontent.com/raw/glpi-project/glpi-inventory-plugin/pull/247.patch

**Comment by walterdasilva** [comment]
@cedric-anne ,

Thank you for you very fast answer, but how do apply this? must a edit each .php and make changes?

Best regards?

**Comment by cedric-anne** [comment]
On linux, go in the glpiinventory directory and run the command `patch -p1 < /path/to/246.patch`.

**Comment by walterdasilva** [comment]
thanks
