### ISSUE TITLE
fusioninventory-injector.pl toward plugins/glpiinventory : ERROR : XML NOT WELL FORMED !

### ISSUE THREAD

**Issue by lble44** [glpi-project/glpi-inventory-plugin#252]
### Describe the bug

Hi,
Here is my set up :
GLPI 10.0.5
Plugin : glpiinventory 1.0.5
Agent Fusion : 2.6

I have agent fusioninventory on some offline asset. They generate XML inventory file and then I have a script that launch fusioninventory-injector.pl on my GLPI Server in order to import the inventory file on my GLPI.

Since I upgraded my GLPI in v10.0.5, this doesn't work anymore. I get the following error : 
 ERROR : XML NOT WELL FORMED !

In addition, I get some asset with the same agent fusioninventory that are online and they communicate fine with my GLPI server and import automatically their inventory. By the way, the path is the same in my agent configuration and in my script, it's : 
http://localhost/glpi/plugins/glpiinventory/

Anybody encountered the same issue ?

Regards,

### To reproduce

1. Generate local XML file with agent fusion 2.6
2. Import the file with fusioninventory-injector.pl on GLPI server 10.0.5 with glpiinventory plugin 1.0.5 with the command : 
   perl fusioninventory-injector.pl -v -d fichiers/ --url http://localhost/glpi/plugins/glpiinventory/
3. ERROR : XML NOT WELL FORMED !

### Expected behavior

As before, xml file should be imported on my GLPI Server.

### Operating system

Windows

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

Other (See additional context below)

### Additional context

no

**Comment by stonebuzz** [comment]
Hi @lble44 
Any error from GLPI log file (PHP or SQL)
Best regards

**Comment by lble44** [comment]
Hi,
yes sorry, I forgot to post it, no SQL error but here is my php-error.log : 

[2022-11-23 09:35:54] glpiphplog.WARNING:   *** PHP User Warning (512): Start tag expected, '<' not found
 in  at line 1
  Backtrace :
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  plugins/glpiinventory/front/communication.php:72   include_once()
  plugins/glpiinventory/index.php:45                 include_once()


Regards,

**Comment by trasher** [comment]
Please provide file.

**Comment by lble44** [comment]
> 
I 'm already on --debug option.
Do yo mean the XML File or the log file ?

**Comment by lble44** [comment]
Yes you are right, I removed the --verbose --debug when I posted it but the script was running with.
Here is the full command running : 
perl /home/inventaire/fusioninventory/scripts/fusioninventory-injector.pl -v -d /home/inventaire/fusioninventory/fichiers/ --url http://localhost/glpi/plugins/glpiinventory/ --verbose --debug

Here is the log : 
[2022-11-23 10:20:23] glpiphplog.WARNING:   *** PHP User Warning (512): Start tag expected, '<' not found
 in  at line 1
  Backtrace :
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  plugins/glpiinventory/front/communication.php:72   include_once()
  plugins/glpiinventory/index.php:45                 include_once()
  
[2022-11-23 10:57:40] glpiphplog.WARNING:   *
[CODRA_BENS_A.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/10074399/CODRA_BENS_A.zip)
** PHP User Warning (512): Start tag expected, '<' not found
 in  at line 1
  Backtrace :
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  plugins/glpiinventory/front/communication.php:72   include_once()
  plugins/glpiinventory/index.php:45                 include_o
[CODRA_BENS_A.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/10074404/CODRA_BENS_A.zip)
nce()


You can find attach the XML.

**Comment by trasher** [comment]
Provided XML file is valid. Are you sure you provide the faultly file?

**Comment by lble44** [comment]
Yes sure, all files I tested  are like that and the result are always the same : ERROR : XML NOT WELL FORMED !

**Comment by trasher** [comment]
I've tried:
```
php front/inventory.php < /path/to/CODRA_BENS_A.xml
```

And did not reproduce. I suspect an issue either in your configuration, or in fusioninventory script.

**Comment by trasher** [comment]
I also do not reproduce using glpi-injector command with glpi-inventory-plugin. 

Double check your configuration, try locally, I guess you'll find the issue.
