### ISSUE TITLE
Enable inventory

### ISSUE THREAD

**Issue by Tanakaz96** [glpi-project/glpi-inventory-plugin#253]
### Describe the bug

When i go to http://my-glpi-server/front/inventory.conf.php i get a message "La propriété enabled inventory n'existe pas !"

I have a similar message on the logs of my glpi agent : [Wed Nov 23 11:05:38 2022][error] [http client] can't uncompress content starting with: Inventory is disabled

And I don't have the checkbox to enable it.
![image](https://user-images.githubusercontent.com/118892861/203521058-d61c033c-d261-490a-9c22-afd4cd36d30d.png)

### To reproduce

Install GLPI Inventory from plugins
GO to http://my-glpi-server/front/inventory.conf.php

### Expected behavior

![image](https://user-images.githubusercontent.com/118892861/203520797-5474aebf-7404-4899-bbae-9476d1fd3605.png)

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin

1.0.4

**Comment by trasher** [comment]
Your GLPI database is probably not up to date

**Comment by Tanakaz96** [comment]
Thanks for fast reply, but db was up to date :
![image](https://user-images.githubusercontent.com/118892861/203725468-b02c7d81-0ec8-4c29-a8a9-51c64cc3fa6b.png)

I try to desintall reinstall plugin, but still doesn't work
![image](https://user-images.githubusercontent.com/118892861/203725631-29c8203a-f97f-4f68-bb4c-14455baac356.png)

**Comment by trasher** [comment]
Udate to latest GLPI

**Comment by Tanakaz96** [comment]
I made a mistake in the description, I am in 10.0.5.

**Comment by trasher** [comment]
OK. You do have an issue in your database, missing property is added in 10.0.m migration file. So your migration has somehow failed; this is another issue.

You can try to add missing entry with name `enabled_inventory`, context `inventory` in the `glpi_configs` table.

**Comment by Tanakaz96** [comment]
Variable is already present 358;inventory;enabled_inventory;1
But even if I uninstall the plugins it remains at 1. However if I go to: https://my-glpi-server/front/inventory.php.
 I get this message: Inventory is disabled
