### ISSUE TITLE
Can't install the plugin from MarketPlace after download

### ISSUE THREAD

**Issue by Max-ime07** [glpi-project/glpi-inventory-plugin#254]
### Describe the bug

When I click on install from the plugins menu in glpi, nothing happen and form the marketplace, there is a graphic bug when I click on install.

### To reproduce

When I click on install from the plugins menu in glpi, nothing happen and form the marketplace, there is a graphic bug when I click on install.

### Expected behavior

When I click on install from the plugins menu in glpi, nothing happen and form the marketplace, there is a graphic bug when I click on install.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

Other (See additional context below)

### Additional context

GLPI 10.0.5
GLPI INVENOTRY 10.0.5

**Comment by cedric-anne** [comment]
Hi,

Could you check your GLPI logs to see if there is some usefull information ?

**Comment by cedric-anne** [comment]
Hi,

Could you check your GLPI logs to see if there is some usefull information ?

**Comment by cedric-anne** [comment]
Hi,

Could you check your GLPI logs to see if there is some usefull information ?

**Comment by Max-ime07** [comment]
[2022-11-23 15:23:28] glpiphplog.CRITICAL:   *** Uncaught Exception ParseError: syntax error, unexpected character 0x00, expecting end of file in /var/www/ht>
  Backtrace :
  marketplace/glpiinventory/hook.php:415             pluginGlpiinventoryInstall()
  src/Plugin.php:787                                 plugin_glpiinventory_install()
  :                                                  Plugin->install()
  src/Marketplace/Controller.php:545                 call_user_func()
  src/Marketplace/Controller.php:435                 Glpi\Marketplace\Controller->setPluginState()
  ajax/marketplace.php:82                            Glpi\Marketplace\Controller->installPlugin()

**Comment by cedric-anne** [comment]
> [2022-11-23 15:23:28] glpiphplog.CRITICAL: *** Uncaught Exception ParseError: syntax error, unexpected character 0x00, expecting end of file in /var/www/ht>

line is truncated, could you ggive the complete line ?

**Comment by Max-ime07** [comment]
sorry...

[2022-11-23 15:11:51] glpiphplog.CRITICAL:   *** Uncaught Exception ParseError: syntax error, unexpected character 0x00, expecting end of file in /var/www/html/glpi/marketplace/glpiinventory/inc/deploypackageitem.class.php at line 471
  Backtrace :
  marketplace/glpiinventory/hook.php:415             pluginGlpiinventoryInstall()
  src/Plugin.php:787                                 plugin_glpiinventory_install()
  front/plugin.form.php:51                           Plugin->install()


and


[2022-11-23 15:23:28] glpiphplog.CRITICAL:   *** Uncaught Exception ParseError: syntax error, unexpected character 0x00, expecting end of file in /var/www/html/glpi/marketplace/glpiinventory/inc/deploypackageitem.class.php at line 471
  Backtrace :
  marketplace/glpiinventory/hook.php:415             pluginGlpiinventoryInstall()
  src/Plugin.php:787                                 plugin_glpiinventory_install()
  :                                                  Plugin->install()
  src/Marketplace/Controller.php:545                 call_user_func()
  src/Marketplace/Controller.php:435                 Glpi\Marketplace\Controller->setPluginState()
  ajax/marketplace.php:82                            Glpi\Marketplace\Controller->installPlugin()

**Comment by cedric-anne** [comment]
Could you try to delete the `/var/www/html/glpi/marketplace/glpiinventory` directory and try to download it again?

**Comment by Max-ime07** [comment]
Same, i can re-download but when I click on install nothing happen. on the after screen, as you can see I also have homescreen showing bug
![after](https://user-images.githubusercontent.com/118915805/203608315-535eded9-19fc-42b5-b415-878d1dfc686e.png)
![before](https://user-images.githubusercontent.com/118915805/203608389-786921db-da17-45b4-b2b0-8af96689094c.png)

**Comment by Max-ime07** [comment]
The first image is after, and other plugins install successfuly

**Comment by Max-ime07** [comment]
I Have this error since i udate glpi inventory to 1.0.5 and i have try to reinstall glpi

**Comment by cedric-anne** [comment]
Can you give details about your server ? i.e the OS, the PHP version, ...

**Comment by Max-ime07** [comment]
Yes,
CentOS Stream  9
PHP 8.2
Apache

Thank for your help

**Comment by Max-ime07** [comment]
I downgrade to 8.1 and now, that's working ! Thank you for your help
