### ISSUE TITLE
Import and Link Rules | Using the Inventory Tag

### ISSUE THREAD

**Issue by eriqueSDB** [glpi-project/glpi-inventory-plugin#256]
### Describe the bug

When using the tag + name criteria for example to update computers, glpi seems to ignore the inventory tag information

So far I've only been able to see the following criteria working: name, ip, mac, serial number

The others I didn't check to test beyond the tag, but it didn't work as it should

### To reproduce

Create new import rule:

name + tag
![Screenshot_1](https://user-images.githubusercontent.com/102301295/203617252-bab72b78-94cc-45ad-9ae1-971ab206589e.png)

Disable all other import rules other than the contain computer name and global rule

Validate

### Expected behavior

The update will be carried out taking into account the tag

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin

1.0.5

**Comment by stonebuzz** [comment]
Hi @eriqueSDB 

To understand, what exactly are you trying to do?

**Comment by cedric-anne** [comment]
You should upgrade your GLPI to 10.0.5.

**Comment by eriqueSDB** [comment]
> Hi @eriqueSDB
> 
> To understand, what exactly are you trying to do?

I have several assets in different physical locations with the same computer name, I put an inventory tag on each computer to differentiate them from where they actually are.

What I did in the print here was to put the criterion of computer name + inventory tag, however in the tests that I performed in the update rule with these 2 criteria, the criterion of the tag seems to be ignored during the check, thus making the computer with the same name will always keep replacing itself with information coming from other computers with the same name.

That's what I want to do, use the tag in this criterion, but it doesn't seem to have an effect on the check.

**Comment by eriqueSDB** [comment]
> You should upgrade your GLPI to 10.0.5.

It's already 10.0.5, git only allowed selecting up to 10.0.3

**Comment by stonebuzz** [comment]
Related Agent have a TAG here ?

![image](https://user-images.githubusercontent.com/7335054/203768289-0e19273e-f63c-4464-a4f4-3370b305735c.png)

Can you post here the two related inventory files ?

Best regards

**Comment by eriqueSDB** [comment]
> Related Agent have a TAG here ?
> 
> ![image](https://user-images.githubusercontent.com/7335054/203768289-0e19273e-f63c-4464-a4f4-3370b305735c.png)
> 
> Can you post here the two related inventory files ?
> 
> Best regards

![Foto de Erique Souza (2)](https://user-images.githubusercontent.com/102301295/203786388-0f4ecaaa-4f0b-4aea-bec8-e5515eb25670.jpg)

![Foto de Erique Souza (1)](https://user-images.githubusercontent.com/102301295/203786416-386f1196-e175-48a7-9268-0ba032339130.jpg)

**Comment by stonebuzz** [comment]
Hi @eriqueSDB  can you try this

https://github.com/glpi-project/glpi/pull/13406

Best regards

**Comment by eriqueSDB** [comment]
> Hi @eriqueSDB can you try this
> 
> [glpi-project/glpi#13406](https://github.com/glpi-project/glpi/pull/13406)
> 
> Best regards

Apologies for the delay

I believe I have solved my problem with the fix code in question, thanks
