### ISSUE TITLE
ESX Inventory Task not starting but dicover and inventory task working fine

### ISSUE THREAD

**Issue by Max-ime07** [glpi-project/glpi-inventory-plugin#257]
### Describe the bug

I Installed Glpi inventory from the marketplace, agent server = http://myip/marketplace/glpiinventory/
My glpi agent running the task but say "No ESX job enabled or ESX support disabled server side."
My glpi agent had ESX fonctionnality installed and my task is correct but the task stay in prepared.

### To reproduce

I Installed Glpi inventory from the marketplace, agent server = http://myip/marketplace/glpiinventory/
My glpi agent running the task but say "No ESX job enabled or ESX support disabled server side."
My glpi agent had ESX fonctionnality installed and my task is correct but the task stay in prepared.

### Expected behavior

I Installed Glpi inventory from the marketplace, agent server = http://myip/marketplace/glpiinventory/
My glpi agent running the task but say "No ESX job enabled or ESX support disabled server side."
My glpi agent had ESX fonctionnality installed and my task is correct but the task stay in prepared.

### Operating system

Windows

### GLPI Agent version

1.4, Other (See additional context below)

### GLPI version

10.0.5

### GLPIInventory plugin

1.0.5

### Additional context

![Capture d’écran 2022-11-24 173517](https://user-images.githubusercontent.com/118915805/203832208-ff201443-3507-41b0-9507-13ad816817d9.png)

**Comment by stonebuzz** [comment]
Hi @Max-ime07 

can you enable debug mode ```2``` and retry (to get more log)

Best regads

**Comment by stonebuzz** [comment]
hi @Max-ime07 
first, you need to check if ```VMware host remote inventory``` is enable from Agent (GLPI side)

![image](https://user-images.githubusercontent.com/7335054/203948042-a5fba7ce-a064-4700-9b0e-135f2f58e639.png)

secondly, check ```Agent base URL``` from entity configuration

![image](https://user-images.githubusercontent.com/7335054/203948287-e985cd74-563b-4fb5-913d-f5efd2fae1bb.png)

You just need base ```url``` 

like ```http://myip``` (without the last ```/```)

**Comment by Max-ime07** [comment]
Hello, thanks for your answer. 
All good but I can't check vmware host remote inventory, i don't have right in super-admin mode ?

**Comment by stonebuzz** [comment]
Hi @Max-ime07 

Can you try this -> https://github.com/glpi-project/glpi-inventory-plugin/pull/255

this should fix your problem =)

**Comment by Max-ime07** [comment]
Thank you but i don't understand what I have to do to use native agent

**Comment by stonebuzz** [comment]
You already use GLPI agent 

> ### GLPI Agent version
> 
> 1.4, Other (See additional context below)

Your current issue "No ESX job enabled or ESX support disabled server side." is it solved ?

**Comment by Max-ime07** [comment]
No, my ESX issue is not solved and the link you send me https://github.com/glpi-project/glpi-inventory-plugin/pull/255 doesn't help me

**Comment by stonebuzz** [comment]
did you disconnect and reconnect after applying #255 ?

**Comment by Max-ime07** [comment]
I don't applying #255 because I don't understand what to do :/

**Comment by stonebuzz** [comment]
For further assistance, maybe consider subscribing to a GLPI subscription =)
Otherwise, you will have to wait for the next release of GLPI-Inventory plugin

Best regards

**Comment by stonebuzz** [comment]
Hi @Max-ime07 
Please update to 1.0.6 (which fixes right issue in super-admin mode for ```AgentModule```)

And retry my previous comment 
https://github.com/glpi-project/glpi-inventory-plugin/issues/257#issuecomment-1327215818

Best regards

**Comment by Max-ime07** [comment]
Thank you, the update solved my problem :)
