### ISSUE TITLE
Adding ip range opens the same form

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi-inventory-plugin#258]
### Describe the bug

After creating an IP range, you are redirected to an empty ip range form to create a new ip range.

### To reproduce

1. Open "Networks" -> "IP range" in plugin menu
2. Click on "Add" blue button at the top of the page
3. Provide a name, a start and last ips, then click on "Add" yellow button at the bottom
4. The same forms opens again to request a new ip range
5. Click on "IP Range" next to the blue "Add" button to check the IP range has been added

### Expected behavior

When clicking on "Add" yellow button, I expects to be redirected to the ip range edit form so I can add SNMP credentials for example.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin

1.0.5

**Comment by g-bougard** [comment]
I just noticed this is also the case when adding new "Authentication for remote devices (VMware)".
This is possibly the case for other forms.

**Comment by stonebuzz** [comment]
hi @g-bougard , thank you for your feedback

Can you try this -> #261 

You need to activate this GLPI option (logout / login to take care of this option from ```$_SESSION```

![image](https://user-images.githubusercontent.com/7335054/203988742-80e55618-212b-482c-97f3-d43dafca62b1.png)

```ESX Credential``` already handle this behavior (with option set to ```Yes```)

Best regards

**Comment by stonebuzz** [comment]
two other fixed redirections  : 

[fix(deploymirror): fix redirect after add](https://github.com/glpi-project/glpi-inventory-plugin/pull/261/commits/4e0e732536137d7a53a092c09f8991f1b72f115c)
[4e0e732](https://github.com/glpi-project/glpi-inventory-plugin/pull/261/commits/4e0e732536137d7a53a092c09f8991f1b72f115c)

[fix(iprangesnmpcredential): fix redirect after add](https://github.com/glpi-project/glpi-inventory-plugin/pull/261/commits/eebcd66ecbcd09b8ac939e6221e9517c03d8bcc9)
[eebcd66](https://github.com/glpi-project/glpi-inventory-plugin/pull/261/commits/eebcd66ecbcd09b8ac939e6221e9517c03d8bcc9)

**Comment by g-bougard** [comment]
Tested with IP range, this is okay. To follow my comment, something should also be done on `front/credential.form.php` ;-)

**Comment by stonebuzz** [comment]
```credential.form.php``` use native GLPI ```dropdown``` object (L36 - 37).

https://github.com/glpi-project/glpi-inventory-plugin/blob/c7a31cb932ea9e16aee8e691b3744901442b122d/front/credential.form.php#L33-L41

which already implements this behavior =)

**Comment by g-bougard** [comment]
You're right 👍
