### ISSUE TITLE
Wrong IP range boxes disposition in edition form

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi-inventory-plugin#259]
### Describe the bug

IP range numbers are splited into dedicated boxes and they can be put on a new line.

### To reproduce

Edit a created IP range. The following case in on a 1920x1080 monitor.
![image](https://user-images.githubusercontent.com/12514489/203977655-47281f2a-c54a-4256-9f35-d5bd341643a7.png)
You can see a lot of space is lost and the last number of ip ranges goes on a new line.

You even can have the last 2 boxes on a new line with a less large window:
![image](https://user-images.githubusercontent.com/12514489/203978414-3e9bb888-9934-4499-899e-031a20a8bfd8.png)

### Expected behavior

IP numbers are not splited othe lines.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin

1.0.5

**Comment by stonebuzz** [comment]
hi @g-bougard , thank you for your feedback

Can you try this -> https://github.com/glpi-project/glpi-inventory-plugin/pull/262

Best regards
