### ISSUE TITLE
Central vue / board

### ISSUE THREAD

**Issue by bbreton09** [glpi-project/glpi-inventory-plugin#26]
Hi, i just migration from GPLI 9.5.6 to Beta 10 and upgrade fusion to glpi-inventory. Migration work fine with the last master branche.
But i can't find the central vue like : https://github.com/fusioninventory/fusioninventory-for-glpi/blob/glpi9.5/screenshots/0.90-central.png
It's an issue or this vue does not exist ?

**Comment by trasher** [comment]
Most of those information were specific to the plugin, all is now handled by native core objects. I guess you can use native dashboards or metabase plugin in order to get similar screens.
