### ISSUE TITLE
No dedicated menu on "Authentication for remote devices (VMware)" page

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi-inventory-plugin#260]
### Describe the bug

The GLPI Inventory plugin menu is not present when managing "Authentication for remote devices (VMware)".

### To reproduce

1. Click on "Network" -> "Authentication for remote devices (VMware)" menu
![image](https://user-images.githubusercontent.com/12514489/203980081-0a85ffc9-417c-4d0c-8fb0-b6e4e4c764bb.png)
2. See the GLPI Inventory plugin menu is not rendered
![image](https://user-images.githubusercontent.com/12514489/203980319-eb98a7bd-dce2-4cbc-aee7-38ffc470b663.png)

### Expected behavior

GLPI Inventory menu is still present.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin

1.0.5

**Comment by stonebuzz** [comment]
hi @g-bougard , thank you for your feedback

Can you try this -> https://github.com/glpi-project/glpi-inventory-plugin/pull/263

Best regards
