### ISSUE TITLE
[feature request] Download button for deploy packages

### ISSUE THREAD

**Issue by M4rkus221** [glpi-project/glpi-inventory-plugin#268]
I hope this is the right place for this:

It would be very helpful to have an option to download the files that were uploaded in the "Deploy Package" section.  

Especially when working with multiple admins it would be good to be able to download the packages locally via the web interface to review what is delivered in them.

I suggest a small download icon next to the "drag" and "uncompress" icons.

**Comment by kintaro1981** [comment]
I agreed! 

So, deploy is now supported? We don't need fusioninventory agent anymore?

**Comment by g-bougard** [comment]
> I agreed!
> 
> So, deploy is now supported? We don't need fusioninventory agent anymore?

Deploy is supported since the beginning by this plugin and GLPI-Agent & FI agents are supported.

**Comment by kintaro1981** [comment]
Thank you @g-bougard 

How about the feature request?
I think it can be very useful.

**Comment by stonebuzz** [comment]
Hi @M4rkus221 , @kintaro1981 

can you try this -> https://github.com/glpi-project/glpi-inventory-plugin/pull/287

Best regards

**Comment by g-bougard** [comment]
Just a point, you still can modify the Deploy task to put the file on your computer and redefine it as before.

**Comment by M4rkus221** [comment]
Thank you for your effort, i didn't expect it to be so tricky, I assumed files must be somewhere we just need a button. But now I learned something, how the files are handled in the background 😅
I will test it as soon as I find time.
