### ISSUE TITLE
Problem with glpi-agent : [http client] unknown content format

### ISSUE THREAD

**Issue by smurdza** [glpi-project/glpi-inventory-plugin#269]
### Describe the bug

I have a problem with inventory Network Devices:
"  [http client] unknown content format "

[debug] [thread 1] #4, [http client] Using Compress::Zlib for compression
[error] [thread 1] #4, [http client] unknown content format
[debug] [thread 1] termination
[debug] [thread 3] #3, [http client] Using Compress::Zlib for compression
[error] [thread 3] #3, [http client] unknown content format
[debug] [thread 3] termination

### To reproduce

Set Network Inventory task for (Cisco SR7, SR12).
Run glpi-agent.

### Expected behavior

The inventory for devices should be sent to the server, and the inventory in GLPI

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin

1.0.6

### Additional context

[debug] [thread 1] #4, [http client] Using Compress::Zlib for compression
[error] [thread 1] #4, [http client] unknown content format
[debug] [thread 1] termination
[debug] [thread 3] #3, [http client] Using Compress::Zlib for compression
[error] [thread 3] #3, [http client] unknown content format
[debug] [thread 3] termination

**Comment by smurdza** [comment]
`[2022-12-05 14:57:11] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to array_is_list() must be of the type array, string given, called in /var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php/Converter.php on line 1441 in /var/www/html/glpi/vendor/symfony/polyfill-php81/bootstrap.php at line 23
  Backtrace :
  ...ect/inventory_format/lib/php/Converter.php:1441 array_is_list()
  ...ject/inventory_format/lib/php/Converter.php:380 Glpi\Inventory\Converter->convertNetworkInventory()
  ...ject/inventory_format/lib/php/Converter.php:323 Glpi\Inventory\Converter->convertTo01()
  src/Inventory/Inventory.php:141                    Glpi\Inventory\Converter->convert()
  src/Inventory/Request.php:265                      Glpi\Inventory\Inventory->setData()
  src/Inventory/Request.php:250                      Glpi\Inventory\Request->network()
  src/Inventory/Request.php:98                       Glpi\Inventory\Request->networkInventory()
  src/Agent/Communication/AbstractRequest.php:305    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()
`

**Comment by stonebuzz** [comment]
Can you use ```glpi-netdiscovery``` with  ```--save``` arg to redirect output to file (and post files here):
https://glpi-agent.readthedocs.io/en/latest/man/glpi-netdiscovery.html

Best regards

**Comment by smurdza** [comment]
`<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHPORT />  <AUTHPROTOCOL />  <AUTHSNMP>1</AUTHSNMP>
      <CONTACT>www.xxxxxxx.pl</CONTACT>
      <DESCRIPTION>TiMOS-C-16.0.R14 cpm/hops64 Nokia 7750 SR Copyright (c) 2000-2020 Nokia.
All rights reserved. All use subject to applicable license agreements.
Built on Wed Jun 17 11:11:37 PDT 2020 by builder in /builds/c/160B/R14/panos/main</DESCRIPTION>
      <DNSHOSTNAME>111.111.111.111</DNSHOSTNAME>
      <IP>111.225.111.27</IP>
      <IPS>
        <IP>194.0.0.1</IP>
        <IP>194.12.1.97</IP>
        <IP>194.127.0.144</IP>
        <IP>194.128.0.1</IP>
        <IP>194.15.1.1</IP>
        <IP>194.190.0.2</IP>
        <IP>194.192.11.6</IP>
        <IP>194.192.12.2</IP>
        <IP>194.192.12.6</IP>
        <IP>194.192.13.2</IP>
        <IP>194.197.1.10</IP>
        <IP>194.2.19.1</IP>
        <IP>194.2.2.1</IP>
        <IP>194.2.250.0</IP>
        <IP>194.2.250.13</IP>
        <IP>194.2.250.17</IP>
        <IP>194.2.250.2</IP>
        <IP>194.2.194.</IP>
        <IP>194.2.251.1</IP>
        <IP>194.2.254.1</IP>
        <IP>194.2.255.1</IP>
        <IP>194.2.27.1</IP>
        <IP>194.2.3.1</IP>
        <IP>194.2.4.1</IP>
        <IP>194.200.0.254</IP>
        <IP>194.194.0.2</IP>
        <IP>194.194.0.29</IP>
        <IP>194.194.0.5</IP>
        <IP>194.194.0.9</IP>
        <IP>194.252.0.1</IP>
        <IP>194.252.128.1</IP>
        <IP>192.168.6.9</IP>  
      </IPS>
      <LOCATION>Lab IP LAB</LOCATION>
      <MAC>00:dx:xx:xx:xx:xx</MAC>
      <MANUFACTURER>Alcatel</MANUFACTURER>
      <MODEL>7750SR12</MODEL>
      <SNMPHOSTNAME>Test-7750SR12</SNMPHOSTNAME>
      <TYPE>NETWORKING</TYPE>
      <UPTIME>4 days, 06:36:53.94</UPTIME>
    </DEVICE>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>`

**Comment by stonebuzz** [comment]
The injection of the XML  file (from ```network-discovery```)  seems OK on my side
Can you please follow the XML from ```network-inventory```

**Comment by smurdza** [comment]
@stonebuzz I can send you to email....

**Comment by stonebuzz** [comment]
You can =)

**Comment by smurdza** [comment]
@stonebuzz Please, check your email.

**Comment by stonebuzz** [comment]
Hi @smurdza thanks for inventory files =)

No error from GLPI nightly build (I think the error is already fixed) can you try it ?

https://nightly.glpi-project.org/glpi/

Best regards

**Comment by smurdza** [comment]
Ok @stonebuzz, I'll wait for the official release.

**Comment by stonebuzz** [comment]
no problem =) 

I am closing this issue, feel free to reopen it if needed.

Best regards
