### ISSUE TITLE
FusionInventory Agent old URL support

### ISSUE THREAD

**Issue by LinU777** [glpi-project/glpi-inventory-plugin#271]
Replacing FusionInventory with GLPI Inventory requires change of server URL in FusionInventory Agent config. We have about 150 Mac computers without normal remote control, so we can't change URL. For now we had to make symlink "fusioninventory" pointing to  "glpiinventory" dir in "plugins" folder (maybe Alias or Rewrite in apache also works, but we could not make it) and patch "setup.php" to ignore symlink.

Is there any right way to save old URI?

**Comment by stonebuzz** [comment]
Hi @LinU777 
```FusionInventory``` plugin need to be deleted (from ```/plugins/``` or ```/marketplace/```) if you want to use ```glpiinventory```

You can add this to glpi ```.htacess``` to redirect to ```glpiinventory``` (is the easiest way, this will give you time to switch to the GLPI agent and change the url of the GLPI server)

```shell
<IfModule mod_rewrite.c>
   RewriteEngine On
   RewriteBase /
   RewriteRule ^.*plugins/fusioninventory/(.*)$ /plugins/glpiinventory/$1 [R=307]
</IfModule>
```

Best regards

**Comment by cedric-anne** [comment]
I pinned the issue, as this information may be usefull for many people.

**Comment by LinU777** [comment]
@stonebuzz Thanks, it works!

**Comment by Baker0052** [comment]
This does work for the Inventory.
But for the Tasks i get this in the agent log:
```
[Sun Dec 25 19:33:03 2022][info] running task ESX
[Sun Dec 25 19:33:04 2022][debug2] https://MYGLPIURL/plugins/fusioninventory/?action=getConfig&machineid=HOSTNAME&task[ESX]=2.7
[Sun Dec 25 19:33:04 2022][debug] [http client] authentication required, submitting credentials
[Sun Dec 25 19:33:04 2022][debug] [http client] authentication required, trying basic with 1322 user (UserGroup)
[Sun Dec 25 19:33:04 2022][error] [http client] Can't decode JSON content, starting with: 
<!DOCTYPE html>
<html lang="de" >
<head>
   <title>GLPI Inventory - GLPI</title>

   <meta charset="utf-8" />

      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
...
[Sun Dec 25 19:33:04 2022][info] ESX task not supported by server0
```

**Comment by g-bougard** [comment]
Hi @Baker0052 
I'm really not sure, but you may need the QSA parameter too on the RewriteRule line:
```
<IfModule mod_rewrite.c>
   RewriteEngine On
   RewriteBase /
   RewriteRule ^.*plugins/fusioninventory/(.*)$ /plugins/glpiinventory/$1 [R=307,QSA]
</IfModule>
```

**Comment by Baker0052** [comment]
Still not working.
Now i made a symlink like @LinU777  and patched the setup.php.
I made a Deploy Task to change the registry on the clients to the new url. Thats why i need the deploy task to work.
Interestingly when i use the rewrite rules and open the url with the browser (including the query strings) everything gets redirected correctly.

In the setup.php in the glpiinventory folder i changed Line 485 from "return false;" to "return true;"

I know this gets wiped if i update the plugin
