### ISSUE TITLE
deploy with user interaction fails

### ISSUE THREAD

**Issue by TheRich-71** [glpi-project/glpi-inventory-plugin#272]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

I prepared a deployment package, and since it contains the removal of the previous software, I wanted to request my users to confirm the installation. I used a predefined "Installation Warning" template, and when the user presses Ok it gets cancelled:
`usercheck after_download: Unsupported on_ok event: setting policy to stop:error_bad_event
usercheck after_download: stopping current job by user choice`

### To reproduce

1. In glpi 10.0.5 with plugin glpi-inventory, prepare a deploy package, add a userinteraction of type "Installation Warning", deploy it to a client windows PC running glpi-agent 1.4
2. At the client, wait for the message and press ok

### Expected behavior

OK should continue the installation, not cancel it

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI 10.0.5 with glpi-inventory 1.0.6

**Comment by stonebuzz** [comment]
hi @M4rkus221  @TheRich-71 

can you try this pull request ?

https://github.com/glpi-project/glpi-inventory-plugin/pull/273

Best regards
