### ISSUE TITLE
Location Rule reopen

### ISSUE THREAD

**Issue by jpdenss** [glpi-project/glpi-inventory-plugin#276]
Unfortunately this problem still exists, even in the GLPI Inventory 1.0.6 version I recently updated. I installed a database from scratch using Windows and GLPI 10.0.5. I just installed this plugin and performed the discovery. I found the device but the rule creates a new location and associates it with the device.

Apache/2.4.51 (Win64) 
PHP/8.1.0

_Originally posted by @jpdenss in https://github.com/glpi-project/glpi/issues/12758#issuecomment-1346859246_

**Comment by stonebuzz** [comment]
Can you retry with GLPI nighlty build
https://nightly.glpi-project.org/glpi/
improvements have been added on the inventory part

and glpi-inventory-plugin 1.0.6 ?

Best regards

**Comment by jpdenss** [comment]
Installed from scratch, new database, version 10.0-e9e72f7.tar.gz
The "agents" menu does not appear. But I circumvented the situation in another menu that presents an icon for accessing the agents' screen.
The feature of re-staging the job is not triggering, after running the job.
That said, the issue of creating a new location remains.
The steps taken are:

Version:
![image](https://user-images.githubusercontent.com/40672533/207632139-af0d010d-8ca1-4f9a-af94-df5939a0e797.png)


location registration
![image](https://user-images.githubusercontent.com/40672533/207630658-dd6393fd-9120-4857-b38f-fab1acb9d5a5.png)

Rule test:
![image](https://user-images.githubusercontent.com/40672533/207630917-2769272b-a90d-424f-b28a-20dda25e5dac.png)

Agent execution:
![image](https://user-images.githubusercontent.com/40672533/207631213-c2e04a80-d816-4058-a867-9b2c2fc746b9.png)

Discovery result:
![image](https://user-images.githubusercontent.com/40672533/207631379-cf919469-1da1-40ac-9118-c8d0b42a51e9.png)

New location created:
![image](https://user-images.githubusercontent.com/40672533/207631531-a49f693d-95e9-4c65-ae46-ed6065df6e0a.png)

**Comment by stonebuzz** [comment]
Can you post here rule action ?

**Comment by jpdenss** [comment]
yeah:
![image](https://user-images.githubusercontent.com/40672533/207633547-470a89d4-6f75-4fab-8028-00ffed9aef2e.png)

![image](https://user-images.githubusercontent.com/40672533/207633609-01d191bb-84d0-418f-9217-fa80160ad58f.png)

**Comment by stonebuzz** [comment]
```location1``` is in same entity than ```NetworkEquipement```?

**Comment by stonebuzz** [comment]
Can you check from ```NetworkEquipement``` if you have a ```Lock``` for ```locations_id``` (```Lock``` tab)

**Comment by stonebuzz** [comment]
Currently I do not reproduce

**Comment by jpdenss** [comment]
Yes, location is in the same entity. Its a fresh database, only with a root entity.

There is no locks in my printer. I only filtered this printer to speed up the test results. But it happens with any device that needs to associate location by the rules.
I'm going to install it on a computer with Debian to see if it has the same behavior.
![image](https://user-images.githubusercontent.com/40672533/207642803-356fbf51-a925-4104-9851-9de41e65e09d.png)

**Comment by jpdenss** [comment]
It definitely doesn't work. I used a new computer, installed Debian, the necessary programs, downloaded the version below, cleaned database, installed the 1.6 inventory plugin, created a location, a simple rule, run discovery and it has the same behavior.

![image](https://user-images.githubusercontent.com/40672533/207705934-0a68ef62-be00-441c-9969-e3a054927414.png)

**Comment by stonebuzz** [comment]
Hi @jpdenss 
any php or sql error in GLPI (```php-error.log``` / ```sql-error.log```) during inventory ?

**Comment by jpdenss** [comment]
I realized that when he creates a new location, he always assigns it to the equipment, without creating a new one. In the example, he created a location id 3 with name "2" which is the id that should match the rule.
When I renamed the name "2" to "Accounting" and performed a new discovery, it created id 4 with the name "2".

![image](https://user-images.githubusercontent.com/40672533/207899937-3234fddf-ca60-4dd4-ba3d-cc6f23cb4943.png)


PHP error: none

MariaDB log:
2022-12-15 12:10:56 0 [Note] InnoDB: Mutexes and rw_locks use Windows interlocked functions
2022-12-15 12:10:56 0 [Note] InnoDB: Uses event mutexes
2022-12-15 12:10:56 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-12-15 12:10:56 0 [Note] InnoDB: Number of pools: 1
2022-12-15 12:10:56 0 [Note] InnoDB: Using SSE2 crc32 instructions
2022-12-15 12:10:56 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2022-12-15 12:10:56 0 [Note] InnoDB: Completed initialization of buffer pool
2022-12-15 12:11:44 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2022-12-15 12:11:44 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-12-15 12:11:44 0 [Note] InnoDB: Setting file '.\ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-12-15 12:11:44 0 [Note] InnoDB: File '.\ibtmp1' size is now 12 MB.
2022-12-15 12:11:44 0 [Note] InnoDB: 10.4.22 started; log sequence number 3908086058; transaction id 8394768
2022-12-15 12:11:44 0 [Note] InnoDB: Loading buffer pool(s) from c:\wamp64\bin\mariadb\mariadb10.4.22\data\ib_buffer_pool
2022-12-15 12:11:44 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-12-15 12:11:44 0 [Note] Server socket created on IP: '::'.
2022-12-15 12:11:45 0 [Note] Reading of all Master_info entries succeeded
2022-12-15 12:11:45 0 [Note] Added new Master_info '' to hash table
2022-12-15 12:11:45 0 [Note] wampmariadb64: ready for connections.
Version: '10.4.22-MariaDB'  socket: ''  port: 3306  mariadb.org binary distribution
2022-12-15 12:11:48 0 [Note] InnoDB: Buffer pool(s) load completed at 221215 12:11:48

**Comment by stonebuzz** [comment]
I just understood that you use the entity engine to assign the location and not the location engine

![image](https://user-images.githubusercontent.com/7335054/208079637-55da9d85-39f7-437a-a573-6c2313ea9cd7.png)

![image](https://user-images.githubusercontent.com/7335054/208079646-3e490404-94f9-4b7f-828b-175135f32fc1.png)


I reproduce

**Comment by jpdenss** [comment]
Yeah, I use it like this because the location rule only has the option to assign the location, while the one I use has several other assignments, in addition to the location.

![image](https://user-images.githubusercontent.com/40672533/208102992-ee70c713-5dc9-43c2-a499-565daeb57211.png)

**Comment by stonebuzz** [comment]
Hi @jpdenss 

can you try this -> https://github.com/glpi-project/glpi/pull/13642

Best regards

**Comment by jpdenss** [comment]
PERFECT!
![image](https://user-images.githubusercontent.com/40672533/208118995-2501448c-0578-472c-b85a-fba2aedd1940.png)

**Comment by stonebuzz** [comment]
Can you try this commit https://github.com/glpi-project/glpi/pull/13642/commits/247da75d181ef23a1025734d964aa441d9fe5b5d

**Comment by jpdenss** [comment]
Same behavior. I deleted the group before performing the discovery. He recreated group 24 and attached it to the equipment.

**Comment by stonebuzz** [comment]
Can you apply this -> https://github.com/glpi-project/glpi/pull/13642/commits/608e7af0767919626ba0a9da65fb31fa422f4f8b
and retry

**Comment by jpdenss** [comment]
Perfect! Thank you very much
![image](https://user-images.githubusercontent.com/40672533/208128826-1aa0b26f-8c48-4f4f-8e3e-e73cf3612bd8.png)

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/issues/13667
