### ISSUE TITLE
Unable to load Plugin

### ISSUE THREAD

**Issue by nwaveIT** [glpi-project/glpi-inventory-plugin#279]
### Describe the bug

No way to  install Glpi Inventory 

[2022-12-19 10:45:53] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to load plugin "glpiinventory" information. in /var/www/html/glpi/src/Plugin.php at line 516
  Backtrace :
  src/Plugin.php:516                                 trigger_error()
  src/Plugin.php:472                                 Plugin->checkPluginState()
  front/marketplace.php:43                           Plugin->checkStates()

  Error: Unknown column 'printers.snmpcredentials_id' in 'field list'
  Backtrace :
  src/DBmysql.php:428
  ...ace/glpiinventory/install/update.native.php:339 DBmysql->queryOrDie()
  marketplace/glpiinventory/hook.php:412             pluginGlpiinventoryUpdateNative()
  src/Plugin.php:787                                 plugin_glpiinventory_install()
  :                                                  Plugin->install()
  src/Marketplace/Controller.php:545                 call_user_func()
  src/Marketplace/Controller.php:435                 Glpi\Marketplace\Controller->setPluginState()
  ajax/marketplace.php:82                            Glpi\Marketplace\Controller->installPlugin()

### To reproduce

Plugin download from marketplace

### Expected behavior

-
-

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin

1.0.6

### Additional context

-
-

**Comment by trasher** [comment]
Missing column should have been created updating to glpi 10.0. Check your database consistency
