### ISSUE TITLE
Discovery Network

### ISSUE THREAD

**Issue by HugzWaaa** [glpi-project/glpi-inventory-plugin#283]
### Describe the bug

Hello, I have a problem with the NetworkDiscovery module of the GLPIinventory plugin, I launch a network discovery, it finds me devices but it does not create me any device in any tab
![image](https://user-images.githubusercontent.com/113598277/211507683-9bbe0e38-9ee2-4b94-a4ec-ff630cad6c19.png)

### To reproduce

- I have created an IP range 
- I associated it with SNMP identifiers
- I have created a discovery task
- I run it

### Expected behavior

I would like the devices discovered by NetworkDiscovery to be imported into a GLPI tab

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin

1.0.6

**Comment by cedric-anne** [comment]
Hi,

If you are using GLPI 10.0.2, should should try to upgrade to GLPI 10.0.5 and check if problem persist.

**Comment by HugzWaaa** [comment]
Apparently it's not compatible
![image](https://user-images.githubusercontent.com/113598277/211512773-5ca51048-ae10-46b6-b768-c0f40f2589af.png)

**Comment by HugzWaaa** [comment]
I upgraded to 10.0.5 and now I can no longer force inventory, the status remains blocked while waiting
![image](https://user-images.githubusercontent.com/113598277/211515751-ae1b14bc-9056-4838-aef9-8797fe32c128.png)

**Comment by HugzWaaa** [comment]
However the configuration has not changed it is still the same as the one I had in 10.0.2 where I could force the inventories

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/211517400-7543d288-586a-4d87-be5a-3a0196d3fa6b.png)

**Comment by cedric-anne** [comment]
> Apparently it's not compatible ![image](https://user-images.githubusercontent.com/113598277/211512773-5ca51048-ae10-46b6-b768-c0f40f2589af.png)

`~10.0.2` means that it is compatible with GLPI >= 10.0.2 and < 10.1.0

**Comment by cedric-anne** [comment]
> I upgraded to 10.0.5 and now I can no longer force inventory, the status remains blocked while waiting ![image](https://user-images.githubusercontent.com/113598277/211515751-ae1b14bc-9056-4838-aef9-8797fe32c128.png)

Is there some entries in GLPI logs ?

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/211518655-6860fdce-2744-4eba-830e-264a51dbb0c0.png)

**Comment by cedric-anne** [comment]
Could you check in `files/_logs/php-errors.log`?

**Comment by HugzWaaa** [comment]
Ty for directory 

[2023-01-10 10:29:58] glpiphplog.WARNING: Test logger  
[2023-01-10 10:40:51] glpiphplog.WARNING:   *** PHP User Warning (512): Échec de connexion. Si vous utilisez un proxy, merci de le configurer. (Connection timed out after 5001 milliseconds) in C:\inetpub\glpi4\src\Toolbox.php at line 1517
  Backtrace :
  src\Toolbox.php:1517                               trigger_error()
  src\GLPINetwork.php:315                            Toolbox::callCurl()
  src\GLPINetwork.php:81                             GLPINetwork::isServicesAvailable()
  src\GLPINetwork.php:50                             GLPINetwork::showForConfig()
  src\CommonGLPI.php:689                             GLPINetwork::displayTabContentForItem()
  ajax\common.tabs.php:113                           CommonGLPI::displayStandardTab()

**Comment by cedric-anne** [comment]
This is not related to your issue.

I do not have any clue relating to your issue, so I have nothing to propose.

**Comment by HugzWaaa** [comment]
Can you send my request to technical support ?

**Comment by cedric-anne** [comment]
> Can you send my request to technical support ?

You can use this form: https://portal.glpi-network.com/marketplace/formcreator/front/formdisplay.php?id=15

**Comment by trasher** [comment]
Looks like a support quesiton rather than a real issue, I close.
