### ISSUE TITLE
Bug when assign technical group

### ISSUE THREAD

**Issue by kbn53** [glpi-project/glpi-inventory-plugin#291]
### Describe the bug

When I create a rule to assign entity + technical group to a computer, my computer take the good entity but he take a new group (the id of my official group).

### To reproduce

Create rule to assign element to entity
Assign entity and technical group
Bad group assigned

### Expected behavior

![2023-01-23 14_53_29-Règle - Alize_International - GLPI et 10 pages de plus - Travail – Microsoft​ Ed](https://user-images.githubusercontent.com/71877652/214057243-0b80a7b0-e6e0-42a8-a2c1-4d0bda5e15ac.png)
![2023-01-23 14_53_00-Groupes - GLPI et 10 pages de plus - Travail – Microsoft​ Edge](https://user-images.githubusercontent.com/71877652/214057250-2ac5e0eb-c995-4f62-b08f-ee3ce96d73b2.png)
![2023-01-23 14_53_11-Groupe - ALIZE INTERNA - GLPI et 10 pages de plus - Travail – Microsoft​ Edge](https://user-images.githubusercontent.com/71877652/214057257-478cdd44-efde-49a7-b944-d605232ff90a.png)
![2023-01-23 14_53_22-Règle - Alize_International - GLPI et 10 pages de plus - Travail – Microsoft​ Ed](https://user-images.githubusercontent.com/71877652/214057260-540e0eef-19bb-402a-97e7-97fae98542a7.png)
![2023-01-23 14_53_27-Règle - Alize_International - GLPI et 10 pages de plus - Travail – Microsoft​ Ed](https://user-images.githubusercontent.com/71877652/214057262-a2d0aad7-e068-44a7-a94f-f6dbc9c2e30d.png)

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin

1.0.6

**Comment by trasher** [comment]
10.0.3 is outdated. Try with laster GLPI core nightly or wait for new release that will be available this week.

**Comment by stonebuzz** [comment]
hi @kbn53 
This issue (already discuss here https://github.com/glpi-project/glpi-inventory-plugin/issues/276 or here https://github.com/glpi-project/glpi/issues/13667)
is fixed by this Pull Request https://github.com/glpi-project/glpi/pull/13668 
and merge in GLPI 10.0.6.

You should update your version of GLPI

Best regards
