### ISSUE TITLE
GLPI Inventory menu missing

### ISSUE THREAD

**Issue by lexcyr** [glpi-project/glpi-inventory-plugin#292]
### Describe the bug

After updated my GLPi from 10.0.3 to 10.0.5 as requested from my previous issue #290, i have now a new issue.

I am not able to have "Agent Management" menu on the GLPI inventory module under "Administration » GLPI Inventory"
![image](https://user-images.githubusercontent.com/10072663/214135286-bdccd427-9d1a-4f4b-a56f-1812c54c392c.png)

Beside than when i use the direct link "server_IP//glpi/front/agent.php" the agent installed in the computer still don't report there.

Thanks in advance for your help.

GLPI 10.0.5
GLPI Inventory 1.0.6
GLPI Agent 1.4

### To reproduce

1. update GLPI from 10.0.3 to 10.0.5
2. activate GLPI inventory Plugin
3. navigate to "Administration » GLPI Inventory» Général "

### Expected behavior

There should be a sub-menu "Agent Management" under Général on the GLPI Inventory module

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin

1.0.6

**Comment by stonebuzz** [comment]
Hi @lexcyr 
can you try this -> https://github.com/glpi-project/glpi-inventory-plugin/pull/293

Best regards
