### ISSUE TITLE
GLPI agent not reporting in GLPI Inventory agent management

### ISSUE THREAD

**Issue by lexcyr** [glpi-project/glpi-inventory-plugin#294]
### Describe the bug

After installation of GLPI agent on a computer, it's not reporting in the list of agent in the glpi inventory agent management section of the glpi inventory plugin.
If i use the search filter and search for that server name, i can find it, but when i clic on it i am redirected to the home page.

### To reproduce

1. Install the glpi inventory plugin on your glpi server 10.0.5
2. Install the glpi agent 1.4 on a computer with option run inventory after installation
3. Navigate to "Administration » GLPI Inventory » General » Agent Management"
4. Activate the search filter
5. Search for the computer
6. Clic on the computer in the result

### Expected behavior

Have the glpi agent registered in the glpi inventory agent management list. 
And be able to config and activate/deactivate agent module.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin

1.0.6

**Comment by cedric-anne** [comment]
Hi,

Could you please try to upgrade GLPI to version 10.0.6 and plugin to version 1.1.0 and check if problem persists ?

**Comment by lexcyr** [comment]
Update done, but still not able to have the computer reporting in the agent mangament list.
this is the error i am having the Agent log:
![image](https://user-images.githubusercontent.com/10072663/214356843-0119857b-d46e-44b5-a9a4-fed0dac9be65.png)

i feel like i am doing something wrong in the configuration of the agent but i am not able to find what. The only things i am setting during the agent configuration for the moment iare the server link (http://_glpi_server_IP_/glpi/plugins/glpiinventory) and disable the ssl_check.

GLPI 10.0.6
GLPI Inventory 1.1.0
GLPI Agent 1.4

**Comment by lexcyr** [comment]
I ran a `php bin/console glpi:database:check_schema_integrity` and i got some differences for the glpi_agent table:
"
--- Schéma attendu de la base de données
+++ Schéma actuel de la base de données
@@ @@
 CREATE TABLE glpi_agents (
-  id int NOT NULL AUTO_INCREMENT,
-  agenttypes_id int NOT NULL,
-  deviceid varchar(255) NOT NULL,
-  entities_id int NOT NULL DEFAULT 0,
-  is_recursive tinyint NOT NULL DEFAULT 0,
-  items_id int NOT NULL,
-  itemtype varchar(100) NOT NULL,
-  last_contact datetime,
-  locked tinyint NOT NULL DEFAULT 0,
-  name varchar(255),
-  port varchar(6),
-  remote_addr varchar(255),
-  tag varchar(255),
-  threads_networkdiscovery int NOT NULL DEFAULT 1,
-  threads_networkinventory int NOT NULL DEFAULT 1,
-  timeout_networkdiscovery int NOT NULL DEFAULT 0,
-  timeout_networkinventory int NOT NULL DEFAULT 0,
-  use_module_collect_data tinyint NOT NULL DEFAULT 0,
-  use_module_computer_inventory tinyint NOT NULL DEFAULT 0,
-  use_module_esx_remote_inventory tinyint NOT NULL DEFAULT 0,
-  use_module_network_discovery tinyint NOT NULL DEFAULT 0,
-  use_module_network_inventory tinyint NOT NULL DEFAULT 0,
-  use_module_package_deployment tinyint NOT NULL DEFAULT 0,
-  use_module_remote_inventory tinyint NOT NULL DEFAULT 0,
-  use_module_wake_on_lan tinyint NOT NULL DEFAULT 0,
-  useragent varchar(255),
-  version varchar(255),
-  PRIMARY KEY (id),
-  UNIQUE KEY deviceid (deviceid),
-  KEY agenttypes_id (agenttypes_id),
-  KEY entities_id (entities_id),
-  KEY is_recursive (is_recursive),
-  KEY item (itemtype,items_id),
-  KEY name (name)
-)
+id int(10) unsigned NOT NULL,
+deviceid varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
+entities_id int(10) unsigned NOT NULL DEFAULT 0,
+is_recursive tinyint(4) NOT NULL DEFAULT 0,
+name varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
+agenttypes_id int(10) unsigned NOT NULL,
+last_contact timestamp NULL DEFAULT NULL,
+version varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
+locked tinyint(4) NOT NULL DEFAULT 0,
+itemtype varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
+items_id int(10) unsigned NOT NULL,
+useragent varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
+tag varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
+port varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
+threads_networkdiscovery int(11) NOT NULL DEFAULT 1 COMMENT 'Number of threads for Network discovery',
+threads_networkinventory int(11) NOT NULL DEFAULT 1 COMMENT 'Number of threads for Network inventory',
+timeout_networkdiscovery int(11) NOT NULL DEFAULT 0 COMMENT 'Network Discovery task timeout (disabled by default)',
+timeout_networkinventory int(11) NOT NULL DEFAULT 0 COMMENT 'Network Inventory task timeout (disabled by default)',
+remote_addr varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
+use_module_wake_on_lan tinyint(4) NOT NULL DEFAULT 0,
+use_module_computer_inventory tinyint(4) NOT NULL DEFAULT 0,
+use_module_esx_remote_inventory tinyint(4) NOT NULL DEFAULT 0,
+use_module_remote_inventory tinyint(4) NOT NULL DEFAULT 0,
+use_module_network_inventory tinyint(4) NOT NULL DEFAULT 0,
+use_module_network_discovery tinyint(4) NOT NULL DEFAULT 0,
+use_module_package_deployment tinyint(4) NOT NULL DEFAULT 0,
+use_module_collect_data tinyint(4) NOT NULL DEFAULT 0
+) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC
"

is there a way or command to auto fix the database schema?

thanks in advance.

**Comment by cedric-anne** [comment]
> I ran a `php bin/console glpi:database:check_schema_integrity` and i got some differences for the glpi_agent table:
> 
> ```diff
> --- Schéma attendu de la base de données
> +++ Schéma actuel de la base de données
> @@ @@
>  CREATE TABLE glpi_agents (
> -  id int NOT NULL AUTO_INCREMENT,
> -  agenttypes_id int NOT NULL,
> -  deviceid varchar(255) NOT NULL,
> -  entities_id int NOT NULL DEFAULT 0,
> -  is_recursive tinyint NOT NULL DEFAULT 0,
> -  items_id int NOT NULL,
> -  itemtype varchar(100) NOT NULL,
> -  last_contact datetime,
> -  locked tinyint NOT NULL DEFAULT 0,
> -  name varchar(255),
> -  port varchar(6),
> -  remote_addr varchar(255),
> -  tag varchar(255),
> -  threads_networkdiscovery int NOT NULL DEFAULT 1,
> -  threads_networkinventory int NOT NULL DEFAULT 1,
> -  timeout_networkdiscovery int NOT NULL DEFAULT 0,
> -  timeout_networkinventory int NOT NULL DEFAULT 0,
> -  use_module_collect_data tinyint NOT NULL DEFAULT 0,
> -  use_module_computer_inventory tinyint NOT NULL DEFAULT 0,
> -  use_module_esx_remote_inventory tinyint NOT NULL DEFAULT 0,
> -  use_module_network_discovery tinyint NOT NULL DEFAULT 0,
> -  use_module_network_inventory tinyint NOT NULL DEFAULT 0,
> -  use_module_package_deployment tinyint NOT NULL DEFAULT 0,
> -  use_module_remote_inventory tinyint NOT NULL DEFAULT 0,
> -  use_module_wake_on_lan tinyint NOT NULL DEFAULT 0,
> -  useragent varchar(255),
> -  version varchar(255),
> -  PRIMARY KEY (id),
> -  UNIQUE KEY deviceid (deviceid),
> -  KEY agenttypes_id (agenttypes_id),
> -  KEY entities_id (entities_id),
> -  KEY is_recursive (is_recursive),
> -  KEY item (itemtype,items_id),
> -  KEY name (name)
> -)
> +id int(10) unsigned NOT NULL,
> +deviceid varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
> +entities_id int(10) unsigned NOT NULL DEFAULT 0,
> +is_recursive tinyint(4) NOT NULL DEFAULT 0,
> +name varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> +agenttypes_id int(10) unsigned NOT NULL,
> +last_contact timestamp NULL DEFAULT NULL,
> +version varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> +locked tinyint(4) NOT NULL DEFAULT 0,
> +itemtype varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
> +items_id int(10) unsigned NOT NULL,
> +useragent varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> +tag varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> +port varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> +threads_networkdiscovery int(11) NOT NULL DEFAULT 1 COMMENT 'Number of threads for Network discovery',
> +threads_networkinventory int(11) NOT NULL DEFAULT 1 COMMENT 'Number of threads for Network inventory',
> +timeout_networkdiscovery int(11) NOT NULL DEFAULT 0 COMMENT 'Network Discovery task timeout (disabled by default)',
> +timeout_networkinventory int(11) NOT NULL DEFAULT 0 COMMENT 'Network Inventory task timeout (disabled by default)',
> +remote_addr varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> +use_module_wake_on_lan tinyint(4) NOT NULL DEFAULT 0,
> +use_module_computer_inventory tinyint(4) NOT NULL DEFAULT 0,
> +use_module_esx_remote_inventory tinyint(4) NOT NULL DEFAULT 0,
> +use_module_remote_inventory tinyint(4) NOT NULL DEFAULT 0,
> +use_module_network_inventory tinyint(4) NOT NULL DEFAULT 0,
> +use_module_network_discovery tinyint(4) NOT NULL DEFAULT 0,
> +use_module_package_deployment tinyint(4) NOT NULL DEFAULT 0,
> +use_module_collect_data tinyint(4) NOT NULL DEFAULT 0
> +) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC
> ```
> 
> is there a way or command to auto fix the database schema?
> 
> thanks in advance.

In you case, you should probably launch `bin/console migration:migrate_all` command.

**Comment by stonebuzz** [comment]
Any ```PHP``` / ```SQL``` error log from GLPI during inventory ?

**Comment by lexcyr** [comment]
> > I ran a `php bin/console glpi:database:check_schema_integrity` and i got some differences for the glpi_agent table:
> > ```diff
> > --- Schéma attendu de la base de données
> > +++ Schéma actuel de la base de données
> > @@ @@
> >  CREATE TABLE glpi_agents (
> > -  id int NOT NULL AUTO_INCREMENT,
> > -  agenttypes_id int NOT NULL,
> > -  deviceid varchar(255) NOT NULL,
> > -  entities_id int NOT NULL DEFAULT 0,
> > -  is_recursive tinyint NOT NULL DEFAULT 0,
> > -  items_id int NOT NULL,
> > -  itemtype varchar(100) NOT NULL,
> > -  last_contact datetime,
> > -  locked tinyint NOT NULL DEFAULT 0,
> > -  name varchar(255),
> > -  port varchar(6),
> > -  remote_addr varchar(255),
> > -  tag varchar(255),
> > -  threads_networkdiscovery int NOT NULL DEFAULT 1,
> > -  threads_networkinventory int NOT NULL DEFAULT 1,
> > -  timeout_networkdiscovery int NOT NULL DEFAULT 0,
> > -  timeout_networkinventory int NOT NULL DEFAULT 0,
> > -  use_module_collect_data tinyint NOT NULL DEFAULT 0,
> > -  use_module_computer_inventory tinyint NOT NULL DEFAULT 0,
> > -  use_module_esx_remote_inventory tinyint NOT NULL DEFAULT 0,
> > -  use_module_network_discovery tinyint NOT NULL DEFAULT 0,
> > -  use_module_network_inventory tinyint NOT NULL DEFAULT 0,
> > -  use_module_package_deployment tinyint NOT NULL DEFAULT 0,
> > -  use_module_remote_inventory tinyint NOT NULL DEFAULT 0,
> > -  use_module_wake_on_lan tinyint NOT NULL DEFAULT 0,
> > -  useragent varchar(255),
> > -  version varchar(255),
> > -  PRIMARY KEY (id),
> > -  UNIQUE KEY deviceid (deviceid),
> > -  KEY agenttypes_id (agenttypes_id),
> > -  KEY entities_id (entities_id),
> > -  KEY is_recursive (is_recursive),
> > -  KEY item (itemtype,items_id),
> > -  KEY name (name)
> > -)
> > +id int(10) unsigned NOT NULL,
> > +deviceid varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
> > +entities_id int(10) unsigned NOT NULL DEFAULT 0,
> > +is_recursive tinyint(4) NOT NULL DEFAULT 0,
> > +name varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> > +agenttypes_id int(10) unsigned NOT NULL,
> > +last_contact timestamp NULL DEFAULT NULL,
> > +version varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> > +locked tinyint(4) NOT NULL DEFAULT 0,
> > +itemtype varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
> > +items_id int(10) unsigned NOT NULL,
> > +useragent varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> > +tag varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> > +port varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> > +threads_networkdiscovery int(11) NOT NULL DEFAULT 1 COMMENT 'Number of threads for Network discovery',
> > +threads_networkinventory int(11) NOT NULL DEFAULT 1 COMMENT 'Number of threads for Network inventory',
> > +timeout_networkdiscovery int(11) NOT NULL DEFAULT 0 COMMENT 'Network Discovery task timeout (disabled by default)',
> > +timeout_networkinventory int(11) NOT NULL DEFAULT 0 COMMENT 'Network Inventory task timeout (disabled by default)',
> > +remote_addr varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
> > +use_module_wake_on_lan tinyint(4) NOT NULL DEFAULT 0,
> > +use_module_computer_inventory tinyint(4) NOT NULL DEFAULT 0,
> > +use_module_esx_remote_inventory tinyint(4) NOT NULL DEFAULT 0,
> > +use_module_remote_inventory tinyint(4) NOT NULL DEFAULT 0,
> > +use_module_network_inventory tinyint(4) NOT NULL DEFAULT 0,
> > +use_module_network_discovery tinyint(4) NOT NULL DEFAULT 0,
> > +use_module_package_deployment tinyint(4) NOT NULL DEFAULT 0,
> > +use_module_collect_data tinyint(4) NOT NULL DEFAULT 0
> > +) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is there a way or command to auto fix the database schema?
> > thanks in advance.
> 
> In you case, you should probably launch `bin/console migration:migrate_all` command.

After running the migration command it says there is no migration requiered
![image](https://user-images.githubusercontent.com/10072663/214593392-178c43ae-db5f-4a88-8bfa-2a5fe962584f.png)

**Comment by cedric-anne** [comment]
What is the result of `php bin/console glpi:database:check_schema_integrity` now ?

**Comment by lexcyr** [comment]
> Any `PHP` / `SQL` error log from GLPI during inventory ?

no PHP error log from GLPI during inventory, but i have only one warning about that specific computer on the SQL log
![image](https://user-images.githubusercontent.com/10072663/214595457-cd280c43-f7a2-449c-bee7-772f7e60b89f.png)

**Comment by lexcyr** [comment]
So i have exported the gpli_agent table from my test environement where i had no error on the schema integrity checks and imported it on the problematic glpi server. It seems it had resolved the db schema issue.
![image](https://user-images.githubusercontent.com/10072663/214640614-f54e2db3-ed3c-4062-9790-01c9a62e339a.png)

After flushing all the glpi agent recorded in the agent management list , it registers them back progressively based on their next planned server contact.

I am using this GLPI server only for asset management and i am not experiencing any other proglem. At least for the moment.

**Comment by cedric-anne** [comment]
Hi,

I close the issue as problem seems to have dissapear. Feel fre to reopen if problem comes back.
