### ISSUE TITLE
Each time a port is removed and added during snmp inventory.

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi-inventory-plugin#295]
### Describe the bug

Hello.
Each time the printer has a network port removed and added during snmp inventory.
![image](https://user-images.githubusercontent.com/16879167/214775798-ad546dfd-9d24-41c9-ada3-0f9f3d49f206.png)
![image](https://user-images.githubusercontent.com/16879167/214776012-2102d33f-a532-4f72-a51e-ed98d4e79d12.png)

### To reproduce

Update GLPI 10.0.5 > 10.0.6
Update GLPIInventory plugin 1.0.6 > 1.1.0
Install GLPI-agent 1.4
Run SNMP Inventory

### Expected behavior

The port information should be updated, but the port should not be deleted and created again.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin

Other (See additional context below)

### Additional context

GLPIInventory plugin 1.1.0

[printer_0_134.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/10507034/printer_0_134.zip)

**Comment by kofe88** [comment]
@stonebuzz 

![image](https://user-images.githubusercontent.com/16879167/215688437-2d1f2acc-48e5-4b6f-9963-ec3da1f79daf.png)

I confirm that the problem has been solved, the port was not deleted during the next inventory.

**Comment by trasher** [comment]
Thanks for your feedback, PR has been merged and will be part of next GLPI core release
