### ISSUE TITLE
The same software is allegedly removed and installed with each inventory.

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi-inventory-plugin#296]
### Describe the bug

On some PCs (mainly Windows 10), the same software is allegedly removed and installed with each inventory.

![image](https://user-images.githubusercontent.com/16879167/214785281-54c3b88d-5ec3-4e48-b42c-3d1bd11295ac.png)

I can assume that this is due to the fact that after switching to GLPI-agent with Fusioninventory-agent, old inventory files remain in the folder, they themselves are not deleted and are available for download from the PC page.

### To reproduce

Update GLPI 10.0.5 > 10.0.6
Update GLPIInventory plugin 1.0.6 > 1.1.0
Install GLPI-agent 1.4
Run Inventory on PCs

### Expected behavior

If the software has not changed, it should not get into the log.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin

1.1.0

### Additional context

[computer_0_39.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/10515942/computer_0_39.zip)

**Comment by stonebuzz** [comment]
Hi @kofe88 
i reproduce but only for ```SoundCloud - Music & Songs - 2.0.0.0``` software

**Comment by stonebuzz** [comment]
Hi @kofe88 
can you try this -> https://github.com/glpi-project/glpi/pull/13893

Best regards

**Comment by kofe88** [comment]
@stonebuzz , Hi!
I made these changes, but it only helped with SoundCloud.
![image](https://user-images.githubusercontent.com/16879167/214904718-9b8272b4-31c7-4385-8e67-559665b04e84.png)

In fact, this happens on a lot of PCs, with different software. But more often it repeats. For example, from another PC.

![image](https://user-images.githubusercontent.com/16879167/214905190-0080f934-aee3-4504-a00c-b0c0ddeafebf.png)

I can make these changes to the production server and tell you tomorrow what other software is also being removed and installed.

**Comment by kofe88** [comment]
@stonebuzz Here's more, before and after the changes.

![image](https://user-images.githubusercontent.com/16879167/214910522-2c24c5aa-4a22-4d8b-9275-e53cab1906cc.png)

**Comment by stonebuzz** [comment]
I may be wrong but I notice that on these softwares there are no manufacturers, it may be a lead. i will check tomorrow

**Comment by stonebuzz** [comment]
I do not reproduce with your last examples (```Yandex Browser```, ```AMD Steady Video Plug-In ```, ```Microsoft SQL Server 2012 Native Client ```)

Do you have any PHP SQL errors (from glpi/files/_log) at the time of import

**Comment by stonebuzz** [comment]
> @stonebuzz Here's more, before and after the changes.
> 
> ![image](https://user-images.githubusercontent.com/16879167/214910522-2c24c5aa-4a22-4d8b-9275-e53cab1906cc.png)
> 
> ```
>             {
>                 "arch": "x86_64",
>                 "from": "registry",
>                 "guid": "{143BC1A3-E923-4379-9550-93881113290E}",
>                 "install_date": "2023-01-25",
>                 "name": "Yandex Browser",
>                 "publisher": "\u041e\u041e\u041e \u00ab\u042f\u041d\u0414\u0415\u041a\u0421\u00bb",
>                 "system_category": "application",
>                 "uninstall_string": "MsiExec.exe \/X{143BC1A3-E923-4379-9550-93881113290E}",
>                 "version": "22.11.0.2424"
>             }
> ```
> 
> ```
>             {
>                 "arch": "x86_64",
>                 "from": "registry",
>                 "guid": "{13146756-9716-4843-84CA-053916D2FCF9}",
>                 "helplink": "http:\/\/go.microsoft.com\/fwlink\/?LinkId=191752",
>                 "install_date": "2022-12-23",
>                 "name": "Microsoft SQL Server 2012 Native Client ",
>                 "publisher": "Microsoft Corporation",
>                 "system_category": "application",
>                 "uninstall_string": "MsiExec.exe \/I{13146756-9716-4843-84CA-053916D2FCF9}",
>                 "version": "11.3.6538.0"
>             }
> ```
> 
> ```
>             {
>                 "arch": "x64",
>                 "folder": "C:\\Program Files\\WindowsApps\\Microsoft.XboxGameOverlay_1.54.4001.0_x64__8wekyb3d8bbwe",
>                 "from": "uwp",
>                 "install_date": "2022-12-06",
>                 "name": "Xbox Game Bar Plugin",
>                 "publisher": "Microsoft Corporation",
>                 "system_category": "store",
>                 "version": "1.54.4001.0"
>             }
> ```
> 
> From another PC
> 
> ![image](https://user-images.githubusercontent.com/16879167/215015818-f901daae-8738-4dd6-ba39-d5ad6c748af9.png)
> 
> ```
>             {
>                 "arch": "x86_64",
>                 "from": "registry",
>                 "guid": "{2C637DB1-3E0A-4089-8366-C6C0B01E5C2B}",
>                 "install_date": "2017-02-28",
>                 "name": "AMD Steady Video Plug-In ",
>                 "publisher": "AMD",
>                 "system_category": "system_component",
>                 "uninstall_string": "MsiExec.exe \/X{2C637DB1-3E0A-4089-8366-C6C0B01E5C2B}",
>                 "url_info_about": "http:\/\/www.AMD.com",
>                 "version": "2.07.0000"
>             }
> ```

Can you redo an inventory on this computer and see if 

- ```Yandex Browser```
- ```AMD Steady Video Plug-In ```
-  ```Microsoft SQL Server 2012 Native Client ```

I think that your test has straightened out the data in the database but that a second inventory should go well

Best regards

**Comment by kofe88** [comment]
@stonebuzz 
Unfortunately, no, the software that was with the '&' signs is gone, but the other one remains.

![image](https://user-images.githubusercontent.com/16879167/215045077-8f1f9fe4-ffc6-442c-8ed0-3dc2db858016.png)

Also ran inventory several times on another PC

![image](https://user-images.githubusercontent.com/16879167/215044424-a1e81aa6-c331-40f6-899e-f2a982fef85c.png)

I don't see any errors in the logs that would coincide with the inventory time.

**Comment by stonebuzz** [comment]
The PR has evolved, could you test the new version

https://github.com/glpi-project/glpi/pull/13893

Best regards

**Comment by kofe88** [comment]
> The PR has evolved, could you test the new version
> 
> [glpi-project/glpi#13893](https://github.com/glpi-project/glpi/pull/13893)
> 
> Best regards

@stonebuzz 

Greetings. I tried with these changes, the result is the same.

![image](https://user-images.githubusercontent.com/16879167/215264034-1a1c3b13-f9b9-4f88-8d0b-0b98de9ce066.png)

Maybe somehow it is possible to output to the log with what he compares what and why he thinks that the software is reinstalled?

**Comment by stonebuzz** [comment]
From ```Xbox Game Bar``` software, have you a ```publisher```?

 
![image](https://user-images.githubusercontent.com/7335054/215457389-16af7736-16e2-456d-84c2-78ffd6bed7da.png)

**Comment by kofe88** [comment]
Greetings, yes, there is a publisher. But I noticed that this particular software has a different feature:

![image](https://user-images.githubusercontent.com/16879167/215552540-ebea1db2-9140-42e7-b315-0474b1791f1e.png)

But after the inventory remains in PC:

![image](https://user-images.githubusercontent.com/16879167/215552856-2d8213a2-4233-420a-9467-fc30cc1d3c3e.png)

In the general list of software there are both:

![image](https://user-images.githubusercontent.com/16879167/215555052-d0621607-0f16-4c18-899b-bad42a7b464a.png)

Nothing was added manually, everything was done only through automatic inventories.

But unfortunately, this has not been noticed with other problematic software.
![image](https://user-images.githubusercontent.com/16879167/215555189-3a28008c-d643-484b-8314-d40389e65c5b.png)

![image](https://user-images.githubusercontent.com/16879167/215554717-593a5742-e8fb-4a65-a192-7ef1339511c4.png)

But maybe this information will help somehow.

**Comment by stonebuzz** [comment]
Hi,
do you have software dictionary rules / manufacturer ?
Can you export them and post file here?

**Comment by kofe88** [comment]
@stonebuzz 

I didn't create any separate rules, there is only one, but as I understand it, it is default and it is turned off.

![image](https://user-images.githubusercontent.com/16879167/215689269-782dd630-a796-4b58-985a-b68a2d1c41ad.png)

**Comment by stonebuzz** [comment]
Hi @kofe88 
Can you retry tomorrow with nighlty build ?

**Comment by kofe88** [comment]
@stonebuzz 
Greetings! Today I will try and unsubscribe about the result.

**Comment by kofe88** [comment]
@stonebuzz 

Greetings, apologies for the delay. Checked the last "night build" 10.0-0826627.tar.gz, no changes. 
I import the same file, the software is deleted/added.

![image](https://user-images.githubusercontent.com/16879167/217363225-ee2e6509-ced6-43cc-9ebf-1e6587d860ac.png)

![image](https://user-images.githubusercontent.com/16879167/217364324-c8855551-4987-45ec-a2ae-346254d2fc13.png)

**Comment by stonebuzz** [comment]
removing the software was the next step for debug =) 
not reproducing on my side the data set on your PROD is perhaps in cause

but, it is necessary to clean other tables that also concern the software

- glpi_softwares
- glpi_softwareversions
- glpi_items_softwareversions

Can you redo a test by emptying these three tables?

Best regards

**Comment by trasher** [comment]
No feedback, I close
