### ISSUE TITLE
Error in DevTools Console on /front/crontask.form.php

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi-inventory-plugin#298]
### Describe the bug

There is an error on the tasks page in the console, but it doesn't seem to affect anything (but this is not accurate)

![image](https://user-images.githubusercontent.com/16879167/215039791-1f893ae6-3c27-4547-929a-405e3e5b99ed.png)

### To reproduce

Go to /front/crontask.php
Go to the page with any task, for example /front/crontask.form.php?id=21
Open DevTools in Browser (F12)

```shell
JQMIGRATE: Migrate is installed with logging active, version 3.4.0
taskjobs.js?v=59a143f1a5d49e31a701e21817e0c6b173076867:212 Uncaught ReferenceError: d3 is not defined
    at taskjobs.js?v=59a143f1a5d49e31a701e21817e0c6b173076867:212:23
(anonymous) @ taskjobs.js?v=59a143f1a5d49e31a701e21817e0c6b173076867:212
```

### Expected behavior

No

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin

1.1.0

### Additional context

/plugins/glpiinventory/js/taskjobs.js?v=59a143f1a5d49e31a701e21817e0c6b173076867

**Comment by trasher** [comment]
Could you please try with https://github.com/glpi-project/glpi-inventory-plugin/pull/299

**Comment by kofe88** [comment]
> Could you please try with #299

@trasher Hi!
Do I need to make these changes and reinstall the plugin?

**Comment by trasher** [comment]
Just apply changes and try again

**Comment by kofe88** [comment]
@trasher Hi

I confirm that the problem has been solved.

![image](https://user-images.githubusercontent.com/16879167/215685470-6d579045-569d-42d4-aa2c-b2b598c9410e.png)

**Comment by trasher** [comment]
Thanks for the feeback
