### ISSUE TITLE
deploy package

### ISSUE THREAD

**Issue by LordSvein** [glpi-project/glpi-inventory-plugin#300]
### Describe the bug

When i create task whith glpi inventory to deploy an app the task don't go to step "in progress" he stay at "to do". but i can do an inventory/scan network/scan snmp work

logs

[Fri Jan 27 15:09:00 2023][debug2] [http client] 28DCF30A: received message:
{"message":"remoteinventory task not supported","disabled":["remoteinventory"],"expiration":"24","status":"ok","tasks":{"collect":{"version":"1.1.0","server":"glpiinventory"},"deploy":{"version":"1.1.0","server":"glpiinventory"},"esx":{"version":"1.1.0","server":"glpiinventory"},"inventory":{"server":"glpi","version":"10.0.6"},"netdiscovery":{"version":"1.1.0","server":"glpiinventory"},"netinventory":{"version":"1.1.0","server":"glpiinventory"}}}
[Fri Jan 27 15:09:00 2023][debug] server message: remoteinventory task not supported
[Fri Jan 27 15:09:00 2023][debug] [http client] Using Compress::Zlib for compression
[Fri Jan 27 15:09:00 2023][info] sending prolog request to server0

[Fri Jan 27 15:09:43 2023][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Fri Jan 27 15:09:43 2023][info] Deploy task not supported by server0
[Fri Jan 27 15:09:43 2023][debug] new thread 7 to handle task Collect

### To reproduce

create task to deploy pakage 
force the deploy

### Expected behavior

i just want to install my app whit a task

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin

1.1.0

**Comment by stonebuzz** [comment]
Hi @LordSvein 
``` communication error: 400 Bad Request, Protocol not supported```

Can you check : 
- ```server``` option from GLPI agent configuration
- ```agent base URL``` from Entity > Assets tab

![image](https://user-images.githubusercontent.com/7335054/215124360-b7aca5b2-5cc5-4188-b9c5-2ac9da61953c.png)

Best regards

**Comment by g-bougard** [comment]
I think the server URL is wrong, but we don't see any example of the URL you configured.
Check this doc to set the right URL: https://glpi-agent.readthedocs.io/en/latest/configuration.html#server

**Comment by LordSvein** [comment]
> * server

my url is good because i can do inventory, scan network and scan snmp 
![Capture d’écran 2023-01-27 173302](https://user-images.githubusercontent.com/39635317/215141216-08a09aac-4fa3-48c9-9653-47c1bec1efbd.png)
 but when i want to deploy an app i have " communication error: 400 Bad Request, Protocol not supported"

**Comment by LordSvein** [comment]
![Capture d’écran 2023-01-27 173503](https://user-images.githubusercontent.com/39635317/215141721-a39e213b-e919-489c-ba6a-aaebbf1bf82b.png)

**Comment by g-bougard** [comment]
> my url is good because i can do inventory, scan network and scan snmp

This is a wrong assumption. The protocol is different and if the URL is wrong you'll obtain Error 400. Please read the doc and fix your url as it is relly specific for Deploy, ESX and Collect tasks. Netdiscovery and netinventory tasks will work even with the native inventory standard url.

**Comment by LordSvein** [comment]
When i read the doc he said we can put 'http://<name-server>' whit glpi 10.0.6 and he is not work when in write 'http:/<name-server>/front/glpiinventory.php ' it the same i cant deploy app

**Comment by LordSvein** [comment]
[Sun Jan 29 13:48:57 2023][info] Deploy task not supported by server0
[Sun Jan 29 13:48:57 2023][debug] new thread 11 to handle task Inventory
[Sun Jan 29 13:48:57 2023][info] running task Inventory
[Sun Jan 29 13:48:57 2023][info] New inventory from DESKTOP-G7DUCUQ-2023-01-28-21-46-03 for server0
[Sun Jan 29 13:48:57 2023][debug2] module GLPI::Agent::Task::Inventory::AIX disabled

**Comment by LordSvein** [comment]
[Sun Jan 29 14:26:21 2023][info] running task Deploy
[Sun Jan 29 14:26:21 2023][debug2] http://192.168.1.130/?action=getConfig&machineid=DESKTOP-G7DUCUQ-2023-01-28-21-46-03&task[Deploy]=2.10
[Sun Jan 29 14:26:21 2023][error] [http client] Can't decode JSON content, starting with: 
         

<!DOCTYPE html>
<html lang="fr" >
<head>
   <title>Authentification - GLPI</title>

   <meta charset="utf-8" />
...
[Sun Jan 29 14:26:21 2023][info] Deploy task not supported by server0
[Sun Jan 29 14:26:21 2023][debug] new thread 54 to handle task Inventory
[Sun Jan 29 14:26:21 2023][info] running task Inventory

**Comment by g-bougard** [comment]
Please, use `http://myserver/marketplace/glpiinventory/` or `http://myserver/plugins/glpiinventory/` as URL depending how you installed GlpiInventory plugin. This is what you're missing in the doc.

**Comment by trasher** [comment]
This is not a bug biut a misconfiguration issue, I close
