### ISSUE TITLE
Inventory Error when Dictionaries Manufactures set

### ISSUE THREAD

**Issue by AndiFo** [glpi-project/glpi-inventory-plugin#301]
### Describe the bug

If set a rule "Dictonaries" for Manufacture Microsoft. When I deactivate the rule all works fine, but if the rule is activited I become following error:

*** PHP User Error (256): Incorrect integer value: 'Microsoft' for column `glpi_qs`.`glpi_softwares`.`manufacturers_id` at row 1 in src\DBmysql.php at line 1969
  Backtrace :
  src\DBmysql.php:1969                               trigger_error()
  src\Inventory\Asset\Software.php:714               DBmysql->executeStatement()
  src\Inventory\Asset\Software.php:443               Glpi\Inventory\Asset\Software->storeSoftware()
  src\Inventory\Asset\MainAsset.php:871              Glpi\Inventory\Asset\Software->handle()
  src\Inventory\Asset\MainAsset.php:791              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src\RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src\Rule.php:1522                                  RuleImportAsset->executeActions()
  src\RuleCollection.php:1626                        Rule->process()
  src\Inventory\Asset\MainAsset.php:571              RuleCollection->processAllRules()
  src\Inventory\Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src\Inventory\Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src\Inventory\Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src\Inventory\Request.php:90                       Glpi\Inventory\Request->inventory()
  src\Agent\Communication\AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src\Agent\Communication\AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front\inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  plugins\glpiinventory\front\communication.php:72   include_once()
  plugins\glpiinventory\index.php:45                 include_once()

### To reproduce

1. With active dictonary-rule i become the error from the discription and the plugin can't link to item.
2. If I set this rule to active "no" all works fine.

### Expected behavior

See description

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin

1.1.0

**Comment by stonebuzz** [comment]
Hi @AndiFo 

Can you post here criteria and action of this rule? 
Best regards

**Comment by AndiFo** [comment]
Sure
![grafik](https://user-images.githubusercontent.com/60271713/215186167-eead2600-9f9a-43d8-8669-01312d968ded.png)

**Comment by stonebuzz** [comment]
Your criteria is wrong if you want to use regex action 

You need to use regex criteria 

Best regards

**Comment by AndiFo** [comment]
You're absolutly right, but if I change action to "Assign" the error is still there. The bad thing, I can't reproduce them in a clean test-installation.

**Comment by AndiFo** [comment]
At the GLPI Issus I found the following: https://github.com/glpi-project/glpi/issues/13925

**Comment by stonebuzz** [comment]
Hi,

Can you export dictionnaries and post file here?
A computer inventory file (related to this issue) maybe usefull too.  

Best regards

**Comment by Tony710** [comment]
Hi @stonebuzz
Please, find manufaturer rules export file.
[rules Manufacturers.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/10543793/rules.Manufacturers.zip)
I can't give full inventory file 
But, just with "Microsoft 365 Apps for enterprise" soft you can reproduce the problem.


		"softwares": [
			{
				"arch": "x86_64",
				"from": "registry",
				"guid": "O365ProPlusRetail - fr-fr",
				"install_date": "2023-01-20",
				"name": "Microsoft 365 Apps for enterprise - fr-fr",
				"no_remove": false,
				"publisher": "Microsoft Corporation",
				"system_category": "application",
				"uninstall_string": "\"C:\\Program Files\\Common Files\\Microsoft Shared\\ClickToRun\\OfficeClickToRun.exe\" scenario=install scenariosubtype=ARP sourcetype=None productstoremove=O365ProPlusRetail.16_fr-fr_x-none culture=fr-fr version.16=16.0",
				"version": "16.0.15601.20456"
			}

**Comment by stonebuzz** [comment]
Hi @Tony710 

can you try this

https://github.com/glpi-project/glpi/pull/13930

**Comment by AndiFo** [comment]
@stonebuzz Thanks the fix works fine.

**Comment by stonebuzz** [comment]
Hi @AndiFo 

Pull request has evolved (to prevent another error), can you apply / try new version ?

Best regards
