### ISSUE TITLE
Static Groups messed up

### ISSUE THREAD

**Issue by grego1981** [glpi-project/glpi-inventory-plugin#308]
### Describe the bug

Coming from 9.5 and FI all static groups are not working as they should. Cannot remove a PC from the group and in Assosiated items, while the count in the menu is correct inside appear computers from other groups.

### To reproduce

Go to GLPI Inventory->General-> Groups of computers, select a group and go to assosiated items
Baloon with item count is correct but in the list appear items that do not belong to that group

### Expected behavior

Items visisble should be only the ones belong to that group.
There should be an action to remove assosiation to the group.

### Operating system

Windows, Linux

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin

1.1.0

**Comment by stonebuzz** [comment]
Hi @grego1981 
can you try this -> https://github.com/glpi-project/glpi-inventory-plugin/pull/309

**Comment by grego1981** [comment]
After applying the 4 files in the fix I can see the remove from group. The issue remains for the view where appear not only the assosiated computers but from other groups as well... Also if trying to sort by any column the view changes and returns ALL computers in a view containg only computername entity name and the field you selected to sort. though the plugin's field static group does not appear at all, not even if you try to select it in the view settings. (wrench  icon)

**Comment by stonebuzz** [comment]
Hi @grego1981
 
can you retry ?

(need to logout / login because of  latered ```$_SESSION```)

**Comment by grego1981** [comment]
I've tested, now column sorting does not work at all. Adding and removing works. Also wrong machines still appear in the assosiated items..

**Comment by stonebuzz** [comment]
Sorting feature have been drop from this two forms (to prevent refresh and wrong display).

"Associated items" tab have been rework entirely

![image](https://user-images.githubusercontent.com/7335054/218482322-07ef8913-0ec3-451c-ad09-f98883ff1874.png)

Are display only computer linked to static group (from database)

**Comment by grego1981** [comment]
You mean that this is what I should see or is it a new addition for the new version? What I'm seeing in the assosiated items is the view I have in the computers view, and not the assosiated to the group computers only..

**Comment by stonebuzz** [comment]
I just say that this view has been reworked, both were based on data in database, but the old view used the framework of GLPI to display the table (which caused display problems when sorting for example).

Now it is the plugin that builds the table

Can you check in database the table  ``glpi_plugin_glpiinventory_deploygroups_staticdatas``` (you can addd ```WHERE``` on ```plugin_glpiinventory_deploygroups_id``` to filter on your static group)

**Comment by grego1981** [comment]
The table has the exact amount of items as appear in the balloon in the
associated items, but not what appears on screen

**Comment by stonebuzz** [comment]
Can you post a screenshot

**Comment by grego1981** [comment]
![Capture](https://user-images.githubusercontent.com/9021998/218497169-78d8a7a7-c649-482a-a384-7a9e45162830.PNG)

**Comment by stonebuzz** [comment]
AS i said, "Associated items" have been rework with ```pull request```

https://user-images.githubusercontent.com/7335054/218482322-07ef8913-0ec3-451c-ad09-f98883ff1874.png

please check the applied patch

**Comment by grego1981** [comment]
I've already  changed the 4 files, from this https://github.com/glpi-project/glpi-inventory-plugin/pull/309 and the output is what I sent you the screenshot from.

**Comment by stonebuzz** [comment]
Commit have been added today ..... 

Please check diff

![Screenshot_20230213_212117_GitHub.jpg](https://user-images.githubusercontent.com/7335054/218566423-d06766f7-a2f1-4923-8d36-ca2129e3e450.jpg)

**Comment by grego1981** [comment]
Didn't realize you made changes during the last hours. No the view and actions works as they should!
