### ISSUE TITLE
Suggested Improvement - Integrated Asset Rules with LDAP

### ISSUE THREAD

**Issue by eriqueSDB** [glpi-project/glpi-inventory-plugin#310]
### Describe the bug

Firstly, I don't know if it's the right place, anything just tells me that I'm opening in the right place, I'd like to make a suggestion for improving asset rules involving AD (Active Directory)

In the rules of entities and locations it is not possible to integrate with the OU of the AD (Active Directory), this would be very useful adding information that the GLPI itself would already have in cases where the GLPI is integrated to the LDAP of that AD, I work at Servicedesk Brazil and we are GLPI partners and consultants in general, we always receive this question if the inventory integrates with AD to create rules for at least locations and entities, but until today without native integration.

That would be the suggestion, having integration with AD for business rules involving the data that GLPI itself already has through LDAP.

### To reproduce

.

### Expected behavior

.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin

1.1.0

**Comment by stonebuzz** [comment]
Hi @eriqueSDB 

> I work at Servicedesk Brazil and we are GLPI partners and consultants in general,

Please contact us directly =)

Best regards
