### ISSUE TITLE
Lors de l'activation d'un module : "vous n'avez pas les droits requis pour réaliser cette action."

### ISSUE THREAD

**Issue by billtemate** [glpi-project/glpi-inventory-plugin#312]
### Describe the bug

Dans la configuration générale de Glpiinventory, lors de l'activation des modules par défaut, au moment de la sauvegarde, le message "vous n'avez pas les droits requis pour réaliser cette action." s'affiche même en profil super-admin

### To reproduce

1. Connecté en Super-Admin (ou peu importe le profil s'il a des droits activés
2. Menu "Adminstration > GLPI Inventory
3. Menu plugin "Général > Configuration générale"
4. Onglet "Modules des agents"
5. Cocher ou décocher l'une des activations des modules
6. Valider en cliquant sur "Mettre à jour"

### Expected behavior

Le module doit passer à l'état activé par défaut (ou désactivé selon le choix lors de la validation).

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin

1.1.0

**Comment by stonebuzz** [comment]
hi @billtemate  (please write in English)

can you check this (you need at least ```update``` rights)

![image](https://user-images.githubusercontent.com/7335054/219316565-5830df20-27d4-49db-b774-5c912547704b.png)

Best regards

**Comment by billtemate** [comment]
Hi @stonebuzz 

Problem : I havn't this screen 

![image](https://user-images.githubusercontent.com/66022155/219319894-3cc88b2d-7b10-4831-aacb-0263b72e6a9c.png)

**Comment by stonebuzz** [comment]
I had not paid attention to the version of your GLPI (10.0.3)
Please update your instance to latest version (10.0.6)

Best regards
