### ISSUE TITLE
error in cron job: PHP User Warning (512): Invalid item "Agent" (69) in /glpi/plugins/glpiinventory/inc/task.class.php at line 833

### ISSUE THREAD

**Issue by wytchmaster** [glpi-project/glpi-inventory-plugin#313]
### Describe the bug

after updating to lasted GLPI (10.0.6) I get errors from the cron-Job:

```
PHP Warning:  Invalid item "Agent" (69). in /opt/web/<SNIP>/glpi/plugins/glpiinventory/inc/task.class.php on line 833
PHP Warning:  Invalid item "Agent" (69). in /opt/web/<SNIP>/glpi/plugins/glpiinventory/inc/task.class.php on line 833
```

and 

```
[2023-02-22 11:30:04] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid item "Agent" (69). in /opt/web/<SNIP>/glpi/plugins/glpiinventory/inc/task.class.php at line 833
  Backtrace :
  plugins/glpiinventory/inc/task.class.php:833       trigger_error()
  plugins/glpiinventory/inc/task.class.php:663       PluginGlpiinventoryTask->getAgentsFromActors()
  plugins/glpiinventory/inc/task.class.php:913       PluginGlpiinventoryTask->prepareTaskjobs()
  src/CronTask.php:1018                              PluginGlpiinventoryTask::cronTaskscheduler()
  front/cron.php:84                                  CronTask::launch()

```
I have already updated from your git-repository and checked out v1.1.0 which was slighly newer as the version I used with GLPI 10.0.5.

### To reproduce

1. Update GLPI to 10.0.6
2. wait for cron-job (5 minutes)
3. finding error in mail from cron-daemon and in phperrors.log inside glpi

### Expected behavior

There should be no error message, neither in cron nor in the logfile

### Operating system

Linux

### GLPI Agent version

1.4, Other (See additional context below)

### GLPI version

10.0.6

### GLPIInventory plugin

1.1.0

### Additional context

I have not tested, if software deployment still works. Agents still change their 'last contact' data field. So it's not completely broken ;-)
I have some old fusioninventory agents out there and some glpi-agents (v1.4). But this looks more like a server side problem.

**Comment by stonebuzz** [comment]
Can you check task actors from your GLPI ?

**Comment by stonebuzz** [comment]
Hi =)

**Comment by wytchmaster** [comment]
Can I check check my task actors for what? Tasks like mailgate work flawlessly. So I think task actors work in general.

**Comment by stonebuzz** [comment]
> "Can I check check my task actors for what" 

If all is OK, if you don't have a blank line on actors list for example.

> Tasks like mailgate work flawlessly. So I think task actors work in general.

Apparently not

**Comment by stonebuzz** [comment]
It seems that a task uses the agent with ID 69

> ```Invalid item "Agent" (69)```

Can you check on your GLPI but I think this agent does not exist anymore.

Best regards

**Comment by wytchmaster** [comment]
Doesn't look like there's an agent with ID 69. There are phones with id < 10 an computers start  with ID > 236. The table "glpi_agents" is the right place to look for, right?

**Comment by stonebuzz** [comment]
Yes it's the right place.

just find the task and reset actor list

**Comment by wytchmaster** [comment]
Look like there was an old job with status "running". I reset the state, It looks promising. No more error messages / mails from cron. I will have an eye on it for next couple of executions and give feedback later. Thanks for your support.

**Comment by wytchmaster** [comment]
OK, that was to early. Still doing errors. I will check again :-/

**Comment by wytchmaster** [comment]
After disabling and re-enabling all deploy jobs, it looks good now. But I haven't found any Item-ID 69 in the database ...
But no more error messages. So may I close the issue?

**Comment by stonebuzz** [comment]
I think too

Maybe agent with ID 69 was deleted

Best regards

**Comment by wytchmaster** [comment]
Problem solved
