### ISSUE TITLE
Some computers are not imported or linked

### ISSUE THREAD

**Issue by efgiese** [glpi-project/glpi-inventory-plugin#315]
### Describe the bug

I have changed the inventory from ocsinventory-ng to glpi-inventory. The old agent is removed from the computers and the new agent (glpi-agent 1.4) is installed with the script. The ocsinventory-ng-plugin is disabled and removed. 

For almost all computers this is fine. But some of them create the agent item in the agent table, but not linked to the computer. These computers are never updated.

I tried to create the inventory locally and import it manually but i got some errors (see logfiles and picture). 

I don not know how to fix this. There are no computers in "Equipments refused by rules log".

[sql-errors.log](https://github.com/glpi-project/glpi-inventory-plugin/files/10850976/sql-errors.log)
[php-errors.log](https://github.com/glpi-project/glpi-inventory-plugin/files/10850978/php-errors.log)
[LAP6455_glpi-agent.log](https://github.com/glpi-project/glpi-inventory-plugin/files/10850982/LAP6455_glpi-agent.log)
[LAP6455.json.txt](https://github.com/glpi-project/glpi-inventory-plugin/files/10851074/LAP6455.json.txt)

![LAP6455](https://user-images.githubusercontent.com/43266079/221876663-732df87b-0814-48c0-9941-fb7efdbe8534.PNG)

### To reproduce

Importing the json file throws the last errors in php-error.log

### Expected behavior

The computer should be updated

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin

1.1.0

**Comment by trasher** [comment]
You should first try with latest GLPI nightly build, since several issues regarding inventory has already been fixed. It looks like you have several issues in provided logs; it may at least makes things clearer.

**Comment by efgiese** [comment]
Thank you for that hint. I have tried this but it did not help. I have seen this https://github.com/glpi-project/glpi-inventory-plugin/issues/311 . The error is similar...

**Comment by trasher** [comment]
Error in the issue you link was about a name inserted instead of an ID. Your logs are about a column being `null`.

What does not help? Using the nightly? Which one?

**Comment by efgiese** [comment]
I have installed this 10.0-1ead1b9.tar.gz from today but the errors remained.

**Comment by stonebuzz** [comment]
I may be wrong (because I can't reproduce on my isntance) 
but it seems that the source error is the software management during inventory

```shell
[2023-02-28 14:31:44] glpiphplog.ERROR:   *** PHP User Error (256): Column 'items_id' cannot be null in /var/www/glpi-nightly/src/DBmysql.php at line 1969
  Backtrace :
  src/DBmysql.php:1969                               trigger_error()                                                                                 <= here
  src/Inventory/Asset/Software.php:878               DBmysql->executeStatement()                                        <= here
  src/Inventory/Asset/Software.php:445               Glpi\Inventory\Asset\Software->storeAssetLink()        <= here
  src/Inventory/Asset/MainAsset.php:874              Glpi\Inventory\Asset\Software->handle()                    <= here
  src/Inventory/Asset/MainAsset.php:794              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:988                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1519                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1625                        Rule->process()
  src/Inventory/Asset/MainAsset.php:571              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  src/Inventory/Conf.php:220                         Glpi\Agent\Communication\AbstractRequest->handleRequest()
  src/Inventory/Conf.php:161                         Glpi\Inventory\Conf->importContentFile()
  front/inventory.conf.php:47                        Glpi\Inventory\Conf->importFile()
```

After importing your file I have 242 softwares.

Do you have rules / dictionaries on software / manufacturer / version ?

**Comment by trasher** [comment]
I cannot reproduce either; and also have 242 softwares after import.

**Comment by efgiese** [comment]
I have some rules for software an disabled all but the errors remained.

First error: 
[2023-02-28 15:33:39] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi-nightly/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_items_devicefirmwares` (`devicefirmwares_id`, `itemtype`, `items_id`, `is_dynamic`, `serial`, `entities_id`, `is_recursive`) VALUES ('521', 'Computer', NULL, '1', 'PF3A73XE', '0', '0')
  Error: Column 'items_id' cannot be null

Second error: 
[2023-02-28 15:33:39] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi-nightly/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_items_deviceprocessors` (`deviceprocessors_id`, `itemtype`, `items_id`, `is_dynamic`, `serial`, `frequency`, `nbcores`, `nbthreads`, `entities_id`, `is_recursive`) VALUES ('709', 'Computer', NULL, '1', 'None', '2000', '8', '1', '0', '0')
  Error: Column 'items_id' cannot be null

Third error: 
[2023-02-28 15:33:39] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi-nightly/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_items_devicememories` (`devicememories_id`, `itemtype`, `**items_id**`, `is_dynamic`, `size`, `serial`, `busID`, `entities_id`, `is_recursive`) VALUES ('827', 'Computer', **NULL**, '1', '8192', '4797FF74', '0', '0', '0')
  Error: Column 'items_id' cannot be null

Fourth error:
[2023-02-28 15:33:39] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi-nightly/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_items_devicememories` (`devicememories_id`, `itemtype`, `items_id`, `is_dynamic`, `size`, `serial`, `busID`, `entities_id`, `is_recursive`) VALUES ('827', 'Computer', NULL, '1', '8192', '00000000', '1', '0', '0')
  Error: Column 'items_id' cannot be null

Fifth error:
[2023-02-28 15:33:39] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi-nightly/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_items_devicenetworkcards` (`devicenetworkcards_id`, `itemtype`, `items_id`, `is_dynamic`, `mac`, `entities_id`, `is_recursive`) VALUES ('1044', 'Computer', NULL, '1', '4c:d5:77:c0:21:8f', '0', '0')
  Error: Column 'items_id' cannot be null

Sixth error:
[2023-02-28 15:33:39] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi-nightly/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_items_devicenetworkcards` (`devicenetworkcards_id`, `itemtype`, `items_id`, `is_dynamic`, `mac`, `entities_id`, `is_recursive`) VALUES ('962', 'Computer', NULL, '1', '88:a4:c2:1f:da:0c', '0', '0')
  Error: Column 'items_id' cannot be null

Every time it is the "item_id" . I don not know which is this in the json file. I think this is not NULL.

**Comment by stonebuzz** [comment]
```items_id``` is computed by GLPI depending of your rules
Can you retry by clearing the following tables:

- glpi_softwarelicenses
- glpi_softwares
- glpi_softwareversions   
- glpi_items_softwareversions

Best regards

**Comment by efgiese** [comment]
What is the meaning of "clearing"? I do not want to delete any data. It is a productive system...

**Comment by stonebuzz** [comment]
For example :

```sql
DELETE FROM glpi_softwarelicenses
```

**Comment by efgiese** [comment]
I have reset the rules for "Rules for assigning a category to software". Now there is only one disabled rule. But on my database there are tables from ocs (ocs_glpi_ruleactions, ocs_glpi_rulecriterias, ocs_glpi_rules). They are not empty. Can I delete them without any problems?

Tomorrow i will set up an test environment with a copy of database and clear the tables.

Thank you...

**Comment by efgiese** [comment]
On the testenvironment (glpi new installation, empty database) the import was successfully completed. I restored the productive database and flush the tables 
-     glpi_softwarelicenses
-     glpi_softwares
-     glpi_softwareversions
-     glpi_items_softwareversions
and the import fails.

I renamed the computer and tried the import again. The import was successfully completed but the objects were not merged.

What should i try next?

**Comment by stonebuzz** [comment]
Disable all software rules / dictionnaries rules

**Comment by stonebuzz** [comment]
Have you an unicity check ?

![image](https://user-images.githubusercontent.com/7335054/222469531-10326955-da84-4b8d-9e88-3310288f13a6.png)

**Comment by stonebuzz** [comment]
I ask becasue of this
https://user-images.githubusercontent.com/43266079/221876663-732df87b-0814-48c0-9941-fb7efdbe8534.PNG

**Comment by efgiese** [comment]
I have one rule (computername) and disabled it. It still fails. The page is nearly blank till i click on inventory. Then it shows this screen.

![grafik](https://user-images.githubusercontent.com/43266079/222471341-cefdd412-3244-4d66-9599-b20bef92d05a.png)

**Comment by stonebuzz** [comment]
can you clean all table related to network ?

 glpi_networkaliases                                         
 glpi_networknames                                           
 glpi_networkportaliases                                    
 glpi_networkportethernets                                   
 glpi_networkportmetrics                                     
 glpi_networkports                                           
 glpi_networkports_networkports                              
 glpi_networkports_vlans                                     

and retry

**Comment by efgiese** [comment]
The import was successfully completed. :-) 
![grafik](https://user-images.githubusercontent.com/43266079/222473588-9c8ea848-23d2-4f63-9fec-3acdd2d12e02.png)

But now i have duplicate entries.

I will try it tomorrow again.

Thank you very much...

**Comment by efgiese** [comment]
After a lot of trying I found out that the UUID has changed. I moved up the rule for the update (serial only). The file could be imported.
Hopefully the other computers will be updated now...

Many thanks for your help...

PS: But i have some other errrors...
