### ISSUE TITLE
The dashboard badges are linked to the wrong update source

### ISSUE THREAD

**Issue by efgiese** [glpi-project/glpi-inventory-plugin#323]
### Describe the bug

The badges on the dashboard shows the wrong numbers.

![grafik](https://user-images.githubusercontent.com/43266079/222699873-e9ae6a14-cebe-42c9-95cb-88cda736e4a5.png)

For example, if I click on "Computers inventoried", the computers with the update source "Edgar Giese" (that's me) are displayed. The update source for "GLPI Native Inventory" has a different ID and must then be selected separately.

Can this be configured?

![grafik](https://user-images.githubusercontent.com/43266079/222700817-8dfd8741-3e84-40fb-ba0f-89690f16f7fa.png)

### To reproduce

GLPI was installed a long time ago and kept updating to new versions. Most recently, OCS inventory was changed to GLPI inventory.

### Expected behavior

The correct ID should be found or configured for the badge to show the correct count.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

development release (See additional context below)

### GLPIInventory plugin

1.1.0

### Additional context

GLPI version nigthly build 10.0-1ead1b9.tar.gz

**Comment by stonebuzz** [comment]
Hi @efgiese 
can you try this -> https://github.com/glpi-project/glpi-inventory-plugin/pull/324

**Comment by efgiese** [comment]
Thank you very much. That's it...
