### ISSUE TITLE
tasks: monitoring/log

### ISSUE THREAD

**Issue by Giudy** [glpi-project/glpi-inventory-plugin#325]
In the tasks-Monitoring/Logs the printer task is not any more correctly linked to the working one as it does not show any more the status of the job.
It stays like this:
![image](https://user-images.githubusercontent.com/7987648/223070292-fb594207-974a-45e8-bd51-65df1aacdaeb.png)
while , if I go directly in the task, I see
![image](https://user-images.githubusercontent.com/7987648/223070420-4977e0a7-9822-44d9-aaf6-1c261f3752b5.png)

_Originally posted by @Giudy in https://github.com/glpi-project/glpi-agent/issues/353#issuecomment-1455782817_

**Comment by stonebuzz** [comment]
hi @Giudy 
I don't reproduce, could you delete / recreate the task to see if it is better?

**Comment by cedric-anne** [comment]
ping @Giudy

**Comment by Giudy** [comment]
Ciao, sorry for the delay.
updated GLPI inventory to 1.2.1, deleted and recreated the task but nothing changed. OI've just noticed that for some printers the situation is aligned:
here from Tasks->Monitoring/Logs
![image](https://user-images.githubusercontent.com/7987648/233607266-c1567df9-5025-4aaf-856f-e8dc93671698.png)

and here from Tasks-Task(s!) management-<task>
![image](https://user-images.githubusercontent.com/7987648/233607410-f4bec2af-d6d8-4ec5-a50f-12165fd65cc8.png)

**Comment by stonebuzz** [comment]
Any error from browser console (F12)

**Comment by Giudy** [comment]
No, just a bunch of warnings about the css
