### ISSUE TITLE
glpi-inventory does not communicate with the glpi-agent

### ISSUE THREAD

**Issue by efgiese** [glpi-project/glpi-inventory-plugin#328]
### Describe the bug

Hello everyone,

I moved my GLPI installation from 9.5.6 with OCSinventory to 10.0.6 with GLPI-Inventory.

I have set up tasks and also receive data, for example from the printers. But the tasks are not started automatically.

With the automatic actions, wakeupAgents is started every 2 minutes, but no action is executed.

I set up an empty installation for testing and connected a computer to this installation. Inventory is reported to this instance. I have also set up a task here and it also starts automatically with the automatic actions and wakupAgents. The executed action is also displayed there.

So I believe I don't have a network connection issue or a permissions issue.

The connection to the agent is displayed in the computer inventory. When I click the request status link, nothing happens. In my test installation, the status was displayed. In the test installation, I was also able to start the inventory via the second link. Nothing happens here either. I can't find anything in the logs either.

But where should I look or what can I check to solve the problem?

### To reproduce

I do not know...

### Expected behavior

The glpi-agent should be controllable by the plugin

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin

1.1.0

### Additional context

 I think the problem is too specific. I couldn't find an answer in the forum.

PS: When I go to the agent's web site and request inventory, the agent starts.

PPS:Sending the data with curl looks like this...
- works not / agent-id=6 -
curl "http://glpi/ajax/agent.php" -X POST
-H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"
-H "Accept: application/json, text/javascript, */*; q=0.01"
-H "Accept-Language: de,en-US;q=0.7,en;q=0.3"
-H "Accept-Encoding: gzip, deflate"
-H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8"
-H "X-Glpi-Csrf-Token: e49d28374f5f93a3c300fa8159aa596f13ba3e897780c6eef0753234d47aae90"
-H "X-Requested-With: XMLHttpRequest"
-H "Origin: http://glpi"
-H "Connection: keep-alive"
-H "Referer: http://glpi/front/computer.form.php?id=690"
-H "Cookie: glpi_98f8c01fb4b9b0bd1b2437fc55e255f2=nvftcsuo99kcm0glbqf8gcsvv9;
glpi_98f8c01fb4b9b0bd1b2437fc55e255f2_rememberme=^%^5B10^%^2C^%^22YW2ICOvjCWsbVcWRoWRgPDbDW2I5jCnlZps7XFzR^%^22^%^5D"
--data-raw "action=status&id=6"
{"answer":"Unbekannt"}

- works / agent-id=3 -
curl "http://glpi-test/ajax/agent.php" -X POST
-H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"
-H "Accept: application/json, text/javascript, */*; q=0.01"
-H "Accept-Language: de,en-US;q=0.7,en;q=0.3"
-H "Accept-Encoding: gzip, deflate"
-H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8"
-H "X-Glpi-Csrf-Token: 6c49b12ed27828a5ee9d1c83fa6889798def0719f95c7c33a896536b1b74c9d5"
-H "X-Requested-With: XMLHttpRequest"
-H "Origin: http://glpi-test"
-H "Connection: keep-alive"
-H "Referer: http://glpi-test/front/computer.form.php?id=1"
-H "Cookie: glpi_ae2ffba5045b9c904e2d92f88b7adef1=c1m453tvgf0btjlhlm2lvuun6m;
glpi_ae2ffba5045b9c904e2d92f88b7adef1_rememberme=^%^5B2^%^2C^%^22EpxqLpvxDbrF5atV6lkqmZjF3ih1xuVFZan7T3FU^%^22^%^5D"
--data-raw "action=status&id=3"
{"answer":"waiting"}

**Comment by stonebuzz** [comment]
Hi @efgiese 
can you check : 

- task configuration

![image](https://user-images.githubusercontent.com/7335054/229797254-586fbf94-7da1-4df5-b40d-56f0c66da7af.png)

- Automatic actions
```WakeupAgent``` and ```taskscheduler``` automatic action are not stuck

You can run this command from glpi root folder

```shell
php bin/console task:unlock
``` 
- PHP SQL error log
check any error from this files (glpi/files/_log/)

Best regards

**Comment by efgiese** [comment]
Hi stonebuzz,

i checked the task configuration. It is like your screen shot.

The automatic actions `WakeupAgent` starts every 2 minutes and `taskscheduler` starts every minute. But run nothing.

I have some errors in `sql-errors.log` but do not know how to fix it.
[sql-errors.log](https://github.com/glpi-project/glpi-inventory-plugin/files/11158169/sql-errors.log)

Errors in php-error.log are from struggle with network inventory...
[php-errors.log](https://github.com/glpi-project/glpi-inventory-plugin/files/11158185/php-errors.log)

Many thanks for your hints...

**Comment by stonebuzz** [comment]
Can you update your GLPI to 10.0.7 

empty the table ```glpi_networkports_networkports```

and retry

**Comment by efgiese** [comment]
Sorry, nothing changed. I have tried this (empty table) serveral times but nothing changed. I trigger the agent with cron.

**Comment by stonebuzz** [comment]
have you updated your GLPI to the latest version (10.0.7)

**Comment by efgiese** [comment]
Yes, and glpi_inventory to 1.2.1

**Comment by stonebuzz** [comment]
Can you retry by clearing the table ```glpi_networkportmetrics``` table

Best regards

**Comment by stonebuzz** [comment]
Same error about

- ```Duplicate entry for glpi_networkportmetrics```
- ```Wired non unique! for NetworkPort_NetworkPort```

can you post here related inventory file ?

**Comment by efgiese** [comment]
I had cleared the  glpi_networkportmetrics and  glpi_networkports_networkports

**Comment by stonebuzz** [comment]
I need inventory file generated by agent during task

**Comment by efgiese** [comment]
Do not know where to get this?
That ist the task...
![grafik](https://user-images.githubusercontent.com/43266079/233383963-58212dc4-28ac-494b-a625-10df806ca727.png)

![grafik](https://user-images.githubusercontent.com/43266079/233383871-963507eb-ca88-44b6-a91b-03a094d0cd46.png)

**Comment by stonebuzz** [comment]
You need to perform netdiscovery directly from CLI

https://glpi-agent.readthedocs.io/en/latest/man/glpi-netinventory.html

Exemple : 
```
glpi-netinventory --host 192.168.0.1 --credentials version:2c,community:public
```
see ```--file``` arg

**Comment by efgiese** [comment]
I did not understand. Should i run a SNMP walk to a device and then run the glpi-netinventory with that file?

--file FILE

    Run an offline inventory against snmpwalk output, stored in given file. Multiple usage allowed, for multiple files.

**Comment by trasher** [comment]
Inventory file has been requested and not provided, I close as this issue is stalled.
