### ISSUE TITLE
Installing Plugin produces an error

### ISSUE THREAD

**Issue by Philb27** [glpi-project/glpi-inventory-plugin#33]
There seems to be an issue with the plugin, we updated from the latest V9 version to V10 we had fusion inventory plugin but opted for the new GLPI Inventory Plugin however when trying to install the plugin we get the following error: 

UPDATE `glpi_plugin_glpiinventory_printers` SET `plugin_glpiinventory_agents_id` = '0' WHERE `plugin_glpiinventory_agents_id` = '1' - Error is Table 'glpi.glpi_plugin_glpiinventory_printers' doesn't exist

Can you check the install as there may be a few of these tables that need creating/populating.

**Comment by trasher** [comment]
Several fixes has already been done, we will produce a new release soon. Please try with that one, and feel free to reopen if your issue persists.
