### ISSUE TITLE
FusionInventory to GLPI Inventory : PHP User Warning (512): plugin_version_fusioninventoryb method must be defined! in /var/www/html/glpi10/src/Plugin.php at line 1603

### ISSUE THREAD

**Issue by CGDV-Sophie** [glpi-project/glpi-inventory-plugin#330]
### Describe the bug

Hello, (sorry for bad english)

I tried to switch from FusionInventory to GLPI inventory.

I had not uninstalled FI before, it was by installing the GLPI inventory plugin that it asked me to delete the FusionInventory directory.

I deleted the FI directory and plugin but it doesn't work.

I have the following errors in php-errors.log

`[2023-03-17 11:06:49] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to load plugin "fusioninventory" information. in /var/www/html/glpi10/src/Plugin.php at line 516
  Backtrace :
  src/Plugin.php:516                                 trigger_error()
  src/Plugin.php:472                                 Plugin->checkPluginState()
  front/marketplace.php:43                           Plugin->checkStates()
  
[2023-03-17 11:06:49] glpiphplog.WARNING:   *** PHP User Warning (512): plugin_version_fusioninventoryb method must be defined! in /var/www/html/glpi10/src/Plugin.php at line 1603
  Backtrace :
  src/Plugin.php:1603                                trigger_error()
  src/Plugin.php:1641                                Plugin::getInfo()
  src/Plugin.php:492                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:472                                 Plugin->checkPluginState()
  front/marketplace.php:43                           Plugin->checkStates()`

I tried uninstalling GLPI inventory and reinstalling them but it still doesn't work.

Thank you for your help

### To reproduce

Install plugin GLPI Inventory From Marketplace
Delete FusionInventory directory on /plugin/ server
Remove FusionInventory plugin on Plugin page

### Expected behavior

that the GLPI Inventory plugin works

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin

1.1.0

**Comment by cedric-anne** [comment]
Do you have a `fusioninventoryb` directory in your `glpi/plugins` directory? You should remove it to fix this issue.

**Comment by CGDV-Sophie** [comment]
Yes, sorry, I realized it 2 minutes ago, since I deleted it.

But I still don't have machines going up in the inventory even if I force the agents.

**Comment by CGDV-Sophie** [comment]
it's ok, sorry for the inconvenience. I thought that renaming the directory would be enough to validate its absence.
