### ISSUE TITLE
feature request: wildcard support on registry collector 

### ISSUE THREAD

**Issue by ftoledo** [glpi-project/glpi-inventory-plugin#331]
### Describe the bug

we have to collect if windows machine need reboot
the registry path is:

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired

key name: {some guid XXXX-XXXXX-XXXXX}
value: 
any chance to get severals keys from registry? using only the path?

![imagen](https://user-images.githubusercontent.com/95441/226030246-41d78f78-8337-4d5a-a0b3-3562db762422.png)

### To reproduce

create a task tha have a registry collector job

### Expected behavior

get each key=>value pair from path set

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin

1.1.0

### Additional context

I notice that path settings "auto add" slashes

I set the path: SYSTEM\CurrentControlSet\Control\Session Manager

It's show:
/SYSTEM\CurrentControlSet\Control\Session Manager/

**Comment by g-bougard** [comment]
Hi @ftoledo 

this is indeed still supported.

I just tested again but with `HKEY_LOCAL_MACHINE/SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\Power/` as I don't have any entry for `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired` at the moment of my test.

Here is the definition:
![image](https://user-images.githubusercontent.com/12514489/227189528-017fa4cd-28e2-4f30-8d11-ea25c26347b7.png)
And the result in the "Collect information" of the test machine:
![image](https://user-images.githubusercontent.com/12514489/227188918-9001340e-a591-47b9-a8d0-d7b3bc84e406.png)

The section should be empty if no key is found.

As I used a nightly build for the test, try eventually a nightly build of glpi-agent.

**Comment by g-bougard** [comment]
Maybe avoid the last `\` in your key definition.
