### ISSUE TITLE
snmp v3 password containing special characters not accepted

### ISSUE THREAD

**Issue by GuidoWilden** [glpi-project/glpi-inventory-plugin#332]
### Describe the bug

When creating a network inventory task via the GUI with snmp v3 credentials containing a special character (exclamation mark in our case) the task is not being executed.
When force starting the job the execution returns 'The preparation of this task did not return any targets'.
The glpi-netinventory command on command line work but only if the password is used with the correct type of quotation marks.

### To reproduce

1. Set create snmp v3 credentials using SHA and AES128 encrytion
2. Password in our case ends with an exclamation mark (both passwords are the same in our case)
3. Associate credentials to an IP range
4. Create network inventory task through GLPI inventory plugin
5. Force start the task

### Expected behavior

Collect network inventory.

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.6

### GLPIInventory plugin

1.1.0

**Comment by cedric-anne** [comment]
Hi,

Can you try https://github.com/glpi-project/glpi/pull/14374 ?

**Comment by cedric-anne** [comment]
Could you try to apply the patch, input your credentials in the SNMP Credential form, save it, and try to see if it fixes your issue?

**Comment by cedric-anne** [comment]
Patch can be downloaded from https://patch-diff.githubusercontent.com/raw/glpi-project/glpi/pull/14374.patch

**Comment by GuidoWilden** [comment]
Unfortunately the result is the same. Saying that I can't see a test directory in version 10.0.6.

**Comment by stonebuzz** [comment]
> The preparation of this task did not return any targets

Can you verify that you have assets whose IP is within the IP range

**Comment by GuidoWilden** [comment]
Yes we do have assets in this range (only trying with one range for the time being) that are detected by a discovery task. The inventory task however will not run.

**Comment by stonebuzz** [comment]
Can you post here job  configuration 
![image](https://user-images.githubusercontent.com/7335054/227216683-78a76269-08b0-4f34-a6e1-fa127e37248e.png)

**Comment by GuidoWilden** [comment]
![capture](https://user-images.githubusercontent.com/13089420/227218079-03e0695c-b270-4310-8771-88cf079c408e.png)

**Comment by stonebuzz** [comment]
Can you uncheck this and retry
![image](https://user-images.githubusercontent.com/7335054/227218346-1adb07f6-f197-469f-9a13-d37f0f4c9cc0.png)

**Comment by GuidoWilden** [comment]
Unfortunately the same
![capture](https://user-images.githubusercontent.com/13089420/227219894-6eeb912d-20bb-49dd-8214-b67cb17bd72e.png)

**Comment by stonebuzz** [comment]
This is the right way to proceed =)

can you delte task and recreate new one (with uncheked option) then retry ?

**Comment by stonebuzz** [comment]
Any GLPI error (PHP / /SQL) ?

**Comment by GuidoWilden** [comment]
The devices in the range I'm testing with are all network switches. I just added the credentials to one of the switches, saved, went back into tasks, clicked `Force start`, but unfortunately still `... did not return any targets`.
![capture](https://user-images.githubusercontent.com/13089420/227234143-e14fd607-cfef-4069-841b-1ed63d1b913d.png)

**Comment by stonebuzz** [comment]
Your screenshot shows an ```Unmanaged``` device (out of SNPM inventory scope)

 all of your network switches are in ```Unmanaged``` ?

**Comment by stonebuzz** [comment]
thank you for reading this documentation

https://glpi-agent.readthedocs.io/en/latest/tasks/network-discovery.html

**Comment by stonebuzz** [comment]
no problem the main thing is to find the solution =)

Best regards

**Comment by GuidoWilden** [comment]
I thought I would share we see this in the logs now:
`[Thu Mar 23 14:58:41 2023][debug] [thread 16] #019, - scanning 10.100.237.20 with SNMP, credentials 4: success`

**Comment by stonebuzz** [comment]
:+1: 
now you should be able to find this device in the ```NetworkEquipment```, and  you should be able to do an SNMP inventory without problem
