### ISSUE TITLE
task not work

### ISSUE THREAD

**Issue by LordSvein** [glpi-project/glpi-inventory-plugin#341]
### Describe the bug

I upgraded my glpi server to the latest version (10.0.7) and the glpi inventory plugin version1.2.0.
I created a network discovery task and the task remains in progress with 0 threads 0 timeout
![Capture7](https://user-images.githubusercontent.com/39635317/230348031-c0308ab0-d6ec-454a-9b2a-74aca25cb2f6.PNG)

### To reproduce

upgraded my glpi server to the latest version (10.0.7)
upgraded my glpi inventory plugin to the latest version (1.2.0)
created a network discovery task

### Expected behavior

i want task run

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.7

### GLPIInventory plugin

1.2.0

**Comment by stonebuzz** [comment]
Hi @LordSvein 
any error from GLPI-Agent (with debug mode 2 enable ) ?

or form GLPI (glpi/files/_log)

**Comment by LordSvein** [comment]
no nothing

**Comment by LordSvein** [comment]
mayby that 

User ID: 2 tried to access or perform an action on /marketplace/glpiinventory/front/iprange.form.php?id=1 with insufficient rights. Additional information: Aucune information supplÃ©mentaire fournie
	Stack Trace:
		/var/www/html/src/CommonGLPI.php:1177 displayRightError()
		/var/www/html/marketplace/glpiinventory/front/iprange.form.php:128 display()

**Comment by stonebuzz** [comment]
Can you check "IP Range" rights from "Profil > GLPI Inventyory tab"

![image](https://user-images.githubusercontent.com/7335054/230377280-a6eb0acf-0362-459f-9a48-70ba2f5c4cd4.png)

**Comment by stonebuzz** [comment]
> i had to create glpi

I did not understand

**Comment by LordSvein** [comment]
in profil i don't have glpi inventory

**Comment by LordSvein** [comment]
in users  i have plugin_glpi_inventory

**Comment by LordSvein** [comment]
![Capture9](https://user-images.githubusercontent.com/39635317/230382581-360c6372-6783-4c39-a181-407dbaa4dad9.PNG)

**Comment by LordSvein** [comment]
I have made change on id 2 and nothing

**Comment by trasher** [comment]
Changing rights mays require a user logout and login again.

**Comment by LordSvein** [comment]
no change

**Comment by LordSvein** [comment]
i just recreate my task wiht an another agent
![Capture10](https://user-images.githubusercontent.com/39635317/230566091-3038e0ad-4658-4382-b383-52192c49c7a8.PNG)
![Capture11](https://user-images.githubusercontent.com/39635317/230566096-2a460ac0-ab28-4fbf-8a76-4632af9442c7.PNG)

**Comment by stonebuzz** [comment]
I think the problem lies with the agent

@g-bougard any idea ?

**Comment by g-bougard** [comment]
Hi @LordSvein 
did you check the tasks are still enabled on that agent in GLPI ?
In the case the agent deviceid changed (after a reinstall for example), that configuration may have been lost.

**Comment by LordSvein** [comment]
> Hi @LordSvein did you check the tasks are still enabled on that agent in GLPI ? In the case the agent deviceid changed (after a reinstall for example), that configuration may have been lost.

i just reinstall agent and i have same trouble

**Comment by LordSvein** [comment]
[Fri Apr  7 10:30:10 2023][debug] new thread 12 to handle task Collect
[Fri Apr  7 10:30:10 2023][info] running task Collect
[Fri Apr  7 10:30:10 2023][debug2] http://buitani.richou.fr/marketplace/glpiinventory?action=getConfig&machineid=RICHOU-INF02.domain.local-2023-01-11-11-56-04&task[Collect]=2.8
[Fri Apr  7 10:30:10 2023][info] No Collect job enabled or Collect support disabled server side.
[Fri Apr  7 10:30:10 2023][debug] new thread 13 to handle task NetInventory
[Fri Apr  7 10:30:10 2023][debug] NetInventory task not supported by server
[Fri Apr  7 10:30:11 2023][debug] new thread 14 to handle task ESX
[Fri Apr  7 10:30:11 2023][info] running task ESX
[Fri Apr  7 10:30:11 2023][debug2] http://buitani.richou.fr/marketplace/glpiinventory?action=getConfig&machineid=RICHOU-INF02.domain.local-2023-01-11-11-56-04&task[ESX]=2.7
[Fri Apr  7 10:30:11 2023][info] No ESX job enabled or ESX support disabled server side.
[Fri Apr  7 10:30:11 2023][debug] new thread 15 to handle task Deploy
[Fri Apr  7 10:30:11 2023][info] running task Deploy
[Fri Apr  7 10:30:11 2023][debug2] http://buitani.richou.fr/marketplace/glpiinventory?action=getConfig&machineid=RICHOU-INF02.domain.local-2023-01-11-11-56-04&task[Deploy]=2.10
[Fri Apr  7 10:30:11 2023][info] No Deploy job enabled or Deploy support disabled server side.
[Fri Apr  7 10:30:12 2023][debug] new thread 16 to handle task NetDiscovery
[Fri Apr  7 10:30:12 2023][debug] NetDiscovery task not supported by server
[Fri Apr  7 10:30:12 2023][info] target server0: next run: Sat Apr  8 09:34:56 2023 - http://buitani.richou.fr/marketplace/glpiinventory
[Fri Apr  7 10:30:12 2023][debug] Agent memory usage before freeing memory: WSS=145096704 PFU=167510016
[Fri Apr  7 10:30:12 2023][info] GLPI Agent memory usage: WSS=3567616 PFU=167510016
[Fri Apr  7 10:30:12 2023][debug] target server0: storage maintenance event for deploy task
[Fri Apr  7 10:30:12 2023][debug] new thread 17 to handle task Deploy
[Fri Apr  7 10:30:12 2023][info] running task Deploy: storage maintenance event
[Fri Apr  7 10:30:12 2023][debug] Deploy task storage maintenance event for server0 target
[Fri Apr  7 10:30:12 2023][debug2] Looking for Win32_LogicalDisk class WMI objects
[Fri Apr  7 10:30:12 2023][debug] Free space on C:\Program Files\GLPI-Agent\var\http..__buitani.richou.fr_marketplace_glpiinventory\deploy: 45220
[Fri Apr  7 10:30:12 2023][debug] No need to plan another storage maintenance event for server0 target

**Comment by g-bougard** [comment]
I didn't asked you to reinstall the agent.
I would you to verify the agent definition in GLPI:
![image](https://user-images.githubusercontent.com/12514489/230581397-59b83381-3315-4266-8a5f-a37ab7523899.png)

**Comment by LordSvein** [comment]
sorry but yes i have the same configuration as you see me

**Comment by LordSvein** [comment]
and i have that for scan snmp task 
![Capture12](https://user-images.githubusercontent.com/39635317/230582606-190baaa7-7f17-4d53-b436-184e2594d1b4.PNG)

**Comment by g-bougard** [comment]
To me this means the plugin didn't find any agent as target for the task. This can happen if you have reinstall the agent and so its deviceid has been changed.
You should also check your iprange has credentials linked to it.

**Comment by LordSvein** [comment]
when I reinstalled the agent I recreated the task with the agent that I had just reinstalled, however it did not work, and for the ip ranges I let you see on the screenshot
![Capture 14](https://user-images.githubusercontent.com/39635317/230586287-707a1687-f85a-4c0b-88b7-840e5b8142e9.PNG)

**Comment by stonebuzz** [comment]
When you prepared job , 
what do you have in the "Job execution" tab?

**Comment by LordSvein** [comment]
![Capture15](https://user-images.githubusercontent.com/39635317/230588538-b15e2450-f1ba-4104-b70a-2c7b7c68e91b.PNG)

**Comment by LordSvein** [comment]
![Capture15](https://user-images.githubusercontent.com/39635317/230588812-31349a55-e4a1-4f71-a3cb-63de77511254.PNG)
and if i want to start i have to force start

**Comment by stonebuzz** [comment]
The agent is installed on which operating system?
How did you install the agent?
are you sure you have installed the ```NetDiscovery``` and ```NetInventory``` modules

**Comment by LordSvein** [comment]
> The agent is installed on which operating system? How did you install the agent? are you sure you have installed the `NetDiscovery` and `NetInventory` modules

the agent is install on windows and i have install with full modules. and 
I installed the agent the same way as with glpi 10.0.6 and with gpli 10.0.6 everything works

**Comment by LordSvein** [comment]
after several time 
![Capture16](https://user-images.githubusercontent.com/39635317/230606909-9fa2d815-26ed-4ba7-8b9c-ce28f0a5bd48.PNG)

**Comment by g-bougard** [comment]
Such message can occur when running the agent will not all tasks enabled on agent side or because you run it manually from the commandline without the `--force` option, or maybe because you didn't installed the agent in service mode.
You have now to force again the task in GLPI, see the related button in the "Gestion des tâches" tab on the task configuration.
Then you have to force again the agent run on the agent side.

**Comment by LordSvein** [comment]
> 
I have already made several attempts
but nothing works the log always tells me the same thing

[Fri Apr  7 13:53:38 2023][info] running task Collect
[Fri Apr  7 13:53:38 2023][debug2] http://buitani.richou.fr/marketplace/glpiinventory?action=getConfig&machineid=RICHOU-INF02.domain.local-2023-01-11-11-56-04&task[Collect]=2.8
[Fri Apr  7 13:53:38 2023][info] No Collect job enabled or Collect support disabled server side.
[Fri Apr  7 13:53:39 2023][debug] new thread 42 to handle task NetInventory
[Fri Apr  7 13:53:39 2023][debug] NetInventory task not supported by server
[Fri Apr  7 13:53:39 2023][debug] new thread 43 to handle task ESX
[Fri Apr  7 13:53:39 2023][info] running task ESX
[Fri Apr  7 13:53:39 2023][debug2] http://buitani.richou.fr/marketplace/glpiinventory?action=getConfig&machineid=RICHOU-INF02.domain.local-2023-01-11-11-56-04&task[ESX]=2.7
[Fri Apr  7 13:53:39 2023][info] No ESX job enabled or ESX support disabled server side.
[Fri Apr  7 13:53:40 2023][debug] new thread 44 to handle task Deploy
[Fri Apr  7 13:53:40 2023][info] running task Deploy
[Fri Apr  7 13:53:40 2023][debug2] http://buitani.richou.fr/marketplace/glpiinventory?action=getConfig&machineid=RICHOU-INF02.domain.local-2023-01-11-11-56-04&task[Deploy]=2.10
[Fri Apr  7 13:53:40 2023][info] No Deploy job enabled or Deploy support disabled server side.
[Fri Apr  7 13:53:40 2023][debug] new thread 45 to handle task NetDiscovery
[Fri Apr  7 13:53:40 2023][debug] NetDiscovery task not supported by server
[Fri Apr  7 13:53:40 2023][info] target server0: next run: Sat Apr  8 13:10:46 2023 - http://buitani.richou.fr/marketplace/glpiinventory

**Comment by LordSvein** [comment]
> Un tel message peut se produire lorsque l'exécution de l'agent n'active pas toutes les tâches du côté de l'agent ou parce que vous l'exécutez manuellement à partir de la ligne de commande sans l'option, ou `--force`peut- être parce que vous n'avez pas installé l'agent en mode service. Vous devez maintenant forcer à nouveau la tâche dans GLPI, voir le bouton correspondant dans l'onglet "Gestion des tâches" de la configuration de la tâche. Ensuite, vous devez forcer à nouveau l'exécution de l'agent côté agent.

how to force agent

**Comment by LordSvein** [comment]
when i run localhost:62354 and i force an inventory it's run and my laptop give to the server some information but i already have 
"[Fri Apr  7 14:33:42 2023][info] No Collect job enabled or Collect support disabled server side."

for the collect task

**Comment by g-bougard** [comment]
> No Collect job enabled or Collect support disabled server side

This means you didn't create a Collect task... and this is normal if you only created Netdiscovery and Netinventory tasks.

Honestly, at that time, you didn't demonstrate any bug related to glpi-inventory plugin. You're only showing you still not completely understand how things work. This kind of discussion should be opened in the forum, not in github issues which should only be used if you really identified a bug and demonstrate how to reproduce it.

Actually I'm able to create a netdiscovery task in a fresh instance of GLPI 10.0.7 + GlpiInventory 1.2.0, so what is really different in your case ?

**Comment by LordSvein** [comment]
> > Aucune tâche de collecte activée ou prise en charge de la collecte désactivée côté serveur
> 
> Cela signifie que vous n'avez pas créé de tâche de collecte... et c'est normal si vous n'avez créé que des tâches Netdiscovery et Netinventory.
> 
> Honnêtement, à ce moment-là, vous n'avez démontré aucun bogue lié au plugin glpi-inventory. Vous ne faites que montrer que vous ne comprenez toujours pas complètement comment les choses fonctionnent. Ce genre de discussion devrait être ouvert dans le forum, pas dans les problèmes de github qui ne devraient être utilisés que si vous avez vraiment identifié un bogue et montré comment le reproduire.
> 
> En fait, je suis capable de créer une tâche netdiscovery dans une nouvelle instance de GLPI 10.0.7 + GlpiInventory 1.2.0, alors qu'est-ce qui est vraiment différent dans votre cas ?

You are probably right but what I don't understand what I'm doing is that I'm doing the same steps as on the previous version of glpi and glpi inventory and it doesn't work

**Comment by LordSvein** [comment]
![Capture19](https://user-images.githubusercontent.com/39635317/230613010-6213b489-3e3e-41d2-8864-394408c6306d.PNG)
![Capture17](https://user-images.githubusercontent.com/39635317/230613016-969521a5-5798-46c0-bad2-e7af01537bb6.PNG)
![Capture18](https://user-images.githubusercontent.com/39635317/230613018-2a6b04ae-6de5-4136-a47d-3db34914f708.PNG)

**Comment by LordSvein** [comment]
explain me where i do somthing wrong?

**Comment by LordSvein** [comment]
![Capture20](https://user-images.githubusercontent.com/39635317/230613803-5938642c-21c1-4482-a0d9-07583694d9df.PNG)

**Comment by LordSvein** [comment]
I redid my glpi installation from a blank base and I still have the same problem

**Comment by LordSvein** [comment]
@g-bougard my problem comes from the fact of a fresh install ation of glpi because I tested through an update of glpi 10.0.5 to 10.0.7 and I is not the problem

**Comment by trasher** [comment]
It seems like a configuration issue rather than a real bug, I close
