### ISSUE TITLE
the plugin not working correctly after upgrade with new httpd configuration for 10.0.7

### ISSUE THREAD

**Issue by rbonser** [glpi-project/glpi-inventory-plugin#342]
### Describe the bug

After upgrading our instance to glpi 10.0.7 /plugin 1.2.0 including adjusting the httpd config as described in thee gpli 10.0.7 installation guide. I noticed the tasks management and monitoring pages were not displaying correctly. When I reversed the httpd config the pages display properly.

Here are a couple screenshots with the change. The Targets, Agents, Clear list, and Delete selected items links are not clickable and the task status does not display within the task management or monitoring pages.
<img width="1219" alt="Screenshot 2023-04-10 at 2 09 18 PM" src="https://user-images.githubusercontent.com/36201987/230966507-0c2d5d05-3316-43be-bd79-cd6da03bc3e9.png">
<img width="1219" alt="Screenshot 2023-04-10 at 2 10 53 PM" src="https://user-images.githubusercontent.com/36201987/230966506-82ecba73-51ee-4e0c-a938-a205130bc4cb.png">

When I reverse the config the pages behave as before but I get a banner that states "Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details."
<img width="1215" alt="Screenshot 2023-04-10 at 2 06 56 PM" src="https://user-images.githubusercontent.com/36201987/230966510-bf46db3b-f034-41f7-bf64-7136a225032d.png">
<img width="1226" alt="Screenshot 2023-04-10 at 2 13 11 PM" src="https://user-images.githubusercontent.com/36201987/230966501-4ddc79c0-0977-41f9-9e8d-c78c80ccd242.png">

### To reproduce

follow https://glpi-install.readthedocs.io/en/latest/prerequisites.html#apache-configuration for the 10.0.7 apache vhost configuration changes. (We do use https rather than http as in the example but that should not matter.)

### Expected behavior

Following the upgrade should not break the plugin

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.7

### GLPIInventory plugin

1.2.0

**Comment by trasher** [comment]
Please note changing directory root is absolutely not mandatory for now.
