### ISSUE TITLE
Feature request: Bulk force inventory

### ISSUE THREAD

**Issue by redddcyclone** [glpi-project/glpi-inventory-plugin#344]
Hello,

I don't know if something like this already exists, but I haven't found anything similar.

Basically, I think it would be good to have an option like "Force inventory" on the Assets -> Computers -> Actions menu, so that we could select multiple computers and force inventory from there instead of doing it one by one.

Could this be done?

Thanks!

**Comment by trasher** [comment]
You can open a topic to discuss with community about this enhancement on [suggestion website](https://glpi.userecho.com/).
