### ISSUE TITLE
Error 403 on collect tasks because of double slash in URL

### ISSUE THREAD

**Issue by MarcSamD** [glpi-project/glpi-inventory-plugin#347]
### Describe the bug

I switched from FusionInventory plugin to GlpiInventory via marketplace. The inventory tasks are working well. But the collect tasks stop working. In access.log, I can see 403 errors for the collect tasks:
```
[20/Apr/2023:11:27:04 +0800] "GET //marketplace/glpiinventory/b/collect/?action=getJobs&machineid=computer1-2023-04-20-09-17-34 HTTP/1.1" 403 200 "-" "GLPI-Agent_v1.5-git3c8816ae"
[20/Apr/2023:11:28:06 +0800] "GET //marketplace/glpiinventory/b/collect/?action=getJobs&machineid=computer2-2023-04-17-09-21-43 HTTP/1.1" 403 200 "-" "FusionInventory-Agent_v2.6"
```
Indeed accessing this URL will be forbiden, as it is trying to get **//marketplace** instead of **/marketplace**.

### To reproduce

Dunno

### Expected behavior

Single slash for the URL and collect tasks working.

### Operating system

Windows

### GLPI Agent version

Other (See additional context below)

### GLPI version

10.0.7

### GLPIInventory plugin

1.2.1

### Additional context

- Same issue on both FI agent and GLPI-Agent nightly build.
- Server config for GLPI-Agent is "https://my.domain.com/marketplace/glpiinventory/"
- Server config for FI agents is either "https://my.domain.com/front/inventory.php" or "https://my.domain.com/plugins/fusioninventory/" (depending on the computers)
- There is a redirect rule enabled: `RewriteRule plugins/fusioninventory/(.*)$ marketplace/glpiinventory/ [R=307]`

**Comment by stonebuzz** [comment]
Hi @MarcSamD 
Can you check this option (from related ```Entity```)

![image](https://user-images.githubusercontent.com/7335054/233277227-1ef6d1fc-a5c5-4b77-9bb9-937b7b0ee380.png)

Best regards

**Comment by MarcSamD** [comment]
Thank you @stonebuzz , problem solved (by modifying the Agent base URL from https://my.domain.com/ to https://my.domain.com).
Still I don't close this issue as I think that you should add a control on this field to avoid people to add a trailing slash, especially knowing that for the [GLPI-Agent configuration](https://glpi-agent.readthedocs.io/en/latest/configuration.html) we should have one, so at the end it is very confusing to setup the right configuration.

**Comment by cedric-anne** [comment]
Indeed, we should trim the ending `/` from input value in concat operations.

**Comment by stonebuzz** [comment]
Hi @MarcSamD 
can you try this -> https://github.com/glpi-project/glpi-inventory-plugin/pull/348

**Comment by MarcSamD** [comment]
@stonebuzz : Patch validated on my side.

In details:

1. Put back the trailing slash at the end of the Agent base URL,
2. Run a new collect, which fails with double slash in the access log (successfully reproduced the issue),
3. Apply the patch https://github.com/glpi-project/glpi-inventory-plugin/pull/348 and restart Apache,
4. Run a new inventory and the collect tasks, they succeed and the access log shows the right URL for collect jobs.

**Comment by stonebuzz** [comment]
Perfect, thank for your test =)
