### ISSUE TITLE
Location is not updated after inventory tag was changed

### ISSUE THREAD

**Issue by Benoit221** [glpi-project/glpi-inventory-plugin#351]
### Describe the bug

Hi,

All my computer have glpi agent installed. When we change computer from one OU to another one, inventory tag is updated.

Best regards

### To reproduce

If computer doesn't exist in GLPI, no problem, the location is take from the tag.
If the computer already exist with another location, I can see that the inventory tag is good but the location is not updated.

### Expected behavior

Location rule should be running everytime a inventory is updated

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.7

### GLPIInventory plugin

1.2.1

**Comment by stonebuzz** [comment]
Hi @Benoit221 
can you check if ```location``` is ```locked``` (see it from ```Computer``` ```Lock``` tab)

Best regards

**Comment by Benoit221** [comment]
Hi @stonebuzz,

Thanks for your help. Effectively i already check for this :

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/56193156/81b1c84c-780b-4222-bb30-2f7b468e6f10)

Actually, there is an exemple :

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/56193156/4c597d58-aade-438a-894f-46b3ebee63b2)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/56193156/3020c27f-99f5-4eb2-9659-0742916999b5)

Here's my rule for location :

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/56193156/d0b20f4d-e924-4fe3-91d3-0f0edfc8182f)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/56193156/fc8b26eb-537e-4fb3-9409-13554a45c8b2)

And here's for entity :
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/56193156/96424076-c81c-4c1a-b214-510c358a885e)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/56193156/b1a24ee4-83cc-4ed1-b29c-90064d722969)

**Comment by stonebuzz** [comment]
Hi @Benoit221 any error from glpi log file (during inventory) ?

**Comment by trasher** [comment]
No feedback, closing
