### ISSUE TITLE
can't make rule for entity to work with proxy

### ISSUE THREAD

**Issue by Blank-Vcf** [glpi-project/glpi-inventory-plugin#352]
### Describe the bug

I made everything work end of last year with glpi 10.0.5 but i have upgrading to 10.0.6 since and rules are doing nothing.
I start from an empty db with last nightly build 10.0.8 dev and plugin 1.2.1 but can't make it work:

2 sub entities :
![image](https://user-images.githubusercontent.com/16317786/234613602-c4d5e6f2-9b50-414e-b8a0-2d3d0176c178.png)

2 simple rules:
![image](https://user-images.githubusercontent.com/16317786/234615830-9ca9a4f4-c3db-4e49-af9e-74626422c165.png)

try with computer name as criteria and contain instead equal = same result

agents stay in root entity:
![image](https://user-images.githubusercontent.com/16317786/234614628-d3e268d1-ea3a-4cc3-8a7a-c9447a240e90.png)

rules test is matching one of my rule, import and link rules maych on import

no trace in php/sql error on server

maybe i'm just on a misconfiguration but can't put a finger on it.

### To reproduce

delete agent in glpi, lauch import on agent
agent is in root entities import is not done

### Expected behavior

computer should be moved on entities based on tag

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

development release (See additional context below)

### GLPIInventory plugin

1.2.1

**Comment by Blank-Vcf** [comment]
ok i get it,
reinstall 10.0.5 = same behaviours,
updating rules with regex and tag on entities = same.
the last thing i put on change is to use a server with agent as a proxy, i switch an agent to use glpi directly and rule is working and computer is correctly imported in asset.

**Comment by trasher** [comment]
Seems like an agent bug or misconfiguration then, I close
