### ISSUE TITLE
Network Discovery and Network Inventory SNMP not works for me

### ISSUE THREAD

**Issue by zakirpcs** [glpi-project/glpi-inventory-plugin#353]
### Describe the bug

Hi Everyone,

I have installed a server with glpi-10.0.7 + glpi-agent-task-network-1.4  over AlmaLinux Server 8.7  and
glpi-agent-1.4 on computers and It works well, I can see the assets Computers.

Now I need discover the Network Devices (Routers, Switches, Printers,...) by SNMP.

I used the plugin "GLPI Inventory" for this goal and I created the two tasks, but didn't work
The two tasks are:

1) Create first task for discover the network devices

In Administration -> GLPI Inventory -> IP Ranges
I created IP range with name "network" ( 172.16.0.1 - 172.16.0.255) and associated it with SNMP credentials ( v2, community: public )

In Administration -> GLPI Inventory -> Task management
I created task "Discover" and in "Job configuration" I associated Object "network" and actors GLPI agent 14.1, then I activated this task in "task management" and I clicked on "Force start"

2) Create second task for SNMP:

In Administration -> GLPI Inventory -> Task management
I created task "SNMP" and in "Job configuration" I associated Object "network" and actors GLPI agent 14.1
I activated this task in "task managment" and I clicked on "Force start"

Finally I went to http://127.0.0.1:62354 and I clicked on Force Inventory

In  Administration -> GLPI Inventory -> GLPI Inventory I see only the one device, the server Linux but the Cisco router no.
I activated the agent in  Administration -> GLPI Inventory -> General setup -> Agents modules

### To reproduce

SNMP should be work.

### Expected behavior

SNMP should be work.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.7

### GLPIInventory plugin

1.2.1

**Comment by g-bougard** [comment]
Hi @zakirpcs 
have you updated the `server` parameter configuration in your agent to match glpiinventory plugin ?
Read the "Caution" notes there: https://glpi-agent.readthedocs.io/en/latest/configuration.html#server
If this is not the problem, you should share the agent log at the point you forced Inventory on the agent-side, eventually setting debug=2.

**Comment by zakirpcs** [comment]
Hi @g-bougard 

I have change as per your suggestion but still result is same.

**Comment by zakirpcs** [comment]
Hi @g-bougard

I am getting below error in /var/log/glpi-agent.log file.

[Thu Apr 27 12:28:46 2023][debug] NetDiscovery task not supported by server
[Thu Apr 27 12:28:46 2023][debug] NetInventory task not supported by server

**Comment by zakirpcs** [comment]
Hi @g-bougard

Please check details logs 

[root@localhost ~]# glpi-agent --force --logger=stderr --tasks netinventory --debug  --server http://192.168.2.104/glpi/plugins/glpiinventory/
[debug] Logger backend Stderr initialized
[debug] Logger backend File initialized
[debug] GLPI Agent (1.4-1)
[debug] Configuration directory: /etc/glpi-agent
[debug] Data directory: /usr/share/glpi-agent
[debug] Storage directory: /var/lib/glpi-agent
[debug] Lib directory: /usr/share/glpi-agent/lib
[debug] [target server0] Next server contact planned for Fri Apr 28 12:50:59 2023
[debug] Available tasks:
[debug] - Inventory: 1.12
[debug] - NetDiscovery: 5.1
[debug] - NetInventory: 5.1
[debug] - RemoteInventory: 1.0
[debug] target server0: server http://192.168.2.104/glpi/plugins/glpiinventory/
[debug] Planned tasks for server0: NetInventory
[debug] Build on Linux fv-az206-808 5.13.0-1031-azure 3720.04.1-Ubuntu SMP Mon Jun 13 22:51:01 UTC 2022 x86_64 x86_64 x86_64 GNULinux
[debug] Source time: 2022-07-01 09:32:14 UTC
[debug] Running in foreground mode
[info] target server0: server http://192.168.2.104/glpi/plugins/glpiinventory/
[debug] [http client] C22658E5: Using Compress::Zlib for compression
[info] sending contact request to server0
[debug] [http client] Using Compress::Zlib for compression
[info] sending prolog request to server0
[debug] NetInventory task execution not requested

**Comment by g-bougard** [comment]
Hi @zakirpcs 
about `... task not supported by server` messages, I guess you fixed it enabling these tasks in GLPI for the agent.
about your last output, it just says the plugin didn't plan a netinventory task. As you used the "tasks" option to limit the run to netinventory task, you should know a netinventory task can only be planned by the plugin if it knows at least one ip for the ip range used. The netdiscovery task exists essentially for that purpose. So did you run the netdiscovery task before the netinventory one ? If unsure, better use `--tasks netdiscovery,netinventory` so the agent tries to run the 2 tasks.
When debugging, you should also add a second time the `--debug` option so you enable the `debug=2` mode. So try this command:
```
glpi-agent --force --logger=stderr --tasks netdiscovery,netinventory --debug --debug --server http://192.168.2.104/glpi/plugins/glpiinventory/
```

**Comment by zakirpcs** [comment]
Hi @g-bougard

# glpi-agent --force --logger=stderr --tasks netdiscovery,netinventory --debug --debug --server 

Using above command getting below output:

http://192.168.2.104/glpi/plugins/glpiinventory/
[debug] Logger backend Stderr initialized
[debug] Logger backend File initialized
[debug] GLPI Agent (1.4-1)
[debug] Configuration directory: /etc/glpi-agent
[debug] Data directory: /usr/share/glpi-agent
[debug] Storage directory: /var/lib/glpi-agent
[debug] Lib directory: /usr/share/glpi-agent/lib
[debug] [target server0] Next server contact planned for Sat Apr 29 09:06:02 2023
[debug2] getAvailableTasks() : add of task Inventory version 1.12
[debug2] getAvailableTasks() : add of task NetDiscovery version 5.1
[debug2] getAvailableTasks() : add of task NetInventory version 5.1
[debug2] getAvailableTasks() : add of task RemoteInventory version 1.0
[debug2] Preparing execution plan
[debug] Available tasks:
[debug] - Inventory: 1.12
[debug] - NetDiscovery: 5.1
[debug] - NetInventory: 5.1
[debug] - RemoteInventory: 1.0
[debug] target server0: server http://192.168.2.104/glpi/plugins/glpiinventory/
[debug] Planned tasks for server0: NetDiscovery,NetInventory
[debug] Build on Linux fv-az206-808 5.13.0-1031-azure 3720.04.1-Ubuntu SMP Mon Jun 13 22:51:01 UTC 2022 x86_64 x86_64 x86_64 GNULinux
[debug] Source time: 2022-07-01 09:32:14 UTC
[debug] Running in foreground mode
[info] target server0: server http://192.168.2.104/glpi/plugins/glpiinventory/
[debug] [http client] 9F8BCA70: Using Compress::Zlib for compression
[info] sending contact request to server0
[debug2] [http client] 9F8BCA70: sending message:
{
   "action": "contact",
   "deviceid": "localhost.localdomain-2023-04-21-12-17-19",
   "enabled-tasks": [
      "netdiscovery",
      "netinventory"
   ],
   "installed-tasks": [
      "inventory",
      "netdiscovery",
      "netinventory",
      "remoteinventory"
   ],
   "name": "GLPI-Agent",
   "version": "1.4-1"
}
[debug2] format: Zlib
[debug2] [http client] 9F8BCA70: received message:
{"expiration":"24","status":"ok","tasks":{"netdiscovery":{"version":"1.2.1","server":"glpiinventory"},"netinventory":{"version":"1.2.1","server":"glpiinventory"}}}
[debug] [http client] Using Compress::Zlib for compression
[info] sending prolog request to server0
[debug2] [http client] sending message:
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <DEVICEID>localhost.localdomain-2023-04-21-12-17-19</DEVICEID>
  <QUERY>PROLOG</QUERY>
  <TOKEN>12345678</TOKEN>
</REQUEST>
[debug2] format: Zlib
[debug2] [http client] receiving message:
<?xml version="1.0"?>
<REPLY><PROLOG_FREQ>24</PROLOG_FREQ><RESPONSE>SEND</RESPONSE></REPLY>
[debug] NetDiscovery task execution not requested
[debug] NetInventory task execution not requested

**Comment by g-bougard** [comment]
`NetDiscovery task execution not requested` => It means you may need to "Force" the task in the plugin. Be sure "Permit to re-prepare task after run :" checkbox is checked. Also check your agent (here 'localhost.localdomain-2023-04-21-12-17-19' is selected as "Actor" in the job configuration.
