### ISSUE TITLE
Getting PHP warnings constantly when computers send Collect result

### ISSUE THREAD

**Issue by redddcyclone** [glpi-project/glpi-inventory-plugin#354]
### Describe the bug

Hi. I keep getting PHP warnings when computers send Collect task results. These are the warnings I get:

![image](https://user-images.githubusercontent.com/58712628/235155153-5e70e090-75d2-45e0-a5ab-0078fe559ad6.png)

This is the associated SQL error:

![image](https://user-images.githubusercontent.com/58712628/235155247-1af24066-bdd9-4226-924f-7fd00beed813.png)

Apparently, this only happens when some registry keys I want to collect are not found ("Caminho não encontrado")

### To reproduce

1. Create a Collect data task that gets registry values
2. Try to collect inexistent registry values from a computer
3. Warnings or errors happen when some values are not found (apparently)

### Expected behavior

No warnings or errors at all.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.7

### GLPIInventory plugin

1.2.1

**Comment by stonebuzz** [comment]
Hi @redddcyclone 

can you try this :

https://github.com/glpi-project/glpi-inventory-plugin/pull/363

**Comment by redddcyclone** [comment]
Hi @stonebuzz 

Just tested, no more errors showing up.

Thanks for the attention! I'll close this issue
