### ISSUE TITLE
pb error 403 access fusion ....

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi-inventory-plugin#358]
### Describe the bug

Good morning,
I just went into production and I just realized that fusioninventory query comes with a 403 .
I had tested in dev and it was ok.
What to do with glpiinventory?
Thank you because we’re all stuck...

### To reproduce

`[11/May/2023:11:15:04 +0200] "POST /plugins/fusioninventory HTTP/1.1" 403 7187 "-" "FusionInventory-Agent_v2.3.19"`

### Expected behavior

`[11/May/2023:11:15:04 +0200] "POST /plugins/fusioninventory HTTP/1.1" 403 7187 "-" "FusionInventory-Agent_v2.3.19"`

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.7

### GLPIInventory plugin

1.2.1

**Comment by cedric-anne** [comment]
Hi,

If you are using Apache, you can add an Alias from fusioninventory to glpiinventory with something like:

`AliasMatch "^/plugins/fusioninventory/((index\.php)?)$" "/var/www/glpi/plugins/glpiinventory/$1"`

You must adapt paths to your configuration.

**Comment by g-bougard** [comment]
Hi @falco2001 
you can also update your FI agents configuration so the server URL matches the new one.
And of course, you should definitively upgrade your FI agents to replace them by GLPI-Agent and follow that documentation which works also for FI agents: https://glpi-agent.readthedocs.io/en/latest/configuration.html#server

**Comment by falco2001** [comment]
après modification j'ai en encore  des lignes en erreur mais d'autres fonctionnent  !
140.77. - - [11/May/2023:13:44:37 +0200] "POST /plugins/fusioninventory HTTP/1.1" 403 7187 "-" "FusionInventory-Agent_v2.3.19"
140.77. - - [11/May/2023:13:44:37 +0200] "POST /plugins/fusioninventory HTTP/1.1" 403 7187 "-" "FusionInventory-Agent_v2.3.19"
140.77. - - [11/May/2023:13:44:37 +0200] "POST /plugins/fusioninventory HTTP/1.1" 403 7187 "-" "FusionInventory-Agent_v2.3.19"
140.77. - - [11/May/2023:13:44:37 +0200] "POST /plugins/fusioninventory HTTP/1.1" 403 7187 "-" "FusionInventory-Agent_v2.3.19"
140.77.- - [11/May/2023:13:44:37 +0200] "POST /plugins/fusioninventory HTTP/1.1" 403 7187 "-" "FusionInventory-Agent_v2.3.19"
^C

**Comment by falco2001** [comment]
An error in this ? 
<Directory /var/www/assistance/public>
 #<Directory /var/www/assistance/maintenance>
              Require all granted
              Order deny,allow
              Deny from all
              Allow from all
        RewriteEngine On

        # Redirect all requests to GLPI router, unless file exists.
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^(.*)$ index.php [QSA,L]

</Directory>

#Règle par défaut
        RewriteEngine           on
        RewriteOptions          inherit

        AliasMatch "^/plugins/fusioninventory/((index\.php)?)$" "/var/www/assistance/plugins/glpiinventory/$1"

    # Pour test lors de migration GLPI
    # RewriteCond %{REQUEST_URI} !\/plugins\/fusioninventory
    #RewriteRule             ^(.*)           https://assistance.ens-lyon.fr/maintenance/index.php [L]

#Suppriler l'utilisation de assistance.ens-lyon.fr/?noAUTO=1 : car  acces ldap distant dangereux
        RewriteCond %{QUERY_STRING} (noAUTO) [NC]
        RewriteRule .* - [F,L]

</VirtualHost>

**Comment by falco2001** [comment]
that's ok thanks ....
