### ISSUE TITLE
Merger equivalence with fusion <-> glpiinventory sql

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi-inventory-plugin#359]
### Describe the bug

Good morning,
is there an equivalance with this in glpiinventoty? Thank you
`SELECT DISTINCT UPPER (B.name),A.remote_addr,D.name FROM glpi_plugin_fusioninventory_inventorycomputercomputers as A LEFT JOIN glpi_computers as B ON A.computers_id = B.id LEFT JOIN glpi_items_operatingsystems as C ON C.items_id = B.id LEFT JOIN glpi_operatingsystems as D on D.id = C.operatingsystems_id LEFT JOIN glpi_plugin_fusioninventory_agents as E on E.computers_id = A.computers_id WHERE TIME_TO_SEC(TIMEDIFF(NOW(),E.last_contact)) < 1200 AND (remote_addr LIKE ...`

### To reproduce

SQL error

### Expected behavior

No wrong answer

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.7

### GLPIInventory plugin

1.2.1

**Comment by stonebuzz** [comment]
Hi @falco2001 

```remote_addr``` is now a column from ```glpi_agents``` table.

Link with ```asset``` is done with

```sql
itemtype = 'Computer' and items_id = ID
``` 

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/7335054/6d1d1027-5f5f-4f0d-bdf4-ac53381c356a)


Best regards

**Comment by falco2001** [comment]
Thank you
Do you have any idea where I can find  ?
-  last_contact  in glpi_computers ? before it was in glpi_plugin_fusioninventory_agents 
-  name LIKE 'Microsoft Windows 11% before it was in  glpi_operatingsystems ?
