### ISSUE TITLE
Inventoried computers

### ISSUE THREAD

**Issue by Tartiflette-glpi** [glpi-project/glpi-inventory-plugin#365]
### Describe the bug

Hi,

I just changed my Inventory system (OCS plugin) to GLPI Inventory.
I deployed the agent by GPO to the domain of our customers, but I don't understand how does it works exactly ?
I have like 250 agents and only 41 inventoried computers:
https://i.ibb.co/4YrYz3C/Capture-d-cran-2023-05-30-143410.png

It seems it happen randomly, because I have some computers inventoried for one customer, but not all are marked as "inventoried" and I can't see the informations we need...
https://i.ibb.co/34xv4Md/Capture-d-cran-2023-05-30-142309.png

Can you explain me or help me please?

Thanks!

### To reproduce

Install GLPI 10.0.6
Install GLPI Inventory plugin 
Deploy GLPI-Agent 1.4 to an external computer

### Expected behavior

Inventoring computer that run the GLPI Agent

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin

1.2.1

**Comment by stonebuzz** [comment]
Hi @Tartiflette-glpi 
Please update GLPI to latest version and retry

Best regards

**Comment by Tartiflette-glpi** [comment]
> Hi @Tartiflette-glpi Please update GLPI to latest version and retry
> 
> Best regards

Hi, 

Thanks for your reply,

Where is the problem exactly ? Is it really necessary to update the entire GLPI ?

If possible, I prefer to not update our GLPI now, because we got new problems every updates. Atm our GLPI works perfectly without the GLPI Inventory...
However I already tested the version 10.0.7 but I don't understand how works this "public" folder. There is a warning that explain the config is not secured but the official doc file isn't clear for me. I broke twice my GLPI-TEST

**Comment by stonebuzz** [comment]
>  Is it really necessary to update the entire GLPI ?

Yes, We are actively working on the inventory

Best regards

**Comment by trasher** [comment]
> ... but I don't understand how works this "public" folder. There is a warning that explain the config is not secured but the official doc file isn't clear for me. I broke twice my GLPI-TEST

This is still a recommendation only.

**Comment by Tartiflette-glpi** [comment]
> > Is it really necessary to update the entire GLPI ?
> 
> Yes, We are actively working on the inventory
> 
> Best regards

Okay... So I'll update my GLPI to the lastest version this weekend, thanks



> > ... but I don't understand how works this "public" folder. There is a warning that explain the config is not secured but the official doc file isn't clear for me. I broke twice my GLPI-TEST
> 
> This is still a recommendation only.

I know about that, but how to remove the warning so ? :/ I have some users that have an admin access to their entity: they can see it in 10.0.7

**Comment by cedric-anne** [comment]
> I know about that, but how to remove the warning so ?

You can set constant `GLPI_CENTRAL_WARNINGS` to `0` if you want to hide these warnings (e.g. by adding `define('GLPI_CENTRAL_WARNINGS', '0');` in `local_define.php` file, see https://glpi-install.readthedocs.io/en/latest/install/index.html#files-and-directories-locations).

**Comment by Tartiflette-glpi** [comment]
Hi,
I updated GLPI to 10.0.7, I works, thank you all
Atm I didn't spoted errors or bugs with this version
All good for me
