### ISSUE TITLE
SNMP community not display

### ISSUE THREAD

**Issue by bbreton09** [glpi-project/glpi-inventory-plugin#37]
The SNMP community name is not display in "Ip Range" associed snmp identifier

![image](https://user-images.githubusercontent.com/10090794/148939322-31f21fd9-4205-44f0-8f06-d533c682a9b5.png)

GLPI BETA 10 upgrade from 9.5
GLPI Inventory RC3

**Comment by trasher** [comment]
I cannot reproduce. 

Any entries in logs? 
Was this an existing entry (migrated) or a new create done?
Is it ok on other pages/in database?

**Comment by trasher** [comment]
Still not able to reproduce. Please try with latest GLPI and plugin RC, feel free to reopen if problem persists.
