### ISSUE TITLE
Lasdt inventory date not migrated

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi-inventory-plugin#372]
### Describe the bug

Seems like "last inventory update" is not migrated when updating from FusionInventory plugin; see https://github.com/glpi-project/glpi/issues/14735

Note that FI plugin is not compatible with GLPI > 10.0.6; therefore I'm not 100% sure of the results of my tests (I have no time to try with old versions right now).

### To reproduce

1. Install FI plugin, do an inventory
2. Install glpiinventory plugin
3. Update plugin
4. See dates in computer main form.

### Expected behavior

Dates should al be migrated.

**Comment by stonebuzz** [comment]
@AldarisPale


Can you try this ?

https://github.com/glpi-project/glpi-inventory-plugin/pull/373

**Comment by AldarisPale** [comment]
@stonebuzz looks like it's working now! Thank you very much!
I can see that the following fields have been migrated: 
* Last contact
* **Last inventory update**
* Last boot date

Do you have any idea when there would be a release of glpi-inventory plugin and glpi, which would include this change and changes made at https://github.com/glpi-project/glpi/issues/14735 ?
