### ISSUE TITLE
slow loading of the package deploy tab

### ISSUE THREAD

**Issue by kintaro1981** [glpi-project/glpi-inventory-plugin#381]
### Describe the bug

Clicking in the package deploy tab takes several seconds to loade the page.
All the other pages and tabs load istantly.

Loading http://glpi/plugins/glpiinventory/front/deploypackage.php don't produce this issue, the problem is only clicking on the package deploy tab.

### To reproduce

1. Search for a computer
2. Open the computer page
3. Click on the tabs Package Deploy

### Expected behavior

The page loads like the other ones.

### Operating system

Other (See additional context below)

### GLPI Agent version

Other (See additional context below)

### GLPI version

10.0.9

### GLPIInventory plugin

1.2.3

### Additional context

operating system and agent version are not involved in this issue

**Comment by kintaro1981** [comment]
Do you think this a resource problem?
All the other GLPI pages are very fast.
Maybe is a too much aggressive query?

we have about:
1000 pc
109 packages
12 static groups
15 dynamic groups

**Comment by stonebuzz** [comment]
Hello, 

your infrastructure could also be the cause, for example :

- Does the server also host the GLPI database?
- Do many people connect to GLPI?
- The size of the server (processor, memory)?
- Is it a virtual machine?
- Does the ESX use an SSD or a hard disk?
- etc ....

we've never had the opportunity to test the plugin on such a large volume.

If you use the plugin more than professionally, 
you should consider taking out a subscription to get professional support.

Best regards

**Comment by kintaro1981** [comment]
We are not this big.
We have 700 active agents but I created many packages because we don't have Active Directory and I use GLPI a lot to deploy software and os configurations.

I'm going to ask sysadmin to check the db when glpi hangs to understand if it's a lack of resources' issue.

**Comment by kintaro1981** [comment]
Virtual machine 
GLPI DB in the the same machine.
Mono processor 
RAM 6GB 
Only 2/3 people connect to GLPI gui as we don't publicied selfservice to users yet. We utilize it only internally as an inventory and package deploy.

With Analize in Firefox I can see this:

![immagine](https://github.com/glpi-project/glpi-inventory-plugin/assets/2357176/08deee12-cc62-4181-888c-b69886a544d4)


Anyone can reproduce it?

**Comment by stonebuzz** [comment]
How many package are available per Computer ?

**Comment by kintaro1981** [comment]
for pc with about 90 packages (os 64bit) it takes from 20 to 25 seconds
for pc with about 50 packages (os 32bit) is takes the same time, 20 to 25 seconds

How about cache the list and reload it only if there's a change in one or more package?
I mean a change in the the entity target and/or to the group able to do deploy on demand of a package?

Here:
![immagine](https://github.com/glpi-project/glpi-inventory-plugin/assets/2357176/28bda77b-2381-4aee-8b77-1c415ec2684e)

and here:
![immagine](https://github.com/glpi-project/glpi-inventory-plugin/assets/2357176/8041f1f6-18aa-401b-81dd-4d25e0f44e8f)

**Comment by kintaro1981** [comment]
p.s. Tasks/Groups tabs loads instantly

**Comment by stonebuzz** [comment]
Can you create a deployment task for a single computer and see if it loads faster?

**Comment by kintaro1981** [comment]
I found a pc that doesn't belong to any dynamic group and it take the same amount of time about 20/25 seconds to fully load Deploy Package tab and then it display: 
No packages available to install

![immagine](https://github.com/glpi-project/glpi-inventory-plugin/assets/2357176/e0d35b42-d726-428d-a738-62051bb95538)

**Comment by kintaro1981** [comment]
> Can you create a deployment task for a single computer and see if it loads faster?

wait I'm not talking about tasks but packages deploy

**Comment by stonebuzz** [comment]
With or without deploy task, tab is load like a charm 

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/7335054/61e84424-6fd9-4335-8788-82bbb6e0f323)

It may be linked to something else, but it's going to be complicated to find without having a hand

Perhaps you could enable the slow-query log in mysql  to see if that's where the problem lies

Or perhaps consider taking out a subscription as you seem to have a very professional and sophisticated use of the plugin

This would enable us to resolve your problem more quickly and easily.

**Comment by kintaro1981** [comment]
we are in the same page?
your last row after id= there's `tab_key=PluginGlpiinventory` in my case is `tab=30`

in my case is `common.tabs.php?_target=/front/computer.form.php&_itemtype=Computer&_glpi_tab=PluginGlpiinventoryDeployPackage$1&id=13718&withtemplate=&formoptions=data-track-changes%3Dtrue` loads slow.

`updatecurrenttab.php?itemtype=Computer&id=12830&tab=30&withtemplate=0` loads in a decent time to me too

**Comment by stonebuzz** [comment]
bad past, but same behavior 
load instantly
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/7335054/f2d44c3e-06f8-4f04-b282-03fb69fe6c13)

**Comment by stonebuzz** [comment]
Database seems huge (1659 against 230 for me) !

can you disable all the other plugins (except glpiinventory) 
to see if it one of them might be at fault)

Can you retry with GLPI latest version (some optimization are added)

**Comment by kintaro1981** [comment]
With only glpiinventory activated:

![immagine](https://github.com/glpi-project/glpi-inventory-plugin/assets/2357176/9fffd25f-4aba-481f-a132-6ef6c7889fd5)

![immagine](https://github.com/glpi-project/glpi-inventory-plugin/assets/2357176/70430af6-173c-4565-8408-25f3a955a29a)

![immagine](https://github.com/glpi-project/glpi-inventory-plugin/assets/2357176/896a9fe5-77af-43c0-b09f-50738ba0399f)

![immagine](https://github.com/glpi-project/glpi-inventory-plugin/assets/2357176/ba62b10d-8697-4bf1-8da2-240e698c1e1b)

![immagine](https://github.com/glpi-project/glpi-inventory-plugin/assets/2357176/ae869cec-cb8b-4fe3-affb-9e645eb1e35f)

**Comment by stonebuzz** [comment]
I confess I don't understand
and I'm afraid I can't help you any more than that
I can't reproduce it myself

**Comment by kintaro1981** [comment]
@stonebuzz ping 😄 
as soon you have 2 minutes can you list "your" queries?

**Comment by stonebuzz** [comment]
hI @kintaro1981 

Here are the only two requests concerning package deployment (when opening the ```Package Deploy``` tab in a Computer)


```sql
SELECT `job`.* 
FROM `glpi_plugin_glpiinventory_taskjobs` AS `job` LEFT JOIN `glpi_plugin_glpiinventory_tasks` AS `task` ON (`job`.`plugin_glpiinventory_tasks_id` = `task`.`id`) 
WHERE `task`.`is_deploy_on_demand` = '1' AND `task`.`is_active` = '1' AND `task`.`entities_id` IN ('0', '1')
```

```sql
SELECT DISTINCT `glpi_plugin_glpiinventory_deploypackages`.* 
FROM `glpi_plugin_glpiinventory_deploypackages` LEFT JOIN `glpi_plugin_glpiinventory_deploypackages_groups` ON (`glpi_plugin_glpiinventory_deploypackages`.`id` = `glpi_plugin_glpiinventory_deploypackages_groups`.`plugin_glpiinventory_deploypackages_id`) LEFT JOIN `glpi_plugin_glpiinventory_deploypackages_entities` ON (`glpi_plugin_glpiinventory_deploypackages`.`id` = `glpi_plugin_glpiinventory_deploypackages_entities`.`plugin_glpiinventory_deploypackages_id`) LEFT JOIN `glpi_plugin_glpiinventory_deploypackages_users` ON (`glpi_plugin_glpiinventory_deploypackages`.`id` = `glpi_plugin_glpiinventory_deploypackages_users`.`plugin_glpiinventory_deploypackages_id`) LEFT JOIN `glpi_plugin_glpiinventory_deploypackages_profiles` ON (`glpi_plugin_glpiinventory_deploypackages`.`id` = `glpi_plugin_glpiinventory_deploypackages_profiles`.`plugin_glpiinventory_deploypackages_id`) 
WHERE `glpi_plugin_glpiinventory_deploypackages`.`plugin_glpiinventory_deploygroups_id` > '0' AND (((`glpi_plugin_glpiinventory_deploypackages_entities`.`entities_id` = '0')) OR (`glpi_plugin_glpiinventory_deploypackages_users`.`users_id` = '2') OR (`glpi_plugin_glpiinventory_deploypackages_profiles`.`profiles_id` = '4'))
```

**Comment by kintaro1981** [comment]
I delete some dynamic groups and now the page loads a little bit faster (10 seconds instead of 25), but the query number is still high (about 1100).

I noticed with debug enabled that deploy tab run many query but the strange thing is that it run multiple time the same queries, is it normal? see attached ods file.

Maybe the problem is in this redundant number of querys? The queries are done relatively fast (2 seconds) but maybe php scripts have to elaborate and/or wait data from them?

[query_list_deploy_package_tab.ods](https://github.com/glpi-project/glpi-inventory-plugin/files/13241937/query_list_deploy_package_tab.ods)

**Comment by kintaro1981** [comment]
any idea why those queries run multiple times?

**Comment by stonebuzz** [comment]
Hi @kintaro1981 

as requested there is a list of SQL query 

```sql
SELECT `job`.*
FROM `glpi_plugin_glpiinventory_taskjobs` AS `job` LEFT JOIN `glpi_plugin_glpiinventory_tasks` AS `task` ON (`job`.`plugin_glpiinventory_tasks_id` = `task`.`id`) 
WHERE `task`.`is_deploy_on_demand` = '1' AND `task`.`is_active` = '1' AND `task`.`entities_id` IN ('0', '1', '2', '3')
0 ms 	1

SELECT DISTINCT `glpi_plugin_glpiinventory_deploypackages`.*
FROM `glpi_plugin_glpiinventory_deploypackages` LEFT JOIN `glpi_plugin_glpiinventory_deploypackages_groups` ON (`glpi_plugin_glpiinventory_deploypackages`.`id` = `glpi_plugin_glpiinventory_deploypackages_groups`.`plugin_glpiinventory_deploypackages_id`) LEFT JOIN `glpi_plugin_glpiinventory_deploypackages_entities` ON (`glpi_plugin_glpiinventory_deploypackages`.`id` = `glpi_plugin_glpiinventory_deploypackages_entities`.`plugin_glpiinventory_deploypackages_id`) LEFT JOIN `glpi_plugin_glpiinventory_deploypackages_users` ON (`glpi_plugin_glpiinventory_deploypackages`.`id` = `glpi_plugin_glpiinventory_deploypackages_users`.`plugin_glpiinventory_deploypackages_id`) LEFT JOIN `glpi_plugin_glpiinventory_deploypackages_profiles` ON (`glpi_plugin_glpiinventory_deploypackages`.`id` = `glpi_plugin_glpiinventory_deploypackages_profiles`.`plugin_glpiinventory_deploypackages_id`) 
WHERE `glpi_plugin_glpiinventory_deploypackages`.`plugin_glpiinventory_deploygroups_id` > '0' AND (((`glpi_plugin_glpiinventory_deploypackages_entities`.`entities_id` = '0')) OR (`glpi_plugin_glpiinventory_deploypackages_users`.`users_id` = '2') OR (`glpi_plugin_glpiinventory_deploypackages_profiles`.`profiles_id` = '4'))
1 ms 	1

SELECT *
FROM `glpi_plugin_glpiinventory_deploygroups`
WHERE `glpi_plugin_glpiinventory_deploygroups`.`id` = '4' LIMIT 1
0 ms 	1

SELECT *
FROM `glpi_plugin_glpiinventory_deploygroups_staticdatas`
WHERE `plugin_glpiinventory_deploygroups_id` = '4' AND `itemtype` = 'Computer'
0 ms 	1
```

For  ```PHP Notice (8): Undefined index: type```

can you try this ->  https://github.com/glpi-project/glpi-inventory-plugin/pull/441

**Comment by kintaro1981** [comment]
I tried to update to 10.0.12. The problem is still there.
I'm going to ask to my manager if we can consider a subscription.

**Comment by trasher** [comment]
Since we cannot reproduce; and existing data is certainly faulty; I close.

Feel free to reopen if you can provide a use case reproducing issue on a fresh install.
