### ISSUE TITLE
Computer Inventory, Os Version not Updating

### ISSUE THREAD

**Issue by SpecialOOps** [glpi-project/glpi-inventory-plugin#383]
### Describe the bug

Hello !

I encounter a problem when trying to synchronize an already existing computer.

We want to migrate from Fusion Inventory to GLPI-Agent. So i'm testing on a computer which have fusion installed.
I've executed the modified VBS to delete fusion inventory, and install the GLPI Agent 1.5. I start a synchro, GLPI receive it, but doesn't update the OS Version of windows and the type of Windows installed. I've made sure that no locks are applied to the OS Version value.
I've verified on the specific computer -> Locks and on the Administration -> Inventory -> Locked field.
Both of them contain nothing about Os Version.

I've tried Disabling the Fusion inventory plugin, but it doesn't change anything too.

If you need more informations, don't hesitate to ask ^^

### To reproduce

GLPI 10.5 + Fusion Inventory (Last Version)
Synchronise a Computer with Fusion Inventory
Uninstall Fusion Inventory on the computer and use GLPI-Agent 1.5
And start an inventory.

### Expected behavior

Should Update Windows Version and Name of the Windows installed.

Should show 
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/20866916/a3961428-80bd-498c-bd8e-d982114b729c)
But show
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/20866916/b1c2c3d1-1e7b-40bd-b511-faa8f8e9ea02)

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.5

**Comment by SpecialOOps** [comment]
Any update on this guys ?

I can provide more information if needed.

**Comment by trasher** [comment]
Also, 10.0.5 is outdated, please try if you reproduce with latest stable release.
