### ISSUE TITLE
SNMP link to IPRange not deleted when a SNMP Credential is deleted

### ISSUE THREAD

**Issue by JulienRemi** [glpi-project/glpi-inventory-plugin#384]
### Describe the bug

When deleting a SNMPCredential who has a link to at least one IPRange, the link still exist in the database (glpi_plugin_glpiinventory_ipranges_snmpcredentials).  
Then the SNMP tab on the IPRange object load indefinitely and a Warning is thrown : `PHP Warning (2): Undefined array key "snmpversion" in C:\inetpub\glpi-10.0.8\src\SNMPCredential.php at line 132`  

### To reproduce

1. Create a SNMPCredential
2. Create an IPRange and add the SNMPCredential to it
3. Delete the SNMPCredential
4. Now the SNMPCredential tab of the IPRange will load indefinitely and the link will still be present in the database (glpi_plugin_glpiinventory_ipranges_snmpcredentials table)

### Expected behavior

When deleting a SNMPCredential all of his links to IPRanges should be deleted with him.

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.8

### GLPIInventory plugin

1.2.2

**Comment by trasher** [comment]
Please provide full warning stack trace.

**Comment by JulienRemi** [comment]
```
[2023-08-07 06:56:54] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "snmpversion" in C:\inetpub\glpi-10.0.8\src\SNMPCredential.php at line 132
  Backtrace :
  ...entory\inc\iprange_snmpcredential.class.php:234 SNMPCredential->getRealVersion()
  ...entory\inc\iprange_snmpcredential.class.php:123 PluginGlpiinventoryIPRange_SNMPCredential->showItemForm()
  src\CommonGLPI.php:691                             PluginGlpiinventoryIPRange_SNMPCredential::displayTabContentForItem()
  ajax\common.tabs.php:117                           CommonGLPI::displayStandardTab()
  public\index.php:82                                require()
```

**Comment by trasher** [comment]
Change proposed in #391 should prevent the error to appear; that will fix the displayed issue.

But I wonder if it's enougth, I guess we should add a hook in the plugin when a snmp credential is removed. We can either prevent removal if it's still in use, or unlink in iprange; first solution seems better to me.

**Comment by maxime-ole** [comment]
The issue where a link to an IPRange remains in the database even after deleting its associated SNMPCredential is still present in GLPI 11.0.4.
