### ISSUE TITLE
local users inventory

### ISSUE THREAD

**Issue by mareban** [glpi-project/glpi-inventory-plugin#385]
### Describe the bug

the collect doesn't seem to work :-( ! We are using the latest GLPI and the 1.5 agent , and the url is /marketplace/glpiinventory !

All the collect parameters are enabled on the web console, and when we start a Collect task we have this error : 
[info] No Collect job enabled or Collect support disabled server side

The agent URL is configured in Entity/Asset too !

Do we miss something or is it a bug ?

Do we have to specify a registry/wmi/file for this to work ?

Thanks for your help.

### To reproduce

.

### Expected behavior

.

### Operating system

Linux

### GLPI Agent version

1.5

### GLPI version

10.0.9

### GLPIInventory plugin

1.2.3

### Additional context

.

**Comment by g-bougard** [comment]
Hi @mareban 

when you see such message on agent side, you have 2 things to do:
1. enable debug2 on the agent: if this doesn't help you to identify a problem, this can help us
2. following what is saying the message, really checking all the points that can explain why a task is not enabled

Also can you describe you collect task ? And I don't understand why your issue title is *local users inventory* and you're talking about collect task, this makes no sens.

**Comment by mareban** [comment]
Thanks a lot for your reply
