### ISSUE TITLE
Transifex URL doesn't Work

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi-inventory-plugin#394]
Hi, We want to help translate the plugin to es_EC, but the transifex URL doesn't work: https://app.transifex.com/glpi/glpi-inventory-plugin/

What is the URL? Can you add the es_EC language please?

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/56606032/a62b99e4-0794-4f86-a1ac-cd6aa6111a27)

**Comment by trasher** [comment]
URL is https://app.transifex.com/teclib/glpi-plugin-glpiinventory/dashboard/ - es_EC has been requested here an added.
