### ISSUE TITLE
Cannot add criterias to a dynamic group

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi-inventory-plugin#396]
### Describe the bug

Cannot add criterias to a dynamic group, so we cannot use it anymore

### To reproduce

1. Create a dynamic group.
2. Go to criterias

### Expected behavior

We should be able to add criterias in order to add computers into a dynamic group

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.9

### GLPIInventory plugin

1.2.3

**Comment by stonebuzz** [comment]
I do not reproduce

Criteria

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/7335054/2de37d5b-6027-41c7-a1a8-d5134288846c)

result of the criteria

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/7335054/d4f95df6-54e5-4f14-a4d6-506ead8f86ec)

can you give us more details

Best regards

**Comment by SteadEXE** [comment]
Oh my bad, I was looking for a "add" button to add a criteria, didn't realised that the filters are the criterias. 
Thanks!
