### ISSUE TITLE
computer groups view column too tight

### ISSUE THREAD

**Issue by kintaro1981** [glpi-project/glpi-inventory-plugin#410]
### Describe the bug

In the Task/Group tab the column displaying computer groups is too tight.

![immagine](https://github.com/glpi-project/glpi-inventory-plugin/assets/2357176/43a70812-c6b5-43c4-9360-288385e62701)

### To reproduce

1. go to the computer page
2. click on Tasks/Groups tab
3. take a look to the Groups column

### Expected behavior

I expect to be able to see the column no that tight and read the text easilly.

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.9

### GLPIInventory plugin

1.2.3

**Comment by stonebuzz** [comment]
Hi @kintaro1981 
can you enable GLPI debug mode to see if some error / warning are displayed ?

**Comment by stonebuzz** [comment]
Can you create a deploy task for a single computer and see if it loads faster?

**Comment by kintaro1981** [comment]
no errors/warnings are displayed with debug activated

**Comment by stonebuzz** [comment]
hi @kintaro1981 
can you try this

https://github.com/glpi-project/glpi-inventory-plugin/pull/413

**Comment by kintaro1981** [comment]
it's working
