### ISSUE TITLE
GLPI inventory v1.2.3 - No link for existing machines and import of serial number

### ISSUE THREAD

**Issue by CireSacud26** [glpi-project/glpi-inventory-plugin#414]
### Describe the bug

Hello,

For an existing machine in GLPI, GLPIInventory with agent 1.5 does not merge even though the rule parameters (computer name + Serial number + UUID) match. Instead, the inventory creates a new duplicate machine. However, I tested the import rules and equipment linking engine with this data and it returned OK.

In addition, for this new machine the inventory number which should be empty is loaded by the serial number. This also happens when importing a machine that does not exist in GLPI.

I noticed that these problems mainly occur when dealing with virtual machines. For physical machines, merge and import seems to work fine.

Regards,
Eric

### To reproduce

1- Install GLPI Agent 1.5 on a virtual machine already existing in GLPI database (same name, serial number and UUID)
2- Force inventory
3- Agent is added in GLPI Inventory but machine is added instead of linked with the existing one
4- The inventory number of the added machine is set with the serial number instead of blank field

### Expected behavior

The inventored virtual machine had to be linked with the existing one and added machine should not set the inventory number this the serial number

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.9

### GLPIInventory plugin

1.2.3

**Comment by stonebuzz** [comment]
Hi @CireSacud26 

can you retry by resetting all rules ?

best regards

**Comment by CireSacud26** [comment]
Hi stonebuzz,

Thanks for this advice. Resetting all rules seems to solve the issue.

Best regards,
Eric
