### ISSUE TITLE
GLPI Inventory 1.3.0 + Agent 1.5

### ISSUE THREAD

**Issue by EC2311** [glpi-project/glpi-inventory-plugin#428]
### Describe the bug

Hello
Computer (existing or not), import refused due to rule.

### To reproduce

Informations on computer (shown in devices refused)
Name : ok
Serial : ok
UUID : ok

Regle 
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/42341169/3a748596-4e1b-4fba-b423-8e655673a226)

when testing : Yes for this rule, although serial is filled

### Expected behavior

The computer should be created or updated

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.10

### GLPIInventory plugin

1.3.0

**Comment by trasher** [comment]
Try with resetted rules, if you reproduce with defaults rules, please provide inventory file.

**Comment by EC2311** [comment]
Hello
I may add information : plugin created new rules after migrating from FusionInventory
I removed the legacy rules (in place in the plugin), let only the rules migrated

When trying to reset rules : maximul execution times of 120 secondes
I try to delete the rules : samething and no rules removes except the legacy set with plugin glpiinventory

**Comment by EC2311** [comment]
Update deletion : I found an explnatation : there are many lines to delete in rulematchedlogs for some rules
-> timeout
when deleting manually the lines in the table, deleting the main rule is ok

> I don't understand why it takes times using GLPI and not using mysql directly (no time out)

**Comment by stonebuzz** [comment]
Because resetting rules changes rule IDs
So GLPI need to empty the 'rules_id' column in the glpi_rulematchedlog table.

**Comment by EC2311** [comment]
resetting : yes of course, but I don't understand why only deleting the rules comes in timeout, although doing that with mysql is ok.

**Comment by stonebuzz** [comment]
you don't have a PHP timeout throught Mysql

**Comment by EC2311** [comment]
yes, but in mysql it takes only 30 seconds to delete lines...

**Comment by stonebuzz** [comment]
GLPI trigger some check to do this, this consum lot of time with large DB

**Comment by trasher** [comment]
Plezase keep focused on original issue; eventually open a new one with all details for slowness.

**Comment by EC2311** [comment]
so
After reinitialize the rules at the default 
and creating ONLY the ones about computer update (legacy in fusion) : the computer is well updated
So, I would say something wrong with migrating rules ?

**Comment by EC2311** [comment]
I understand

**Comment by stonebuzz** [comment]
We're migrating the "fusion" rules to the core, but it's mainly to allow the functional administrator to run another check.

Which is the case here

The use of rules is so varied from one installation to another that it's going to be difficult to understand.

especially since your problem seems to have been solved with GLPI's native rules.

**Comment by EC2311** [comment]
Import is ok too
I close Incident
