### ISSUE TITLE
Some fields seem not to be there anymore

### ISSUE THREAD

**Issue by EC2311** [glpi-project/glpi-inventory-plugin#429]
### Describe the bug

Hello
Some fields from inventory computer are no more there
they were in operating system of each computer (with FusionInventory)

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/42341169/654a9b05-0734-4cb3-a5c1-ab1937efedb4)

there is now only date installation.

### To reproduce

Inventory of computer
the fields are well present in inventory

### Expected behavior

perhaps in a next version ?

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.10

### GLPIInventory plugin

1.3.0

**Comment by stonebuzz** [comment]
Hi EC2311

Can you check from related inventory file if 
- ```hostid``` 
- ```wincompany```
- ```winowner```
- ```oscomment```

always exist under ```operatingsystem``` "node"

**Comment by EC2311** [comment]
The fields are not under operatingsystem node, but in hardware node
the keys are : 
<WINCOMPANY>
<WINOWNER>

even in the 'old inventory file from fusion' i kept : there are no Oscomment neither hostid

**Comment by g-bougard** [comment]
`OSCOMMENTS` has been obsoleted in glpi-agent 2 years ago: [00e7b27](https://github.com/glpi-project/glpi-agent/commit/00e7b27eb7fbd62b7f7a156eeeca704cebbbaa95)
`HOSTID` can be reported for linux and solaris OS.

**Comment by EC2311** [comment]
> `OSCOMMENTS` has been obsoleted in glpi-agent 2 years ago: [00e7b27](https://github.com/glpi-project/glpi-agent/commit/00e7b27eb7fbd62b7f7a156eeeca704cebbbaa95) `HOSTID` can be reported for linux and solaris OS.

ok thanks for information @g-bougard
