### ISSUE TITLE
Unknown column 'glpi_ipaddresses_3714572b4d6732a91ac0d68a00a3c328.name' in 'where clause'

### ISSUE THREAD

**Issue by kintaro1981** [glpi-project/glpi-inventory-plugin#430]
### Describe the bug

I'm trying to create a static computer group but if put ip criteria the search fails with this message:
`Unknown column 'glpi_ipaddresses_3714572b4d6732a91ac0d68a00a3c328.name' in 'where clause'`

this is the query from the mysql server log:

```
SQL: SELECT DISTINCT `glpi_computers`.`id` AS id, 'myusername' AS currentuser,
`glpi_computers`.`entities_id`, `glpi_computers`.`is_recursive`, `glpi_computers`.`name` AS `ITEM_Computer_1`,
`glpi_computers`.`id` AS `ITEM_Computer_1_id` FROM `glpi_computers` WHERE `glpi_computers`.`is_deleted` = 0 AND `glpi_computers`.`is_template` = 0 AND ( (`glpi_ipaddresses_3714572b4d6732a91ac0d68a00a3c328`.`name` LIKE '%10.2.1%' ) ) ORDER BY `ITEM_Computer_1` ASC
```

and I think that this is going impact tasks too as they are they refer to dynamic and static groups.

### To reproduce

New static computer group
in criteria search for "ip contains"

I noticed that this is happening with all the networking's fields: ip, mac address, network names, etc.

### Expected behavior

list computers based on criteria

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.10

### GLPIInventory plugin

1.3.0

### Additional context

glpi inventory 1.3.1

**Comment by trasher** [comment]
Try if reproducible without any other plugin installed

**Comment by kintaro1981** [comment]
I disabled all the plugins except for glpi-inventory plugin and the error is still there.. have I to uninstall them instead of disable them? If yes I'm going to loose their configurations.

**Comment by trasher** [comment]
I have no idea how to reproduce

**Comment by stonebuzz** [comment]
Can you retry with latest version (1.3.3) 

Best regards

**Comment by kintaro1981** [comment]
@stonebuzz already tried with 1.3.3, same error
is it normal that the query add that kind of id? my sysadmin says that the column is glpi_ipaddresses there's no id in the table name.
![immagine](https://github.com/glpi-project/glpi-inventory-plugin/assets/2357176/a045ac77-3830-48be-8e51-0da19974be5c)

@trasher 
I wrote in the original post how to reproduce, or you can't reproduce?
The error is only in **static groups**, dynamic groups are ok.

**I uninstalled all the plugins but glpi-inventory and the error is still there.**

I've done more search trying all the fields in the criteria search, I noticed it give me unknown column not only in the networking fields category but also in:
- Assistence
example:
Unknown column 'ITEM_Computer_60' in 'having clause'
the same all the other fields
- Networking
MAC contains aa
Unknown column 'glpi_networkports.mac' in 'where clause'
or
IP contains 10.2.1
Unknown column 'glpi_ipaddresses_3714572b4d6732a91ac0d68a00a3c328.name' in 'where clause'
VLAN contains 33
Unknown column 'glpi_vlans_30b720f4ff8116eb3dfe981ed77541e0.name' in 'where clause'
the same all the other fields
- Contracts
Location contains 33
Unknown column 'ITEM_Computer_139' in 'having clause'
the same all the other fields
- Documents
Number of documents contains
Unknown column 'ITEM_Computer_119' in 'having clause'
- Financial
Invoice number contains 22
Unknown column 'glpi_infocoms.bill' in 'where clause'
- Domains
Name contains test
Unknown column 'glpi_domains_d1caf635b80e6661ec0116b04e3197c7.name' in 'where clause'
- Appliances
Name contains test
Unknown column 'glpi_appliances_5e0bf63273626cb3c8880409b2a54e7b.name' in 'where clause'
- Plugins
Modul Deploy is no
Unknown column 'FUSION_DEPLOY.is_active' in 'where clause'

**All the other fields categories are working and let me find computers and add them to the static group.**

**Comment by stonebuzz** [comment]
Hi @kintaro1981 

can you try this

https://github.com/glpi-project/glpi-inventory-plugin/pull/439

Best regards

**Comment by kintaro1981** [comment]
Yes it is working 👍
Thank you
