### ISSUE TITLE
Laptop monitor disconnection

### ISSUE THREAD

**Issue by Blank-Vcf** [glpi-project/glpi-inventory-plugin#433]
### Describe the bug

That's not really a bug or a maybe a new feature. We have laptop with usb dock and external monitors. When an inventory is send from dock all monitors are connected to computer in glpi. When inventory is send from wifi or vpn, only internal screen is reported by agent and in glpi all external monitors are disconnected.
I know they will we re connected on next inventory on dock but can't they only disconnect/reconnect when serial number is detected on another computer ?
Haven't found rules for that or a config in inventory.

### To reproduce

send inventory on dock:
```
      "monitors": [
         {
            "base64": "AP///////wAF4wEkppIAACUcAQOANR54KpEBo1VPoSYOUFS/7wDRwLMAlQCBgIFAgcABAQEBAjqAGHE4LUBYLEUADyghAAAeAAAA/wBHTlJKOUhBMDM3NTQyAAAA/AAyNFAxVzEKICAgICAgAAAA/QAyTB5TEQAKICAgICAgAdoCAx7xSxAfBRQEEwMSAhEBIwkHB4MBAABlAwwAEACMCtCKIOAtEBA+lgAPKCEAABgBHQByUdAeIG4oVQAPKCEAAB6MCtCKIOAtEBA+lgAPKCEAABiMCtCQIEAxIAxAVQAPKCEAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzQ==",
            "caption": "24P1W1",
            "description": "37/2018",
            "manufacturer": "AOC International (USA) Ltd.",
            "serial": "GNRJ9HA037542"
         },
         {
            "base64": "AP///////wAGry1WAAAAAAAcAQSlHRF4Au6Vo1RMmSYPUFQAAAABAQEBAQEBAQEBAQEBAQEBtDeAoHA4PkA6KjUAJaUQAAAatDeAoHA4XEE6KjUAJaUQAAAaAAAA/gA4NFhGN4BCMTMzSEFOAAAAAAACQQOeABEAAAoBCiAgAMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
            "caption": "84XF7",
            "description": "0/2018",
            "manufacturer": "AU Optronics",
            "serial": "00000000"
         }
      ],
      "networks": [
         {
            "description": "Intel(R) Ethernet Connection (10) I219-LM",
            "ipaddress": "10.x.x.x",
            "ipdhcp": "10.x.x.x",
            "ipgateway": "10..x.x.x",
            "ipmask": ".x.x.x",
            "ipsubnet": ".x.x.x",
            "mac": "8C:47:BE:23:13:0C",
            "pciid": "8086:0D4E:099F:1028",
            "pnpdeviceid": "PCI\\VEN_8086&DEV_0D4E&SUBSYS_099F1028&REV_00\\3&11583659&0&FE",
            "speed": "1000",
            "status": "up",
            "type": "ethernet",
            "virtualdev": false
         }
      ],

```
monitor detect and link to device
send inventory without dock
`     "monitors": [
         {
            "base64": "AP///////wAGry1WAAAAAAAcAQSlHRF4Au6Vo1RMmSYPUFQAAAABAQEBAQEBAQEBAQEBAQEBtDeAoHA4PkA6KjUAJaUQAAAatDeAoHA4XEE6KjUAJaUQAAAaAAAA/gA4NFhGN4BCMTMzSEFOAAAAAAACQQOeABEAAAoBCiAgAMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
            "caption": "84XF7",
            "description": "0/2018",
            "manufacturer": "AU Optronics",
            "serial": "00000000"
         }
      ],
      "networks": [
         {
            "description": "Intel(R) Ethernet Connection (10) I219-LM",
            "mac": "8C:47:BE:23:13:0C",
            "pciid": "8086:0D4E:099F:1028",
            "pnpdeviceid": "PCI\\VEN_8086&DEV_0D4E&SUBSYS_099F1028&REV_00\\3&11583659&0&FE",
            "status": "down",
            "type": "ethernet",
            "virtualdev": false
         },
         {
            "description": "Intel(R) Wi-Fi 6 AX201 160MHz",
            "ipaddress": "10.x.x.x",
            "ipdhcp": "10.x.x.x",
            "ipgateway": "10.x.x.x",
            "ipmask": "255.255.255.128",
            "ipsubnet": "10.x.x.x",
            "mac": "9C:29:76:42:AB:67",
            "pciid": "8086:02F0:4070:8086",
            "pnpdeviceid": "PCI\\VEN_8086&DEV_02F0&SUBSYS_40708086&REV_00\\3&11583659&0&A3",
            "speed": "721",
            "status": "up",
            "type": "wifi",
            "virtualdev": false
         }`
only laptop monitor is detect
link to dock monitor are deleted

### Expected behavior

there's no trace connection in glpi history just disconnect:
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/16317786/6bffb107-758d-4a61-a0eb-72e78f7a5702)

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.9

### GLPIInventory plugin

1.3.0

**Comment by g-bougard** [comment]
Hi @Blank-Vcf 

to be honest, what's wrong in that comportment ? To me, if the computer is not docked, the dock connected monitor is not seen by the computer. So it won't be inventoried. And the change is just telling you the computer is not docked. This looks like GLPI works the way it should: in another word, this is a feature.

If you don't want the dock monitor to be disconnected each time an inventory is made while it is no more connected, you should probably have to make it static. But you will go against the automatic inventory principle that way.

**Comment by g-bougard** [comment]
Maybe setting an attribute like "Last connected computer" on the monitor could be more useful when it is no more connected.

**Comment by Blank-Vcf** [comment]
> Hi @Blank-Vcf
> 
> to be honest, what's wrong in that comportment ? To me, if the computer is not docked, the dock connected monitor is not seen by the computer. So it won't be inventoried. And the change is just telling you the computer is not docked. This looks like GLPI works the way it should: in another word, this is a feature.
> 
> If you don't want the dock monitor to be disconnected each time an inventory is made while it is no more connected, you should probably have to make it static. But you will go against the automatic inventory principle that way.

I'm agree with that, it's just my workmate old habit with ocsng. Maybe just missing in history the connection of the monitor to the computer.

**Comment by stonebuzz** [comment]
Hi @Blank-Vcf 

this https://github.com/glpi-project/glpi/pull/16222

should add ```history``` entry when an item is connected to computer (ie: Monitor)

Best regards

**Comment by stonebuzz** [comment]
I close as the fix (https://github.com/glpi-project/glpi/pull/16222) is merged into GLPI

Best regards
