### ISSUE TITLE
GLPI-Agents displays 0 if they cannot obtain the ITEM

### ISSUE THREAD

**Issue by andsong88** [glpi-project/glpi-inventory-plugin#434]
### Describe the bug

GLPI-Agents displays 0 if they cannot obtain the ITEM

### To reproduce

GLPI-Agents displays 0 if they cannot obtain the ITEM

### Expected behavior

GLPI-Agents displays 0 if they cannot obtain the ITEM

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.9

### GLPIInventory plugin

1.2.3

### Additional context

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/149749447/23d7614b-59ff-4112-97b7-28254197ec40)

**Comment by trasher** [comment]
Please provide details to reproduce.

**Comment by steph461** [comment]
Maybe When I start a task I get this error message ( ITEM)
my stack example : 
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/68054991/a68189d9-59a4-4cd3-a155-4b6b2b62aa77)


[2023-11-06 12:29:02] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid item "Agent" (1009). in /var/www/html/glpi/marketplace/glpiinventory/inc/taskview.class.php at line 1000
  Backtrace :
  ...place/glpiinventory/inc/taskview.class.php:1000 trigger_error()
  ...tplace/glpiinventory/inc/taskview.class.php:832 PluginGlpiinventoryTaskView->getAgentsFromActors()
  marketplace/glpiinventory/inc/task.class.php:622   PluginGlpiinventoryTaskView->prepareTaskjobs()
  src/CronTask.php:1018                              PluginGlpiinventoryTask::cronTaskscheduler()
  front/cron.php:84                                  CronTask::launch()

**Comment by stonebuzz** [comment]
Agent with ID 1009 no longer exist from your GLPI (can you check it ?)

Then fix task (update related agent) and rerun job

**Comment by steph461** [comment]
> Agent with ID 1009 no longer exist from your GLPI (can you check it ?)
> 
> Then fix task (update related agent) and rerun job

I saw the name of the agent to change
its was good

I have on SQL error message in the 1.3.2 , I upgraded to version 1.3.3 its was ok. I must have made a mistake when I changed my name :)

thx stonebuzz
