### ISSUE TITLE
[Update process] Error on update from 1.3.1 to 1.3.2 

### ISSUE THREAD

**Issue by keguira** [glpi-project/glpi-inventory-plugin#436]
### Describe the bug

During update process, on my test-environment, i got the following error message in the interface :

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/453169/fea8cbb7-13a0-42c7-b924-753cd7451fdb)

From php.log, i have this error :

```
[2023-11-03 15:20:49] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method DB::doQueryOrDie() in /home/glpi/public_html/glpi-10.0.10/marketplace/glpiinventory/install/update.native.php at line 388
  Backtrace :
  marketplace/glpiinventory/hook.php:405             pluginGlpiinventoryUpdateNative()
  src/Plugin.php:915                                 plugin_glpiinventory_install()
  :                                                  Plugin->install()
  src/Marketplace/Controller.php:545                 call_user_func()
  src/Marketplace/Controller.php:435                 Glpi\Marketplace\Controller->setPluginState()
  ajax/marketplace.php:82                            Glpi\Marketplace\Controller->installPlugin()
  public/index.php:82                                require()

```

I'm trying to update from 1.3.1 to 1.3.2

### To reproduce

1. Download update from market place
2. Click on update 

### Expected behavior

The update is processed correctly and applied without error

### Operating system

Linux

### GLPI Agent version

1.5

### GLPI version

10.0.10

### GLPIInventory plugin

1.3.1 to 1.3.2

### Additional context

Server is 
* debian 
* php 8.1
* mysql 8.0

**Comment by Gor3pig** [comment]
I confirm. Same thing here 👍 

![Bug](https://github.com/glpi-project/glpi-inventory-plugin/assets/42821532/41a04183-820c-46e9-8b61-8be7ddab0c10)

**Comment by trasher** [comment]
As a quick fix, replace `doQueryOrDie` with `queryOrDie` in `install/update.netiv.php` file.

UI issue is yet another problem...

**Comment by trasher** [comment]
(bug introduced in #431)

**Comment by keguira** [comment]
> As a quick fix, replace `doQueryOrDie` with `queryOrDie` in `install/update.netiv.php` file.
> 
> UI issue is yet another problem...

ok, i confirm this fixed the update process.
