### ISSUE TITLE
Restrict agents to send data on server side.

### ISSUE THREAD

**Issue by felamachado** [glpi-project/glpi-inventory-plugin#438]
I have a concern regarding security. With the default configuration of the GLPI server, anyone with the server link can inject unwanted data.

Even after installing the GLPI Inventory plugin, the situation remains unchanged.

I can't find anywhere how to configure the security aspect and prevent unwanted agents from sending information about undesired equipment.

I understand that a possible solution could be to add a rule that disregards records that don't have a TAG, but this seems to me not very rigorous, as the sending to the server is already done and it could constitute a potential attack on the server, a saturation of resources, or some other security breach.

Other possible solution can be [this one](https://github.com/glpi-project/glpi-agent/discussions/271#discussion-4593275) but it seems a bit rudimentary. 

I have also tried this solution, adding to the file

`/etc/apache2/sites-available/000-default.conf`

the line:

`RewriteRule ^ocsinventory - [F,L]`

And indeed, it prevents agents from sending information, but then I can't enable the agents that I actually DO want to send data.

I haven't found documentation on security aspects or the protocol used. I understand this is an important aspect.

I would appreciate it if you could provide information on these aspects and especially on how to restrict the server so that unwanted agents don't send information.

**Comment by trasher** [comment]
This issue has been closed as we only track bugs here.
            
You can get community support on [forums](https://forum.glpi-project.org/) or you can consider [taking a subscription](https://glpi-project.org/subscriptions/) to get professional support.
You can also [contact GLPI editor team](https://portal.glpi-network.com/contact-us) directly.
