### ISSUE TITLE
API REST "ERROR_GLPI_ADD" "You do not have the required rights to perform this action."

### ISSUE THREAD

**Issue by HugzWaaa** [glpi-project/glpi-inventory-plugin#442]
### Describe the bug

I'm trying to create dynamic groups on GLPI 10.0. 8 thanks to the REST API, I managed to create a Dynamic group via API but now I'm trying to modify the criteria of a group using the API, so I did a GET on the URL of the criteria for dynamic groups to see what I need to modify so that the criteria fits my needs, so far no problem, the problem occurs when I try to make a POST to modify the criteria of a dynamic group, the GLPI returns the error "ERROR_GLPI_ADD" "You do not have the required rights to perform this action. "So I went to see what rights the user I'm using with the API has and I replaced the current authorization with "super-admin" and gave ALL rights to the "super-admin" authorization to make sure that GLPI no longer sends me back "You do not have the required rights to perform this action. "But the error persists, I've logged in with the account I use for the API to add a criterion manually from the GLPI interface and I haven't encountered any error, what can I do to fix this problem?

 For all: 
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/a9c90813-b183-423e-989a-cb924e6d663d)

### To reproduce

I'm trying to create dynamic groups on GLPI 10.0. 8 thanks to the REST API, I managed to create a Dynamic group via API but now I'm trying to modify the criteria of a group using the API, so I did a GET on the URL of the criteria for dynamic groups to see what I need to modify so that the criteria fits my needs, so far no problem, the problem occurs when I try to make a POST to modify the criteria of a dynamic group, the GLPI returns the error "ERROR_GLPI_ADD" "You do not have the required rights to perform this action. "So I went to see what rights the user I'm using with the API has and I replaced the current authorization with "super-admin" and gave ALL rights to the "super-admin" authorization to make sure that GLPI no longer sends me back "You do not have the required rights to perform this action. "But the error persists, I've logged in with the account I use for the API to add a criterion manually from the GLPI interface and I haven't encountered any error, what can I do to fix this problem?

 For all: 
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/a9c90813-b183-423e-989a-cb924e6d663d)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/fcfe6611-c4c7-43d6-8ba0-a6bb5f896195)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/c0685645-4d52-4343-86b4-01d5f5feef57)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/7c266744-9787-42f0-9bef-21d4cba310fd)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/0312be96-50dc-4f18-b7ab-d2c099db3e3a)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/8deed889-e29d-4ba7-9466-7d149742edc8)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/3f1a7739-f123-488e-a957-173c431806f1)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/3d597a58-2d0d-4f0a-957d-57c07523a3c3)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/c67449a4-3996-4b97-b946-ccc3b8f12804)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/7a86cebe-6c91-4aa8-837a-4522fbc2bca3)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/e0d00f3e-77ee-4e94-8649-865443829be4)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/d2d6ffac-853e-4964-90d6-f96872d3172d)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/2cac1bea-2e40-4fc5-983e-54e4d67ab563)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/7a53164f-45ec-422c-8d97-6ae38dec955a)

### Expected behavior

that if I give ALL existing rights to the API user, I no longer get the error "You do not have the required rights to perform this action."

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.8

### GLPIInventory plugin

1.3.0

**Comment by HugzWaaa** [comment]
I also made a "getActiveProfile" request to make sure my user had taken the "super-admin" profile, which has ALL rights

**Comment by stonebuzz** [comment]
Hi @HugzWaaa 
can you post your code here (which updates the group dynamic) ?

**Comment by HugzWaaa** [comment]
Hi, of course, 
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/9e914fc1-a924-4258-a1dd-861bbe830b92)
so i create the input parrameter like:
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/487d2402-2011-4d41-91c6-fe0e9ec96bc9)


 msg.payload = {
        "input":
        {
            "fields_array": 'a:2:{s:8:"criteria";a:1:{i:0;a:6:{s:4:"link";s:3:"AND";s:8:"itemtype";s:8:"Location";s:4:"meta";s:1:"1";s:5:"field";s:1:"1";s:10:"searchtype";s:6:"equals";s:5:"value";s:3:"249";}}s:12:"metacriteria";a:0:{}}'
           
        }
    }

**Comment by HugzWaaa** [comment]
and I POST this on this endpoint "http://xxx.xxx.xxx.xxx/apirest.php/PluginGlpiinventoryDeployGroup_Dynamicdata"

**Comment by stonebuzz** [comment]
You need to set related object ID to your endpoint

http://xxx.xxx.xxx.xxx/apirest.php/PluginGlpiinventoryDeployGroup_Dynamicdata/##AN_ID##

**Comment by stonebuzz** [comment]
to update it

**Comment by HugzWaaa** [comment]
I've tried two different ways, http://xxx.xxx.xxx.xxx/apirest.php/PluginGlpiinventoryDeployGroup_Dynamicdata/15 and http://xxx.xxx.xxx.xxx/apirest.php/PluginGlpiinventoryDeployGroup_Dynamicdata/&id=15 but neither of the 2 works (the glpi returns "You do not have the required rights to perform this action").

**Comment by HugzWaaa** [comment]
I've also tried to replace POST with PUT because PUT is more used for update, and the request no longer returns an error, but the criterion is not created in the group

**Comment by stonebuzz** [comment]
URL have been cleaned (by PHP or GLPI) with ```[urlencode](https://www.php.net/manual/fr/function.urlencode.php)```

(for (among others) security)

I therefore advise you not to rely on the URL.

I'd rather do my filter in GLPI, then check the added value in the database (cleaned / serialized) and use it for API request

**Comment by HugzWaaa** [comment]
Thanks for your reply, but I don't understand what I should do  ;(

**Comment by HugzWaaa** [comment]
nothing to do with that?
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/a5d23e7d-2033-4c0d-98bb-de0e087db5aa)

**Comment by stonebuzz** [comment]
No it's for internal use.

**Comment by stonebuzz** [comment]
For "You do not have the required rights to perform this action"

can you run this SQL query and post result here

```sql
MariaDB [10bugfixes]> select * from glpi_profilerights where profiles_id = 4 and name = 'plugin_glpiinventory_group';
+-----+-------------+----------------------------+--------+
| id  | profiles_id | name                       | rights |
+-----+-------------+----------------------------+--------+
| 788 |           4 | plugin_glpiinventory_group |     31 |
+-----+-------------+----------------------------+--------+

```

**Comment by HugzWaaa** [comment]
Yes of course:
	id	profiles_id	name	rights
	1388	4	plugin_glpiinventory_group	23

**Comment by stonebuzz** [comment]
```right``` => ```21``` correspond to this


![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/7335054/e34664ed-a73d-4f22-ba12-4727e67a0c55)


```sql
MariaDB [10bugfixes]> select * from glpi_profilerights where profiles_id = 4 and name = 'plugin_glpiinventory_group';
+-----+-------------+----------------------------+--------+
| id  | profiles_id | name                       | rights |
+-----+-------------+----------------------------+--------+
| 788 |           4 | plugin_glpiinventory_group |     21 |
+-----+-------------+----------------------------+--------+

```

Can you (re)check the profile/user rights used by the API client?

If necessary, can you run the following GLPI command (at the root of GLPI)

```php bin/console cache:clear```

**Comment by HugzWaaa** [comment]
I double-checked the super-admin profile 
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/03d22aa3-8b86-4b73-8294-c1f87af1551a)
My user is a super-admin
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/c266b93a-f3e4-4c75-b539-195233c89286)
I can confirm this by making a "getActiveProfile" request to make sure it uses the super-admin profile. Here is what the request says: 
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/98757a5d-b463-475a-b3ed-2bc6be7b54ff)
And I've RUN the command you gave me as you asked and I've restarted the request but the error still persists.
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/2fa084de-1c0b-4651-aacd-279a128f7af7)

**Comment by stonebuzz** [comment]
Can you "uncheck" then "check" the right "update" and save the profile? 

Then retry (and check from database value with last SQL query)

**Comment by HugzWaaa** [comment]
I have unchecked all rights 
 
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/f75b10cf-009e-4330-9d7e-f3e307d7cfcf)

I restarted the order 
 
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/dfe190d2-e64f-4109-b97c-3c22f8db6b7b)


Then I checked the rights again
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/b06f3310-4502-4126-b7f0-577110c68abe)

 
And I restarted the order but I still get the same result
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/2b402d2a-216f-4a00-8d8d-b5c35d6eb328)

I did save the profile from GLPI after each modification

**Comment by stonebuzz** [comment]
are you sure you're on the right database, on the right GLPI?

Un check all rights give this result from SQL query 

```sql
MariaDB [10bugfixes]> select * from glpi_profilerights where profiles_id = 4 and name = 'plugin_glpiinventory_group';
+-----+-------------+----------------------------+--------+
| id  | profiles_id | name                       | rights |
+-----+-------------+----------------------------+--------+
| 788 |           4 | plugin_glpiinventory_group |      0 |
+-----+-------------+----------------------------+--------+
1 row in set (0,000 sec)
```

**Comment by HugzWaaa** [comment]
I thought so but apparently not, now that I've told him to use the right base, I'm behaving like you.
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/db8756df-63b2-45df-a767-35163d5a873b)
but the request always returns the same error even after rechecking.

**Comment by HugzWaaa** [comment]
I have check again, 
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/0bf2007c-11aa-4e6c-a137-5f81a05796c9)
I re-launched the request
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/e4bc996e-2308-483e-af4c-0685f4747a3f)

**Comment by stonebuzz** [comment]
before going any further, we need to

- Update your GLPI to latest version (10.0.10)
- Update glpiinventory plugin to latest version (1.3.3)

To make sure you have the latest version of the fixes

**Comment by HugzWaaa** [comment]
Okay no worries I'll look into updating the plugin and GLPI I'll get back to you when I have news.

**Comment by HugzWaaa** [comment]
hello sir, I've updated the plugin and GLPI but the rights problem still persists.
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/520e0c08-82c3-462f-b223-f9c48f2d2088)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/d92cd2c3-6380-40f8-a75c-0986a4d95c03)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/b45eec1e-83f0-404c-837f-8d2d0eccee06)

**Comment by HugzWaaa** [comment]
I don't know how GLPI works at all, but if checking this box means that you have the right to access the "PluginGlpiinventoryDeployGroup" class, that's right, but this box must also allow you to access the "PluginGlpiinventoryDeployGroup_Dynamicdata" class to be able to modify the criteria of a dynamic group.
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/113598277/79b274a7-75de-491d-ad5d-04ca826bf51f)

**Comment by stonebuzz** [comment]
Hi @HugzWaaa  

"PluginGlpiinventoryDeployGroup_Dynamicdata" right depends on this checkbox =)


I'm not sure how to help you, since I don't reproduce on my side (with basic curl call).

Perhaps you should consider taking out a subscription to benefit from professional support.
This would allow me (among other things) to take control of your instance for debugging purposes.

**Comment by trasher** [comment]
Since we cannot reproduce; and existing data is certainly faulty; I close.

Feel free to reopen if you can provide a use case reproducing issue on a fresh install.
