### ISSUE TITLE
This plugin requires GLPI version >= 10.0.10 and < 10.0.99.

### ISSUE THREAD

**Issue by bajosega** [glpi-project/glpi-inventory-plugin#444]
### Describe the bug

This plugin requires GLPI version >= 10.0.10 and < 10.0.99.

When attempting to install on GLPI 10.0.9, I receive this message and it does not allow me to proceed, even though the plugin states that it is compatible with 10.0.x.

### To reproduce

Access GLPI.
Navigate to Plugins.
Attempt to install the plugin.

### Expected behavior

It should allow the installation of the plugin or, failing that, be more specific about the version requirements that might be incorrect.

### Operating system

Linux

### GLPI Agent version

Other (See additional context below)

### GLPI version

10.0.9

**Comment by cedric-anne** [comment]
Hi,

Your GLPI version is 10.0.9, that is not `>= 10.0.10`, so the message seems correct.

> even though the plugin states that it is compatible with 10.0.x

Where did you find this information. We should indeed fix it.

**Comment by bajosega** [comment]
> Hi,
> 
> Your GLPI version is 10.0.9, that is not `>= 10.0.10`, so the message seems correct.
> 
> > even though the plugin states that it is compatible with 10.0.x
> 
> Where did you find this information? We should indeed fix it.

Hi, in the description here is where it says compatible with 10.0.x.
[https://github.com/glpi-project/glpi-inventory-plugin/releases/tag/1.3.3](url) 
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/8278087/e300bfad-5ce0-48f4-9079-d196049b0acc)

**Comment by cedric-anne** [comment]
Fixed:

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/33253653/cbea22de-76c7-40c6-962c-a8e1f18e9955)
