### ISSUE TITLE
GLPI-Agent can't link item and obtain 0

### ISSUE THREAD

**Issue by procajlok** [glpi-project/glpi-inventory-plugin#447]
### Describe the bug

After uninstall FusionInventory and install GLPI-Inventory, inventory from new GLPI-Agent can't be linked to existing equipment (computer) and set ITEM to 0. Attached AgentLOG, rules export (in ZIP) and screens from inventory. If I delete existing Computer and force new inventory, they create new equipment and linked correctly.
[rules (2).zip](https://github.com/glpi-project/glpi-inventory-plugin/files/13453601/rules.2.zip)
[glpi-agent.log](https://github.com/glpi-project/glpi-inventory-plugin/files/13453622/glpi-agent.log)

![obraz](https://github.com/glpi-project/glpi-inventory-plugin/assets/33727231/c9f1b236-04b4-4272-86b1-f85d15ad8296)
![obraz](https://github.com/glpi-project/glpi-inventory-plugin/assets/33727231/818ba2e4-d5a1-4cd6-bde8-e46e6b50cdda)
![obraz](https://github.com/glpi-project/glpi-inventory-plugin/assets/33727231/5f44c097-56ad-4a1e-ac9b-136e40ac582d)

![obraz](https://github.com/glpi-project/glpi-inventory-plugin/assets/33727231/d21eadf3-1edf-43fd-8905-a51f0b2743e0)
![obraz](https://github.com/glpi-project/glpi-inventory-plugin/assets/33727231/baab6838-c642-4ce9-9488-9ac98ff2b5d3)
![obraz](https://github.com/glpi-project/glpi-inventory-plugin/assets/33727231/34cc6cb6-1601-4d65-83a1-ecff2e8c8859)

### To reproduce

1. Have existing computer equipments inventoried from FusionInventory
2. Uninstall FusionInventory
3. Install on computer new GLPI-Agent
4. Force inventory
5. Give ITEM 0 on inventory.

### Expected behavior

Want link new agent and inventory to existing equipment.

### Operating system

Windows

### GLPI Agent version

Other (See additional context below)

### GLPI version

10.0.10

### GLPIInventory plugin

1.3.0

### Additional context

GLPI Inventory: 1.3.3 from marketplace.
Uninstalled FusionInventory: 10.0.6+1.1
GLPI-agent 1.6.1

**Comment by procajlok** [comment]
Heh... I enable for a while FusionInventory, and now see this computer, linked to existing equipment but only in Fusion-Agents list:
![obraz](https://github.com/glpi-project/glpi-inventory-plugin/assets/33727231/2d0536de-b2dd-4eb6-ae34-308e52f78a02)

But still no in native GLPI Agents list:
![obraz](https://github.com/glpi-project/glpi-inventory-plugin/assets/33727231/35419889-46d4-4d39-b443-bdc0f25429ee)

**Comment by stonebuzz** [comment]
You say you uninstalled FusionInventory, then reactivated the plugin.

I'm confused

If you have uninstalled FusionInventory you should no longer have any data.


To migrate easily to the native inventory and the GLPIInventory plugin, we recommend the following procedure

Put the Glpiinventory plugin in the GLPI "plugin" ("marketplace") folder.

Then delete the FusionInventory folder 

Then install the Glpiinventory plugin

The installation procedure will migrate the FusionInventory data either to the core (e.g. Agent) or to the Glpiinventory plugin.

**Comment by procajlok** [comment]
U see on screenshots, in plugin list i still have FusionInventory, but not installed (folder icon with plus - for install) and deactivated. For a while, after 5h fighting with that i checked what happens if revert this - disable GLPIInventory and install and enable FusionAgent (and of course change server address in GLPIAgent on workstation).

OK - i'll check this method. Uninstall and deactivate FusionInventory, delete Fusion folder and install GLPIInventory.

**Comment by procajlok** [comment]
But... problem i think is in the inventory and link it to existing Computer object.... 😢

**Comment by stonebuzz** [comment]
your agent always points to fusion path, or did you change the "server" directive in the configuration ?

**Comment by procajlok** [comment]
Of course i change it in Windows Regedit. After installation GLPIInventory, agents send data to _http://glpi.domain.pl/marketplace/glpiinventory_
U see all of data with debug2 in attachement on post.

**Comment by procajlok** [comment]
In i see this, that no problem? 
```
[Thu Nov 23 22:45:29 2023][info] running task Collect
[Thu Nov 23 22:45:29 2023][debug2] [http client] Not using compression
[Thu Nov 23 22:45:29 2023][debug2] http://glpi.sp7wolomin.pl/marketplace/glpiinventory?action=getConfig&task[Collect]=2.9&machineid=S69-P02.szkola.local-2023-11-23-20-05-52
[Thu Nov 23 22:45:29 2023][info] No Collect job enabled or Collect support disabled server side.
[Thu Nov 23 22:45:30 2023][info] running task Deploy
[Thu Nov 23 22:45:30 2023][debug2] [http client] Not using compression
[Thu Nov 23 22:45:30 2023][debug2] http://glpi.sp7wolomin.pl/marketplace/glpiinventory?action=getConfig&task[Deploy]=3.0&machineid=S69-P02.szkola.local-2023-11-23-20-05-52
**[Thu Nov 23 22:45:30 2023][info] No Deploy job enabled or Deploy support disabled server side.**
[Thu Nov 23 22:45:30 2023][info] running task Inventory
[Thu Nov 23 22:45:30 2023][info] New inventory from S69-P02.szkola.local-2023-11-23-20-05-52 for server0
```

**Comment by procajlok** [comment]
> OK - i'll check this method. Uninstall and deactivate FusionInventory, delete Fusion folder and install GLPIInventory.

Done this and have situation when Agents writing to the server, and still no linked to existing equipment:
![obraz](https://github.com/glpi-project/glpi-inventory-plugin/assets/33727231/2c202500-2bb8-4e90-9ba9-2aaa26074dff)

Have Inventory enable:
![obraz](https://github.com/glpi-project/glpi-inventory-plugin/assets/33727231/de29cc89-afc3-4edb-b673-67e09a210cb6)

**Comment by procajlok** [comment]
Soo,  have other question - where i can see the LOG's on server site about inventory, rules processing and other?

**Comment by g-bougard** [comment]
Hi @procajlok 
in your agent journal, I can see this in response to the inventory submission:
```
[Thu Nov 23 22:41:32 2023][error] [http client] communication error: 500 Internal Server Error, Call to a member function bind_param() on bool
[Thu Nov 23 22:41:32 2023][debug2] format: Zlib
[Thu Nov 23 22:41:32 2023][debug2] [http client] F58CE9FB: received message:
{"status":"error","message":"Call to a member function bind_param() on bool","expiration":24}
[Thu Nov 23 22:41:32 2023][error] [http client] F58CE9FB: server error: Call to a member function bind_param() on bool
```
I don't know where it can come from, but something is preventing the process to work properly.

**Comment by procajlok** [comment]
As I understand, this error came to AgentLog from server site, not agent? 

I have GLPI on XAMPP, and generally don't have any problems with system (other problems, errors etc.). Maybe GLPI require for agent some extra libraries?

**Comment by procajlok** [comment]
I try manual import XML to inventory,  and have the same error! "Call to a member function bind_param()"

**Comment by g-bougard** [comment]
This probably just means you have wrong datas in your database after the migration and this leaves GLPI triggers that error. Or eventually you may also have a plugin which triggers that error: can you try to disable all enabled plugin but GlpiInventory ?

**Comment by procajlok** [comment]
I don't have any other plugins. How we can check what provide this error - logs on server maybe?

**Comment by stonebuzz** [comment]
Look at GLPI log files (glpi/files/_logs/  php-error.log and sql-error.log) during manual import 
and past here stacktrace.

**Comment by procajlok** [comment]
Hmm, import from XML not generate php-error in logs, but i have a lot of errors in SQL...
[sql-errors.log](https://github.com/glpi-project/glpi-inventory-plugin/files/13457673/sql-errors.log)

**Comment by g-bougard** [comment]
This only shows glpi_logs table has not been created. Thus, the only clue this gives us is your migration didn't work well. Do you remember if you had any error during migration ? Can you also tell us from which GLPI version you migrated ? Did you make it with some steps ?

**Comment by procajlok** [comment]
Okayy, but, there we see Rule Action - Inventory link Assign Import denied (no log) (198)   😐
For unknown reasons, this rules don't update existing objects...

```
[2023-11-23 20:58:50] glpisqllog.ERROR: DBmysql::query() in C:\xampp\htdocs\glpi\public\src\DBmysql.php line 379
  *** MySQL query error:
  SQL: INSERT INTO `glpi_logs` (`items_id`, `itemtype`, `itemtype_link`, `linked_action`, `user_name`, `date_mod`, `id_search_option`, `old_value`, `new_value`) VALUES ('187', 'RuleImportAsset', 'RuleAction', '17', 'Procajło Krzysztof (2)', '2023-11-23 20:58:43', '0', '', 'Inventory link Assign Import denied (no log) (198)')
  Error: Table 'glpi.glpi_logs' doesn't exist
  Backtrace :
  src\DBmysql.php:1348                               
  src\Log.php:280                                    DBmysql->insert()
  src\CommonDBChild.php:531                          Log::history()
  src\RuleAction.php:122                             CommonDBChild->post_addItem()
  src\CommonDBTM.php:1324                            RuleAction->post_addItem()
  src\Rule.php:3691                                  CommonDBTM->add()
  front\rule.common.php:58                           Rule::initRules()
  front\ruleimportasset.php:40                       include()
  public\index.php:82                                require()
  {"user":"2@SERWER01","mem_usage":"0.006\", 44.19Mio)"} 
```

> Do you remember if you had any error during migration ? Can you also tell us from which GLPI version you migrated ? Did you make it with some steps ?

Hmm, don't remember... I remember migration from 9.5 to 10.0.6 and from this to 10.0.10.

**Comment by trasher** [comment]
Having SQL errors in the middle of any process may have unexpected effects. There are very few chances this will fix your issue, but it's something that **must** be fixed anyway.

**Comment by procajlok** [comment]
You're great! I create glpi_logs table and everything works OK 😎
![obraz](https://github.com/glpi-project/glpi-inventory-plugin/assets/33727231/162bdf03-7570-465f-a004-316a6a990210)

Thank You so much for your time, have great day!

For others, if anyone search similar problem - there is code for create glpi_logs table:
```
DROP TABLE IF EXISTS `glpi_logs`;
CREATE TABLE `glpi_logs` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `itemtype` varchar(100) NOT NULL DEFAULT '',
  `items_id` int unsigned NOT NULL DEFAULT '0',
  `itemtype_link` varchar(100) NOT NULL DEFAULT '',
  `linked_action` int NOT NULL DEFAULT '0' COMMENT 'see define.php HISTORY_* constant',
  `user_name` varchar(255) DEFAULT NULL,
  `date_mod` timestamp NULL DEFAULT NULL,
  `id_search_option` int NOT NULL DEFAULT '0' COMMENT 'see search.constant.php for value',
  `old_value` varchar(255) DEFAULT NULL,
  `new_value` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date_mod` (`date_mod`),
  KEY `itemtype_link` (`itemtype_link`),
  KEY `item` (`itemtype`,`items_id`),
  KEY `id_search_option` (`id_search_option`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
```
