### ISSUE TITLE
Problem in getting readings from the registry

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi-inventory-plugin#46]
There are errors in tasks/groups.
This issue was discovered while solving the problem of data collection jobs failing here https://github.com/glpi-project/glpi-agent/issues/56 .
Here are the screenshots of the task settings themselves.
![1](https://user-images.githubusercontent.com/97535165/151758185-6f7422c7-3fdc-40d5-bd44-c8734bac3819.png)
![2](https://user-images.githubusercontent.com/97535165/151758189-f13496c2-c217-413f-83be-00d8353a5761.png)
![3](https://user-images.githubusercontent.com/97535165/151758190-cf800d56-8aa7-47d4-9c9c-a0bf5ef98289.png)
![4](https://user-images.githubusercontent.com/97535165/151758191-050caad3-8383-4eac-8638-1e07405b83b3.png)
![5](https://user-images.githubusercontent.com/97535165/151758192-b0e3eac6-ac58-41b9-8988-821a485551c9.png)

**Comment by Badkempachi** [comment]
@trasher The problem remained, I installed the latest version of the agent 1.1-git1d9ab8e9, but I still have the status prepared and no further changes. I did not see any errors in the agent log, but I did not see the log of the completed task either.
[agent log.txt](https://github.com/glpi-project/glpi-inventory-plugin/files/7987100/agent.log.txt)

**Comment by g-bougard** [comment]
Hi @Badkempachi 
in your agent_log, the agent didn't contact the server so the task didn't run.
Check this line:
```
[Wed Feb  2 09:49:19 2022][info] target server0: next run: Thu Feb  3 09:13:57 2022 - https://glpi.localhost.ru/marketplace/glpiinventory
```
It means the agent will contact server0 tomorrow unless you force the run. So this is normal you think the problem remains.
Try from the agent computer to access the `http://127.0.0.1:62354/` page within a browser and click on "Run now". Then wait a little and check agent_log.

**Comment by g-bougard** [comment]
Anyway you don't need to run the agent if you really applied the patch from 71b2b0c as it only fixes UI warnings.

**Comment by Badkempachi** [comment]
> Hi @Badkempachi in your agent_log, the agent didn't contact the server so the task didn't run. Check this line:
> 
> ```
> [Wed Feb  2 09:49:19 2022][info] target server0: next run: Thu Feb  3 09:13:57 2022 - https://glpi.localhost.ru/marketplace/glpiinventory
> ```
> 
> It means the agent will contact server0 tomorrow unless you force the run. So this is normal you think the problem remains. Try from the agent computer to access the `http://127.0.0.1:62354/` page within a browser and click on "Run now". Then wait a little and check agent_log.

I may have misunderstood, but the task has a separate execution timer, and it can itself wake up the agent for, for example, executing the data collection function, right?
But even if my reasoning above was not correct, in any case, forcing the inventory did not change the status of the task.


log agent:
[Wed Feb  2 17:43:51 2022][debug2] format: Zlib
[Wed Feb  2 17:43:51 2022][debug2] [http client] D0E1F713: received message:
{"expiration":24,"status":"ok"}
[Wed Feb  2 17:43:52 2022][debug] new thread 21 to handle task RemoteInventory
[Wed Feb  2 17:43:52 2022][debug] Remote inventory task execution disabled: no remote set
[Wed Feb  2 17:43:52 2022][info] target server0: next run: Thu Feb  3 17:21:56 2022 - https://glpi.localhost.ru/marketplace/glpiinventory
[Wed Feb  2 17:43:52 2022][debug] Agent memory usage before freeing memory: WSS=158670848 PFU=175337472
[Wed Feb  2 17:43:52 2022][info] GLPI Agent memory usage: WSS=3260416 PFU=175337472

**Comment by g-bougard** [comment]
As I understand, you didn't apply 71b2b0c patch.
Anyway as @trasher pushed 71b2b0c commit, this means there's a patch you still can apply manually server-side other glpiinventory code. If you don't feel easy enough to apply yourself the patch, just wait next release as the patch will be included.

**Comment by Badkempachi** [comment]
> As I understand, you didn't apply [71b2b0c](https://github.com/glpi-project/glpi-inventory-plugin/commit/71b2b0cd94abcff71a48a29361c8e9edeaa3bdab) patch. Anyway as @trasher pushed [71b2b0c](https://github.com/glpi-project/glpi-inventory-plugin/commit/71b2b0cd94abcff71a48a29361c8e9edeaa3bdab) commit, this means there's a patch you still can apply manually server-side other glpiinventory code. If you don't feel easy enough to apply yourself the patch, just wait next release as the patch will be included.

Yes, indeed, the respected @trasher indicated what needs to be done, and I did it and the errors were gone, but I still could not see the results of the completed tasks. Today I updated glpi master.16615cb.tar.gz, but this did not bring any result and my request was closed. For this reason, I again turned to you again.

**Comment by g-bougard** [comment]
Then this is another problem, please open a new issue in glpi-agent joining your agent_log where we see the Collect task is running.
We should not discuss about side problem here as this issue is really fixed.
