### ISSUE TITLE
500 Internal Server Error, Key drives is not handled in network devices conversion

### ISSUE THREAD

**Issue by Stijn-weather** [glpi-project/glpi-inventory-plugin#462]
### Describe the bug

When running glpi-injector on an .xml file generated by the netdiscovery tool, the device does not get added to our inventory and we get this error.
Device is not inventoried at all. Not under "unmanaged devices", nor "Equipments refused by rules log"

### To reproduce

sudo glpi-netdiscovery --host 192.168.16.232 --credentials version:2c,community:public --debug -i -s .

sudo glpi-injector -f ./netinventory/192.168.16.232.xml -u https://our-glpi-inventory.com/ --debug -vv 

### Expected behavior

The device would show up under "Network Devices"
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/132081310/a2b01059-d915-410d-b126-e90d8d180196)

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below), Other (See additional context below)

### GLPI version

10.0.10

### GLPIInventory plugin

1.3.4, Other (See additional context below)

### Additional context

GLPI Agent (1.7-git6961b4c7)
- NetInventory (v6.0)
- NetDiscovery (v6.0)

**Comment by trasher** [comment]
Will be fixed in next glpi release; see https://github.com/glpi-project/glpi/pull/16408
