### ISSUE TITLE
Software inventory doesn't update the install_date

### ISSUE THREAD

**Issue by Frflamingo** [glpi-project/glpi-inventory-plugin#463]
### Describe the bug

On windows (Glpi Agent 1.7.1)

Install SW1 at date1
Run Inventory task
Result = SW1 shown for date1 : OK
Reinstall SW1 at date2
Run Inventory task
Result = SW1 shown for date1 : KO

Agent is reporting/uploading correctly 
The inventory file on server is showing correct information, i.e. : 

>   {
>                 "arch": "i586",
>                 "from": "registry",
>                 "guid": "XXXX",
>                 "install_date": "2024-01-29",
>                 "name": "XXXX",
>                 "publisher": "XXXX",
>                 "system_category": "application",
>                 "uninstall_string": "N\/A",
>                 "version": "1.0"
>             }

But UI/DB is reporting the wrong install_date , it keeps the first occurrence i.e. :
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/120394273/f4647973-793c-4b19-8fdf-a043621295b5)

Some details can be found here 
https://github.com/glpi-project/glpi-agent/issues/593

### To reproduce

Install SW1 at date1
Run Inventory task
Result = SW1 shown for date1 : OK
Reinstall SW1 at date2
Run Inventory task
Result = SW1 shown for date1 : KO

### Expected behavior

Installation date should be refreshed at each inventory ie should be date2

### Operating system

Windows

### GLPI Agent version

1.6.1

### GLPI version

10.0.11

### GLPIInventory plugin

1.3.4

**Comment by trasher** [comment]
Please provide inventory files that can be used to reproduce.

**Comment by g-bougard** [comment]
Hi @Frflamingo 

as I said in the glpi-agent issue, before opening an issue, you must check first the last imported inventory. My guess is the inventory fails to reach the server for some reason, maybe network issue or misconfiguration.

**Comment by Frflamingo** [comment]
The last inventory is fine  and its install date is 2024-01-29 
The display (thus teh DB) is showing 26/jan which is the date it was first installed 

Json attached
[computer_0_246.json](https://github.com/glpi-project/glpi-inventory-plugin/files/14096868/computer_0_246.json)

Note using a cloud hosted glpi instance (glpi network)

**Comment by g-bougard** [comment]
If you're using a GLPI Network instance, you should always first open a support ticket on GLPI Network.

What do you see in the asset history tab ? And in the asset import informations tab ?

**Comment by Frflamingo** [comment]
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/120394273/5d7f92ec-3033-4acd-a16d-122da6d5295f)

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/120394273/7e138e11-fbd1-4bc3-9e68-b3754d13e226)

**Comment by g-bougard** [comment]
Hi, can you confirm you setup the inventory frequency to 2 hours in GLPI ?

If yes, you're a good candidate to test [this new feature from glpi-agent available in nightly builds](https://github.com/glpi-project/glpi-agent/discussions/592). Could you try to install it on few computers ?

Also, to go deeper with more private datas like an agent log, can you open a ticket on GLPI Cloud support and provide the ticket number only ?

**Comment by trasher** [comment]
> If yes, you're a good candidate to test [this new feature from glpi-agent available in nightly builds](https://github.com/glpi-project/glpi-agent/discussions/592). Could you try to install it on few computers ?

That seems out of the scope of the current issue.

> Also, to go deeper with more private datas like an agent log, can you open a ticket on GLPI Cloud support and provide the ticket number only ?

I've tested changing only date on a local test, and yes I can confirm the installation date is indeed not updated.
Software update is quite complex process, and to make things short, installation date is not part of the updated discovery; I do not know if we really want to include it; we'll have to talk about that with the team.

**Comment by g-bougard** [comment]
@Frflamingo can you confirm only the "installdate" is changing in your case ?
This is surely the point I missed before and I thanks @trasher to really have identified it.

**Comment by Frflamingo** [comment]
hello . sorry for delay  in answering 
Indeed i just need the install_date to be updated

**Comment by g-bougard** [comment]
Hi @Frflamingo 
we still understood you need the installdate to be updated in GLPI. But we still need you to confirm only the installdate is really changing on the computer itself. Actually if your concern is for an internal software, you still can fix yourself that issue by also including a revision number in the name for example.

**Comment by Frflamingo** [comment]
The install date is indeed changing on the remote computer ....If you cannot take this one (for any reason) i will indeed need to workaround using the version number (but this will produce some SW version entries in the DB which is not really convenient)

**Comment by trasher** [comment]
Fixed: https://github.com/glpi-project/glpi/pull/16598. It will be part of GLPI next major release.
