### ISSUE TITLE
SNMP inventory bug on Cisco devices

### ISSUE THREAD

**Issue by erique-souza** [glpi-project/glpi-inventory-plugin#469]
### Describe the bug

In GLPI, I believe we have found a bug involving Cisco equipment. When executing the SNMP Network Discovery task, the device is found as expected using a registered private SNMP v2 credential, as shown in the print below

![Discovery](https://github.com/glpi-project/glpi-inventory-plugin/assets/102301295/608f4d7d-4798-4076-955b-465f73907442)

However, for some reason, this same device, when we tried to perform the SNMP inventory to get as much information as possible from the device, received the "SNMP Communication error" message, but the equipment is connected, the credentials are correct and the network discovery was made. few seconds, as shown in the print below

![inventory](https://github.com/glpi-project/glpi-inventory-plugin/assets/102301295/184687c0-71c6-44f2-a102-478ad3463749)

This is very strange because when trying to perform a snmpwalk through the GLPI Linux server itself, we were able to connect to the device without any problems and get its information, as shown in the print below

![snmp walk](https://github.com/glpi-project/glpi-inventory-plugin/assets/102301295/51ffde1d-f34c-4d59-b70b-041de3a1702e)

Some evidence of the device in question:
![snmp credencias](https://github.com/glpi-project/glpi-inventory-plugin/assets/102301295/c6f4e532-9a98-47c9-abe2-369e4ab24b97)

![snmp ativo](https://github.com/glpi-project/glpi-inventory-plugin/assets/102301295/03eafa7b-9efb-4011-b57f-f316399fa6d9)

Model: SG300-52 52-Port Gigabit Managed Switch

We put the glpi-agent that did the inventory on the same server as GLPI in debug2 for evidence, we also tested it on version 1.7.1 of glpi-agent and on the latest version 1.8 of the nightly build to validate
[glpi-agent.log](https://github.com/glpi-project/glpi-inventory-plugin/files/14226377/glpi-agent.log)

Is there anything we can test to validate if it really is a bug? It may appear that the way to authenticate to the device is different from the network discovery task for SNMP inventory

This was an example, but we have other devices of the same model, and also others from Cisco that are different models that gave the same results, some others are working as they should.

### To reproduce

- Network Discovery on Cisco device
- Network Inventory on Cisco device

### Expected behavior

The connection to the Cisco equipment and the additional inventory taking the number of ports, manufacturer, model, description, and other data from the SNMP inventory task

### Operating system

Linux

### GLPI Agent version

Other (See additional context below)

### GLPI version

10.0.11

### GLPIInventory plugin

1.3.4

**Comment by stonebuzz** [comment]
Yes, we had encountered the problem once.
Here the plugin, when generating the targets, does not remember from which IP range the target is found.

So when I send the information back to the agent, I can't determine the IP based on the IP range provided in the job.

(in addition, it is possible to provide several IP ranges in a job .....)

For the moment I have no idea how to fix it (at least the fork code doesn't allow me to find the information) and it remains a very, very "rare" case.

The easiest thing would be to delete (permanently) this network port (which will delete the offending IP)

The next discovery will not add it because discovery (after asset creation) does not add port information.

Thus, during the SNMP inventory, only the "correct" IP will be given to the agent.

**Comment by erique-souza** [comment]
I can try to contribute a suggestion to separate the first IP that the equipment was inventoried into in an independent field within the computer for network devices and printers, from the IP ranges that it was inventoried the first time with the discovery, perhaps this will help with the task of snmp to avoid bugs of losing which IP the equipment was on instead of trying to use the information in Network Ports

**Comment by trasher** [comment]
@francisco-vilaca please open new ticket(s) for issue(s) not directly related to the initial one described here.

**Comment by francisco-vilaca** [comment]
ok

**Comment by trasher** [comment]
> The easiest thing would be to delete (permanently) this network port (which will delete the offending IP)
> 
> The next discovery will not add it because discovery (after asset creation) does not add port information.
> 
> Thus, during the SNMP inventory, only the "correct" IP will be given to the agent.

Does this fix the initial issue?

**Comment by erique-souza** [comment]
> > The easiest thing would be to delete (permanently) this network port (which will delete the offending IP)
> > The next discovery will not add it because discovery (after asset creation) does not add port information.
> > Thus, during the SNMP inventory, only the "correct" IP will be given to the agent.
> 
> Does this fix the initial issue?

Yes, removing the extra IP worked as expected with the SNMP task for the device in question.

**Comment by trasher** [comment]
Great, thank you for the feedback.

I'll close that issue for now since it's resolved, I guess it should be OK now that your data has been redressed.
