### ISSUE TITLE
Trigger error : impossible deployment 

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi-inventory-plugin#470]
### Describe the bug

[2024-02-14 09:27:51] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "rows" in /var/www/assistance/plugins/glpiinventory/inc/deploygroup_dynamicdata.class.php at line 283
  Backtrace :
  ...ins/glpiinventory/inc/deploygroup.class.php:643 PluginGlpiinventoryDeployGroup_Dynamicdata::getTargetsByGroup()
  plugins/glpiinventory/inc/toolbox.class.php:407    PluginGlpiinventoryDeployGroup::getTargetsForGroup()
  plugins/glpiinventory/inc/taskview.class.php:1013  PluginGlpiinventoryToolbox->executeAsGlpiinventoryUser()
  plugins/glpiinventory/inc/taskview.class.php:832   PluginGlpiinventoryTaskView->getAgentsFromActors()
  plugins/glpiinventory/inc/task.class.php:623       PluginGlpiinventoryTaskView->prepareTaskjobs()
  src/CronTask.php:1018                              PluginGlpiinventoryTask::cronTaskscheduler()
  front/cron.php:84                                  CronTask::launch()

[2024-02-14 09:27:51] glpiphplog.WARNING:   *** PHP Warning (2): foreach() argument must be of type array|object, null given in /var/www/assistance/plugins/glpiinventory/inc/deploygroup_dynamicdata.class.php at line 283
  Backtrace :
  ...ins/glpiinventory/inc/deploygroup.class.php:643 PluginGlpiinventoryDeployGroup_Dynamicdata::getTargetsByGroup()
  plugins/glpiinventory/inc/toolbox.class.php:407    PluginGlpiinventoryDeployGroup::getTargetsForGroup()
  plugins/glpiinventory/inc/taskview.class.php:1013  PluginGlpiinventoryToolbox->executeAsGlpiinventoryUser()
  plugins/glpiinventory/inc/taskview.class.php:832   PluginGlpiinventoryTaskView->getAgentsFromActors()
  plugins/glpiinventory/inc/task.class.php:623       PluginGlpiinventoryTaskView->prepareTaskjobs()
  src/CronTask.php:1018                              PluginGlpiinventoryTask::cronTaskscheduler()
  front/cron.php:84                                  CronTask::launch()

### To reproduce

nothing

### Expected behavior

Does the group name matter, for example: 
nom :  "__office- 2017 -_A" est-ce correct ? 

### Operating system

Linux

### GLPI Agent version

1.5

### GLPI version

10.0.10

### GLPIInventory plugin

1.3.4

### Additional context

nothing

**Comment by stonebuzz** [comment]
Hi @falco2001 

do you have any SQL errors?

no error in debug mode on the dynamic group?

does the "glpi_plugin_glpiinventory_deploygroups_dynamicdatas" table exist?

And the "glpi_plugin_glpiinventory_deploygroups" table?

**Comment by falco2001** [comment]
Hello,
do you have any SQL errors? no

no error in debug mode on the dynamic group? yes

does the "glpi_plugin_glpiinventory_deploygroups_dynamicdatas" table exist? yes

And the "glpi_plugin_glpiinventory_deploygroups" table? yes

However we tried to remove all the special characters from the name of the group (_ - ...) and the name of the package it seems to work better?

**Comment by stonebuzz** [comment]
So cleaning up the group name was enough to solve the problem?

**Comment by falco2001** [comment]
it looks that way

**Comment by stonebuzz** [comment]
strange but ok =)

no need to go any further then

Thanks
