### ISSUE TITLE
After migrated 9.5.5 -> 10.0.10 error Undefined constant "PLUGIN_FUSIONINVENTORY_VERSION"

### ISSUE THREAD

**Issue by EC2311** [glpi-project/glpi-inventory-plugin#471]
### Describe the bug

Undefined constant "PLUGIN_FUSIONINVENTORY_VERSION" fusioninventory\front\communication.php at line 72 although FI is replaced by GLPI_inventory 1.3.4

### To reproduce

Migration from 9.5.5 -> 10.0.10 
FI 9.5+4.2 -> glpi plugin 1.3.4

**And agents are FI**

### Expected behavior

No error

### Operating system

Windows

### GLPI Agent version

Other (See additional context below)

### GLPI version

10.0.10

### GLPIInventory plugin

1.3.4

### Additional context

- Agents are still with FI (2.6)
- on an other platform, no error (same agents with FI, same plugin inventory 1.3.4)

**Comment by trasher** [comment]
You probably have to remove fusioninventory directory.

**Comment by EC2311** [comment]
but, 
How the agents with still FI will communicate ? : in their config they send to FI and not glpiinventory

**Comment by trasher** [comment]
I do not understand the question.
Anyway; the error you report is fired from a fusioninventory plugin file; it's somehow loaded. Either remove directory, or get this issue fixed on fusioninventory plugin side.
