### ISSUE TITLE
Running task Deploy - [error] [http client] Can't decode JSON content, starting with

### ISSUE THREAD

**Issue by mauriciolamego** [glpi-project/glpi-inventory-plugin#475]
### Describe the bug

I am trying to use the software deployment module but it is showing the following error in the target asset log.
the package has the target and group configured, and the deploy module enabled on the asset agents and on the server.
As a result, the installation does not start.
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/40633272/bf2b9650-2177-4b4e-80fb-a8856709f569)
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/40633272/1655a657-ee4f-4d13-b3d2-efa109e44bfe)

### To reproduce

enable the client-side deploy module
enable the server-side deploy module
create computer group
create software package
Select Deployment Target
Go to Target and select the available software package
Force client side to start service
see the expected results by following the log.

### Expected behavior

As a result, the installation does not start.

### Operating system

Windows

### GLPI Agent version

1.7.1

### GLPI version

10.0.11

### GLPIInventory plugin

1.3.4

### Additional context

LOG:

[Sat Feb 10 09:40:24 2024][info] running task Deploy
[Sat Feb 10 09:40:24 2024][error] [http client] Can't decode JSON content, starting with: 
         
<!DOCTYPE html>
<html lang="pt"       >
<head>
   <title>Autentica....o - GLPI</title>
   <meta charset="utf-8" />
...
[Sat Feb 10 09:40:24 2024][info] Deploy task not supported by server0

**Comment by g-bougard** [comment]
Hi @mauriciolamego 

you probably set a wrong url on glpi-agent side, check the Caution note on this documentation: https://glpi-agent.readthedocs.io/en/latest/configuration.html#server

**Comment by mauriciolamego** [comment]
Thanks for the answer!
Do you consider it to be wrong even though the inventory is functioning normally?

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/40633272/66ea32cd-e476-4892-b262-01a784c20202)

**Comment by VeniooSEPM** [comment]
I got exactly the same issue.
Inventory assets etc. works fine. Only 'GLPI Inventory plugin' Deployment module does not work.

**GLPI 10.0.12 (on Ubuntu 22.04, PHP 8.1.2, MariaDB)
GLPI Agent 1.7.1 (Win10 64b)
GLPI Inventory 1.3.5 (plugin)**

**Comment by mauriciolamego** [comment]
Dear all, I really appreciate your work.
I could not review this reported problem, as the URL is working normally, so much so that the inventory is reporting normally.

**Comment by g-bougard** [comment]
Hi @mauriciolamego 

as this is explained in the doc I pointed to you, for some tasks (Collect & Deploy included), the url set on agent for `server` MUST include `/marketplace/glpiinventory/` or `/plugins/glpiinventory/` depending on your plugin installation mode: the first if you installed the plugin via marketplace. And in your last screenshot, I see your url is only valid for inventory, netdiscovery and netinventory tasks.

**Comment by VeniooSEPM** [comment]
@mauriciolamego I resolved this problem Today as follows:
you should add another server address in your Windows registry (limited by comma), in my case

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/161463575/d0ff9f14-049b-4834-b00f-729dfdf224b0)

Now everything works perfect.

**Comment by mauriciolamego** [comment]
Thanks for all.
It's Works fine.
