### ISSUE TITLE
Repository has some strange version tags

### ISSUE THREAD

**Issue by AKorezin** [glpi-project/glpi-inventory-plugin#478]
### Describe the bug

Some time ago, strange tags were added to the repo, such as *1.3.5* and *2.1.3*.
Can you untag them?

### To reproduce

1. `git clone https://github.com/glpi-project/glpi-inventory-plugin.git -b 2.1.3`

### Expected behavior

I think these tags are wrong and should be removed to avoid unexpected situations.

### Operating system

Other (See additional context below)

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

Other (See additional context below)

**Comment by trasher** [comment]
Indeed, I thinks it was my fault. I've cleand all tags; all should be ok now.
