### ISSUE TITLE
Update 1.3.5

### ISSUE THREAD

**Issue by ricardo98349** [glpi-project/glpi-inventory-plugin#479]
### Describe the bug

Hello, I can't update to version 1.3.5 via Marketplace. Error: Unable to download plugin file

### To reproduce

1. Marketplace
2. Update to plugin

### Expected behavior

Update to 1.3.5

### Operating system

Linux

### GLPI Agent version

1.6.1

### GLPI version

10.0.11

### GLPIInventory plugin

1.3.4

**Comment by trasher** [comment]
There were a problem releasing; this will be solved today
