### ISSUE TITLE
[GLPI 10] Nothing seem be supported

### ISSUE THREAD

**Issue by ASLLR** [glpi-project/glpi-inventory-plugin#48]
Hi everyone,

i would try to test the new GLPI-Agent with GLPI-Inventory. I configure the GLPI-Inventory with my task (Vmware for example), the task seems to be ready on server side but when i launch glpi-agent command in debug mode i have :

[debug] ESX task not supported by GLPI server
[debug] NetInventory task not supported by GLPI server
[debug] NetDiscovery task not supported by GLPI server

And nothing be inventoried. My glpi-agent and my GLPI server is on the same server. which link inform in agent.cfg ? 
- `http://GLPISRV/GLPI/front/inventory.php`
- `http://GLPISRV/GLPI/plugins/glpiinventory`

i don't find a documentation about that.

Thank in advance

**Comment by g-bougard** [comment]
Hi @ASLLR 
first of all, don't forget to make your issue as accurate as possible, here you forgot to tell us which agent and plugin version you're using.
About the agent, you should absolutely still try a [nightly build](https://nightly.glpi-project.org/glpi-agent) as I made some fixes related to task support.
As you're expecting tasks to be run, the url to use is `http://GLPISRV/GLPI/plugins/glpiinventory` if you manually installed the plugin into your GLPI `/plugins` subfolder. If you installed the plugin via Marketplace, you should use `http://GLPISRV/GLPI/marketplace/glpiinventory`.

**Comment by ASLLR** [comment]
Hi, 

thank you for your answer.
So i use GLPI Agent (1.0-1) with GLPI inventory plugin 1.0.0-rc3 on GLPI 10 Beta 1 server. 

I'll try to update my agent with nightly build and i update my link, i will answer you if the nightly build correct my issue. 

Have a nice day,

**Comment by ASLLR** [comment]
Hi, 

that's more good with the nightlybuild 1.1 of the glpi-agent. The ESX job run's. 
But for snmp i've a timeout with this error : 
Odd number of elements in hash assignment at /usr/share/glpi-agent/lib/GLPI/Agent/Inventory.pm line 231.

and on the server side for SNMP dicovery, i've this error : 
The agent requests a configuration that has already been sent to it by the server. The agent may have encountered a critical error

Thank in advance,

**Comment by g-bougard** [comment]
Nice to here ESX task works as expected for you.
For SNMP tasks, if you're still with GLPI 10.0-beta, you can wait few days as an RC will be released soon and it will include many important related fixes. A new RC will probably be released at the same time for GlpiInventory plugin. But you still can try also the [GLPI nightly build](https://nightly.glpi-project.org/glpi).

**Comment by ASLLR** [comment]
Thank you i look forward to the publication of the RC !

Have a nice day.
