### ISSUE TITLE
Change agent name according to pc name change

### ISSUE THREAD

**Issue by kintaro1981** [glpi-project/glpi-inventory-plugin#483]
### Describe the bug

If a PC changes name the agent is still named with the old name.

This can be missleading, usually when you search for a the pc name in a agent dropdown.

The only way to solved this is uninstall and install again glpi-agent

or maybe the uninstall is not needed with install with REINSTALL=feat_AGENT?

### To reproduce

Install glpi-agent and run an inventory
Change pc name and reboot the pc
Now pc name and agent name are not in sync

### Expected behavior

After a pc name change the next inventory changes the agent name too.

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

1.3.4

### Additional context

GLPI Version 10.0.12

**Comment by trasher** [comment]
In the produced XML file, what's the agent name?

**Comment by g-bougard** [comment]
Hi @kintaro1981 

to reset the agent name, you just need to remove the C:\Program Files\GLPI-Agent\var\GLPI-Agent.dump` file and restart the service. That file will be generated again with an updated name.
