### ISSUE TITLE
No access to Inventory  Agents

### ISSUE THREAD

**Issue by fab44240** [glpi-project/glpi-inventory-plugin#496]
### Describe the bug

I update GLPI on 10.0.14 and glpiinventory to 1.3.5.
Since this upgrade, no one can access to [ Inventory][ Agents] to monitor agent except super-admin accounts.
I try to update profiles but theres no "Agent management" tab even if I check all the profile for the plugin...
We should access to this section vene if we are not the full administrator ? Is there a misconfiguration with this update ?

### To reproduce

Try to acces Administratiion -> GLpi inventory -> There is no agent management tab in general section if we are not full admin GLPI.
The link http://myglpi/front/agent.php did not work if we are not GLPI admin.

### Expected behavior

I wish I can edit profiles to choose which profiles could acces to agent management

### Operating system

Linux

### GLPI Agent version

1.6.1, Other (See additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

1.3.5

### Additional context

GLPI v10.0.14, a lot off agent version : (fusioninventory, glpi agent 1.5 to 17.)

**Comment by trasher** [comment]
That sounds like an configuration issue rather than a bug.
Also, agents management is done core, not from the plugin.

ACLs can be found in profiles administration tab:
![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/224733/48da28ed-8900-4e70-815d-1e592cd72803)

**Comment by fab44240** [comment]
I try to check all case but the agent management section does no appear and the direct link redirect to main page.
Is it a glpi inventory plugin bug or a glpi bug. It seeams to be a right acces failed.
I have the same problem on anothers GLPI server.

**Comment by arthurrschaefer** [comment]
@fab44240 you might need to add the option to **Import inventories** so you may access the page where the Agents button is.

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/13874922/59e68171-55e0-4c1e-af6a-fc5e4aa3c31f)

This way, it worked.

@trasher without adding, at least, the import ability, the Administration > Inventory menu won't appear, and the user must use the direct hyperlink to access it (https://server/front/agent.php)

**Comment by fab44240** [comment]
Hello,
Thank you, it works !


Le lun. 8 avr. 2024 à 22:16, Arthur Schaefer ***@***.***> a
écrit :
