### ISSUE TITLE
Import children locations

### ISSUE THREAD

**Issue by khaegebaert** [glpi-project/glpi-inventory-plugin#513]
### Describe the bug

Hi,  I 've setup locations with children, eg. : Father > Son.  
The snmp network inventory task performs an inventory where the location of a printer is set to "Father > Son" but this will create a new location "Father > Son" and will not take the correct Son location with "Father" as Father.

### To reproduce

Perform an inventory on an item (printer in this case ) where the location is configured as Father > Son.  This location must already exist in GLPI.  

### Expected behavior

The import should take the existing location and not create a new one.

### Operating system

Linux

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

Other (See additional context below)

### Additional context

GLPi version :GLPI 10.0.15
GLPI-agent on server: GLPI-Agent_v1.7.3-1

**Comment by trasher** [comment]
Fixed as of https://github.com/glpi-project/glpi/pull/17187
