### ISSUE TITLE
Unmanaged devices will created even they are disabled

### ISSUE THREAD

**Issue by joschi99** [glpi-project/glpi-inventory-plugin#519]
### Describe the bug

GLPI 10.0.15
GLPI Inventory 1.3.5
GLPI Agent: 1.5 or greater

Network discovery jobs will create/update "unmanaged devices" even if the inventory configuration has "Unmanaged devices" disabled into Import options

### To reproduce

1. goto to Home -> Administration -> Inventory - Configuration -> Unmanaged devices: disable the option
2. create e network discovery and inventory job
3. run the job
4. Devices without snmp access and a failed discovery/inventory will be created under unmanaged devices

### Expected behavior

The devices should not created

### Operating system

Linux

### GLPI Agent version

1.6.1, 1.6, 1.5

### GLPI version

10.0.12

### GLPIInventory plugin

1.3.5

**Comment by trasher** [comment]
Will be fixed in next GLPI core release.
