### ISSUE TITLE
SNMP inventory issue

### ISSUE THREAD

**Issue by Lucasberthier01** [glpi-project/glpi-inventory-plugin#52]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

I still have but want a public following to keep the community aware

### Describe the bug

During an SNMP inventory on an IP range which is executed by the FusionInventory agent installed on my workstation, the inventory is executed but when the agent arrives on a switch, it is fixed on the switch. So the inventory stops.

I am therefore obliged to carry out an inventory from my workstation so that GLPI knows that the agent is installed on my workstation and not on the switch.

State of my PC before inventory:
![2022-02-10 16_29_34-Ordinateur - CTR100 - GLPI – Brave](https://user-images.githubusercontent.com/71436267/153440672-92c9fe1b-8b6d-42b0-ac96-9dd4cb779cc2.png)

Running the current task:
![image](https://user-images.githubusercontent.com/71436267/153441620-a4e88ebc-cf40-44e1-b51a-4692f96fe9de.png)

State of my PC during the inventory (when the execution of the tasks turns white like the photo above):
![image](https://user-images.githubusercontent.com/71436267/153441952-21271a8a-328a-46cf-8fd2-c4ce9ecf24cd.png)

We can therefore see on the last photo that the agent is no longer considered to be installed on the post.

Here is where the agent is currently:
![image](https://user-images.githubusercontent.com/71436267/153442284-ddc9337d-bd98-43b4-a23c-0fee15d14480.png)
We can see that according to GLPI, the agent is installed on a printer (PRN181)

### To reproduce

During an SNMP inventory on an IP range which is executed by the FusionInventory agent installed on my workstation, the inventory is executed but when the agent arrives on a switch, it is fixed on the switch. So the inventory stops.

I am therefore obliged to carry out an inventory from my workstation so that GLPI knows that the agent is installed on my workstation and not on the switch.

State of my PC before inventory:
![2022-02-10 16_29_34-Ordinateur - CTR100 - GLPI – Brave](https://user-images.githubusercontent.com/71436267/153440672-92c9fe1b-8b6d-42b0-ac96-9dd4cb779cc2.png)

Running the current task:
![image](https://user-images.githubusercontent.com/71436267/153441620-a4e88ebc-cf40-44e1-b51a-4692f96fe9de.png)

State of my PC during the inventory (when the execution of the tasks turns white like the photo above):
![image](https://user-images.githubusercontent.com/71436267/153441952-21271a8a-328a-46cf-8fd2-c4ce9ecf24cd.png)

We can therefore see on the last photo that the agent is no longer considered to be installed on the post.

Here is where the agent is currently:
![image](https://user-images.githubusercontent.com/71436267/153442284-ddc9337d-bd98-43b4-a23c-0fee15d14480.png)
We can see that according to GLPI, the agent is installed on a printer (PRN181)

### Expected behavior

When I was on GLPI 9.5.6, my inventory worked perfectly... there was no such bug...

### Operating system

Windows

### GLPI Agent version

1.1

### GLPI version

10.0.0-rc1

### GLPIInventory plugin or FusionInventory for GLPI plugin version

9.5+3.0

### Logs:
log:
Nothing in the agent's .log file indicates where the error may have come from.

**Comment by g-bougard** [comment]
Hi @Lucasberthier01 
thank you for your submission.
Indeed I found yesterday the same issue and I need to investigate on it. I'm even not sure if this is a glpi-inventory plugin issue or a native inventory one.
Maybe @trasher can investigate too.

What I understood is: the agent submitting a netinventory will have its "Item type" field changed to the last type set in imported inventory. So it can become **Printer** or **Networking**. This is clearly an error, the "Item type" associated with the agent should not be changed while importing a networking or printer device.

**Comment by g-bougard** [comment]
As a side-effect, if you change from the related agent page, the "Item type" ("Type d'élément" in french) from "Printer" to "Computer", before running the task, your task should run as expected. Can you confirm ?

**Comment by Lucasberthier01** [comment]
Hey ! Juste pour vous dire que le problème est encore présent...
Lors de mon inventaire de ce matin, mon agent est venu se fixer sur un équipement réseau (switch) ce qui arrête l'inventaire...
Et donc mon switch se retrouve sans aucun ports dans son onglet "Ports réseaux"

Merci

**Comment by g-bougard** [comment]
@Lucasberthier01 @steph461 

can you try to apply glpi-project/glpi#10819 as this should fix this problem ?

**Comment by steph461** [comment]
Hello @g-bougard 
fix this problem glpi-project/glpi/issues/10817 ?
 
On the master GLPI, i see that files with the fix #10819
define.php 
Mainasset.php

the other files are in another folder test/functionioal/glpi

**Comment by g-bougard** [comment]
Hi @steph461 
I don't know for glpi-project/glpi#10817.

For #10819, yes, only these 2 files should be updated but be sure you're updating after rc2 upgrade.

**Comment by trasher** [comment]
3 files have changed in https://github.com/glpi-project/glpi/pull/10819

![image](https://user-images.githubusercontent.com/224733/156733734-2cec0ec9-c88a-4cc8-a2d9-bc46dccf35f4.png)

Since this has been merged yesterday; it should be part of latest nightly build.

**Comment by g-bougard** [comment]
Good catch @trasher

**Comment by steph461** [comment]
> Pour information : après avoir tenté un inventaire ce matin, l'agent a encore changé de cible... J'ai donc changé le type d'élément de la fiche de l'agent en ordinateur et j'ai relancé l'inventaire juste après mais ça a fait pareil.

it works for issue #52 the agent don't change target, its ok.
Indeed, this fix does not correct the SNMP discovery  https://github.com/glpi-project/glpi/issues/10817
