### ISSUE TITLE
"taskscheduler" automatic action doesn't report the number of updated tasks

### ISSUE THREAD

**Issue by eduardomozart** [glpi-project/glpi-inventory-plugin#522]
### Describe the bug

When running the "taskscheduler" automatic action, it updates the task status to "Preparing" but the "Number" column does not report the number of changed tasks status (it's always "0").

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/2974895/657eba84-f970-425d-8a8c-8b9eda3b849d)

### To reproduce

1. Run automatic action "taskscheduler".

### Expected behavior

The "Numbers" column should reflect the number of tasks status updated.

### Operating system

Windows

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

1.3.5

### Additional context

GLPI Agent version: 1.9
GLPI version: 10.0.16

**Comment by stonebuzz** [comment]
Hi @eduardomozart `taskscheduler` it works mainly on the agents to be prepared in the tasks

We could (possibly) count the agents prepared, but I'm not sure about the relevance of this information (the total changes depending on the task, doesn't allow you to go back to the task, etc.).

**Comment by eduardomozart** [comment]
It would be more useful than "0", even if it doesn't report the task name itself, as the admin would know that it's task is being handled and prepared to run by this task, and if the number didn't increase, it can troubleshoot somewhere else.

**Comment by stonebuzz** [comment]
Hi @eduardomozart 
can you try this -> https://github.com/glpi-project/glpi-inventory-plugin/pull/525

**Comment by eduardomozart** [comment]
I can confirm this fix seems to be working as expected.
