### ISSUE TITLE
 Management device IP returned to NetInventory task doesn't reflect the ones on IP range 

### ISSUE THREAD

**Issue by eduardomozart** [glpi-project/glpi-inventory-plugin#523]
### Describe the bug

I created a NetInventory task to NetInventory the network range 192.168.0.0/24 but it seems that the first IP (172.31.98.1) is returned to the task:

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/2974895/9e8e622a-7ace-40cc-875a-2979ec455cec)

Print of Network devices > [Device] > Network ports.

GLPI Agent Debug (Level 1) output:

```
[Mon Jul  8 16:03:39 2024][debug] new thread 12 to handle task NetInventory
[Mon Jul  8 16:03:39 2024][info] running task NetInventory
[Mon Jul  8 16:03:39 2024][debug] Current netinventory run expiration timeout: 1.0 hour
[Mon Jul  8 16:03:39 2024][debug] using 4 netinventory workers
[Mon Jul  8 16:03:40 2024][debug] #1, full snmp scan of 192.168.0.1 with credentials 2
[Mon Jul  8 16:03:40 2024][debug] #2, full snmp scan of 172.31.98.1 with credentials 2
[Mon Jul  8 16:03:41 2024][debug] #3, full snmp scan of 172.31.98.1 with credentials 2
[Mon Jul  8 16:03:41 2024][debug] #4, full snmp scan of 172.31.98.1 with credentials 2
[Mon Jul  8 16:03:55 2024][error] #1, SNMP communication error: no response from host 192.168.0.1
[Mon Jul  8 16:03:56 2024][error] #2, SNMP communication error: no response from host 172.31.98.1
[Mon Jul  8 16:03:56 2024][error] #3, SNMP communication error: no response from host 172.31.98.1
[Mon Jul  8 16:03:56 2024][error] #4, SNMP communication error: no response from host 172.31.98.1
```

It seems to be a known glpi-inventory-plugin issue as reported by @g-bougard in https://github.com/glpi-project/glpi-agent/issues/705

Downloads:

GLPI Inventory file: [networkequipment_0_4.xml.txt](https://github.com/user-attachments/files/16134698/networkequipment_0_4.xml.txt)

### To reproduce

1. Create a new NetInventory task after a NetDiscovery task.
2. See error on GLPI Agent debug log.

### Expected behavior

Use the IP that matches the IP range setup.
OR
If the contact with the device fails through the first IP, try the next one until the contact succeeds.

### Operating system

Windows

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

1.3.5

### Additional context

GLPI Agent version: 1.9.0
GLPI version: 10.0.16

**Comment by g-bougard** [comment]
Hi @eduardomozart 

for your information, #587 updates #524 in the case taskjob ids and tasks ids are not aligned. So it can help if this is your case.
