### ISSUE TITLE
IP addresses disappears after Network Discovery

### ISSUE THREAD

**Issue by leruetkins** [glpi-project/glpi-inventory-plugin#53]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Hi

I have made Net Discovery and list of printers looks like this:
![Screenshot_236](https://user-images.githubusercontent.com/15270519/153540164-f7ab77b7-9419-4a96-a7f9-d84aa5333d57.png)

After Net Inventory list of printers looks like like this:
![Screenshot_237](https://user-images.githubusercontent.com/15270519/153540247-60e5b44c-1fce-42d3-a523-620e92dfe9d6.png)

IP addresses dissapire after Network Discovery.

Also by default settings after some Net Discoverys and Net Invenrories printers duplicate and their number increases.
I have chenged rules printer like this to sort by MAC:
![Screenshot_239](https://user-images.githubusercontent.com/15270519/153540580-dbe4ba70-d31e-44c1-93eb-1bc8d9bdb1b0.png)

p/s Yesterday I had a problem due the fact that GLPI-Agent v1.2-git70294ae7 nightly build didn't want to start tasks. I came back to previous GLPI-Agent v1.2-git73986331 nightly build verison.

### To reproduce

1. Make Net Discovery
2. Make Net Infentory
3. Look Assets-Printers
4. Ip addresses dissapired 
### Expected behavior

Should be fine.

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.0-rc1

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0-rc4

**Comment by leruetkins** [comment]
345

**Comment by trasher** [comment]
Please try again with latest master branch, and latest GLPI nightly build; several fixes has been applied that can impact your issue.

**Comment by steph461** [comment]
Hello @trasher 

Last GLPI  nightly build is always present

1. Discovery new add printer
![image](https://user-images.githubusercontent.com/68054991/159258954-1222e4fc-8f1c-4b37-bf59-6a97bb0f4814.png)

2. SNMP Printer
![image](https://user-images.githubusercontent.com/68054991/159259575-6ff19bf9-3019-491c-8c8c-0e852e9995da.png)
![image](https://user-images.githubusercontent.com/68054991/159259652-87e237c9-d49d-4f1a-b742-4376767ffd91.png)
![image](https://user-images.githubusercontent.com/68054991/159259955-fd8f8fd0-e1a6-45ba-9eb8-edb278bf7581.png)

3. Snmp ===>Discovery

ip ok
![image](https://user-images.githubusercontent.com/68054991/159261663-173f8215-081f-4091-af76-414807776088.png)
![image](https://user-images.githubusercontent.com/68054991/159261817-463501e6-60ae-4970-aae0-ad3d7e6fe7bf.png)

**Comment by steph461** [comment]
hello @leruetkins 

have you same issue ?  https://github.com/glpi-project/glpi/issues/10960
thera are 2*etho (black and green) may be the probleme ?

**Comment by g-bougard** [comment]
> It still doesn't work for me. GLPI 10-rc3. GLPI inventory 1.0.0-rc7.
> 
> Step by step on these versions:
> 
> ```
> root@glpi:/home/glpi#glpi-netdiscovery --first 192.168.244.7 --last 192.168.244.9 -control -i -s=/home/glpi/inv --debug --threads 5
> root@glpi:/home/glpi# dir /home/glpi/inv/netdiscovery
> 192.168.244.7.xml  192.168.244.8.xml  192.168.244.9.xml
> 
> 
> root@glpi:/home/glpi# glpi-injector -R -d /home/glpi/inv/netdiscovery/ --debug -url http://my.server/glpi/marketplace/glpiinventory/
> Loading /home/glpi/inv/netdiscovery//192.168.244.7.xml...[21777093] OK
> DEBUG: <?xml version="1.0"?>
> <REPLY><RESPONSE>SEND</RESPONSE></REPLY>
> 
> Loading /home/glpi/inv/netdiscovery//192.168.244.8.xml...[16BDF05A] OK
> DEBUG: <?xml version="1.0"?>
> <REPLY><RESPONSE>SEND</RESPONSE></REPLY>
> 
> Loading /home/glpi/inv/netdiscovery//192.168.244.9.xml...[30E909ED] OK
> DEBUG: <?xml version="1.0"?>
> <REPLY><RESPONSE>SEND</RESPONSE></REPLY>
> ```
> 
> ![изображение](https://user-images.githubusercontent.com/15270519/159720596-71bc7339-4f2f-40d2-b830-41d945d557e3.png)
> 
> ```
> root@glpi:/home/glpi# glpi-injector -R -d /home/glpi/inv/netinventory/ --debug -url http://my.server/glpi/marketplace/glpiinventory/
> Loading /home/glpi/inv/netinventory//192.168.244.7.xml...[6D8E4E3F] OK
> DEBUG: <?xml version="1.0"?>
> <REPLY><RESPONSE>SEND</RESPONSE></REPLY>
> 
> Loading /home/glpi/inv/netinventory//192.168.244.8.xml...[84B6EB1E] OK
> DEBUG: <?xml version="1.0"?>
> <REPLY><RESPONSE>SEND</RESPONSE></REPLY>
> 
> Loading /home/glpi/inv/netinventory//192.168.244.9.xml...[8801497D] OK
> DEBUG: <?xml version="1.0"?>
> <REPLY><RESPONSE>SEND</RESPONSE></REPLY>
> ```
> 
> ![изображение](https://user-images.githubusercontent.com/15270519/159720963-8dc3aea8-863c-468f-9078-75f49fbcb902.png) Ip adresses dissapired(
> 
> Also as youcan see mac address duplicated.
> 
> You can try to use my xml files in archive:
> 
> [xml.ZIP](https://github.com/glpi-project/glpi-inventory-plugin/files/8333802/xml.ZIP)

Thank you @leruetkins 
I can reproduce the problem with your XMLs. At least for the 192.168.244.9 ip when using default rules as for the 2 other XMLs, a serial is missing. I imagine you're using the rules import and update by MAC Address.

So to resume:
1. netdiscovery xml import creates a printer with the expected IP.
2. netinventory xml import makes the associated IP disappeared.

At that point, this still can be a glpi-agent issue as it seems the `<IP/>` node is missing in netinventory XML.
@trasher how mandatory is this node in netinventory XML to keep a coherent IP between netdiscovery and netinventory tasks ?

@leruetkins would you mind to provide some [snmpwalk output](https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output) for your concerned printers ? At least for IP 192.168.244.7 & 192.168.244.9.

**Comment by trasher** [comment]
>  @trasher how mandatory is this node in netinventory XML to keep a coherent IP between netdiscovery and netinventory tasks ?

I don't know, sorry.

**Comment by leruetkins** [comment]
Yes. I'm using the rules import and update by MAC Address, because printers duplicate due the import:

![изображение](https://user-images.githubusercontent.com/15270519/159750399-0bd2cfb7-d9ed-4f31-a089-3ce84b9f3a01.png)


Sure:
[snmpwalks.ZIP](https://github.com/glpi-project/glpi-inventory-plugin/files/8334860/snmpwalks.ZIP)

**Comment by g-bougard** [comment]
Hi @leruetkins 

thank you for your walks.

First of all, they permitted me to update HP printers support on GLPI Agent (in [9418c6e](https://github.com/glpi-project/glpi-agent/commit/9418c6ef61ae54f7fce5c4dc30a9423edf767dfb)). Now GLPI Agent detects more things for HP LaserJet Pro MFP M127fw models: serialnumber, manufacturer and firmware are now set. This would have fix you printers duplicate problem. Anyway, this doesn't fix the current issue.

But this permitted me to create a new set of XML file we can use to reproduce the case: [XML.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/8352038/XML.zip)
These ones are valid while using default import rule configuration.

We can use them with integrated import file feature.

I tested them on GLPI 10.0.0-rc3 & GLPI 9.5.4+FI4G 9.5+3.0 (with fusioninventory/fusioninventory-for-glpi#3239 applied).

Here is what I can tell:
 - on GLPI 9.5:
   - netdiscovery xml first import only sets management port
   - netinventory xml import sets all the ports, also resetting management port name
   - further netdiscovery xml import doesn't change networt port inventory
   - the printer ip is always kept in the printers list
 - on GLPI 10.0.0-rc3:
   - netdiscovery xml import always resets network ports to only management port
   - netinventory xml import sets all the ports, also resetting management port name, but the printer ip is also removed from the printers list

I don't have any error in php-errors.log.

So there's clearly something different between FI & native inventory support.

I think native inventory is processing netdiscovery XML the same way than netinventory ones. This can involve native inventory decides to remove network ports set by netinventory XML import at the time it imports a netdiscovery XML. Tell me if I'm wrong @trasher

@trasher can you confirm you're reproducing the same way than me using the [XML.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/8352038/XML.zip) XML files ? If yes, do you see what should be done to fix the issue ?

**Comment by trasher** [comment]
Native inventory was not originally planned to handle network discovery/inventory. Issue is "simple": each new inventory overrides the old one.
I have no idea how to fix this; I'm still looking at the code.

I did not understand the problem with printer IP.

**Comment by steph461** [comment]
Hello @trasher 

I perform another manipulationmanipulation for the dispiration of the ip with this interface of glpi.
![image](https://user-images.githubusercontent.com/68054991/161005517-28e70102-e054-415e-a1ca-6c5e749d2534.png)


I test with an xml file (snmp).

1)  import of the xml file, Ip disappears

2) I perform the same manipulation, the ip appears

3) I perform the same manipulation, lip disappears

4) import ip OK

I feel like it's a knock yes and a knock no

**Comment by trasher** [comment]
https://github.com/glpi-project/glpi/pull/11154 will solve overriding of network inventories when a new network discovery occurs.

It certainly solves some issues you may have but probably not the IP one... You said you import an XML file. Is this file the result of a network discovery or inventory?

**Comment by leruetkins** [comment]
> [glpi-project/glpi#11154](https://github.com/glpi-project/glpi/pull/11154) will solve overriding of network inventories when a new network discovery occurs.
> 
> It certainly solves some issues you may have but probably not the IP one... You said you import an XML file. Is this file the result of a network discovery or inventory?

Hi

Do you mean ip duplicate?

**Comment by steph461** [comment]
hello i have test but i have this error

I updated these files : 
![image](https://user-images.githubusercontent.com/68054991/161712931-d1b418eb-bbff-4142-93fa-800776b1b375.png)


```shell
[2022-04-05 10:29:14] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: json_decode(): Argument #1 ($json) must be of type string, stdClass given in /var/www/html/glpi10beta/src/Inventory/Inventory.php at line 207
  Backtrace :
  src/Inventory/Inventory.php:207                    json_decode()
  src/Inventory/Request.php:314                      Glpi\Inventory\Inventory->contact()
  src/Inventory/Request.php:81                       Glpi\Inventory\Request->contact()
  src/Agent/Communication/AbstractRequest.php:323    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:235    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:83                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
``

**Comment by orthagh** [comment]
Hello @steph461 

with the merge of:
- #11205
- #11154
- #11207

Disapearance of ips and ports after netinventory and netdiscovery should now be ok.
As the first pr was merged this morning, you should expect the nightly build to be ok tomorrow.

Regards.

**Comment by steph461** [comment]
hello @orthagh 

Thx I will try with glpi nightly

**Comment by cedric-anne** [comment]
I triggered the master branch build manually, you can find the archive here: https://github.com/glpi-project/glpi/actions/runs/2113879539

**Comment by steph461** [comment]
the ip no longer disappears on the printers but there is the double display of the ip. It's almost good

![image](https://user-images.githubusercontent.com/68054991/162402001-63a8d939-b09d-4dc5-bd1f-fb77258304f1.png)

Example :
ETH0
![image](https://user-images.githubusercontent.com/68054991/162402282-3b90cac0-8b54-48ea-b76e-baa1183571bf.png)

MANAGEMENT
![image](https://user-images.githubusercontent.com/68054991/162402777-fef069ab-efce-457c-b9f2-647304809883.png)

**Comment by orthagh** [comment]
I will check in the afternoon if can do better, i know exactly where the duplicate come from.
For a quick explanation, we collect all known ips from an equipment into a virtual (and hidden) port to ease matching of rules.
The fix will probably consist of a de-duplication of the displayed ips

**Comment by leruetkins** [comment]
I can't check because after all updates (GLPI 10, glpi-inventory 1.0, glpi-agent-1.3-git03e16233) I have error:

```
root@glpi:/home/glpi# glpi-injector -R -d /home/glpi/inv/netdiscovery/ --debug -url 'http://my.server/glpi/marketplace/glpiinventory/'
Loading /home/glpi/inv/netdiscovery//192.168.244.7.xml...[707AA515] ERROR: Bad content as server response
DEBUG: 400 URL must be absolute

Loading /home/glpi/inv/netdiscovery//192.168.244.8.xml...[C9A8FA1B] ERROR: Bad content as server response
DEBUG: 400 URL must be absolute

Loading /home/glpi/inv/netdiscovery//192.168.244.9.xml...[E69B3BB4] ERROR: Bad content as server response
DEBUG: 400 URL must be absolute

These elements were not sent:
/home/glpi/inv/netdiscovery//192.168.244.7.xml
/home/glpi/inv/netdiscovery//192.168.244.8.xml
/home/glpi/inv/netdiscovery//192.168.244.9.xml
```
Any idea?
