### ISSUE TITLE
Actors keep disappearing from Tasks

### ISSUE THREAD

**Issue by GuidoWilden** [glpi-project/glpi-inventory-plugin#538]
### Describe the bug

We set the target as an IP range for both the network discovery and network inventory task, as an Actor a single glpi-agent runs on the server that handles both remote inventory as well as network discovery and network inventory tasks. This has worked reliably for months, however, currently the Actor keeps disappearing from the Task. We have not yet figured out what triggers the disappearance.

### To reproduce

1. Create a Task
2. Set a Target as an IP range
3. Set Actor to the glpi-agent
4. Double-check the Task a day or so later
5. Actor has vanished

### Expected behavior

Once the Task is defined the parameters should remain unchanged.

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

1.3.5

### Additional context

GLPI version 10.0.16, GLPI agent nightly build v1.11-git7b8a5f0b

**Comment by stonebuzz** [comment]
Hi @GuidoWilden 

We've already come across this case.
It turned out that the workstation had both the FusionInventory agent and the GLPI inventory agent.

When the FusionInventory agent did the invetary, it deleted the GLPI agent connected to this workstation (and vice versa).

So if a task was prepared with the GLPI agent, the actor was deleted.

perhaps this is the case for you?

**Comment by GuidoWilden** [comment]
Hi @stonebuzz, thank you for your response but this is not my case no.

The server is fairly new and never had the fusion inventory plugin installed. Sorry ...

**Comment by stonebuzz** [comment]
And the computer in question has only one agent installed ?

Can you check in the agent (history tab on glpi) whether he keeps changing PCs?

**Comment by GuidoWilden** [comment]
That is indeed a little confusing. If I list it on command line I get:
```
apt list --installed | grep glpi-agent

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

glpi-agent-task-esx/now 1:1.11-git7b8a5f0b all [installed,local]
glpi-agent-task-network/now 1:1.11-git7b8a5f0b all [installed,local]
glpi-agent/now 1:1.11-git7b8a5f0b all [installed,local]
```

However in the GUI it appears to flip flop or am I missing something?

<img width="1385" alt="Screenshot 2024-08-30 at 15 16 04" src="https://github.com/user-attachments/assets/af90c343-12d1-45f9-965e-b10ac73ec29a">

**Comment by stonebuzz** [comment]
Here you are on a computer

can you click here

![image](https://github.com/user-attachments/assets/91bde9c3-952a-4103-8dac-19e846368150)

and then look here

![image](https://github.com/user-attachments/assets/4070d336-52cb-4197-a022-c67d1a021e10)

**Comment by GuidoWilden** [comment]
OK is this what you are after?

<img width="1385" alt="Screenshot 2024-08-30 at 15 22 46" src="https://github.com/user-attachments/assets/8f789414-b2d7-434d-8d88-aeacf3622a0c">

**Comment by stonebuzz** [comment]
if the linked PC does not change to another

this is not the case here

and I can't see what would cause the agent to be removed from the task

**Comment by stonebuzz** [comment]
task entity is the same as computer entity ?

![image](https://github.com/user-attachments/assets/8caf564f-7c8d-412b-8389-910276a14065)

**Comment by GuidoWilden** [comment]
It is yes, and currently the Actor is also listed. Not sure if this is still true on Monday.

<img width="1385" alt="Screenshot 2024-08-30 at 15 35 56" src="https://github.com/user-attachments/assets/9fc00e49-9271-4cd8-9c78-e2638c9b073a">

**Comment by GuidoWilden** [comment]
Just like I thought: I just checked the Tasks and the Actors have vanished again.

**Comment by stonebuzz** [comment]
Wouldn't the agent in question be deleted and then recreated at some point?

**Comment by GuidoWilden** [comment]
That's not the behaviour I would expect tot see. There is only one Agent on our whole estate and its running on the server or am I missing something?

**Comment by g-bougard** [comment]
Hi @GuidoWilden 

did you try to install glpi-agent with AppImage or snap before using rpm package ? If such a installation still exists on the computer, it may also produce such a comportment.

You still can check if you have another glpi-agent process running.

**Comment by GuidoWilden** [comment]
The server runs Ubuntu so no rpm. We always install via 

`perl <PACKAGE_NAME> --install --verbose`

I can not see anger agent process running

```
ps -ef | grep agent
root       94086       1  0 Aug29 ?        00:16:36 glpi-agent (tag ldnaz): waiting
root      294118   94086 12 10:17 ?        00:02:18 glpi-agent (tag ldnaz): processing OOB VLAN network scan request
root      298109    3191  0 10:35 pts/3    00:00:00 grep --color=auto agent
```

**Comment by stonebuzz** [comment]
I think the agent is deleted then recreated, if I go back to your screenshot we can see that it was created on the 29th.

![image](https://github.com/user-attachments/assets/6c96da2c-ec4b-4bf8-86f7-f4dcda741963)

can you show me the agent's history

**Comment by GuidoWilden** [comment]
Is that not the moment I installed the latest update?

It looks like this now

<img width="1213" alt="Screenshot 2024-09-02 at 10 39 50" src="https://github.com/user-attachments/assets/aaf1905b-dd7d-4cd1-a8e7-d40da4f15fdd">

**Comment by stonebuzz** [comment]
So yes, the agent was deleted and then recreated.

Can you run the agent to see if it switches to GLPI?

**Comment by GuidoWilden** [comment]
Sorry I don't think I follow. Do you want me to run the agent on command line? And the observe what exactly?

**Comment by stonebuzz** [comment]
> Do you want me to run the agent on command line?

Yes

> And the observe what exactly?

I Agent ID change

**Comment by stonebuzz** [comment]
and if you get errors in the GLPI log files (/glpi/files/_log/ php-errors.log or sql-errors.log)

**Comment by stonebuzz** [comment]
what is the result of the following commands :

```shell
sudo updatedb 
locate agent.cgf
```

Wouldn't you have cloned the server?

**Comment by GuidoWilden** [comment]
1. OK its a Hyper V VM running Ubuntu so no container.

2. Commands:

```
sudo updatedb 
sudo: updatedb: command not found
```

`locate agent.cgf` retuns nothing.

3. When you say cloned server I'm not too sure what you mean. The server has been restored from a snapshot when I broke things. Not sure if this is what you mean.

4. When I run the agent on command line the ID does indeed change:

<img width="552" alt="Screenshot 2024-09-02 at 11 23 02" src="https://github.com/user-attachments/assets/af4d6479-a4d2-4dbf-b195-0089fe389c12">


What could be the cause for this?

**Comment by stonebuzz** [comment]
either it actually has 2 agents on the same machine, or it has 2 cloned machines with the same S/N and or UUID

**Comment by GuidoWilden** [comment]
I can see only one Agent:

```
apt list --installed .| grep agent

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

root@ldnaz-wiki01:/var/log/glpi# apt list --installed | grep agent

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

glpi-agent-task-esx/now 1:1.11-git7b8a5f0b all [installed,local]
glpi-agent-task-network/now 1:1.11-git7b8a5f0b all [installed,local]
glpi-agent/now 1:1.11-git7b8a5f0b all [installed,local]
gpg-agent/jammy-updates,jammy-security,now 2.2.27-3ubuntu2.1 amd64 [installed,automatic]
libpolkit-agent-1-0/jammy,now 0.105-33 amd64 [installed,automatic]
lxd-agent-loader/jammy,now 0.5 all [installed,automatic]
```

It finds only one machine against the serial number and from what I can see I can not search by UUID.

**Comment by trasher** [comment]
> [...]
> This means you effectively have 2 agents, one installed in april and one in june which are claiming the same computer.

This does not seems to be a bug, I close

**Comment by stonebuzz** [comment]
do you have errors in the GLPI log files (/glpi/files/_log/ php-errors.log or sql-errors.log) when the agent pushes the inventory?

**Comment by GuidoWilden** [comment]
I have been searching for clones with UUID and serial no. but even if I use only snippets of the two I can't find anything. There is guaranteed only one agent installed.

I tried tracing the logs but nothing sticks out to. Filtered logs only for today attached.
[Archive.zip](https://github.com/user-attachments/files/16849815/Archive.zip)
