### ISSUE TITLE
I can't use Deploy via GlpiInventory with version 1.4.0

### ISSUE THREAD

**Issue by jcsanchezrb** [glpi-project/glpi-inventory-plugin#546]
### Describe the bug

After updating GLPiInventory to version 1.4.0, the GLPI Inventory option has disappeared from the Administrator menu

### To reproduce

Upgrading GLPiInventory from version 1.3.5 to version 1.4.0

### Expected behavior

The GLPI Inventory option within that menu has disappeared, so I cannot use Deploy.

### Operating system

Windows

### GLPI Agent version

Other (See additional context below)

### GLPI version

10.0.12

### GLPIInventory plugin

Other (See additional context below)

### Additional context

GLPI Agent version: 1.10
GLPI Version: 10.0.16
GLPIInventory plugin: 1.4.0

![imagen](https://github.com/user-attachments/assets/de3ba33a-c82e-46a3-901d-d94fe450ef62)

**Comment by MarcSamD** [comment]
I don't have this issue after the upgrade. Are you sure that you re-enabled the plugin after the upgrade in Setup -> Plugins ?
![image](https://github.com/user-attachments/assets/42f24760-d75b-466b-bf77-d401c5c60974)

**Comment by jcsanchezrb** [comment]
Hello,
You were right, I didn't re-enabled the plugin after upgrading.

Thank you very much for your help.



José Carlos Sánchez Rubio 

    En lunes, 9 de septiembre de 2024, 04:30:39 CEST, MarcSamD ***@***.***> escribió:  
 
 


I don't have this issue after the upgrade. Are you sure that you re-enabled the plugin after the upgrade in Setup -> Plugins ?
image.png (view on web)
