### ISSUE TITLE
Unmanaged Devices always created in Root Entity

### ISSUE THREAD

**Issue by fabriceverkor** [glpi-project/glpi-inventory-plugin#552]
### Describe the bug

Discovery task and IP range are in 'Facility'
Unmanaged Devices are always created in Root Entity, not in 'Facility'

### To reproduce

1- create an IP range in 'Facility' entity
2- create a NetDiscovery task in 'Facility' entity and associated to IP range above
3-  run the task

### Expected behavior

Unmanaged Devices should be created in 'Facility' entity, not in Root entity.

### Operating system

Linux

### GLPI Agent version

1.5

### GLPI version

10.0.10

### GLPIInventory plugin

1.3.4

**Comment by trasher** [comment]
Does not seems a bug; I do not think it has ever worked like this.

**Comment by stonebuzz** [comment]
After rereading the code, the management of unmanaged elements is based on this option for the destination entity

![image](https://github.com/user-attachments/assets/1cb63b67-59ff-4edf-bd96-10efe3420a46)

Unmanaged then passes to the rules for assigning an element to an entity

![image](https://github.com/user-attachments/assets/90f520a2-6aed-4dd6-b9ae-e54d72dadf1d)

**Comment by trasher** [comment]
Using entities rules is certainly the way to go there. 

Using IP range entity would be a new feature, if it would be accepted.
I close this one.
