### ISSUE TITLE
Collect say Access Denied when upload data to server

### ISSUE THREAD

**Issue by achillebnt** [glpi-project/glpi-inventory-plugin#558]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### GLPI Version

10.0.16

### Plugin version

1.4.0

### Bug description

In my installation i setup the plugin to inventory computers and this work fine, i have a task to collect a reg key an it stop working (maybe after update glpi).

In agent i notice this error message:
```
[error] [http client] Can't decode JSON content, starting with:
<!DOCTYPE html>
<html lang="it"       >
<head>
   <title>Accesso negato - GLPI</title>

   <meta charset="utf-8" />

      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
...
```
I check the request on server and i found GET and POST:
```
"GET /glpi-test/marketplace/glpiinventory/?action=getConfig&task%5BCollect%5D=2.9&machineid=MyComputer-2023-02-14-17-57-22 HTTP/1.1" 200 2505 "-" "GLPI-Agent_v1.11"
"GET /glpi-test/marketplace/glpiinventory/b/collect/?action=getJobs&machineid=MyComputer-2023-02-14-17-57-22 HTTP/1.1" 200 2579 "-" "GLPI-Agent_v1.11"
"POST /glpi-test/marketplace/glpiinventory/b/collect/?action=setAnswer&uuid=67078c2b265e0&method=POST HTTP/1.1" 200 9660 "http://192.168.1.11/glpi-test/marketplace/glpiinventory/b/collect/" "GLPI-Agent_v1.11"
"GET /glpi-test/marketplace/glpiinventory/b/collect/?action=jobsDone&uuid=67078c2b265e0 HTTP/1.1" 200 2295 "-" "GLPI-Agent_v1.11"

```
I make that request and i found the GET action works fine and the POST give that error:
![image](https://github.com/user-attachments/assets/9d48e7c5-4bc3-4234-a059-c5872bc9f136)

I suppose the gpli framework allow only to get but not put data but i can't figure out if is a bug o a missing configuration.

### Your GLPI setup information

Glpi server (10.0.16) 
glpiinventory (1.4.0)
GLPI Agent (1.11)

**Comment by achillebnt** [comment]
I found the issue is caused by missing CSRF token, i momentarily workaround the problem by adding a definition in glpi define.php
```php
define("GLPI_USE_CSRF_CHECK", "0");
```

**Comment by stonebuzz** [comment]
Hi @achillebnt 

When the agent performs a `GET` action (to request the job `getJobs`) `GLPI` also returns the `CSRF_TOKEN`

(`collect.class.php L728`)
```php
$response->token = Session::getNewCSRFToken();
```

Then, when the agent performs the `JOB` and wishes to post the response (`setAnswer`), the data sent contains the `CSRF_TOKEN`

(`GLPI-Agent` `collect.pm L269`)
![image](https://github.com/user-attachments/assets/66560ec3-3eb0-4523-ba5d-8be6148e1b81)


when the data is received, GLPI retrieves the CSRF_TOKEN into `POST`

(`collect.class.php L728`)
```php
$a_values = $_POST;
```


and passes it to the `add` method.

(`collect.class.php L811`)
```php
$pfCollect_subO->updateComputer(
    $computers_id,
    $a_values,
    $sid
);
```



`GLPI` doesn't seem to be involved, as we are in the plugin.

The plugin seems to handle the `CSRF_TOKEN` correctly, as long as it is passed in the `POST`.

Your test via postman does not seem to reflect reality, the `CSRF_TOKEN` is missing.


Can you debug the `collect.class.php` file to see what GLPI sends/receives via `getJob` and `setAnswer`?

Best regards

**Comment by stonebuzz** [comment]
Several things to look at: 

- Lifetime (I don't really believe in it), by default the `CSRF_TOKEN` lifetime is 7200 sec (120 min) maybe you have redefined this constant `GLPI_CSRF_EXPIRES`.

- The `CSRF_TOKEN` generated and sent to the agent is kept in session (`$_SESSION`). If you have several web front-ends, make sure they share session data correctly.

- `CSRF_TOKEN` generation uses PHP `time()` function, so check that your server is on time !

**Comment by achillebnt** [comment]
I check and constant `GLPI_CSRF_EXPIRES` is default 7200.

After some debugging i find the token is present on post and is set on `_glpi_csrf_token` variable.

Analyzing glpi Session.php i discovered the function validateCSRF and this search for `$_SESSION['glpicsrftokens'][$requestToken]` for validation but is missing in that agent request and i dont no why.

I check server configuration and it is all set fine and the portal is working fine too.

**Comment by stonebuzz** [comment]
Ensure that `session.cookie_secure` in your php.ini file is configured correctly, especially if you're using SSL. If this flag is misconfigured, the session cookies might not be sent or maintained, leading to a lost session or token during requests.

see this -> https://glpi-install.readthedocs.io/en/latest/prerequisites.html#security-configuration-for-sessions

**Comment by achillebnt** [comment]
I found it! And is a miss configuration on General setup.. the url was in http and not in https. 

> Explanation:
The agent ask in https, server respond with CSRF and information where post data and this specify base url specified in general setting. So agent switch protocol https to http loosing session data, this is normal if `session.cookie_secure` is on.

I change setting and now work all fine, thanks for support and hope this may be useful to someone.

![immagine](https://github.com/user-attachments/assets/9917c231-e4d9-4bf6-8873-683829e24f30)
