### ISSUE TITLE
Network device name + IP is not being updated

### ISSUE THREAD

**Issue by erique-souza** [glpi-project/glpi-inventory-plugin#562]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### GLPI Version

10.0.16

### Plugin version

1.4.0

### Bug description

When carrying out the first inventory of a Network Device, it is correctly inventoried, with its data, name, IP, model, manufacturer, etc. 

However, when changing the name of the device, and also the IP as an example, name + IP is not being updated in GLPI, I did some tests, restarted the device, and until the moment of inventory everything is fine, including in GLPI-Agent

![{A82F14B8-52E0-4DF3-83CA-DDCB9843B5F3}](https://github.com/user-attachments/assets/96285e05-2f54-4570-9988-84a4d348045a)

If we look at the glpi-agent inventory log, the new device name appears correctly, but in the plugin at the time of updating the glpi it does not update in any way, I have already checked that there is no blocking on the device

![{8D517ABA-E075-4842-902C-92DE2B5ABBA5}](https://github.com/user-attachments/assets/817e1225-93a3-4b35-b8ca-05915aad9aff)
![{071B6747-0AE6-4E5B-9A98-15A33E0881D3}](https://github.com/user-attachments/assets/99c6f9c3-1279-444d-99a4-18879b2e8f81)

![image](https://github.com/user-attachments/assets/afe5d6f7-f8fd-470b-a1fa-abc4cf11e508)

Doing some more tests, when completely deleting the network device in question, cleaning it from the trash, and having the SNMP Discovery task run, it is inventoried again now with the new name, but when trying to change the name again, it does not update

Leading me to believe that there is a bug in the glpi inventory plugin when updating this data

I activated debug in the plugin, I believe it is the log below that was generated for analysis
![{45CE77ED-182D-4590-92D1-49D7F0217759}](https://github.com/user-attachments/assets/679acdfa-2aa3-41a1-8100-0523d818d8d3)

[pluginGlpiinventory-communication.log](https://github.com/user-attachments/files/17510957/pluginGlpiinventory-communication.log)
[pluginGlpiinventory-jobs.log](https://github.com/user-attachments/files/17510958/pluginGlpiinventory-jobs.log)
[pluginGlpiinventory-tasks.log](https://github.com/user-attachments/files/17510959/pluginGlpiinventory-tasks.log)

For testing purposes I also took the glpi-agent log showing that the name of the SNMP inventory is correct with the name "FISIO-AP-ALMOXARIFADO2", below
[glpi-agent.log](https://github.com/user-attachments/files/17510968/glpi-agent.log)

### Steps To reproduce

1 - Have a network device SNMP inventory
2 - Change the device name
3 - Restart the device
4 - Try redoing SNMP
5 - Observe the result if it changes in the glpi

**Comment by trasher** [comment]
That's because you're running a network discovery, and not a network inventory here. `discovery` just create the equipment if it does not exists. It prevents discoveries to remove all ports, IPs and so on found with network inventory.

**Comment by erique-souza** [comment]
> That's because you're running a network discovery, and not a network inventory here. `discovery` just create the equipment if it does not exists. It prevents discoveries to remove all ports, IPs and so on found with network inventory.

Hello, I actually now saw that Discovery is not updating the already inventoried device, I tested the SNMP inventory pointing to the IP and it really has now been updated, thank you

However, I believe we have a problem with this change in Discovery not being able to update devices already inventoried, which is cases of IP change

For example:

I did Discovery on the Network, it inventoried 1 network device at IP 172.22.27.160

If we try to execute another SNMP inventory task, it will work, and the data will be updated, so far perfect, everything ok

However, if I change the IP there on the equipment, to 172.22.27.161 and run both Discovery and the SNMP inventory, both will not be able to update the equipment, if I understood correctly, the equipment simply becomes outdated because Discovery does not update the IP, and SNMP will only try to authenticate to IPs that GLPI already knows, which in this case was the old 172.22.27.160 and not the new 172.22.27.161

To resolve this, if the process really is what I mentioned above, it would be interesting for Discovery to allow updating the IP of the device that it eventually finds on the network, so that if the IP changes, it can change it, and other changes such as model, manufacturer, comments , name, etc.. would be unique in the SNMP task
