### ISSUE TITLE
GLPI Unable to update network device IP

### ISSUE THREAD

**Issue by erique-souza** [glpi-project/glpi-inventory-plugin#568]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### GLPI Version

10.0.16

### Plugin version

1.4.0

### Bug description

As the Discovery task is no longer capable of updating the IP address of an already inventoried network device, the SNMP Inventory task is unable to perform its function successfully if the device's IP is changed, causing a problem for all devices. SNMP inventories, the suggestion to resolve this would be to enable the Discovery task during its discovery if it finds the same inventoried device to be able to update at least the device IP, thus fixing this issue

### Relevant log output

```shell

```

### Steps To reproduce

- Have an SNMP device inventoried
- Change the device IP
- Try Discovery and also SNMP Inventory
- Check if you were able to connect to update the data or not

**Comment by stonebuzz** [comment]
Hi @erique-souza 
 GLPI's native inventory already takes this scenario into account. 

If the printer's IP address changes, GLPI allows the discovery feature to automatically update the printer's information.

Could you please upload two inventory files here (with different IP addresses)?

**Comment by erique-souza** [comment]
> Hi [@erique-souza](https://github.com/erique-souza) GLPI's native inventory already takes this scenario into account.
> 
> If the printer's IP address changes, GLPI allows the discovery feature to automatically update the printer's information.
> 
> Could you please upload two inventory files here (with different IP addresses)?

I carried out new tests with the latest version of the plugin 1.4.0 and the Discovery task was actually able to update the IP of the network device, I am considering the case as closed
