### ISSUE TITLE
"moniker" definition in WMI Collect related code

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi-inventory-plugin#574]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### GLPI Version

10.0.17

### Plugin version

1.4.0

### Bug description

"moniker" is a technical term which should not be translated IMHO. For example it is translated as "surnom" in french, "Name" in german (yes first letter is capitalized) or "alias" in spanish.

Also it could be nice to show an example as indeed glpi-agent expects a specific format. For example the default comportment if the value is empty is to use `winmgmts://./root/cimv2`. If someone wants to use [Root\CIMV2\Security\MicrosoftTpm as Namespace for Win32_Tpm](https://learn.microsoft.com/en-us/windows/win32/secprov/win32-tpm), he have to define moniker with `winmgmts://./Root/CIMV2/Security/MicrosoftTpm`.

Related ticket: `!35436`

### Relevant log output

```shell

```

**Comment by trasher** [comment]
I've never heard of this word expect in this plugin... Since it seems related to microsoft stuff, and microsoft themselves do not translate it; I guess it's OK to drop translations.
