### ISSUE TITLE
Entity creation from api don't work as expected

### ISSUE THREAD

**Issue by tekmans** [glpi-project/glpi-inventory-plugin#577]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### GLPI Version

10.0.0.16

### Plugin version

1.3.4 and 1.4.0

### Bug description

I have scripted the installation of glpi and glpi plugin, next i had rename root entity and create different entities

Those son entities are wrongly created as

![Image](https://github.com/user-attachments/assets/0d9ff43f-8f25-4593-984a-0e7d7951a667)

As we can see son entities are not clickable

On the main screen, i can see only one entity
![Image](https://github.com/user-attachments/assets/6f548f5a-5541-4769-a6a1-b446b7705afa)

And it becomes impossible to create rule based on entity (entities are missing)
![Image](https://github.com/user-attachments/assets/81622441-553e-4ad6-9fb1-21fa4ca5ed81)

If on my script i bypass this
```
#- name: GLPI - Enable glpi plugin after db init
#  ansible.builtin.command: php /usr/share/glpi/bin/console {{ item }} glpiinventory
#  with_items:
#    - 'glpi:plugin:install --username=root'
#    - 'glpi:plugin:activate'
```
And do it from glpi interface everything works as a charme
![Image](https://github.com/user-attachments/assets/1384e118-7d5e-42a7-90b3-c099d2586068)
![Image](https://github.com/user-attachments/assets/9ebedb13-9f62-4017-8c2b-aa73e744f9d9)

And rules are possible
![Image](https://github.com/user-attachments/assets/85dc151e-e819-42f5-8cf4-5f6d6573929f)

Why the plugin is working differently if is activated by command line ?

### Relevant log output

```shell

```

**Comment by trasher** [comment]
I do not see any relation beetween API and glpiinventory plugin; so I'll close this one.

Either you need support and should take a look at GLPI core support possibilities, or you really find a bug and you must declare it on GLPI core, and provide all information including a easy way to reproduce on a fresh instance.

**Comment by tekmans** [comment]
I could understand that the title may thinks that issue is on the wrong repository.

But i summarize : 
if i install glpiinventory from ui, API entity creation is Okay
if i install glpiinventory from cmd, API entity creation is KO.

It seems coming from glpiinventory but i will post issue also in GLPI Core
