### ISSUE TITLE
Network scan threads default values should be "General setup"

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi-inventory-plugin#7]
After first import, a agent should show it uses "General setup" related value" for "Network discovery threads" and "Network inventory threads".
![image](https://user-images.githubusercontent.com/12514489/146204276-34c146cf-eae8-4ae9-960a-06b069c7dd46.png)

GLPI: 10.0.0-beta
GLPI-Inventory plugin: 10.0.0-beta1
GLPI-Agent: 1.0, asset imported via native inventory

**Comment by trasher** [comment]
Fixed
