### ISSUE TITLE
Update plugin failed

### ISSUE THREAD

**Issue by floriant29** [glpi-project/glpi-inventory-plugin#82]
Hello,

When I update the plugin to 1.0.0-rc7 I have error message : 

Use core computers (1 seconde)
- Erreur durant l'éxecution de la requête : UPDATE `glpi_computers` AS `computers` INNER JOIN ( SELECT `computers_id`, `last_inventory_update` FROM `glpi_plugin_glpiinventory_inventorycomputercomputers` ) AS `plugin_computers` ON `plugin_computers`.`computers_id` = `computers`.`id` SET `computers`.`last_inventory_update` = `plugin_computers`.`last_inventory_update` ; - L'erreur est Unknown column 'computers.last_inventory_update' in 'field list' 

Thanks

**Comment by tcotidiane33** [comment]
![Capture](https://github.com/glpi-project/glpi-inventory-plugin/assets/51900661/7bf562e3-4bbe-4700-94cf-ec6efb781dca)


hello world !
i need help please?
