### ISSUE TITLE
Incorrect string value 

### ISSUE THREAD

**Issue by EC2311** [glpi-project/glpi-inventory-plugin#86]
Bonjour

[2022-03-31 16:25:29] glpiphplog.ERROR:   *** PHP User Error (256): Incorrect string value: '\xC2 Mana...' for column 'name' at row 1 in C:\wamp64\www\glpi\src\DBmysql.php at line 1936
  Backtrace :
  src\DBmysql.php:1936                               trigger_error()
  src\Inventory\Asset\Software.php:631               DBmysql->executeStatement()
  src\Inventory\Asset\Software.php:371               Glpi\Inventory\Asset\Software->storeSoftware()
  src\Inventory\Asset\MainAsset.php:765              Glpi\Inventory\Asset\Software->handle()
  src\Inventory\Asset\MainAsset.php:686              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src\RuleImportAsset.php:951                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src\Rule.php:1505                                  RuleImportAsset->executeActions()

Le probleme vient du nom du logiciel
00560Administration de Windows Azure AD Rights Management : entre Rights et management, présence dun caractere xc2 (echappement, retour à la ligne ?) 

 du coup cela genere une erreur dans la log agent 
![image](https://user-images.githubusercontent.com/42341169/161081021-216c2ef6-36ab-409d-a1cb-3f9b5c9ea8f6.png)

pour information : 
le traitement du meme agent vers GLPI et plugin FusionInventory passe : donc traitement spécifique à apporter dans la gestion software.php

**Comment by g-bougard** [comment]
Hi @EC2311 

the problem is probably relative to native inventory and maybe the agent, probably not this plugin.

But can you tell which GLPI 10 rc version you're using, which GlpiInventory plugin version and which agent and version.

You also need to share the inventory entry so we can reproduce the case.

**Comment by EC2311** [comment]
V10 RC3
and you're right, it's not the plugin, but the native inventory src/inventory/asset/software.php

Strange, I have no more the initial error, but another one now : 
[2022-03-31 15:18:04] glpiphplog.WARNING:   *** PHP Warning (2): mysqli_stmt::bind_param(): Number of elements in type definition string doesn't match number of bind variables in C:\wamp64\www\glpi\src\Inventory\Asset\Software.php at line 629
  Backtrace :
  src\Inventory\Asset\Software.php:629               mysqli_stmt->bind_param()
  src\Inventory\Asset\Software.php:371               Glpi\Inventory\Asset\Software->storeSoftware()
  src\Inventory\Asset\MainAsset.php:765              Glpi\Inventory\Asset\Software->handle()
  src\Inventory\Asset\MainAsset.php:686              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src\RuleImportAsset.php:939                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src\Rule.php:1505                                  RuleImportAsset->executeActions()
  src\RuleCollection.php:1589                        Rule->process()
  src\Inventory\Asset\MainAsset.php:517              RuleCollection->processAllRules()
  src\Inventory\Inventory.php:671                    Glpi\Inventory\Asset\MainAsset->handle()
  src\Inventory\Inventory.php:313                    Glpi\Inventory\Inventory->handleItem()
  src\Inventory\Request.php:368                      Glpi\Inventory\Inventory->doInventory()
  src\Inventory\Request.php:83                       Glpi\Inventory\Request->inventory()
  src\Agent\Communication\AbstractRequest.php:307    Glpi\Inventory\Request->handleAction()
  src\Agent\Communication\AbstractRequest.php:219    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front\inventory.php:74                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  plugins\glpiinventory\front\communication.php:72   include_once()
  plugins\glpiinventory\index.php:45                 include_once()
  
[2022-03-31 15:18:04] glpiphplog.ERROR:   *** PHP User Error (256): No data supplied for parameters in prepared statement in C:\wamp64\www\glpi\src\DBmysql.php at line 1936
  Backtrace :
  src\DBmysql.php:1936                               trigger_error()
  src\Inventory\Asset\Software.php:630               DBmysql->executeStatement()
  src\Inventory\Asset\Software.php:371               Glpi\Inventory\Asset\Software->storeSoftware()
  src\Inventory\Asset\MainAsset.php:765              Glpi\Inventory\Asset\Software->handle()

**Comment by EC2311** [comment]
I tried to debug by adding output file : 
![image](https://user-images.githubusercontent.com/42341169/161093240-621f740d-99e7-498c-9a38-28507d40a56d.png)
![image](https://user-images.githubusercontent.com/42341169/161093310-2be92d51-51d3-4074-a70d-bef75c7ba663.png)
![image](https://user-images.githubusercontent.com/42341169/161093375-ac387541-4369-4764-abd2-e6518ac37dc0.png)

**Comment by cedric-anne** [comment]
Hi,

`\xC2` would probably be correctly handle by the `utf8mb4` MySQL charset. Did you run the `utf8mb4` migration of GLPI tables ?

**Comment by EC2311** [comment]
Hello

Yes I have run the command,
Nevertheless I continue my research, and As I said previously, the error has changed (for the moment ?)
I added some output in var.txt file
![image](https://user-images.githubusercontent.com/42341169/161211711-e8507106-a0c0-4317-8fa1-3a31e8bd131e.png)

and here is the var.txt file as output
![image](https://user-images.githubusercontent.com/42341169/161211639-85df8ca8-9923-4d8b-bee9-8d050d22890f.png)

I wonder about the number of 's' and the number of values.... ?

**Comment by trasher** [comment]
Whiwh glpi version are you using? As far as I remember, we saw a similar problem that has been solved yet.

**Comment by EC2311** [comment]
V10 RC3

**Comment by trasher** [comment]
OK. So, one of software in list may miss an information. Please provide an inventory file that reproduce the issue so we can investigate our side.

**Comment by EC2311** [comment]
how to create this file ?

**Comment by trasher** [comment]
Also, please open a new issue on glpi reprository, this is not a plugin issue, and that is no linked with original issue here

**Comment by EC2311** [comment]
Can you advise me to create the file and the glpi repository (I found the one in glpi forum... but ?)
THanks

**Comment by EC2311** [comment]
Here is the extract of the part software with the product
    <SOFTWARES>
      <ARCH>x86_64</ARCH>
      <COMMENTS>Update</COMMENTS>
      <FROM>WMI</FROM>
      <INSTALLDATE>03/12/2020</INSTALLDATE>
      <NAME>KB4578968</NAME>
      <RELEASE_TYPE>Update</RELEASE_TYPE>
      <SYSTEM_CATEGORY>update</SYSTEM_CATEGORY>
    </SOFTWARES>

**Comment by g-bougard** [comment]
Hi @EC2311 
screenshot is not what we expect. We expect a text copy with the exactly same encoding. So please, can you save the inventory as a new file, then remove all other lines then this XML node, then zip it an attach it here ?

**Comment by EC2311** [comment]
what do you mean by 'remove all other lines' ?

**Comment by g-bougard** [comment]
Just manage to keep the lines from KB4578968 SOFTWARE node in the file.

**Comment by EC2311** [comment]
Here is it : 
[test.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/8396106/test.zip)

**Comment by EC2311** [comment]
I looked at the full file generated by the glpi-inventory.bat : 
the initial value xc2 is not in it, as yoou can see below (lines 1417)
![image](https://user-images.githubusercontent.com/42341169/161234454-27f37587-a87b-466e-92ed-fa82805a96cd.png)
and the software KB4578968 is in lines 2453
![image](https://user-images.githubusercontent.com/42341169/161234775-d574c29b-0caf-44fd-9a79-be153bdb16bb.png)
so others softwares have been managed correctly (i think ?)

**Comment by EC2311** [comment]
I Added an other debug point : 
![image](https://user-images.githubusercontent.com/42341169/161236227-0948c4cf-e03b-4ba9-832f-09cf1499c823.png)
the var.txt file output : 
![image](https://user-images.githubusercontent.com/42341169/161236320-ebfafa3b-c957-442e-8599-9a53fcd1a816.png)

so  a new column appears
and what about the 's' in types ? : always 5 ?

**Comment by cedric-anne** [comment]
> I Added an other debug point : ![image](https://user-images.githubusercontent.com/42341169/161236227-0948c4cf-e03b-4ba9-832f-09cf1499c823.png) the var.txt file output : ![image](https://user-images.githubusercontent.com/42341169/161236320-ebfafa3b-c957-442e-8599-9a53fcd1a816.png)
> 
> so a new column appears and what about the 's' in types ? : always 5 ? perhaps moving this building part of types after the search of categorie ?

For this point, can you check if https://github.com/glpi-project/glpi/pull/11153 fixes this issue ?

**Comment by EC2311** [comment]
Yes !
it's ok now
I dont' find the Third file (tests/functionnal/software.php) : I think it's for your tests ?

I will check another problem (perhaps a problem with Entity and rules : I have a tag on my agent, and another computer had been created. If such a problem I will create another topic. Can you give me the glpi repository ?

THanks
Best regards

**Comment by cedric-anne** [comment]
> If such a problem I will create another topic. Can you give me the glpi repository ?

https://github.com/glpi-project/glpi/issues
