### ISSUE TITLE
Network ports deleted on network devices inventoried via SNMP

### ISSUE THREAD

**Issue by armanduchi** [glpi-project/glpi-inventory-plugin#88]
Hello,
Adding network devices (hp switches) via netdiscover and netinventory,
item is added with network ports info. (in my case 9).

![image](https://user-images.githubusercontent.com/62557199/161594193-736cf6a8-1f8a-4a5d-ad2d-268c114e05e5.png)

After task update, we experiment deletion of this network ports

![image](https://user-images.githubusercontent.com/62557199/161594265-8e3fe1b5-ee26-4bcc-851d-0027180e5cea.png)

**Comment by trasher** [comment]
Please check if https://github.com/glpi-project/glpi/pull/11154 solves this issue

**Comment by armanduchi** [comment]
Sorry,


It does not solve this issue.

Network Ports are deleted once again

Tried with last nightly build

master 	master.8b6a4ee.tar.gz 
<https://nightly.glpi-project.org/glpi/master.8b6a4ee.tar.gz> 
2022-04-06 00:24:44 UTC 	88854020
